### ISSUE TITLE
Could not initialize Amplify

### ISSUE THREAD

**Issue by bpappin** [aws-amplify/amplify-android#1005]
- This only happens when built on our CI server.
- The file its looking for is: awsconfiguration.json
- That file is missing from the APK, or at least is not in the res/raw/* directory.

```
2020-11-27 13:06:51.663 29129-29129/ambimi.rogue.dev E/RogueApplication: Could not initialize Amplify
    AmplifyException{message=Failed to find the resource with ID 0., cause=android.content.res.Resources$NotFoundException: Resource ID #0x0, recoverySuggestion=Please check that it has been created.}
        at com.amplifyframework.core.Resources.readJsonResourceFromId(Resources.java:80)
        at com.amplifyframework.core.AmplifyConfiguration.builder(AmplifyConfiguration.java:226)
        at com.amplifyframework.core.AmplifyConfiguration.fromConfigFile(AmplifyConfiguration.java:115)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:120)
        at ambimi.rogue.RogueApplication.onCreate(RogueApplication.kt:96)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
        at android.content.res.ResourcesImpl.openRawResource(ResourcesImpl.java:352)
        at android.content.res.Resources.openRawResource(Resources.java:1301)
        at android.content.res.Resources.openRawResource(Resources.java:1245)
        at com.amplifyframework.core.Resources.readJsonResourceFromId(Resources.java:78)
        at com.amplifyframework.core.AmplifyConfiguration.builder(AmplifyConfiguration.java:226) 
        at com.amplifyframework.core.AmplifyConfiguration.fromConfigFile(AmplifyConfiguration.java:115) 
        at com.amplifyframework.core.Amplify.configure(Amplify.java:120) 
        at ambimi.rogue.RogueApplication.onCreate(RogueApplication.kt:96) 
```

**Comment by jamesonwilliams** [comment]
This is working as designed. Amplify won't configure without a configuration of some kind.

You should either:
1. Bundle an `app/src/main/res/raw/amplifyconfiguration.json` with your app, or;
2. [Specify one from Java/Kotlin](https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/core/Amplify.java#L123-L129), if that's easier in your CI/CD flow.

Our various tests under [`aws-datastore/src/androidTest`](https://github.com/aws-amplify/amplify-android/tree/main/aws-datastore/src/androidTest/java/com/amplifyframework/datastore) and [`aws-api/src/androidTest`](https://github.com/aws-amplify/amplify-android/tree/main/aws-api/src/androidTest/java/com/amplifyframework/api/aws) generally use the _second_ approach, since we want to load various different configurations, not just the one from the single configuration file.
