### ISSUE TITLE
Deleting a parent in datastore doesn't delete the children from remote, only locally

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-android#1013]
In DataStore category, if you have a connected model such as `Blog` and `Post` where a `Post` belongs to a `Blog` and a `Blog` has several `Post`s if a `Blog` instance is deleted, all the children `Post` instances are deleted in the local datastore, however these children remove Mutations are not sent to appsync. 

Since appsync itself doesn’t reinforce foreign key constraints, the orphaned items (Posts) will stay in the server and when a new device tries to sync it will result in a Foreign Key Constraint error while saving these orphaned `Post`s since their `BlogId` doesn't exist in the `Blog` table. See the exception below

```
 W/amplify:aws-datastore: Failed to sync remote model into local storage: ModelWithMetadata{model=SerializedModel{id='02e358b8-f89a-4616-b631-1ca833dd7781', serializedData={_deleted=null, comments={startedAt=null, items=[{id=7f4ca241-9c4e-4113-9186-93e9aa513d98}], nextToken=null}, _lastChangedAt=1.60677993E12, created=null, rating=1, id=02e358b8-f89a-4616-b631-1ca833dd7781, blog={id=d6de9839-49a4-4a4c-996f-d05cbbd3e5b7}, title=1, _version=1}, modelSchema=ModelSchema{name='Post', pluralName='Posts', authRules=[], fields={blog=ModelField{name='blog', javaClassForValue='interface com.amplifyframework.core.model.Model', targetType='Blog', isRequired=false, isArray=false, isEnum=false, isModel=true}, comments=ModelField{name='comments', javaClassForValue='interface java.util.List', targetType='Comment', isRequired=false, isArray=true, isEnum=false, isModel=false}, created=ModelField{name='created', javaClassForValue='class com.amplifyframework.core.model.temporal.Temporal$Date', targetType='AWSDate', isRequired=false, isArray=false, isEnum=false, isModel=false}, id=ModelField{name='id', javaClassForValue='class java.lang.String', targetType='String', isRequired=true, isArray=false, isEnum=false, isModel=false}, rating=ModelField{name='rating', javaClassForValue='class java.lang.Integer', targetType='Integer', isRequired=true, isArray=false, isEnum=false, isModel=false}, title=ModelField{name='title', javaClassForValue='class java.lang.String', targetType='String', isRequired=true, isArray=false, isEnum=false, isModel=false}}, associations={blog=ModelAssociation{name='BelongsTo', targetName='blogID', associatedName='null', associatedType='Blog'}, comments=ModelAssociation{name='HasMany', targetName='null', associatedName='post', associatedType='Comment'}}, indexes={}, modelClass=class com.amplifyframework.datastore.appsync.SerializedModel}}, syncMetadata=ModelMetadata{id='02e358b8-f89a-4616-b631-1ca833dd7781', _deleted=null, _version=1, _lastChangedAt=Temporal.Timestamp{timestamp=1606779949802}}}
    DataStoreException{message=Error in saving the model: Post[id=02e358b8-f89a-4616-b631-1ca833dd7781], cause=android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY), recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:318)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:740)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:303)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
W/amplify:aws-datastore: Initial cloud sync failed.
```

This cannot be resolved until the customer delete such orphans from the server, no workaround that I am aware of.

**Comment by jamesonwilliams** [comment]
Note: the key implementation flaw here is that we are doing cascading deletes via [a SQL statement](https://github.com/aws-amplify/amplify-android/blob/5078df9e7054c669f5ccf54510f5953b430e924f/aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteCommandFactory.java#L476):
```sql
ON DELETE CASCADE
```
However, we don't generate outbound AppSync mutations for the child of a parent.

----------

However it happens, we need to have `observe()` fire for each individual model that gets generated, this way a new mutation will be created for each.

That probable means that we need to cascade the deletes as a recursive function from Java, instead of using the SQL command. We need to populate deletions into the mutation queue in topological order, according to the relationship graph.
