### ISSUE TITLE
Amplify.Storage.uploadFile fails with large files

### ISSUE THREAD

**Issue by Aswin-appmetry** [aws-amplify/amplify-android#1104]
File uploading operation fails while uploading a video file. 4 out of 10 time the video uploading fails with the below exception.
The internet connection is good as well. File upload operation tested with both wifi/mobile networks , results in same error.

The same file upload operation with same network works fine in the Amplify IOS SDK.

Amplify version used **1.6.8**

**Code used to call file upload**
```kotlin
Amplify.Storage.uploadFile(
    UUID.randomUUID().toString(),
    file,
    StorageUploadFileOptions.builder()
        .accessLevel(StorageAccessLevel.PUBLIC)
        .contentType(Mimetypes.getInstance().getMimetype(file))
        .build(),
    { progress -> },
    { success -> },
    { error -> }
)
```

> W/System.err: StorageException{message=Storage upload operation was interrupted., cause=null, recoverySuggestion=Please verify that you have a stable internet connection.}
> W/System.err: StorageException{message=Something went wrong with your AWS S3 Storage upload file operation, cause=com.amazonaws.AmazonClientException: Unable to execute HTTP request: failed to connect to development-uplift-remote-resources.s3.us-west-2.amazonaws.com/52.218.249.201 (port 443) from /192.168.0.101 (port 40772) after 15000ms, recoverySuggestion=See attached exception for more information and suggestions}
2021-01-11 13:39:33.760 24912-24912/com.uplift.coach.dev W/System.err:     at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:207)
> Caused by: java.net.SocketTimeoutException: failed to connect to development-uplift-remote-resources.s3.us-west-2.amazonaws.com/52.218.249.201 (port 443) from /192.168.0.101 (port 40772) after 15000ms

**Devices tested with**

One plus 6T - OS version 10 
Galaxy M11 -  OS version 10

**Comment by raphkim** [comment]
Thank you for reporting this issue @Aswin-appmetry ,
I will investigate what may be causing this inconsistent behavior.

**Comment by Ankish** [comment]
@raphkim : We are facing the same issue and all uploads are failing most of the time. This seems to be quite critical. Any estimate would help us plan the workaround for production. Thank you for your support.

**Comment by Ankish** [comment]
50 % uploads are failing for us in production. Any estimate will help us a lot to plan up things. Thanks !
@raphkim

**Comment by Ankish** [comment]
@raphkim : This is very critical. Sorry, but super amazed at how lightly this issue is been taken. Any path or estimate with be greatly appreciated.

**Comment by raphkim** [comment]
Hi @Ankish ,
I apologize for prolonged inactivity regarding this issue. I will give it the attention it deserves and prioritize resolving it this week.

**Comment by Aswin-appmetry** [comment]
@raphkim @richardmcclellan Any update or alternative ways to upload file will be helpful to resolve the issue.

**Comment by raphkim** [comment]
Hi @Aswin-appmetry ,

I was able to reproduce the issue on my end, but I'm unable to get the error to trigger reliably. I will continue to investigate the issue to find a fix as soon as possible.

Thank you for your patience.

**Comment by SamiLakka1979** [comment]
We are really waiting for solution to this. Today even small uploads failed (little over 10Mb).

**Comment by tiendung717** [comment]
We are facing same issues. Really waiting for a solution.

**Comment by ashishHolofy** [comment]
Hi Guys,

Not sure if its a permanent fix but i was able to reduce the failure rate by increasing the socket timeout or even setting it to 0(which is infinite). Please do some trial and error to come up with suitable timeout.

```kotlin
val plugin = Amplify.Storage.getPlugin("awsS3StoragePlugin") as AWSS3StoragePlugin
            val client = plugin.escapeHatch
            client.setConfiguration(ClientConfiguration().apply {
                socketTimeout = 60 * 1000 
            })
```
Disclaimer: This is not a solution, its just a fix for people who are using this is production as `setConfiguration(ClientConfiguration clientConfiguration)` is deprecated.

**Comment by raphkim** [comment]
Hi, the latest version of Amplify (1.17.4 as of writing) contains fix to increase the stability of large file uploads. Please let us know if the issue persists after updating the library.

**Comment by tiendung717** [comment]
@raphkim  Could you share a little bit how this issue was fixed ?

**Comment by richardmcclellan** [comment]
Hi @tiendung717, we expect https://github.com/aws-amplify/aws-sdk-android/pull/2447 to resolve this issue.  Previously, all of the "parts" of a multi-part upload were being uploaded in parallel.  Each part is 5MB, so for a 100MB file, this would initiate 20 simultaneous uploads.  In practice, mobile devices can't actually process this many requests in parallel, so some requests get queued and eventually time out, which causes the entire upload to fail.  The change modifies the library so that only one part is uploaded at a time.  Note that this shouldn't actually slow down the entire upload time significantly, because each part will be able to be uploaded much faster than before, since only one is active at a time.

**Comment by Aswin-appmetry** [comment]
@richardmcclellan I can able to reproduce the issue. 

I was trying to upload 300 MB file in mobile network connection. At some point i get the socket timeout exception. After reaching this state when i call resume with the `StorageUploadFileOperation` it doesn't do anything. I have added the exception below for your reference.

Alternatively i'm using S3 Transfer utility file to upload. I can able to produce the same issue in that as well. I can set the socket timeout to 0 and can able to upload large files without any interruption.

> val plugin = Amplify.Storage.getPlugin("awsS3StoragePlugin") as AWSS3StoragePlugin
            val client = plugin.escapeHatch
            client.setConfiguration(ClientConfiguration().apply {
                socketTimeout = 60 * 1000 
            })
            
           Since this is deprecated, is there a way to set the socket timeout in the latest SDK.

> 2021-05-21 12:17:29.708 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler: StorageException{message=Something went wrong with your AWS S3 Storage upload file operation, cause=java.util.concurrent.ExecutionException: com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout, recoverySuggestion=See attached exception for more information and suggestions}
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:207)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:306)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at android.os.Handler.handleCallback(Handler.java:883)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at android.os.Handler.dispatchMessage(Handler.java:100)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at android.os.Looper.loop(Looper.java:214)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at android.app.ActivityThread.main(ActivityThread.java:7697)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at java.lang.reflect.Method.invoke(Native Method)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler: Caused by: java.util.concurrent.ExecutionException: com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at java.util.concurrent.FutureTask.report(FutureTask.java:123)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at java.util.concurrent.FutureTask.get(FutureTask.java:193)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:177)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:109)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at java.lang.Thread.run(Thread.java:919)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler: Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4829)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3821)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:59)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:29)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler: 	... 4 more
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler: Caused by: java.net.SocketTimeoutException: timeout
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:538)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:110)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:30)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:386)
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler: 	... 9 more
2021-05-21 12:17:29.709 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler: Caused by: java.net.SocketException: socket is closed
2021-05-21 12:17:29.710 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:554)
2021-05-21 12:17:29.710 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
2021-05-21 12:17:29.710 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
2021-05-21 12:17:29.710 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler: 	... 24 more
2021-05-21 12:17:29.710 7025-7025/com.uplift.coach.dev E/FileUploadManager: retry
2021-05-21 12:17:29.711 7025-7025/com.uplift.coach.dev E/FileUploadManager: retry upload
2021-05-21 12:17:29.734 7025-7025/com.uplift.coach.dev E/AmplifyErrorHandler: StorageException{message=Storage upload operation was interrupted., cause=null, recoverySuggestion=Please verify that you have a stable internet connection.}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onStateChanged(AWSS3StorageUploadFileOperation.java:188)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:224)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2021-05-21 12:17:29.734 7025-7025/com.uplift.coach.dev E/FileUploadManager: retry
2021-05-21 12:17:29.734 7025-7025/com.uplift.coach.dev E/FileUploadManager: retry upload

**Comment by pcanas** [comment]
@Aswin-appmetry did you find a solution on how to set the socket timeout in the latest SDK? Thanks!

**Comment by burak-pensa** [comment]
@Aswin-appmetry Any progress on this one?
