### ISSUE TITLE
[Storage] Support downloading files in background

### ISSUE THREAD

**Issue by richardmcclellan** [aws-amplify/amplify-android#1115]
The `AWSS3StoragePlugin` creates a `TransferService`, which is an Android `Service`.  As of Android O (API 26), a `Service` cannot be started in the background ([source](https://stackoverflow.com/a/46445436/282279)), which means that transfers cannot be initiated while the app is in the background.   Instead, we should use the new `JobScheduler`, which gets called periodically in the background  

Attempts to start a transfer while in the background result in the following error:

```
AmplifyException {message=Something went wrong with your AWS S3 Storage list operation, cause=java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.netafim.tech_app/com.amazonaws.mobileconnectors.s3.transferutility.TransferService }: app is in background uid UidRecord{e945dd1 u0a281 TRNB bg:+1m5s172ms idle change:idle procs:1 seq(0,0,0)}, recoverySuggestion=See attached exception for more information and suggestions}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageListOperation.lambda$start$0$AWSS3StorageListOperation(AWSS3StorageListOperation.java:95)
        at com.amplifyframework.storage.s3.operation.-$$Lambda$AWSS3StorageListOperation$h_rYgEkUSCQ04HohVqKR6853m80.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.netafim.tech_app/com.amazonaws.mobileconnectors.s3.transferutility.TransferService }: app is in background uid UidRecord{e945dd1 u0a281 TRNB bg:+1m5s172ms idle change:idle procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
        at android.app.ContextImpl.startService(ContextImpl.java:1571)
        at android.content.ContextWrapper.startService(ContextWrapper.java:669)
        at com.amplifyframework.storage.s3.service.AWSS3StorageService.startServiceIfNotAlreadyStarted(AWSS3StorageService.java:226)
        at com.amplifyframework.storage.s3.service.AWSS3StorageService.listFiles(AWSS3StorageService.java:157)
        at com.amplifyframework.storage.s3.operation.AWSS3StorageListOperation.lambda$start$0$AWSS3StorageListOperation(AWSS3StorageListOperation.java:91)
        at com.amplifyframework.storage.s3.operation.-$$Lambda$AWSS3StorageListOperation$h_rYgEkUSCQ04HohVqKR6853m80.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

Originally reported on StackOverflow: https://stackoverflow.com/questions/65789564/failed-to-use-amplify-storage-with-a-periodic-worker

**Comment by LaurieScheepers** [comment]
I have figured out a workaround for this. Please see https://stackoverflow.com/questions/65789564/failed-to-use-amplify-storage-with-a-periodic-worker/71171153#71171153

**Comment by HuiSF** [comment]
Before delivering support of background download/upload, I think at least it should prevent App from crashing.
[This thread](https://github.com/aws-amplify/aws-sdk-android/issues/1193) suggests a change to prevent the crash.

Change call of `startService` to `startForegroundService`.

https://github.com/aws-amplify/amplify-android/blob/1375235eb2d100f40f70afc8a4de8e2f77b457ab/aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/service/AWSS3StorageService.java#L249-L255

**Comment by androidcodehunter** [comment]
@HuiSF so this issue will be resolved in the next version of amplify in android right? Because it is so common in android to run the uploading tasks using Worker.
