### ISSUE TITLE
Amplify.DataStore.delete not working

### ISSUE THREAD

**Issue by anandanwar4** [aws-amplify/amplify-android#1146]
An exception is thrown when trying to delete a record from database.

**Version Info**:
```
implementation 'com.amplifyframework:core:1.16.11'
implementation 'com.amplifyframework:aws-datastore:1.16.11'
implementation 'androidx.multidex:multidex:2.0.1'
```

**Code**:
```
    @Override
    public void deleteItem(Item itemToBeDeleted, Consumer<Item> deletionSuccessAction,
                           Consumer<Throwable> deletionFailureAction) {
        Amplify.DataStore.delete(itemToBeDeleted,
                deletedItem -> deletionSuccessAction.accept(deletedItem.item()),
                deletionFailureAction::accept
        );
    }
```

**Error Log**:
```
E/SQLiteLog: (1) no such column: Item.id
    DataStoreException{message=Error in deleting the model., cause=android.database.sqlite.SQLiteException: no such column: Item.id (code 1): , while compiling: SELECT `Category`.`id` AS `Category_id`, `Category`.`isCustom` AS `Category_isCustom`, `Category`.`name` AS `Category_name` FROM `Category` WHERE `Item`.`id` = ?;, recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:523)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.database.sqlite.SQLiteException: no such column: Item.id (code 1): , while compiling: SELECT `Category`.`id` AS `Category_id`, `Category`.`isCustom` AS `Category_isCustom`, `Category`.`name` AS `Category_name` FROM `Category` WHERE `Item`.`id` = ?;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1257)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.queryAll(SQLiteModelTree.java:173)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.recurseTree(SQLiteModelTree.java:136)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteModelTree.descendantsOf(SQLiteModelTree.java:92)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:491)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Reference Documentation**:
https://docs.amplify.aws/lib/datastore/data-access/q/platform/android#create-and-update

**schema.graphql**:
```
type Item @model @key(fields: ["id"]) {
  id: ID!
  name: String!
  categoryId: ID!
  category: Category @connection(fields: ["categoryId"])
}

type Category @model @key(fields: ["id"]) {
  id: ID!
  name: String!
  isCustom: Boolean!
}
```

**Extra Note**:
The same thing works fine with the following versions:
```
implementation 'com.amplifyframework:core:1.4.1'
implementation 'com.amplifyframework:aws-datastore:1.4.1'
implementation 'androidx.multidex:multidex:2.0.1'
```
As soon as I upgrade to 1.16.11 the problem starts.

**Comment by raphkim** [comment]
Hi @anandanwar4 ,

It appears that error stems from ambiguity in model schema that prevented a complete relation from forming between `Item` and `Category`. The generated model assumes that `Item` has one `Category` but `Category` does not belong to any other model. 

In a `A HasOne B` relationship, the following are true:
* `A` is associated with one or zero `B`
* `B` is associated with _exactly_ one `A`

Here is a suggested workaround to create a fully linked relationship between two models:
```
type Item @model @key(fields: ["id"]) {
  id: ID!
  name: String!
  categoryId: ID!
  category: Category! @connection(fields: ["categoryId"])
}

type Category @model @key(fields: ["id"]) {
  id: ID!
  name: String!
  isCustom: Boolean!
  item: Item @connection(fields: ["id"])
}
```

Note that this actually "flips" the relationship that your current schema in such way that `Category` now has a HasOne relationship with `Item` rather than the other way around.

If you would like to discuss further about correctly configuring your GraphQL schema, then feel free to reach out to us via our [discord channel](https://discord.gg/gGZfAr3Xnv) or direct message me (Raphael#2771) regarding this issue.

**Comment by anandanwar4** [comment]
Hi @raphkim ,

The discord is not opening. It asks for my date of birth but does not let me select anything from dropdown.
So commenting here.

My requirement is to have many to one relationship from Item to Category:
- Item is associated with exactly one Category.
- One Category can be referred to by multiple Items.

Can you suggest the schema for this?

Regards,
Ankit

**Comment by raphkim** [comment]
Aha! I figured it makes sense for `Category` to have one-to-many relationship with `Item`.

Please refer to [this documentation](https://docs.amplify.aws/cli/graphql-transformer/connection#has-many) when creating model connections. I imagine the following schema should suffice for your use-case:

```
type Category @model {
  id: ID!
  name: String!
  isCustom: Boolean!
  items: [Item] @connection(keyName: "byCategory", fields: ["id"])
}

type Item @model @key(name: "byCategory", fields: ["categoryId"]) {
  id: ID!
  name: String!
  categoryId: ID!
  category: Category! @connection(fields: ["categoryId"])
}
```

**Comment by jamesonwilliams** [comment]
> The discord is not opening. It asks for my date of birth but does not let me select anything from dropdown.

Please try https://discord.gg/amplify

**Comment by richardmcclellan** [comment]
Re-opening for tracking purposes, until the mentioned PR is merged.

**Comment by milk531** [comment]
same error here. We use amplify admin ui to create the data model, for one to many schema it give:
```
type Category @model  {
  id: ID!
  name: String
  coverUrl: String
  sort: Int
  ItemSet: [Item] @connection(keyName: "byCategory", fields: ["id"])
}

type Item @model @key(name: "byCategory", fields: ["categoryID"]) {
  id: ID!
  name: String
  downloadUrl: String
  categoryID: ID!
}
```
so Item only have `categoryID` column, so when delete one Category on remote, SQLiteStorageAdapter generate this sqlcommand 
```
SELECT `Item`.`id` AS `Item_id`, `Item`.`downloadUrl` AS `Item_downloadUrl`, `Item`.`name` AS `Item_name`,  `Item`.`categoryID` AS `Item_categoryID` FROM `Item` WHERE `Category`.`id` = ?;
```
 it will throw error for `Category`.`id` is not exist in table Item, only categoryID does.

**Comment by raphkim** [comment]
Hi @milk531 ,
It appears that the issue you are experiencing is unrelated to this issue.
There is currently an issue with model codegen that causes child model to be formed without a connection to its parent model. Once the codegen issue is resolved, any query on `Item` table will be properly joined with `Category` table.

Please refer to https://github.com/aws-amplify/amplify-codegen/issues/102 for more details.
