### ISSUE TITLE
Help with Query on Secondary Key

### ISSUE THREAD

**Issue by EdwardFinegan** [aws-amplify/amplify-android#1147]
I'm trying to do a custom Query based on a secondary key. However I can't seem to find an example or figure out what the return type (---XXX---) and responseType (---YYY---) should be. Since this is returning data based on a secondary key it should be an array of 0 or more TestRecords. Could someone provide an example of a query on a secondary key or help me with this syntax? Thanks.

```
private GraphQLRequest<---XXX---> getTestRecordByName(String name) {
        String document = ""
                + "query getTestRecordByName($name: String!) { \n"
                + "   getTestRecordByName(name: $name) { \n"
                + "       items { \n"
                + "           id \n"
                + "           name \n"
                + "           app \n"
                + "        } \n"
                + "    } \n"
                + "} \n";
        return new SimpleGraphQLRequest<>(
                document,
                Collections.singletonMap("name", name),
                ---YYY---.class,
                new GsonVariablesSerializer());
    }
```

**Comment by richardmcclellan** [comment]
Try this:
 - Replace  `---XXX---` with `PaginatedResult<TestRecord>`.  `TestRecord` should be the name of your auto generated `Model` class.
 - Replace `---YYY---` with `TypeMaker.getParameterizedType(PaginatedResult.class, TestRecord.class)`

**Comment by EdwardFinegan** [comment]
Unfortunately this generates` java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.gson.JsonElement.isJsonPrimitive()' on a null object reference`

Could you explain why `TypeMaker.getParameterizedType(PaginatedResult.class, TestRecord.class)` is what it is? I can't seem to find any docs that discuss it. I believe my query is working because if I set ---XXX--- to Object and ---YYY--- to Object.class, I can dig around and find the correct data in the debugger. I just can't seem to get it returned as an object that corresponds to the record type.

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.gson.JsonElement.isJsonPrimitive()' on a null object reference
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory$IterableDeserializer.buildPaginatedResult(GsonGraphQLResponseFactory.java:159)
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory$IterableDeserializer.deserialize(GsonGraphQLResponseFactory.java:121)
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory$IterableDeserializer.deserialize(GsonGraphQLResponseFactory.java:75)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:1003)
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
        at com.amplifyframework.api.graphql.GsonResponseAdapters$ResponseDeserializer.deserialize(GsonResponseAdapters.java:99)
        at com.amplifyframework.api.graphql.GsonResponseAdapters$ResponseDeserializer.deserialize(GsonResponseAdapters.java:59)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory.buildResponse(GsonGraphQLResponseFactory.java:65)
        at com.amplifyframework.api.graphql.GraphQLOperation.wrapResponse(GraphQLOperation.java:53)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation.access$100(AppSyncGraphQLOperation.java:48)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:139)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by richardmcclellan** [comment]
> Could you explain why TypeMaker.getParameterizedType(PaginatedResult.class, TestRecord.class) is what it is?

`TypeMaker.getParameterizedType` is just a utility for creating a parameterized type (`PaginatedResult<TestRecord>`).  You could create the parameterized type yourself, but it is somewhat difficult to do in Java, as described [here](https://stackoverflow.com/questions/2989475/creating-parameterized-type-object-using-anonymous-class).

Regarding the `NullPointerException` - it is crashing when trying to deserialize the `PaginatedResult` because it can't find a `nextToken` field in the response.   Here are three options to solve it:

1. Add `nextToken` to the request document, so that the response will contain it, like this:
```
        String document = ""
                + "query getTestRecordByName($name: String!) { \n"
                + "   getTestRecordByName(name: $name) { \n"
                + "       items { \n"
                + "           id \n"
                + "           name \n"
                + "           app \n"
                + "        } \n"
                + "        nextToken \n"
                + "    } \n"
                + "} \n";
```
2. Use `Iterable<TestRecord>` instead of `PaginatedResult<TestRecord>>` as the responseType.  This will avoid trying to parse a `nextToken` from the response JSON, but you won't be able to request subsequent pages of results with this approach.

3.  Use `String` as the responseType and `GraphQLRequest<String>` as your method return type.  This prevents Amplify from trying to deserialize the response as a model, and will just give you a raw JSON `String`, which you can deserialize yourself.
