### ISSUE TITLE
How to refresh token when using Custom Auth on AWS Mobile SDK

### ISSUE THREAD

**Issue by CWijaya** [aws-amplify/amplify-android#1175]
Hi, I'm having a problem to refresh the token when it expires.
Currently I'm using Cognito Custom Auth flow on AWS Mobile SDK (because we don't have the same guide using Amplify) with multiple lambda function as the triggers.
I'm following the tutorial from [this link.](https://itnext.io/passwordless-sms-authentication-backend-9932391c49dc)

The flow of my app is as follows:
1. User input their phone number.
2. Call the sign up function (AWSMobileClient.getInstance().signUp) -> with random default password, phone number auto confirmed
3. Call the sign in function(AWSMobileClient.getInstance().signIn), it will send an OTP to the phone number
4. After user input the otp, call function to confirm the sign in (AWSMobileClient.getInstance().confirmSignIn)
5. Done, go to next screen

After the sign is process has finished, all is well. I can get all the tokens (id token, access token, refresh token).
This changed, however when the access token expires. The refresh token is not expired yet.
Currently the expiry of access token is set to 15 minutes. 

When I tried getting the token with this function:
```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        AWSMobileClient.getInstance().initialize(applicationContext, object :
            com.amazonaws.mobile.client.Callback<UserStateDetails> {
            override fun onResult(userStateDetails: UserStateDetails) {
                when (userStateDetails.userState) {
                    UserState.SIGNED_IN -> runOnUiThread {
                        Log.e("user","Signed In")
                        Log.e(TAG,AWSMobileClient.getInstance().getUsername() )      //String
                        Log.e(TAG,AWSMobileClient.getInstance().getIdentityId())     //String
                        Log.e(TAG, AWSMobileClient.getInstance().getTokens().getIdToken().getTokenString())
                        Log.e(TAG, AWSMobileClient.getInstance().getTokens().accessToken.tokenString)
                        Log.e(TAG, AWSMobileClient.getInstance().getTokens().refreshToken.tokenString)
                    }
                    UserState.SIGNED_OUT -> runOnUiThread {
                        Log.e("user","Signed Out")
                    }
                    else -> {
                        Log.e(TAG, "Sign Out Called")
                        AWSMobileClient.getInstance().signOut()
                    }
                }
            }

            override fun onError(e: java.lang.Exception) {
                Log.e("INIT", e.toString())
            }
        })
}
```

I got an error saying that there are no cached session. The UserState is Signed In. however.

```
2021-02-16 21:11:42.761 23294-23294/com.idemia.mobileid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.idemia.mobileid, PID: 23294
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.signalTokensNotAvailable(AWSMobileClient.java:1858)
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.onFailure(AWSMobileClient.java:1853)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1034)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1819)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1767)
        at com.idemia.mobileid.MainActivity$onCreate$1$onResult$1.run(MainActivity.kt:119)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoInternalErrorException: Failed to authenticate user
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:1307)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1019)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1819) 
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115) 
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1767) 
        at com.idemia.mobileid.MainActivity$onCreate$1$onResult$1.run(MainActivity.kt:119) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1448)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:102)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
        at java.net.InetAddress.getAllByName(InetAddress.java:787)
        at com.android.okhttp.Dns$1.lookup(Dns.java:39)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:200)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:148)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:90)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:190)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:142)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:104)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:410)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:343)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:489)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
        at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6329)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.initiateAuth(AmazonCognitoIdentityProviderClient.java:4290)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.refreshSession(CognitoUser.java:2831)
2021-02-16 21:11:42.761 23294-23294/com.idemia.mobileid E/AndroidRuntime:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:1297)
        	... 12 more

```

What is the correct way to refresh the token when using Custom Auth flow?

**Version Used**
com.amplifyframework:core:1.4.1
com.amplifyframework:aws-auth-cognito:1.4.1

**Comment by CWijaya** [comment]
okay so the solution was to get the access token on .addUserStateListener instead of on .initialize
```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

       AWSMobileClient.getInstance().addUserStateListener { userStateDetails ->
            when (userStateDetails.userState) {
                UserState.GUEST -> Log.i("AuthQuickStart", "user is in guest mode")
                UserState.SIGNED_OUT -> Log.i(
                    "AuthQuickStart",
                    "user is signed out"
                )
                UserState.SIGNED_IN -> {
                    Log.e("AuthQuickStart", "user is signed in")
                    Log.e(TAG, AWSMobileClient.getInstance().tokens.accessToken.tokenString)
                }
                UserState.SIGNED_OUT_USER_POOLS_TOKENS_INVALID -> Log.i(
                    "AuthQuickStart",
                    "need to login again"
                )
                UserState.SIGNED_OUT_FEDERATED_TOKENS_INVALID -> Log.i(
                    "AuthQuickStart",
                    "user logged in via federation, but currently needs new tokens"
                )
                else -> Log.e("AuthQuickStart", "unsupported")
            }
        } 
       
}
```

sorry for the stupid question :(
