### ISSUE TITLE
W/AWSMobileClient: Failed to federate tokens during sign-in     java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.

### ISSUE THREAD

**Issue by OferWormser** [aws-amplify/amplify-android#1187]
This is the error I get after signin - 
W/AWSMobileClient: Failed to federate tokens during sign-in
    java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1708)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1661)
        at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1193)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1020)
        at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1178)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)
I/AuthQuickstart: Sign in succeeded

When I try to Amplify.Auth.fetchAuthSession I get this - 
D/AWSMobileClient: hasFederatedToken: false provider: cognito-idp.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
I/AuthQuickStart: IdentityId not present because: InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=com.amazonaws.AmazonClientException: Cognito Identity not configured, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}

**Comment by Foivos-Stamopoulos** [comment]
Same error here. Was this issue solved somehow? 

I am using the following versions in my Android project:
'com.amplifyframework:aws-auth-cognito:1.27.0'
'com.amplifyframework:core-kotlin:0.11.0'

**Comment by Foivos-Stamopoulos** [comment]
I solved this by creating an Identity Pool and adding the identityPoolId to the `amplifyconfiguration.json`

**Comment by Foivos-Stamopoulos** [comment]
The reason why I was getting this error is that when I was checking for the`AWSCognitoAuthSession` `type,` I was accessing the `identityId` property. Now I use the `userSub` property to check its type.
