### ISSUE TITLE
Access Denied Service: Amazon S3; Status Code: 403

### ISSUE THREAD

**Issue by marenero1974** [aws-amplify/amplify-android#1228]
Hi all, 
i am facing this issue while trying to upload a file to my s3 bucket:

```
StorageException{message=Something went wrong with your AWS S3 Storage upload input stream operation, cause=com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 8NSQZVMZYH6DVE69), S3 Extended Request ID: tJPfhEUH3oaaI6i0nea6hhidakOtRk6+n/gcnwxd8FJYqCDZbE5RHSscFbOkQBcb1OCBWIIRuVc=, recoverySuggestion=See attached exception for more information and suggestions}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadInputStreamOperation$UploadTransferListener.onError(AWSS3StorageUploadInputStreamOperation.java:212)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:306)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 8NSQZVMZYH6DVE69), S3 Extended Request ID: tJPfhEUH3oaaI6i0nea6hhidakOtRk6+n/gcnwxd8FJYqCDZbE5RHSscFbOkQBcb1OCBWIIRuVc=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4911)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1958)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:282)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:114)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
```

my amplify version is: 

```
    implementation 'com.amplifyframework:core:1.17.0'
    implementation 'com.amplifyframework:aws-api:1.17.0'
    implementation 'com.amplifyframework:aws-datastore:1.17.0'

    implementation 'com.amplifyframework:aws-storage-s3:1.17.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.17.0'
```

i am configuring amplify in this way:

```
public class MyAmplifyApp extends android.app.Application {

    @Override
    public void onCreate() {
        super.onCreate();
        try {
            Amplify.addPlugin(new AWSApiPlugin()); // UNCOMMENT this line once backend is deployed
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.addPlugin(new AWSDataStorePlugin());
            Amplify.configure(getApplicationContext());
            Log.i("Amplify", "Initialized Amplify");
        } catch (AmplifyException error) {
            Log.e("Amplify", "Could not initialize Amplify", error);
        }
    }
}
```

and my amplifyconfiguration.json:

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "pubwin2": {
                    "endpointType": "GraphQL",
                    "endpoint": "XXX",
                    "region": "eu-west-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "eu-west-2:XXX",
                            "Region": "eu-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-west-2_XXX",
                        "AppClientId": "XXX",
                        "Region": "eu-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "XXX",
                        "Region": "eu-west-2",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "pubwin2_AMAZON_COGNITO_USER_POOLS"
                    },
                    "pubwin2_AWS_IAM": {
                        "ApiUrl": "XXX",
                        "Region": "eu-west-2",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "pubwin2_AWS_IAM"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "MY-Bucket-NAME",
                        "Region": "eu-west-2"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "MY-Bucket-NAME",
                "region": "eu-west-2",
                "defaultAccessLevel": "guest"
            }
        }
    }
}
```

and the running code is:

```
Uri uri = getImageUri(bitmap);
InputStream exampleInputStream = getContentResolver().openInputStream(uri);
Amplify.Storage.uploadInputStream(
	"ExampleKey",
	exampleInputStream,
	StorageUploadInputStreamOptions.defaultInstance(),
	progress -> Log.i("MyActivity", "Fraction completed: " + progress.getFractionCompleted()),
	result -> Log.i("MyActivity", "Successfully uploaded: " + result.getKey()),
	storageFailure -> {
		Log.e("MyActivity", "Upload failed", storageFailure);
		Toast.makeText(MyActivity.this, R.string.Error_Occurred  + storageFailure.getMessage(), Toast.LENGTH_SHORT).show();
	}
);
```

I followed this guide: https://docs.amplify.aws/lib/storage/getting-started/q/platform/android#provision-backend-storage, but this doesn't appear in the questions about configuring the storage: 
`You need to add auth (Amazon Cognito) to your project in order to add storage for user files. Do you want to add auth now?`

what should be the problem?

Thanks

**Comment by richardmcclellan** [comment]
Hi @marenero1974, I believe your issue is that you haven't configured Auth.    I just checked with the latest version of the CLI (4.45.0), and I was prompted to add auth.  Here are the exact prompts I got after running `amplify add storage`:

```
? Please select from one of the below mentioned services: Content (Images, audio, video, etc.)
? You need to add auth (Amazon Cognito) to your project in order to add storage for user files. Do you want to add auth now? Yes
Using service: Cognito, provided by: awscloudformation

 The current configured provider is Amazon Cognito.

 Do you want to use the default authentication and security configuration? Default configuration
 Warning: you will not be able to edit these selections.
 How do you want users to be able to sign in? Username
 Do you want to configure advanced settings? No, I am done.
Successfully added auth resource tmp466bd510 locally

Some next steps:
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

? Please provide a friendly name for your resource that will be used to label this category in the project: s38443878f
? Please provide bucket name: tmp4828ba669aa84aac9c8218eaa4e8efa0
? Who should have access: Auth and guest users
? What kind of access do you want for Authenticated users? create/update, read, delete
? What kind of access do you want for Guest users? create/update, read, delete
? Do you want to add a Lambda Trigger for your S3 Bucket? No
Auth configuration is required to allow unauthenticated users, but it is not configured properly.
Successfully updated auth resource locally.
Successfully added resource s38443878f locally

If a user is part of a user pool group, run "amplify update storage" to enable IAM group policies for CRUD operations
Some next steps:
"amplify push" builds all of your local backend resources and provisions them in the cloud
"amplify publish" builds all of your local backend and front-end resources (if you added hosting category) and provisions them in the cloud
```

Things to try:
1. Make sure you are using the latest Amplify CLI (`npm i -g @aws-amplify/cli`)
2. If you selected "No" when asked if you want to configure Auth on the first time that you did `amplify add storage`, you can probably add auth via `amplify add auth`
3. If you are still having trouble, try starting over:
    1. `amplify delete storage`
    2. `amplify delete auth`
    3. `amplify push`
    4. `amplify add storage` (and make sure to say "Yes" to configuring Auth)
    5. `amplify push`

**Comment by marenero1974** [comment]
I tryied to do:
amplify remove storage
amplify remove auth : i deleted all auth's that i had ( there were two unused )
amply push

and it gives me this error:

`An error occurred when pushing the resources to the cloud

Template error: instance of Fn::GetAtt references undefined resource authpubwin216f010e5
An error occurred during the push operation: Template error: instance of Fn::GetAtt references undefined resource authpubwin216f010e5`

**Comment by marenero1974** [comment]
Just solved this issue:
i removed all references of 

`          "Fn::GetAtt": [
            "authpubwin216f010e5",
          ]`

and then pushed and then amplify add storage: this asked for auth
And it solved also the upload problem
