### ISSUE TITLE
Confirm sign up failed

### ISSUE THREAD

**Issue by zeeshandevninja** [aws-amplify/amplify-android#1236]
I am trying to signup and after sign up I am going through the confirm up step via email code. While confirming the signup, I am getting null pointer exception in error while the user is confirmed on user pool. If I resend the code and try to confirm sign up again i get error that user is already confirmed.

Stracktrace of `nullpointer exception`

```
AuthException{message=Confirm sign up failed, cause=java.lang.NullPointerException, recoverySuggestion=See attached exception for more details.}
	at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:106)
	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$3.onError(AWSCognitoAuthPlugin.java:318)
	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
	at com.amazonaws.mobile.client.AWSMobileClient$14$1.onFailure(AWSMobileClient.java:2150)
	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmSignUp(CognitoUser.java:381)
	at com.amazonaws.mobile.client.AWSMobileClient$14.run(AWSMobileClient.java:2136)
	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException
	at com.markhorist.barrys.auth.EmailVerificationActivity$onCreate$1$1.accept(EmailVerificationActivity.kt:38)
	at com.markhorist.barrys.auth.EmailVerificationActivity$onCreate$1$1.accept(EmailVerificationActivity.kt:22)
	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$3.onResult(AWSCognitoAuthPlugin.java:312)
	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$3.onResult(AWSCognitoAuthPlugin.java:309)
	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:75)
	at com.amazonaws.mobile.client.internal.InternalCallback.onResult(InternalCallback.java:62)
	at com.amazonaws.mobile.client.AWSMobileClient$14$1.onSuccess(AWSMobileClient.java:2140)
	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmSignUp(CognitoUser.java:379)
	... 3 more
```

Snippet that I am using to confirm the sign up process.

```
Amplify.Auth.confirmSignUp(
                email,
                binding.etVerify.text.toString(),
                {
                    addUserToBackend(AddUser(it.user?.username!!, it.user?.userId!!))
                    hideProgress()
                },
                { error ->
                    runOnUiThread {
                        hideProgress()
                        Toast.makeText(
                            this,
                            error.localizedMessage,
                            Toast.LENGTH_LONG
                        ).show()
                    }
                })
```
Following are the dependencies that I am using

```
implementation 'com.amplifyframework:core:1.6.9'
implementation 'com.amplifyframework:aws-auth-cognito:1.6.9'
```
How can i resolve this issue?

**Comment by zeeshandevninja** [comment]
Seeing the same behaviour on `1.17.0` version.

**Comment by zeeshandevninja** [comment]
How can I fix this issue?

**Comment by jamesonwilliams** [comment]
Hi @zeeshandevninja.

It looks like the error is actually being thrown from within one of your lambdas:

``console
Caused by: java.lang.NullPointerException
	at com.markhorist.barrys.auth.EmailVerificationActivity$onCreate$1$1.accept(EmailVerificationActivity.kt:38)
	at com.markhorist.barrys.auth.EmailVerificationActivity$onCreate$1$1.accept(EmailVerificationActivity.kt:22)
```

Either in this code:
```kotlin
addUserToBackend(AddUser(it.user?.username!!, it.user?.userId!!))
hideProgress()
```

Or this code:
```kotlin
hideProgress()
Toast.makeText(this, error.localizedMessage, Toast.LENGTH_LONG).show()
```

If I had to guess, it's one of those `!!`. Can you please verify that neither of these blocks of code throw a `NullPointerException`?

**Comment by zeeshandevninja** [comment]
Oh yeah you are right. My bad, one of the view was reference as null.  Thank you for help!

**Comment by zeeshandevninja** [comment]
So I checked in further details there was a null reference via view but there is null on `it.user` Any idea why do I get user null on confirming the sign up?
