### ISSUE TITLE
Fail to Sign up user and get AuthException{message=Sign up failed, cause=java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp

### ISSUE THREAD

**Issue by perseus-toku** [aws-amplify/amplify-android#1258]
I have set up the Cognito Identity Pool and would want to use Amplify to set up the credential for uploading to S3. 

Below is my onCreate Function to setup the config 
```
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //Fabric.with(this, new Crashlytics());
        ctx = this;
        preferences = PreferenceManager.getDefaultSharedPreferences(this);
        preferences.registerOnSharedPreferenceChangeListener(prefListener);

        try {
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.configure(
                    AmplifyConfiguration.fromConfigFile(getApplicationContext(), R.raw.amplifyconfiguration),
                    getApplicationContext());
            Log.i("MyAmplifyApp", "Initialized Amplify");
        } catch (AmplifyException e) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", e);
        }

        Amplify.Auth.fetchAuthSession(
                result -> Log.i("AmplifyAuthResult", result.toString()),
                error -> Log.e("AmplifyAuthError", error.toString())
        );
        
        AuthSignUpOptions options = AuthSignUpOptions.builder()
                .userAttribute(AuthUserAttributeKey.email(), "my@email.com")
                .build();
        Amplify.Auth.signUp("username", "12345", options,
                result -> Log.i("AuthQuickStart", "Result: " + result.toString()),
                error -> Log.e("AuthQuickStart", "Sign up failed", error)
        );
```

But the sign up failed with the following message:
```
E/AuthQuickStart: Sign up failed
    AuthException{message=Sign up failed, cause=java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(java.lang.String, java.lang.String, com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserAttributes, java.util.Map, java.util.Map, com.amazonaws.mobileconnectors.cognitoidentityprovider.handlers.SignUpHandler)' on a null object reference, recoverySuggestion=See attached exception for more details.}
        at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:106)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onError(AWSCognitoAuthPlugin.java:295)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
        at com.amazonaws.mobile.client.internal.InternalCallback.access$000(InternalCallback.java:34)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:103)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(java.lang.String, java.lang.String, com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserAttributes, java.util.Map, java.util.Map, com.amazonaws.mobileconnectors.cognitoidentityprovider.handlers.SignUpHandler)' on a null object reference
        at com.amazonaws.mobile.client.AWSMobileClient$13.run(AWSMobileClient.java:2020)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:923) 
```

My `amplifyconfiguration.json` json set up as the follow 

```
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:08106c51-*************",
                            "Region": "us-east-1"
                        }
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "random-android-bucket",
                "region": "us-east-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}
```

I am generally confused about the workflow of the Amplify setup and what I have to do on the AWS web portal. Would appreciate some help. 

Btw, the upload would work if I directly use awsAccessID, SecretID and SecurityToken. But for mobile dev, it is much better to use the Cognito Services.

**Comment by raphkim** [comment]
Hello @perseus-toku ,

May I ask which version of Amplify you are using just for reference?

**Comment by poojamat** [comment]
You don't need to setup configuration manually in the  amplify configure like this:
```
Amplify.configure(
                    AmplifyConfiguration.fromConfigFile(getApplicationContext(), R.raw.amplifyconfiguration),
                    getApplicationContext());
```

Just call amplify configure with context:

```
Amplify.configure(getApplicationContext());

```


Also verify that "Initialized Amplify" is printed in your logcat. you might have a failure in initializing amplify.
