### ISSUE TITLE
Update User Attributes

### ISSUE THREAD

**Issue by vivekathreya1** [aws-amplify/amplify-android#1263]
Hello,

I am trying to update user attributes with the following code. 
 
```kotlin
val attributes = listOf(
    AuthUserAttribute(AuthUserAttributeKey.familyName(), "lastname"),
    AuthUserAttribute(AuthUserAttributeKey.givenName(), "firstname")
)

try {
    val result = Amplify.Auth.updateUserAttributes(attributes)
    println(result)
} catch (error: Exception) {
    Timber.e(error)
}
```

Though the method returns success, but I get this error

```console
 java.lang.IllegalStateException: Already resumed
        at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:44)
        at com.amplifyframework.kotlin.auth.KotlinAuthFacade$updateUserAttributes$2$2.accept(KotlinAuthFacade.kt:246)
        at com.amplifyframework.kotlin.auth.KotlinAuthFacade$updateUserAttributes$2$2.accept(KotlinAuthFacade.kt:41)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$17.onError(AWSCognitoAuthPlugin.java:840)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
        at com.amazonaws.mobile.client.internal.InternalCallback.access$000(InternalCallback.java:34)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:103)
        at java.lang.Thread.run(Thread.java:764)
```

I don't get this error when the single-valued `updateUserAttribute(...)` is called.

Thanks,
Vivek

**Comment by jamesonwilliams** [comment]
Looks like the AWSMobileClient is trying to invoke its error callback, but has already previously invoked its success callback.

I'm hesitant that this is a bug with the `core-kotlin` module itself, since that code is fairly cut-and-dry:

https://github.com/aws-amplify/amplify-android/blob/7dc76ee8ee635b217fed015a00fb93bfe6c846ee/core-kotlin/src/main/java/com/amplifyframework/kotlin/auth/KotlinAuthFacade.kt#L240-L249

Not immediately obvious to me from reading the SDK code how that could happen, though.

https://github.com/aws-amplify/aws-sdk-android/blob/8de48797ae2e5c157169a94746c768da7de61056/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L2602-L2624

**Comment by rjuliano** [comment]
Release with 1.17.7
