### ISSUE TITLE
App Crash when trying to save item to DataStore offline

### ISSUE THREAD

**Issue by rommank** [aws-amplify/amplify-android#1273]
If I go offline and try to save an item the app crashes.

aws-datastore: 1.17.2

```
    private fun addDevice() {
        val device = Device.builder()...
            .build()

        Amplify.DataStore.save(device,
            {},
            {
                Log.e("addDevice", "AddDevice error: ", it)
            }
        )
    }
```

```
FATAL EXCEPTION: OkHttp https://fnguccyr6nhmtdnniyxq6xpzte.appsync-api.eu-central-1.amazonaws.com/...
    Process: net.escalibre.myapplication, PID: 29980
    io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | DataStoreException{message=Failure during mutation., cause=ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}, recoverySuggestion=Check details.}
        at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:82)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$H2kP2N9w3X0gYQg1QzSwv0s9uXc.accept(Unknown Source:4)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$5(AppSyncClient.java:328)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$FfgHx1XvivjmTcZhtf9BjbrAq_M.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:156)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: DataStoreException{message=Failure during mutation., cause=ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}, recoverySuggestion=Check details.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$5(AppSyncClient.java:328) 
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$FfgHx1XvivjmTcZhtf9BjbrAq_M.accept(Unknown Source:4) 
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:156) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:156) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.amplifyframework.api.aws.UserAgentInterceptor.intercept(UserAgentInterceptor.java:56)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2021-04-07 15:00:26.366 29980-30150/net.escalibre.myapplication I/Process: Sending signal. PID: 29980 SIG: 9
```

**Comment by rommank** [comment]
Using coroutine instead is giving the same issue.

            lifecycleScope.launch {
                try {
                    val device = Device.builder()...
                        .build()
                    Amplify.DataStore.save(device)
                } catch (error: DataStoreException) {
                    Log.e("Error", error.toString())
                }
            }

**Comment by rommank** [comment]
Tried RxJava as well. No success.

         ```
   val device = Device.builder()...
                .build()

            RxAmplify.DataStore.save<Model>(device)
                .subscribe(
                    { Log.i("addDevice", "Saved a device.") }
                ) { failure: Throwable? ->
                    Log.e(
                        "addDevice",
                        "Save failed.",
                        failure
                    )
                }
```

**Comment by rommank** [comment]
@drochetti Could you please suggest any workaround if available?

**Comment by mathieuedet** [comment]
@rommank I use same version of SDK and test app with offline scenario. I reproduce this crash but not when offline, only when online AND network bandwidth is next to 0bps. When airplane mode is enabled or mobile data disabled, problem doesn't occur.

When you said "offline", are you connected to network without data or not connected ?

**Comment by rommank** [comment]
@mathieuedet  You are absolutely right. The issue appears ONLY when I am connected to network without data. 
I am able to catch an error and avoid the crash with:
        `RxJavaPlugins.setErrorHandler`
But, still, I have to relaunch the app or restart DataStore(stop followed by start) engine in order to sync the data.

**Comment by mathieuedet** [comment]
@rommank Thanks you very much for your solution. I'll test that now. Avoiding a crash is a good start 👍 Awaiting a fix

**Comment by frimfram** [comment]
The fix is merged.  Keeping this open until the commit is released.

**Comment by MandyFlutter** [comment]
The same thing happened to me but it was in places where the connection was low, what I did was increase the timeout of the save method within the same timeout method, you can add a function to it so that it does what you want in the event that the timeout that is given is met you defined using flutter eg:
await Amplify.DataStore.save(newitem)
                .timeout(const Duration(minutes: 2,()=> your function));
