### ISSUE TITLE
Amplify.configure() is failing when AWSCognitoAuthPlugin() is added as a plugin.

### ISSUE THREAD

**Issue by tomtaila-wesayhi** [aws-amplify/amplify-android#1316]
Description:
Amplify.configure() is failing when AWSCognitoAuthPlugin() is added as a plugin.

Here is my initialization logic from within my Application class:
```
 private fun initAmplify() {
        try {
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.configure(this)
            Log.i(logTag, "Initialized Amplify")
        } catch (error: AmplifyException) {
            Log.e(logTag, "Could not initialize Amplify", error)
        }
    }
```

Here is my gradle:
```
// Amplify core dependency
    implementation 'com.amplifyframework:core:1.17.4'
    implementation 'com.amplifyframework:rxbindings:1.17.4' // rx support
    implementation 'com.amplifyframework:aws-api:1.17.4'
    implementation 'com.amplifyframework:core-kotlin:0.1.2' // coroutine support
    implementation 'com.amplifyframework:aws-auth-cognito:1.17.4' // auth
    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
```
    
Here is my awsconfiguration.json file:
```
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "AppSync": {
        "Default": {
            "ApiUrl": "https://xxxxxxxxxxfakeurlxxxxxxxxxx",
            "Region": "us-east-2",
            "AuthMode": "API_KEY",
            "ApiKey": "xxxxxxxxxx",
            "ClientDatabasePrefix": "Kleo_API_KEY"
        },
        "Kleo_AWS_IAM": {
            "ApiUrl": "https://xxxxxxxxxxfakeurlxxxxxxxxxx",
            "Region": "us-east-2",
            "AuthMode": "AWS_IAM",
            "ClientDatabasePrefix": "Kleo_AWS_IAM"
        }
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-2:xxxxxxxxxx",
                "Region": "us-east-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-2xxxxxxxxxx
            "AppClientId": "xxxxxxxxxx",
            "Region": "us-east-2"
        }
    },
    "GoogleSignIn": {
        "Permissions": "email,profile,openid",
        "ClientId-WebApp": "xxxxxxxxxx"
    },
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "xxxxxxxxxx.auth.us-east-2.amazoncognito.com",
                "AppClientId": "xxxxxxxxxx",
                "SignInRedirectURI": "xxxxxxxxxx",
                "SignOutRedirectURI": "xxxxxxxxxx",
                "Scopes": [
                    "email",
                    "openid",
                    "profile"
                ]
            },
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    }
}
```

Here is my amplifyconfiguration.json file:
```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "api": {
    "plugins": {
      "awsAPIPlugin": {
        "Kleo": {
          "endpointType": "GraphQL",
          "endpoint": "xxxxxx",
          "region": "us-east-2",
          "authorizationType": "API_KEY",
          "apiKey": "xxxxxx"
        },
        "AdminQueries": {
          "endpointType": "REST",
          "endpoint": "xxxxxx",
          "region": "us-east-2",
          "authorizationType": "AMAZON_COGNITO_USER_POOLS"
        }
      }
    }
  },
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "AppSync": {
          "Default": {
            "ApiUrl": "xxxxxx",
            "Region": "us-east-2",
            "AuthMode": "API_KEY",
            "ApiKey": "xxxxxx",
            "ClientDatabasePrefix": "Kleo_API_KEY"
          },
          "Kleo_AWS_IAM": {
            "ApiUrl": "xxxxxx",
            "Region": "us-east-2",
            "AuthMode": "AWS_IAM",
            "ClientDatabasePrefix": "Kleo_AWS_IAM"
          }
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "xxxxxx",
              "Region": "us-east-2"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "xxxxxx",
            "AppClientId": "xxxxxx",
            "Region": "us-east-2"
          }
        },
        "GoogleSignIn": {
          "Permissions": "email,profile,openid",
          "ClientId-WebApp": "xxxxxx"
        },
        "Auth": {
          "Default": {
            "OAuth": {
              "WebDomain": "xxxxxx.auth.us-east-2.amazoncognito.com",
              "AppClientId": "xxxxxx",
              "SignInRedirectURI": "https://xxxxxx.com/sign-in/",
              "SignOutRedirectURI": "https://xxxxxx.com/",
              "Scopes": [
                "email",
                "openid",
                "profile"
              ]
            },
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  }
}
```

Here is the stacktrace of the error I get:
```
2021-05-12 17:17:31.414 5496-5496/com.wesayhi.app E/KleoApp: Could not initialize Amplify
    AuthException{message=Failed to instantiate AWSMobileClient, cause=com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoParameterInvalidException: error in parsing JSON, recoverySuggestion=See attached exception for more details}
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:242)
        at com.amplifyframework.core.category.Category.configure(Category.java:91)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:153)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:123)
        at com.wesayhi.app.KleoApp.initAmplify(KleoApp.kt:51)
        at com.wesayhi.app.KleoApp.onCreate(KleoApp.kt:31)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6715)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoParameterInvalidException: error in parsing JSON
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.util.CognitoJWTParser.getPayload(CognitoJWTParser.java:76)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.getUserIdFromToken(AWSCognitoAuthPlugin.java:1139)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.access$200(AWSCognitoAuthPlugin.java:107)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$1.onResult(AWSCognitoAuthPlugin.java:174)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$1.onResult(AWSCognitoAuthPlugin.java:163)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:75)
        at com.amazonaws.mobile.client.internal.InternalCallback.onResult(InternalCallback.java:62)
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:617)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:923)
```

And here is the relevant documentation regarding this:
https://docs.amplify.aws/lib/auth/getting-started/q/platform/android#initialize-amplify-auth

My iOS codebase has no issues running Amplify.configure() and is using the same configuration.json files

**Comment by taranabhangoo** [comment]
@tomtaila-wesayhi I had the same issue. You can first try to delete the app on the device and have a fresh install, Amplify should be able to configure properly then. 
If this doesn't work, try using the new sdk version of 1.17.5 and then creating a new backend with a fresh install of the app.

**Comment by tomtaila-wesayhi** [comment]
Yeah thank you @taranabhangoo when I attempted to install on a new device it worked fine
