### ISSUE TITLE
Amplify.configure() results in error when authentication plugin AWSCognitoAuthPlugin() is added

### ISSUE THREAD

**Issue by taranabhangoo** [aws-amplify/amplify-android#1323]
**Description:**
I want to add Facebook login to the app using amplify sdks in Android. We use user pools for authentication, so we decided to try social sign in with web UI.

I have set up the project on Android Studio as mentioned here : 
https://docs.amplify.aws/lib/project-setup/prereq/q/platform/android 
 
And I am able to set up the backend for authentication according to this doc: https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android#amazon-cognito-user-pool-setup 
 
However, I am getting an error at ‘Amplify.configure()’ in the main application class.

**Observations:**
-  If I don’t add ‘AWSCognitoAuthPlugin’ plugin to Amplify, then amplify is initialized properly.

**Details:**
SDK version: com.amplifyframework:aws-auth-cognito:1.17.4

Here is my awsconfiguration.json file:
```{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx”,
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "us-east-1_xxxxxxxxxxxxxx”,
            "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "Region": "us-east-1"
        }
    },
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.auth.us-east-1.amazoncognito.com",
                "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "SignInRedirectURI": "xxxxxxxxxxxxxx",
                "SignOutRedirectURI": "xxxxxxxxxxxxxx",
                "Scopes": [
                    "phone",
                    "email",
                    "openid",
                    "profile",
                    "aws.cognito.signin.user.admin"
                ]
            },
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    }
}
```

And this is the amplifyconfiguration.json file:
```{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_xxxxxxxxxxxxx",
                        "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.auth.us-east-1.amazoncognito.com",
                            "AppClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                            "SignInRedirectURI": "xxxxxxxxxxxxxxx",
                            "SignOutRedirectURI": "xxxxxxxxxxxxxx",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

**Error:**
```Could not initialize Amplify
    AuthException{message=Failed to instantiate AWSMobileClient, cause=java.lang.RuntimeException: Failed to initialize OAuth, please check your awsconfiguration.json, recoverySuggestion=See attached exception for more details}
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:242)
        at com.amplifyframework.core.category.Category.configure(Category.java:91)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:153)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:123)
        at com.example.MainApplication.onCreate(MainApplication.kt:70)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: Failed to initialize OAuth, please check your awsconfiguration.json
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:603)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidParameterException: validation failed
        at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.validateCognitoAuthParameters(Auth.java:546)
        at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.build(Auth.java:486)
        at com.amazonaws.mobile.client.AWSMobileClient._initializeHostedUI(AWSMobileClient.java:654)
        at com.amazonaws.mobile.client.AWSMobileClient.access$500(AWSMobileClient.java:163)
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:600)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidParameterException: {"AppCognitoWebDomain":"invalid"}
        at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.validateCognitoAuthParameters(Auth.java:543)
        at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.build(Auth.java:486) 
        at com.amazonaws.mobile.client.AWSMobileClient._initializeHostedUI(AWSMobileClient.java:654) 
        at com.amazonaws.mobile.client.AWSMobileClient.access$500(AWSMobileClient.java:163) 
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:600) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:919)```

**Comment by taranabhangoo** [comment]
I have even debugged with the aws support team over a screenshare session (support case number 8323128281), and they recommended to created a new application at a different location on local machine (as we suspected amplify could be holding on to a previous configuration file), but even that did not help. I am still getting the same error everytime.

**Comment by richardmcclellan** [comment]
That error indicates that the value for "WebDomain" in your config file does not match [this regex for a domain name](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/util/Patterns.java#309). 

I'm guessing you are including the scheme (`https://`), and that should _not_ be included, as that is added internally.  

Was the value for "WebDomain" auto generated, or did you manually edit the configuration file to add this `WebDomain`?

**Comment by taranabhangoo** [comment]
Yes, it was auto-generated after `amplify add auth` and `amplify push` commands. It does not have `https://` prefix to it.
The support engineers checked both the configuration files, and it looked good to them (support case number 8323128281).

I have tried starting fresh with amplify init and add auth, but it is the same error every time. 

Another observation: the validation of configuration files should append all the errors like `("AppClientId", "invalid")`. But even if I keep the app client id empty, I still only get web domain invalid error and not the app client id invalid error. So just wondering if sdk is getting is configuration data from somewhere other than the local files?

**Comment by taranabhangoo** [comment]
An update: I am able to resolve this issue with sdk version 1.17.5, creating a new backend, and a fresh install of app on the device.
