### ISSUE TITLE
Error in federating the token trying to sign in

### ISSUE THREAD

**Issue by buntupana** [aws-amplify/amplify-android#1333]
1. A **short** description: Getting `Error in federating the token` when I try to sign-in. Funcion `Amplify.Auth.signIn(username, password)` isn't throwing any exception or error and `result.isSignInComplete` is `true` but when check the status with `Amplify.Auth.fetchAuthSession()` the result is sign-out

2. The version of Amplify Android you're using
`amplify_version = '0.1.6'`
 `cognito_version = '1.17.4'`
3. The **code** you're using to call Amplify Android
``` kotlin
            try {
                Amplify.Auth.signIn(username, password).let { result ->
                    if (result.isSignInComplete) {
                        Timber.d("signIn success")
                    } else {
                        Timber.d("signIn failed")
                    }
                }
            } catch (exception: Exception) {
                Timber.e(exception)
                Timber.d("signIn error")
            }
```

4. Any relevant [logs](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#getting-more-output)

```
2021-05-24 10:56:16.519 21076-21137/com.example.login D/AWSMobileClient: _federatedSignIn: Putting provider and token in store
2021-05-24 10:56:16.534 21076-21137/com.example.login D/AWSMobileClient: Inspecting user state details
2021-05-24 10:56:16.534 21076-21137/com.example.login D/AWSMobileClient: hasFederatedToken: false provider: cognito-idp.eu-west-1.amazonaws.com/eu-west-XXXXXXXXX
2021-05-24 10:56:16.929 21076-21137/com.example.login W/AWSMobileClient: Failed to federate tokens during sign-in
    java.lang.RuntimeException: Error in federating the token.
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1740)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1668)
        at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1200)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1020)
        at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1185)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.amazonaws.services.cognitoidentity.model.ResourceNotFoundException: IdentityPool 'eu-west-1:XXXXXXXX' not found. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 6feab820-3733-4321-9242-ef4c970d9dd4)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.refresh(AWSMobileClient.java:3860)
        at com.amazonaws.auth.CognitoCredentialsProvider.retryRefresh(CognitoCredentialsProvider.java:723)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:691)
        at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:640)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:511)
        at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1771)
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1727)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115) 
        at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1668) 
        at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1200) 
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1020) 
        at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1185) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:923) 
```
5. Any relevant guides or documentation you're referencing

My `amplifyconfiguration.json` is imported from the ios app (which is working nicely)
```  json
 {
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "eu-west-1:XXXXXXXX",
              "Region": "eu-west-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "eu-west-XXXXXXXXX",
            "AppClientId": "XXXXXXXXXX",
            "Region": "eu-west-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  }
}
```
I found [this ticket] but not solution was provided(https://github.com/aws-amplify/aws-sdk-android/issues/942)

**Comment by buntupana** [comment]
@richardmcclellan I'm stuck because if this, is there any easy fix for this please?

**Comment by poojamat** [comment]
-The signin failure is caused by the following exception in your log: 
```
com.amazonaws.services.cognitoidentity.model.ResourceNotFoundException: IdentityPool 'eu-west-1:XXXXXXXX' not found. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 6feab820-3733-4321-9242-ef4c970d9dd4)

```
Could you please check if the resource exists in cognito?


- The amplifyconfiguration.json should not be copied over from another project, try running " amplify pull " from your android project instead.

**Comment by buntupana** [comment]
> -The signin failure is caused by the following exception in your log:
> 
> ```
> com.amazonaws.services.cognitoidentity.model.ResourceNotFoundException: IdentityPool 'eu-west-1:XXXXXXXX' not found. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 6feab820-3733-4321-9242-ef4c970d9dd4)
> ```
> 
> Could you please check if the resource exists in cognito?
> 
>     * The amplifyconfiguration.json should not be copied over from another project, try running " amplify pull " from your android project instead.

The ios app is using the same `IdentityPool` and can signin, actually signup is working without problem but signin is the problem here. Regarding to the `amplifyconfiguration.json` I've just copied the data from the ios file as the [documentation](https://docs.amplify.aws/lib/project-setup/use-existing-resources/q/platform/android) says
