### ISSUE TITLE
NullPointerException in SerializedModel toString() with has-many relationship between models.

### ISSUE THREAD

**Issue by JordanSekky** [aws-amplify/amplify-android#1340]
Hi, I'm receiving a NullPointerException in the toString() of the SerializedModel class when deleting a model instance, where model A has-many of B.

Using Amplify Android 1.17.6.

A little debugging reveals the issue is that the SerializedModel object created from an instance of the child/B model has a reference to a SerializedModel object of the parent model. In this (parent / A) object, `modelSchema` is null.

When `toString()` is called on the child object, it calls the `toString()` on the reference to the parent, which throws a nullpointer exception because modelSchema is null.

Crash Log:
```
W/amplify:aws-datastore: Error ended observation of mutation outbox: 
    io.reactivex.rxjava3.exceptions.CompositeException: 2 exceptions occurred. 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:92)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableResumeNext$ResumeNextObserver.onError(CompletableResumeNext.java:74)
        at io.reactivex.rxjava3.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:73)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableError.subscribeActual(CompletableError.java:29)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableResumeNext$ResumeNextObserver.onError(CompletableResumeNext.java:89)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onError(CompletableAndThenCompletable.java:62)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeFlatMapCompletable$FlatMapCompletableObserver.onError(MaybeFlatMapCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeCreate$Emitter.tryOnError(MaybeCreate.java:101)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:87)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$kiz4II4KbIBzRIogcFyXR5MEcPo.accept(Unknown Source:4)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:534)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
      ComposedException 1 :
    	DataStoreException{message=Error in deleting the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelSchema.getName()' on a null object reference, recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:530)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelSchema.getName()' on a null object reference
        at com.amplifyframework.datastore.appsync.SerializedModel.toString(SerializedModel.java:154)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at java.util.AbstractMap.toString(AbstractMap.java:559)
        at java.util.Collections$UnmodifiableMap.toString(Collections.java:1540)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.datastore.appsync.SerializedModel.toString(SerializedModel.java:151)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.datastore.syncengine.PendingMutation.toString(PendingMutation.java:247)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.datastore.syncengine.PersistentMutationOutbox.lambda$null$5$PersistentMutationOutbox(PersistentMutationOutbox.java:164)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$PersistentMutationOutbox$gQ88OCkWmjbGwYigK8qwL_mDxWg.accept(Unknown Source:10)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:526)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
      ComposedException 2 :
    	java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.amplifyframework.core.model.ModelSchema.getName()' on a null object reference
        at com.amplifyframework.datastore.appsync.SerializedModel.toString(SerializedModel.java:154)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at java.util.AbstractMap.toString(AbstractMap.java:559)
        at java.util.Collections$UnmodifiableMap.toString(Collections.java:1540)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.datastore.appsync.SerializedModel.toString(SerializedModel.java:151)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.datastore.syncengine.PendingMutation.toString(PendingMutation.java:247)
        at java.lang.String.valueOf(String.java:2924)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$processOutboxItem$10(MutationProcessor.java:171)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$3c9dUzW-gFMqVVIKbdVOxj29Y-A.accept(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:88)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableResumeNext$ResumeNextObserver.onError(CompletableResumeNext.java:74)
        at io.reactivex.rxjava3.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:73)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableError.subscribeActual(CompletableError.java:29)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableResumeNext$ResumeNextObserver.onError(CompletableResumeNext.java:89)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
W/amplify:aws-datastore:     at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onError(CompletableAndThenCompletable.java:62)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeFlatMapCompletable$FlatMapCompletableObserver.onError(MaybeFlatMapCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeCreate$Emitter.tryOnError(MaybeCreate.java:101)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:87)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$kiz4II4KbIBzRIogcFyXR5MEcPo.accept(Unknown Source:4)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:534)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$XngSjLlcHwo0KebM60Fw5B2MrsM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by rjuliano** [comment]
Fixed in 1.17.7
