### ISSUE TITLE
DataStore and API version 1.17.7 - observe by syncExpression array.contains crashed

### ISSUE THREAD

**Issue by michaelgust** [aws-amplify/amplify-android#1358]
I use DataStore with syncExpression 

 _.syncExpression( Message::class.java ) { Message.MEMBERS.contains( "XYZ" ) }_

where MEMBERS is implemented as Array<String>.

**Current behavior**

- All Queries works fine with this synExpression
- When I have started Amplify.DataStore.observe and get a new event the application crashed.
- I started the debugger with a break point in ContainsQueryOperator at the function evaluate()  and found out that for this function only an argument of type String is given. I had expected the argument type Array to.
- I got the follow Exception:

```
2021-06-04 18:55:57.909 22557-22612/com.example.myamplifyapp E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-2
    Process: com.example.myamplifyapp, PID: 22557
    io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: members field inside provided object cannot be evaluated by the operator type: CONTAINS
        at io.reactivex.rxjava3.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:156)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onError(ObservableFlatMapCompletableCompletable.java:125)
        at io.reactivex.rxjava3.internal.observers.DisposableLambdaObserver.onError(DisposableLambdaObserver.java:65)
        at io.reactivex.rxjava3.subjects.ReplaySubject$UnboundedReplayBuffer.replay(ReplaySubject.java:782)
        at io.reactivex.rxjava3.subjects.ReplaySubject.onError(ReplaySubject.java:385)
        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.lambda$baDcOAPYRoCcJg8VmByDb2fJo9E(Unknown Source:0)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$SubscriptionProcessor$baDcOAPYRoCcJg8VmByDb2fJo9E.accept(Unknown Source:4)
        at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:117)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onError(ObservableDoOnEach.java:117)
        at io.reactivex.rxjava3.internal.observers.DisposableLambdaObserver.onError(DisposableLambdaObserver.java:65)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalArgumentException: members field inside provided object cannot be evaluated by the operator type: CONTAINS
        at com.amplifyframework.core.model.query.predicate.QueryPredicateOperation.evaluate(QueryPredicateOperation.java:141)
        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.lambda$subscriptionObservable$8$SubscriptionProcessor(SubscriptionProcessor.java:231)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$SubscriptionProcessor$YOw2A6cN9GaUbIKehklooffucIg.test(Unknown Source:6)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:46)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2021-06-04 18:55:57.909 22557-22612/com.example.myamplifyapp E/AndroidRuntime: Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
        at com.amplifyframework.core.model.query.predicate.ContainsQueryOperator.evaluate(ContainsQueryOperator.java:23)
        at com.amplifyframework.core.model.query.predicate.QueryPredicateOperation.evaluate(QueryPredicateOperation.java:137)
        	... 13 more
```

**Comment by poojamat** [comment]
The AppSync "contains" operation does not support arrays. Please do not use Sync expressions. Update your model with code below:
```
 type Message @model {
@auth(rules: [
    # Allow the owner to CRUD
    { allow: owner },
    # Authorize members to read the message
    { allow: owner, ownerField: "members", operations: [read] },
  ])
  id: ID!
  text: String!
  members: [String]
}
```
This will restrict only the members to have read permissions
Here  is the documentation for static group authorization.
 https://docs.amplify.aws/cli/graphql-transformer/auth#static-group-authorization
With this the datastore will automatically only sync with what user is authorized to see.

Let us know if it doesn't solve your problem.

**Comment by michaelgust** [comment]
Hello,

In order to implement the proposed solution, I need a way to pass an argument (e.g. members) to the Amplify.DataStore.observe() function.
I use the Amplify library for Android. I have not found a way to do this there.
In the Amplify library for Android, on the other hand, there is the option of:

const id = '69ddcb63-7e4a-4325-b84d-8592e6dac07b';

const subscription = DataStore.observe(Post, id).subscribe(msg => {
  console.log(msg.model, msg.opType, msg.element);
});

With kind regards
Michael Gust

Von: poojamat ***@***.***>
Datum: Montag, 14. Juni 2021 um 23:46
An: aws-amplify/amplify-android ***@***.***>
Cc: Michael Gust ***@***.***>, Author ***@***.***>
Betreff: Re: [aws-amplify/amplify-android] DataStore and API version 1.17.7 - observe by syncExpression array.contains crashed (#1358)

The AppSync "contains" operation does not support arrays. Please do not use Sync expressions. Update your model with code below:

 type Message @model {

@auth(rules: [

    # Allow the owner to CRUD

    { allow: owner },

    # Authorize members to read the message

    { allow: owner, ownerField: "members", operations: [read] },

  ])

  id: ID!

  text: String!

  members: [String]

}

This will restrict only the members to have read permissions
Here is the documentation for static group authorization.
https://docs.amplify.aws/cli/graphql-transformer/auth#static-group-authorization
With this the datastore will automatically only sync with what user is authorized to see.

Let us know if it doesn't solve your problem.
