### ISSUE TITLE
Initial Sync Failed - Empty Response from AppSync

### ISSUE THREAD

**Issue by PS-MS** [aws-amplify/amplify-android#1383]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

GraphQL API, DataStore

### Gradle script dependencies

<details>

```groovy
    def amplify_version = "1.19.0"
    implementation 'com.amplifyframework:core-kotlin:0.3.0'
    implementation "com.amplifyframework:aws-storage-s3:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
    implementation "com.amplifyframework:aws-api:$amplify_version"
    implementation "com.amplifyframework:aws-datastore:$amplify_version"
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_265 (Amazon.com Inc. 25.265-b01)
OS:           Windows 10 10.0 amd64

```

</details>

### Describe the bug

Earlier this morning everything was working correctly and DataStore was returning results, Around 2pm GMT I started getting an error when running simple queries:

```
2021-06-22 15:43:41.021 8300-8394 E/amplify:aws-datastore: Error encountered in the DataStore.
    DataStoreException{message=Initial cloud sync failed., cause=DataStoreException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}, recoverySuggestion=Check your internet connection.}
        at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$createHydrationTask$7$SyncProcessor(SyncProcessor.java:163)
        at com.amplifyframework.datastore.syncengine.SyncProcessor$$ExternalSyntheticLambda21.accept(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:88)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:117)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle$ToSingle.onError(CompletableToSingle.java:73)
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:156)
        at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapCompletable$ConcatMapCompletableObserver.onError(FlowableConcatMapCompletable.java:129)
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:94)
        at io.reactivex.rxjava3.internal.util.HalfSerializer.onError(HalfSerializer.java:67)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.onError(FlowableConcatMap.java:199)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runBackfused(FlowableObserveOn.java:449)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:172)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: DataStoreException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}
        at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$null$14(SyncProcessor.java:272)
        at com.amplifyframework.datastore.syncengine.SyncProcessor$$ExternalSyntheticLambda11.accept(Unknown Source:4)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0(AppSyncClient.java:117)
        at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda4.accept(Unknown Source:6)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:147)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2021
```

This error would appear after every Amplify DataStore action such as below returns "Successful query, but no users":

```
Amplify.DataStore.query(User.class, Where.id(userId),
                queryMatches -> {
                    if (queryMatches.hasNext()) {
                        Log.i("MyAmplifyApp", "Successful query, found users.");
                        User thisUser = queryMatches.next();

                        userLiveData.postValue(thisUser);
                    } else {
                        Log.i("MyAmplifyApp", "Successful query, but no users.");
                    }
                },
                error -> Log.e("MyAmplifyApp",  "Error retrieving users", error)
        );
```

Note: Running the same query through Amplify.API works correctly.

**Comment by richardmcclellan** [comment]
Hi @PS-MS, it looks like this is the main issue:

```
DataStoreException{message=Empty response from AppSync., cause=null, recoverySuggestion=Report to AWS team.}
```

This is not an expected scenario.   Basically, AppSync always returns `errors`, `data`, or both, per the GraphQL specification, but in your case, it is returning neither.

> Earlier this morning everything was working correctly and DataStore was returning results.

Is the error still occurring now?  Is it reproduceable all the time or just sometimes?

> Note: Running the same query through Amplify.API works correctly.

FYI, using `Amplify.API` and `Amplify.DataStore` in the same app is not supported.  This is because `Amplify.DataStore` requires conflict detection to be _enabled_, while `Amplify.API` requires conflict detection to be _disabled_.  To enable conflict detection, run `amplify update api`, and then choose "Enable DataStore for entire API".

**Comment by PS-MS** [comment]
Good morning @richardmcclellan 

This is still happening, I read somewhere on here that configure no longer starts an initial sync so I've added in a datastore start with the configuration setup and still see the same message of an empty response, this happens every time the app tried to run the initial sync

```
        try {
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.addPlugin(AWSDataStorePlugin())
            Amplify.addPlugin(AWSS3StoragePlugin())
            Amplify.configure(applicationContext)
            Amplify.DataStore.start(
                { Log.i("DataStoreStart", "onCreate: started")},
                { Log.e("DataStoreStart", "onCreate: Failed!", )}
            )
        } catch(error: AmplifyException) {
            Log.e("MainActivity", "onCreate: $error")
        }
```

**Comment by richardmcclellan** [comment]
> This is still happening

Given that this was working before, can you identify what changes you made, if any, between when it was working and when it wasn't?  

> configure no longer starts an initial sync

This is true.  However, calling any DataStore operation (`query(...)`, `save(...)`, `observe(...)`, or `delete(...)`) will also start the sync process, so calling `Amplify.DataStore.start(...)` is not explicitly necessary.

**Comment by richardmcclellan** [comment]
I would also suggest [enabling logging on your AppSync API](https://docs.aws.amazon.com/appsync/latest/devguide/monitoring.html), and then checking the CloudWatch logs to see if the response body contains the expected data, or errors.

**Comment by PS-MS** [comment]
During some major schema changes the environment was updated and conflict detection was disabled causing the initial sync to fail, thank you for the below comment it really helped point us in the right direction.

> FYI, using Amplify.API and Amplify.DataStore in the same app is not supported. This is because Amplify.DataStore requires conflict detection to be enabled, while Amplify.API requires conflict detection to be disabled. To enable conflict detection, run amplify update api, and then choose "Enable DataStore for entire API".
