### ISSUE TITLE
aws-datastore: Failure encountered while attempting to start API sync.

### ISSUE THREAD

**Issue by marenero1974** [aws-amplify/amplify-android#1392]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy

// Put output below this line


```

</details>
implementation 'com.amplifyframework:aws-datastore:1.20.0'

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am facing this:

```
2021-06-28 15:18:44.781 25773-26364/ E/amplify:aws-datastore: Failure encountered while attempting to start API sync.
    DataStoreException{message=Error during subscription., cause=ApiException{message=Connection failed., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:329)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$797ziDK0io-qXODzROLOA77stS8.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$null$1$SubscriptionOperation(SubscriptionOperation.java:87)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$l9lC7Ew6niNmyszMXQSUKS6YhwE.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:144)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$2$SubscriptionOperation(SubscriptionOperation.java:77)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$dV6kPdbE8Z12Qd0_rE-16cujgUk.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: ApiException{message=Connection failed., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:145)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$2$SubscriptionOperation(SubscriptionOperation.java:77) 
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$dV6kPdbE8Z12Qd0_rE-16cujgUk.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929)
``` 

while starting mi app and connecting with datastore,
What should be the problem?

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by rjuliano** [comment]
Your issue could be caused by a connectivity issue or something with the configuration file. Did you setup the amplify project via the CLI? Can you provide code snippets of how you're initializing Amplify in your app and also how you're starting DataStore? Are there any other messages in the log?

**Comment by marenero1974** [comment]
@rjuliano yes i set up amplify project via CLI. i did follow the instructions on the amplify web site: https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android#option-1-platform-integration. Then i am initializing in my app like this:
```
            Amplify.addPlugin(new AWSApiPlugin()); // UNCOMMENT this line once backend is deployed
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.addPlugin(new AWSDataStorePlugin());
            Amplify.configure(getApplicationContext());
```


and this logs are written a little after the first exception:

```
2021-06-28 16:05:33.615 32442-866/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.620 32442-875/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.630 32442-32665/ D/SharedPreferencesImpl: Time required to fsync /data/user/0//shared_prefs/com.google.android.gms.measurement.prefs.xml: [<1: 0, <2: 0, <4: 0, <8: 0, <16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 0, <1024: 0, <2048: 0, <4096: 1, <8192: 0, <16384: 0, >=16384: 0]
2021-06-28 16:05:33.637 32442-32659/ D/TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lDY2traUg4aTJaQVJ3T3MxTEV6RktsZDE1YU9HOG96S28=) is already scheduled. Returning...
2021-06-28 16:05:33.644 32442-876/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.649 32442-881/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.655 32442-882/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.666 32442-886/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.686 32442-890/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.693 32442-1002/ W/: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2021-06-28 16:05:33.706 32442-888/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.733 32442-1002/ W/: Accessing hidden method Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe; (greylist,core-platform-api, linking, allowed)
2021-06-28 16:05:33.736 32442-887/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.736 32442-1002/ W/: Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
2021-06-28 16:05:33.736 32442-1002/ W/: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
2021-06-28 16:05:33.741 32442-892/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.747 32442-945/ W/amplify:aws-api: Websocket connection failed.
    java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2021-06-28 16:05:33.750 32442-897/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.783 32442-898/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.797 32442-906/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.803 32442-915/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.818 32442-916/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.871 32442-32754/ W/: Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
2021-06-28 16:05:33.877 32442-32754/ W/: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
2021-06-28 16:05:33.877 32442-32442/ I/Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
2021-06-28 16:05:33.881 32442-32442/ I/HwViewRootImpl: removeInvalidNode jank list is null
2021-06-28 16:05:33.888 32442-927/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.904 32442-936/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.919 32442-32754/ W/: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
2021-06-28 16:05:33.939 32442-32754/ W/: Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
2021-06-28 16:05:33.940 32442-937/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.990 32442-938/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:33.996 32442-32659/ D/TransportRuntime.CctTransportBackend: Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
2021-06-28 16:05:34.040 32442-940/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:34.087 32442-942/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:34.087 32442-32665/ D/SharedPreferencesImpl: Time required to fsync /data/user/0//shared_prefs/FirebasePerfSharedPrefs.xml: [<1: 0, <2: 0, <4: 0, <8: 0, <16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 1, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
2021-06-28 16:05:34.118 32442-32754/ W/: Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
2021-06-28 16:05:34.144 32442-943/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:34.154 32442-944/ W/amplify:aws-api: Thread interrupted waiting for connection acknowledgement
2021-06-28 16:05:34.224 32442-32754/ W/: Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
2021-06-28 16:05:34.224 32442-32754/ W/: Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
2021-06-28 16:05:34.225 32442-32682/ V/FA: Connection attempt already in progress
2021-06-28 16:05:34.256 32442-1116/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.272 32442-1114/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.272 32442-1123/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.279 32442-1127/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.284 32442-1128/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.290 32442-945/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.293 32442-1112/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.294 32442-1122/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.296 32442-1137/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.305 32442-1121/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.308 32442-1135/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.312 32442-1120/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.312 32442-1119/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.331 32442-1125/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.334 32442-1134/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.343 32442-1144/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.346 32442-32682/ V/FA: Connection attempt already in progress
2021-06-28 16:05:34.357 32442-32754/ W/: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
2021-06-28 16:05:34.358 32442-32754/ W/: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
2021-06-28 16:05:34.359 32442-32653/ D/FirebasePerformance: CollectionEnabled metadata key unknown or value not found in manifest.
2021-06-28 16:05:34.359 32442-32754/ W/: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
2021-06-28 16:05:34.359 32442-32754/ W/: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
2021-06-28 16:05:34.359 32442-32754/ W/: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
2021-06-28 16:05:34.359 32442-32754/ W/: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
2021-06-28 16:05:34.359 32442-32653/ D/FirebasePerformance: Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
2021-06-28 16:05:34.360 32442-32653/ D/FirebasePerformance: Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
2021-06-28 16:05:34.367 32442-32653/ W/: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
2021-06-28 16:05:34.368 32442-32653/ D/FirebasePerformance: CollectionEnabled metadata key unknown or value not found in manifest.
2021-06-28 16:05:34.368 32442-32653/ D/FirebasePerformance: Fetched value: 'true' for key: 'fpr_enabled' from Firebase Remote Config.
2021-06-28 16:05:34.368 32442-32653/ D/FirebasePerformance: Fetched value: '' for key: 'fpr_disabled_android_versions' from Firebase Remote Config.
2021-06-28 16:05:34.373 32442-32754/ W/: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
2021-06-28 16:05:34.373 32442-1150/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.375 32442-32754/ W/: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
2021-06-28 16:05:34.376 32442-32754/ W/: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
2021-06-28 16:05:34.377 32442-1146/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.380 32442-32653/ D/FirebasePerformance: Fetched value: '1.0' for key: 'fpr_vc_network_request_sampling_rate' from Firebase Remote Config.
2021-06-28 16:05:34.382 32442-32653/ I/FirebasePerformance: Logging network request trace: https://graph.facebook.com/v5.0/288671402500317/model_asset (responseCode: 200, responseTime: 498.3150ms)
2021-06-28 16:05:34.401 32442-1002/ W/: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
2021-06-28 16:05:34.401 32442-1002/ W/: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
2021-06-28 16:05:34.432 32442-1152/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.439 32442-1154/ W/amplify:aws-api: Websocket listener received a CONNECTION_ERROR event. {"payload":{"errors":[{"errorType":"com.amazonaws.deepdish.graphql.auth#UnauthorizedException","message":"You are not authorized to make this call.","errorCode":400}]},"type":"connection_error"}
2021-06-28 16:05:34.444 32442-32463/ I/: Background young concurrent copying GC freed 109276(5787KB) AllocSpace objects, 14(796KB) LOS objects, 10% free, 12MB/14MB, paused 14ms total 403.391ms
2021-06-28 16:05:34.451 32442-1116/ W/amplify:aws-api: Websocket connection failed.
    java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
```

**Comment by rjuliano** [comment]
What did you choose as default auth type when creating the API? Does your schema define [authorization rules](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/android)?

The `UnauthorizedException` typically indicates that the default authorization type does not have the necessary permissions to interact with the type defined in the schema. For example: if you chose API key for default auth type, but setup your schema to require owner authorization.

**Comment by marenero1974** [comment]
I chose API for default auth type, and never changed my schema manually or something else, it has worked since yesterday and i set up auth 3 months ago, showd i have to udpate auth again?

**Comment by rjuliano** [comment]
Check and see if the API key has expired. If that's the case, you can rotate it by following [these instructions.](https://docs.amplify.aws/cli/graphql-transformer/config-params#createapikey)

**Comment by marenero1974** [comment]
@rjuliano yes it was due to the expiration, thanks
