### ISSUE TITLE
Cannot signin (ios app works)

### ISSUE THREAD

**Issue by mariuspena** [aws-amplify/amplify-android#1396]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:core:1.20.0'
implementation 'com.amplifyframework:aws-auth-cognito:1.20.0'
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

```

</details>

### Environment information

<details>

```
# Put output below this line

Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_91 (Oracle Corporation 25.91-b14)
OS:           Mac OS X 10.16 x86_64

```

</details>

### Describe the bug

`Amplify.Auth.signIn(username, password)` returns isSignInComplete true. but Amplify.Auth.currentUser is null
```
AuthSignInResult{isSignInComplete=true, nextStep=AuthNextSignInStep{signInStep=DONE, additionalInfo={}, codeDeliveryDetails=null}}
```

`Amplify.Auth.fetchAuthSession` replies with (before and after signIn)
```
AWSCognitoAuthSession{isSignedIn=false, awsCredentials=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=If you have guest access enabled, please check that your device is online and try again. Otherwise if guest access is not enabled, you'll need to sign in and try again.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}',....
```

**ios app runs just fine.**

my amplifyconfiguration.json is this
```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "eu-west-1_xxxxxxxxx",
              "Region": "eu-west-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "eu-west-1_xxxxxxxxx",
            "AppClientId": "yyyyYYYyyyYYyyyYYyyyYY",
            "AppClientSecret": "zzzZZZzzzZZZzzzzzzZZZzZZzzzzzZZZzzzZZZ",
            "Region": "eu-west-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_PASSWORD_AUTH"
          }
        }
      }
    }
  }
}
```

### Reproduction steps (if applicable)

followed the exact documentation
1. I add the auth plugin
2. I configure Amplify with app context
3. run Amplify.Auth.signIn and Amplify.Auth.fetchAuthSession
...

### Code Snippet

```kotlin
// Put your code below this line.
Amplify.Auth.signIn(username, password,
            { result: AuthSignInResult ->
                progressSubject.onNext(false)
                loginResultSubject.onNext(result.isSignInComplete)
                if (result.isSignInComplete) {

                    Log.i("AuthQuickstart", "Sign in succeeded ")
                    if (Amplify.Auth.currentUser != null)
                        Log.i("AuthQuickstart", Amplify.Auth.currentUser.username)

                } else {
                    Log.i("AuthQuickstart", "Sign in not complete")
                }
            },
            { authException: AuthException ->
                progressSubject.onNext(false)
                loginResultSubject.onNext(false)
                errorSubject.onNext(authException)
                Log.e("AuthQuickstart", "Failed to sign in", authException)
            }
        )
```

### Log output

<details>

```
D/AWSMobileClient: Using the SignInProviderConfig from `awsconfiguration.json`. 
...... ^ something wrong here because I just have the amplifyconfiguration.json

D/AWSMobileClient: hasFederatedToken: false provider: cognito-idp.eu-west-1.amazonaws.com/eu-west-1_xxxxxxxxx

W/AWSMobileClient: Failed to federate tokens during sign-in
    java.lang.RuntimeException: Error in federating the token.
 at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1803)
...
Caused by: com.amazonaws.AmazonServiceException: 1 validation error detected: Value 'eu-west-1_eudw64F6W' at 'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+ (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ValidationException; Request ID: 6bc02952-57b5-44a0-a215-c80ac72af575)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)


```

</details>

### amplifyconfiguration.json
```json
{
   "auth":{
      "plugins":{
         "awsCognitoAuthPlugin":{
            "IdentityManager":{
               "Default":{
                  
               }
            },
            "CredentialsProvider":{
               "CognitoIdentity":{
                  "Default":{
                     "PoolId":"eu-west-1_xxxxxxxxx",
                     "Region":"eu-west-1"
                  }
               }
            },
            "CognitoUserPool":{
               "Default":{
                  "PoolId":"eu-west-1_xxxxxxxxx",
                  "AppClientId":"xxxxxxxxxxxxxxxxxxxxxxxxxxx",
                  "AppClientSecret":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                  "Region":"eu-west-1"
               }
            },
            "Auth":{
               "Default":{
                  "authenticationFlowType":"USER_PASSWORD_AUTH"
               }
            }
         }
      }
   }
}

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by mariuspena** [comment]
aws console 
General Settings > App Clients - I can see the app client id and secret and flow configs
App integration > App Client Settings - found my client id > "select all" check is on, "Cognito User Pool" check is on

I think my problem is in the amplifyconfiguration.json

json "CredentialsProvider":{ "CognitoIdentity":{ "Default":{ "PoolId":"eu-west-1_xxxxxxxxx", "Region":"eu-west-1" } } }
because "PoolId":"eu-west-1_xxxxxxxxx" should resemble "us-west-1:123e4567-e89b-12d3-a456-426614174000", right ?

**Comment by mariuspena** [comment]
If I delete this from amplifyconfiguration.json
`"CredentialsProvider":{
               "CognitoIdentity":{
                  "Default":{
                     "PoolId":"eu-west-1_eudw64F6W",
                     "Region":"eu-west-1"
                  }
               }
            },`

the result is:
1. I login, result is ok, currentUser is ok (not null, has userId, has username)
2. I call fetchAuthSession just to be sure and result (casted to AWSCognitoAuthSession just like in the docs) has these errors: 
- awsCredentials : AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=com.amazonaws.AmazonClientException: Cognito Identity not configured, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}
- identityId : AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=com.amazonaws.AmazonClientException: Cognito Identity not configured, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}
>>>>>> hence it is a failure according to the code snippet from docs : 
`kotlin
val cognitoAuthSession = authSession as AWSCognitoAuthSession
                when (cognitoAuthSession.identityId.type) {
                    AuthSessionResult.Type.SUCCESS ->
                        Log.i("AuthQuickStart", "IdentityId: " + cognitoAuthSession.identityId.value)
                    AuthSessionResult.Type.FAILURE ->
                        Log.i("AuthQuickStart", "IdentityId not present because: " + cognitoAuthSession.identityId.error.toString())
                }
`

**Comment by mariuspena** [comment]
so we added an identity pool linked to cognito and got the id for that and it works. thanks
