### ISSUE TITLE
DataStoreException: Failed to start DataStore.

### ISSUE THREAD

**Issue by woutermilants** [aws-amplify/amplify-android#1403]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "be.milants.loonskleinfruit2021"
        minSdkVersion 25
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    implementation 'com.amplifyframework:aws-api:1.20.0'
    implementation 'com.amplifyframework:aws-datastore:1.20.0'

    implementation files('libs/platform_sdk_v3.0.0514.jar')
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.0.1'
}


```

</details>

### Environment information

<details>

```
# Put output below this line

Welcome to Gradle 6.5!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5/release-notes.html


------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          15.0.1 (Oracle Corporation 15.0.1+9-18)
OS:           Linux 5.4.0-52-generic amd64


```

</details>

### Describe the bug

App has been working without issues for a few weeks now.
Without a clear cause I'm no longer able to interact with the datastore. 
I cant start the datastore so I can't even query the local datastore. 

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
07/06 22:33:33: Launching 'app' on Unitech EA602.
Install successfully finished in 9 s 121 ms.
$ adb shell am start -n "be.milants.loonskleinfruit2021/be.milants.loonskleinfruit2021.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 32617 on device 'unitech-ea602-06025042960193'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/System: ClassLoader referenced unknown path: /data/app/be.milants.loonskleinfruit2021-1/lib/arm64
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/LoonsKleinFruit: Initialized Amplify
I/amplify:aws-datastore: Orchestrator lock acquired.
D/ScanManager: ScanManager , --------- mService:android.os.IScanService$Stub$Proxy@5b12427
I/ScanManager: resetScannerParameters......[0]
I/amplify:aws-datastore: Orchestrator transitioning from STOPPED to SYNC_VIA_API
    Starting to observe local storage changes.
W/CursorWindow: Window is full: requested allocation 3588 bytes, free space 934 bytes, window size 2097152 bytes
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
    mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
    mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
    mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@1383288
    BoostFramework() : mPerf = com.qualcomm.qti.Performance@1832421
I/art: Do partial code cache collection, code=30KB, data=28KB
I/art: After code cache collection, code=30KB, data=28KB
    Increasing code cache capacity to 128KB
E/LoonsKleinFruit: Observation failed.
    DataStoreException{message=Failed to start DataStore., cause=DataStoreException{message=Timed out while starting to observe storage changes., cause=java.util.concurrent.TimeoutException: Timed out while preparing local-only mode., recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}, recoverySuggestion=Retry.}
        at com.amplifyframework.datastore.AWSDataStorePlugin.lambda$start$11(AWSDataStorePlugin.java:293)
        at com.amplifyframework.datastore.-$$Lambda$AWSDataStorePlugin$cggRMfd1LBrEzQR62lPbVtwdUwY.accept(lambda)
        at io.reactivex.rxjava3.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:64)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableDoFinally$DoFinallyObserver.onError(CompletableDoFinally.java:72)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableDoFinally.subscribeActual(CompletableDoFinally.java:43)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout$TimeOutObserver.onComplete(CompletableTimeout.java:87)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:47)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout.subscribeActual(CompletableTimeout.java:53)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: DataStoreException{message=Timed out while starting to observe storage changes., cause=java.util.concurrent.TimeoutException: Timed out while preparing local-only mode., recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
        at com.amplifyframework.datastore.syncengine.Orchestrator.startObservingStorageChanges(Orchestrator.java:277)
        at com.amplifyframework.datastore.syncengine.Orchestrator.transitionToApiSync(Orchestrator.java:251)
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$start$0$Orchestrator(Orchestrator.java:158)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$qjDvX8bU79JsBLU0hHve6y1vGzc.run(lambda)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:36)
        	... 20 more
     Caused by: java.util.concurrent.TimeoutException: Timed out while preparing local-only mode.
        at com.amplifyframework.datastore.syncengine.Orchestrator.startObservingStorageChanges(Orchestrator.java:274)
        	... 24 more
I/amplify:aws-datastore: Orchestrator lock released.
I/amplify:aws-datastore: Orchestrator lock acquired.
I/MyAmplifyApp: saving: 
I/System.out: Tue Jul 06 22:33:46 GMT+02:00 2021
I/amplify:aws-datastore: Orchestrator transitioning from STOPPED to SYNC_VIA_API
    Starting to observe local storage changes.
I/art: Do partial code cache collection, code=61KB, data=47KB
I/art: After code cache collection, code=60KB, data=46KB
    Increasing code cache capacity to 256KB
I/MyAmplifyApp: saving: 
I/System.out: Tue Jul 06 22:33:48 GMT+02:00 2021
E/MyAmplifyApp: Query failed.
    DataStoreException{message=Failed to start DataStore., cause=DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}, recoverySuggestion=Retry.}
        at com.amplifyframework.datastore.AWSDataStorePlugin.lambda$start$11(AWSDataStorePlugin.java:293)
        at com.amplifyframework.datastore.-$$Lambda$AWSDataStorePlugin$cggRMfd1LBrEzQR62lPbVtwdUwY.accept(lambda)
        at io.reactivex.rxjava3.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:64)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
        at io.reactivex.rxjava3.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:73)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableError.subscribeActual(CompletableError.java:29)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout$TimeOutObserver.onComplete(CompletableTimeout.java:87)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:47)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout.subscribeActual(CompletableTimeout.java:53)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}
        at com.amplifyframework.datastore.syncengine.Orchestrator.performSynchronized(Orchestrator.java:180)
        at com.amplifyframework.datastore.syncengine.Orchestrator.start(Orchestrator.java:152)
        at com.amplifyframework.datastore.AWSDataStorePlugin.start(AWSDataStorePlugin.java:289)
        at com.amplifyframework.datastore.AWSDataStorePlugin.query(AWSDataStorePlugin.java:476)
        at com.amplifyframework.datastore.DataStoreCategory.query(DataStoreCategory.java:135)
        at helper.DataStoreService.getLocations(DataStoreService.java:251)
        at helper.DataStoreService.getUniqueLocations(DataStoreService.java:291)
        at be.milants.loonskleinfruit2021.MainActivity.onCreate(MainActivity.java:67)
        at android.app.Activity.performCreate(Activity.java:6723)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/MyAmplifyApp:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by div5yesh** [comment]
@woutermilants Thank you for posting the issue.

Can you share the code snippets that you have in your app related to datastore calls and `amplifyconfiguration.json` with sensitive information removed?

**Comment by woutermilants** [comment]
```

        Amplify.DataStore.query(TimeRegistration.class, Where.matches(TimeRegistration.SCAN_DATE.eq("01/07/2021").or(TimeRegistration.SCAN_DATE.eq("02/07/2021")
                        .or(TimeRegistration.SCAN_DATE.eq("03/07/2021")).or(TimeRegistration.SCAN_DATE.eq("04/07/2021")).or(TimeRegistration.SCAN_DATE.eq("05/07/2021")))),
                foundScanned -> {
                    while (foundScanned.hasNext()) {
                        Log.i("Test", foundScanned.next().toString());
                        Amplify.DataStore.delete(foundScanned.next(), success -> Log.i("success", "success"), failed -> Log.i("failed", "failed"));
                        TimeRegistration next = foundScanned.next();
                    }
                }, failure -> Log.e("MyAmplifyApp", "Query failed.", failure));
```

amplifyconfiguration.json
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "amplifyDatasource": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxxxxxxxxxxxxxxxxx.appsync-api.eu-west-1.amazonaws.com/graphql",
                    "region": "eu-west-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "xxxxxxxxxxxxxxxxxx"
                }
            }
        }
    }
}
```

**Comment by woutermilants** [comment]
Any things I can try to debug ? I can't remove the app cause I don't want to lose the local data ...

**Comment by div5yesh** [comment]
You can turn on the debug and verbose logs by using the below statement in your app.

```java
Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))
```

You also can enable [developer](https://docs.amplify.aws/lib/debugging/dev-menu/q/platform/android) menu.

**Comment by mjbrown-msee** [comment]
I had a similar error.  My app worked for several days and then started mysteriously failing to start DataStore.  It was a SocketTimeoutError on the sync request.  After using your logging recommendation, I was able to deduce the source of the problem.

Once the database got loaded up with a LOT of data, the Scan during the sync request was taking too long.  I changed the SyncExpression to a global secondary index (GSI) so that it would use a Query instead of a Scan, then DataStore started working again.

Maybe the timeout should be extended?  Maybe the SocketTimeoutError on the SyncRequest could be rewritten offer more useful advice?

**Comment by benwicks** [comment]
@mjbrown-msee I am facing a similar problem. Could you please demonstrate how you made that change to get your DataStore working again? Thanks

**Comment by sach16795** [comment]
I am facing the same problem. Is there any update on this issue?

**Comment by rjuliano** [comment]
To limit the amount of data getting sync'd you can try to use sync expressions

https://docs.amplify.aws/lib/datastore/sync/q/platform/android/#selectively-syncing-a-subset-of-your-data

**Comment by joekiller** [comment]
We are hunting this same issue actively.

**Comment by joekiller** [comment]
From what I can tell, this error occurs when minify is enabled in the build. Starting to observe local storage changes. is the last message. then timeout.

**Comment by joekiller** [comment]
FWIW, when we enabled minifiy with AGP 7.0.2 our sync was failing due to a conflict with android json and org.json calls. I think prior our AGP was 4.0 so the Proguard was hitting it instead of R8. Anyway, we plugged `-keep class org.json.**` into the proguard rules to fix. this [stackoverflow](https://stackoverflow.com/questions/65077282/why-does-minify-cause-error-jsonobjectrewards-not-a-string) was helpful but it was a slog through the APK diff. So I'll end my hijack there.

As for other timeouts, typically you can put in your config `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))` or something to that effect and then see in your logs all the Sync queries that go out. Those are the first that run against the AppSync api backend. You can also go to the [appsync console](https://console.aws.amazon.com/appsync/home) and try running the query yourself.

> query SyncExampleModels($filter: ModelExampleMoelFilterInput, $lastSync: AWSTimestamp, $limit: Int) { ... rest of it }

You can plug that query into your graphql backend and see if it takes too long. The query itself is string quoted, I usually copy the string and the run `console.log("query..")` in my closest browser console or node console. If the query is taking a while but returning remember 10 seconds is the default timeout and the service can support up to 30 seconds. So the query can work on the console but not for the default application timeouts.

If it just takes a little longer you could [consider lengthening your timeouts](https://github.com/aws-amplify/amplify-android/blob/682c9e778adac74c2261bce4de4866c5e255a5eb/aws-api/src/main/java/com/amplifyframework/api/aws/OkHttpConfigurator.java#L37-L48) but I've found it really means the access pattern is unsustainable so you'll likely need a query operation instead of scan.

Sometimes if your models are too big the default page size of 1000 could exhaust your GraphQL max response size of 5MB as well. That size can be adjust with the sync query builder page size limit. This typically happens when the system at first can only get <1000 results back but after a lot of use the size exhausts the response size and the sync will fail.

**Comment by poojamat** [comment]
Are you guys still facing this problem?

**Comment by babyitachi** [comment]
problem still persists while initialization of the app
