### ISSUE TITLE
Getting timeout exception on uploading file to s3 file size is just (666 KB) Android 10

### ISSUE THREAD

**Issue by iamAliRaza** [aws-amplify/amplify-android#1455]
Hi Guyz,

I am trying to upload video file. File size is just 666 Kb and duration is 7 seconds.
File **successfully uploading** but still getting this exception.
Any Solution please.

I/com.dancers.hu: Background young concurrent copying GC freed 85519(3895KB) AllocSpace objects, 34(3424KB) LOS objects, 38% free, 12MB/19MB, paused 575us total 109.898ms
W/System.err: StorageException{message=Something went wrong with your AWS S3 Storage upload file operation, cause=com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout, recoverySuggestion=See attached exception for more information and suggestions}
W/System.err:     at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:203)
W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:306)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:888)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err:     at android.os.Looper.loop(Looper.java:213)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8178)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
W/System.err: Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456)
W/System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4829)
W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1912)
W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:282)
W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:114)
W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:929)
W/System.err: Caused by: java.net.SocketTimeoutException: timeout
W/System.err:     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
W/System.err:     at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
W/System.err:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
W/System.err:     at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
W/System.err:     at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
W/System.err:     at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:538)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:110)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:30)
W/System.err:     at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
W/System.err:     at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:386)
W/System.err: 	... 10 more
W/System.err: Caused by: java.net.SocketException: socket is closed
W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:554)
W/System.err:     at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
W/System.err:     at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
W/System.err: 	... 25 more

**Comment by iamAliRaza** [comment]
okay so the reason was Network issue like high latency, packet loss.. I changed my internet to high speed its start working...

If packets are dropped because of a slow or poor network connection, then S3 waits for the expected number of bytes to be received. If the connection is idle for 20 seconds or longer, then S3 closes the connection and returns the 400 RequestTimeout error. 

https://aws.amazon.com/premiumsupport/knowledge-center/s3-socket-connection-timeout-error/
