### ISSUE TITLE
Timed out while performing initial model sync

### ISSUE THREAD

**Issue by xuaninbox** [aws-amplify/amplify-android#1458]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
AmplifyCore = 1.20.0;
AmplifyDataStore = 1.20.0;
AmplifyAWSRxBindings = 1.20.0;
AmplifyAWSApi = 1.20.0;


```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_301 (Oracle Corporation 25.301-b09)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Describe the bug

We are getting a error about sync failed:

<details>

```
2021-08-20 13:16:23.219 11183-11183/com.amazon.rabbit.gamma I/Amplify: [main] Amplify initialized
2021-08-20 13:16:23.242 11183-11183/com.amazon.rabbit.gamma I/amplify:aws-datastore: Orchestrator lock acquired.
2021-08-20 13:16:23.323 11183-11553/com.amazon.rabbit.gamma I/amplify:aws-datastore: Orchestrator transitioning from STOPPED to SYNC_VIA_API
2021-08-20 13:16:23.323 11183-11553/com.amazon.rabbit.gamma I/amplify:aws-datastore: Starting to observe local storage changes.
2021-08-20 13:16:23.382 11183-11569/com.amazon.rabbit.gamma I/amplify:aws-datastore: Now observing local storage. Local changes will be enqueued to mutation outbox.
2021-08-20 13:16:23.383 11183-11569/com.amazon.rabbit.gamma I/amplify:aws-datastore: Setting currentState to LOCAL_ONLY
2021-08-20 13:16:23.386 11183-11553/com.amazon.rabbit.gamma I/amplify:aws-datastore: Setting currentState to SYNC_VIA_API
2021-08-20 13:16:23.387 11183-11552/com.amazon.rabbit.gamma I/amplify:aws-datastore: Starting API synchronization mode.
2021-08-20 13:16:23.387 11183-11553/com.amazon.rabbit.gamma I/Amplify: [RxCache-b1] Amplify started
2021-08-20 13:16:23.387 11183-11553/com.amazon.rabbit.gamma I/amplify:aws-datastore: Orchestrator lock released.
2021-08-20 13:16:23.398 11183-11552/com.amazon.rabbit.gamma I/amplify:aws-datastore: Starting processing subscription events.
2021-08-20 13:16:25.308 11183-11552/com.amazon.rabbit.gamma I/amplify:aws-datastore: Started subscription processor for models: [Configuration] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
2021-08-20 13:17:25.324 11183-11552/com.amazon.rabbit.gamma E/amplify:aws-datastore: Failure encountered while attempting to start API sync.
    DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.util.concurrent.TimeoutException: Timed out while performing initial model sync., recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3(Orchestrator.java:323)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.util.concurrent.TimeoutException: Timed out while performing initial model sync.
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3(Orchestrator.java:319)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(Unknown Source:2) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2021-08-20 13:17:25.326 11183-11552/com.amazon.rabbit.gamma W/amplify:aws-datastore: API sync failed - transitioning to LOCAL_ONLY.
    DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.util.concurrent.TimeoutException: Timed out while performing initial model sync., recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3(Orchestrator.java:323)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.util.concurrent.TimeoutException: Timed out while performing initial model sync.
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3(Orchestrator.java:319)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(Unknown Source:2) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2021-08-20 13:17:25.328 11183-11552/com.amazon.rabbit.gamma I/amplify:aws-datastore: Orchestrator transitioning from SYNC_VIA_API to LOCAL_ONLY
2021-08-20 13:17:25.328 11183-11552/com.amazon.rabbit.gamma I/amplify:aws-datastore: Setting currentState to LOCAL_ONLY
2021-08-20 13:17:25.328 11183-11552/com.amazon.rabbit.gamma I/amplify:aws-datastore: Stopping subscription processor.
2021-08-20 13:17:25.791 11183-11552/com.amazon.rabbit.gamma I/amplify:aws-api: No more active subscriptions. Closing web socket.
2021-08-20 13:17:25.792 11183-11552/com.amazon.rabbit.gamma I/amplify:aws-datastore: Stopped subscription processor.
```
</details>

We have seen in console log that the request is successful but timeout on the android side

### Reproduction steps (if applicable)

Setup Amplify as normal and add the following code:

### Code Snippet

```java
try {
            Amplify.addPlugin(new AWSDataStorePlugin());
            Amplify.addPlugin(new AWSApiPlugin());
            Amplify.configure(getApplicationContext());
            RLog.i("Amplify", "Amplify initialized");
            Amplify.DataStore.start(
                    () -> {
                        RLog.i("Amplify", "Amplify started");
                        
                    },
                    error -> RLog.e("Amplify", error.toString(), error)
            );
        } catch (AmplifyException ex) {
            RLog.e("Amplify", "Could not initialize Amplify", ex);
        }

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by joekiller** [comment]
you may want to try version 1.20.1 because they fixed some timeouts there. https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.20.1

**Comment by rjuliano** [comment]
Related to #1403 

In addition, you can limit the amount of data getting sync'd by using sync expressions.

https://docs.amplify.aws/lib/datastore/sync/q/platform/android/#selectively-syncing-a-subset-of-your-data

**Comment by eeatonaws** [comment]
@xuaninbox did using a newer version of Amplify or limiting how much data is being synced resolve the issue?
