### ISSUE TITLE
Abstract Method Error When Calling Amplify.Auth.confirmSignup

### ISSUE THREAD

**Issue by Krondo** [aws-amplify/amplify-android#1507]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
    implementation 'com.amplifyframework:aws-api:1.3.2'
    implementation 'com.amplifyframework:core-kotlin:0.2.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.3.2'

```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_301 (Oracle Corporation 25.301-b09)
OS:           Mac OS X 10.16 x86_64



```

</details>

### Describe the bug

I am using Amplify to facilitate authentication in my app through the KotlinAuthFacade provided by Amplifies core-kotlin.
Everything seems to be working fine minus the confirmSignUp call. I am able to call methods like signIn and receive a result using the same object reference just fine. My repository has the following call:

```kotlin
return withContext(dispatcher) {
            try {
                Amplify.Auth.confirmSignUp(username, confirmationCode)
                EventStatus.Success
            } catch (e: AuthException) {
                EventStatus.Failure(e)
            } catch(e: Exception) {
                EventStatus.Failure(e)
            }
        }
```

I make a call to confirmSignUp and the app crashes with the following log:
```
2021-09-21 12:20:29.684 6833-6833/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 6833
    java.lang.AbstractMethodError: abstract method "void com.amplifyframework.auth.AuthCategoryBehavior.confirmSignUp(java.lang.String, java.lang.String, com.amplifyframework.auth.options.AuthConfirmSignUpOptions, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer)"
        at com.amplifyframework.auth.AuthCategory.confirmSignUp(AuthCategory.java:73)
        at com.amplifyframework.kotlin.auth.KotlinAuthFacade.confirmSignUp(KotlinAuthFacade.kt:66)
        at com.amplifyframework.kotlin.auth.Auth$DefaultImpls.confirmSignUp$default(Auth.kt:81)
        at com.example.components.account.authentication.amplify.AuthenticationRepositoryImpl$confirmSignUp$2.invokeSuspend(AuthenticationRepositoryImpl.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

For some reason, runtime believes I am trying to call an abstract method. Yet calls like `Amplify.Auth.signin(username, password)` work just fine in the same repository set up with the same coroutine paradigm.  Any insight would be appreciated. Happy to provide any additional information that might be relevant. 

### Code Snippet

```kotlin
return withContext(dispatcher) {
            try {
                Amplify.Auth.confirmSignUp(username, confirmationCode)
                EventStatus.Success
            } catch (e: AuthException) {
                EventStatus.Failure(e)
            } catch(e: Exception) {
                EventStatus.Failure(e)
            }
        }

```

### Log output

<details>

```
2021-09-21 12:20:29.684 6833-6833/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 6833
    java.lang.AbstractMethodError: abstract method "void com.amplifyframework.auth.AuthCategoryBehavior.confirmSignUp(java.lang.String, java.lang.String, com.amplifyframework.auth.options.AuthConfirmSignUpOptions, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer)"
        at com.amplifyframework.auth.AuthCategory.confirmSignUp(AuthCategory.java:73)
        at com.amplifyframework.kotlin.auth.KotlinAuthFacade.confirmSignUp(KotlinAuthFacade.kt:66)
        at com.amplifyframework.kotlin.auth.Auth$DefaultImpls.confirmSignUp$default(Auth.kt:81)
        at com.example.components.account.authentication.amplify.AuthenticationRepositoryImpl$confirmSignUp$2.invokeSuspend(AuthenticationRepositoryImpl.kt:82)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by changxu0306** [comment]
According to your build.gradle file, you are using old versions of Amplify. Could you please try the latest version to see if it works? (Amplify 1.27.0 & core kotlin 0.11.0).

**Comment by Krondo** [comment]
> According to your build.gradle file, you are using old versions of Amplify. Could you please try the latest version to see if it works? (Amplify 1.27.0 & core kotlin 0.11.0).

Matching those version numbers seems to have resolved it. Apologies, thank you for the reply!
