### ISSUE TITLE
Storage.downloadFile does not invoke error callback for an expired session

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-android#1516]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication, Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line

plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.example.myamplifystorageapp"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        // Support for Java 8 features
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    // Amplify core dependency
    implementation 'com.amplifyframework:core:1.27.0'
    implementation 'com.amplifyframework:aws-storage-s3:1.27.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.27.0'

    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.1'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_291 (Oracle Corporation 25.291-b10)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Describe the bug

Amplify.Storage.downloadFile will not invoke the error callback (or the success callback) if a user has an expired session. There are no callbacks invoked at any point.

### Reproduction steps (if applicable)

1. Setup a sample app with Auth and Storage. Enable storage for authenticated users
2. Set the refresh token expiration to the minimum value (60 minutes)
3. Login and observe that downloadFile works as expected
4. Wait until the refresh token expires
5. observe that downloadFile does not invoke any callback

### Code Snippet

```java
// Put your code below this line.
    fun downloadFile(view: View) {
        val file = File("${applicationContext.filesDir}/download.txt")
        val options = StorageDownloadFileOptions.defaultInstance()
        Amplify.Storage.downloadFile("ExampleKey", file, options,
            { Log.i("MyAmplifyApp", "Successfully downloaded: ${it.file.name}") },
            { Log.e("MyAmplifyApp", "Download Failure", it) }
        )
    }

```

### Log output

<details>

```
// Put your logs below this line

W/CognitoUserSession: CognitoUserSession is not valid because idToken is null.
W/AWSMobileClient: signalTokensNotAvailable
W/AWSMobileClient: Tokens are invalid, please sign-in again.
    java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.signalTokensNotAvailable(AWSMobileClient.java:1966)
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.getAuthenticationDetails(AWSMobileClient.java:1946)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1035)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1927)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1893)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1096)
        at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:975)
        at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:394)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4823)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1585)
        at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:102)
        at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:42)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

I believe this is an issue for other methods in storage, not just downloadFile.

**Comment by jack24254029** [comment]
Do you have any updates about this issue?

**Comment by div5yesh** [comment]
This is expected behavior. Since the refresh token is expired, automatic refresh is not possible and user must be prompted with a login screen to fetch new set of tokens (along with refresh token). 

When refresh token is expired, `AWSMobileClient` locks the thread with a `waitForSignIn` call which means the system is waiting for the user to signin. This lock is released automatically once the user signs in and the thread should continue which will invoke the success callback of the download API.

Recommendation on how to handle this scenario:
- Listen to Hub events https://docs.amplify.aws/lib/auth/auth-events/q/platform/android/
- Notice the case `SESSION_EXPIRED`. This is where the app can show login screen to the user to get a new session.
- Once the user signs in, download should continue as usual.
- If not, call `releaseSignInWait` on AWSMobileClient [escape hatch](https://docs.amplify.aws/lib/auth/escapehatch/q/platform/android/) to release the lock and initiate the download again.

**Comment by div5yesh** [comment]
Closing this issue due to inactivity. Please create a new issue if you have additional questions.
