### ISSUE TITLE
Cannot retrieve accessToken after signing in with web UI

### ISSUE THREAD

**Issue by longthanhle91** [aws-amplify/amplify-android#1547]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation "com.amplifyframework:core:1.28.1"
implementation "com.amplifyframework:aws-auth-cognito:1.28.1"

```

</details>

### Environment information

<details>

```
# Put output below this line

------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_261 (Oracle Corporation 25.261-b12)
OS:           Mac OS X 10.16 x86_64

```

</details>

### Describe the bug

I'm using Amplify and AWSMobileClient to login into Cognito via an OIDC based flow. Here is my setup:

1. Initialise Amplify.Auth then get AWSMobileClient by calling `Amplify.Auth.getPlugin("awsCognitoAuthPlugin").escapeHatch as AWSMobileClient.`
2. Call `AWSMobileClient.showSignIn(final Activity callingActivity, final SignInUIOptions signInUIOptions, final Callback<UserStateDetails> callback)` and wait for the sign in page to load.
3. Sign in with valid email and password.
4. The sign in success and returns UserStateDetails with `SIGNED_IN` state and details of my provider name and token
5. I call fetchAuthSession and receive the following object ```AWSCognitoAuthSession{isSignedIn=true, awsCredentials=AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=com.amazonaws.AmazonClientException: Cognito Identity not configured, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=null, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=com.amazonaws.AmazonClientException: Cognito Identity not configured, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=InvalidAccountTypeException{message=The account type you have configured doesn't support this operation., cause=null, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}'}```

### Code Snippet

```kotlin
// Put your code below this line.
    override fun showSNSWSignIn(onSuccess: () -> Unit, onError: (Throwable?) -> Unit) {
        val hostedUIOptions = HostedUIOptions.builder()
            .disableFederation(true)
            .identityProvider("placeholder")
            .signInQueryParameters(mapOf("identity_provider" to "placeholder"))
            .federationProviderName("placeholder")
            .tokenQueryParameters(mapOf("identityProvider" to "placeholder"))
            .scopes("openid")
            .build()
        val signInUIOptions = SignInUIOptions.builder()
            .hostedUIOptions(hostedUIOptions)
            .build()

        cpcRepository.awsMobileClient.showSignIn(
            activity,
            signInUIOptions,
            object : Callback<UserStateDetails> {
                override fun onResult(result: UserStateDetails?) {
                    if (result?.userState == UserState.SIGNED_IN) {
                        Amplify.Auth.fetchAuthSession(
                            {
                                Timber.d("fetchAuthSession: $it")
                                onSuccess.invoke()
                            },
                            {
                                Timber.d("fetchAuthSession: $it")
                            }
                        )
                    } else onError.invoke(UnauthorisedAccessException(result?.userState?.name))
                }

                override fun onError(e: Exception?) {
                    onError.invoke(e?.cause ?: e)
                }
            }
        )
    }
```

### Log output

<details>

```
// Put your logs below this line

2021-10-22 19:21:09.627 24582-24741/au.com.my.ap.debug D: Using the SignInProviderConfig from `awsconfiguration.json`.
2021-10-22 19:21:09.740 24582-24741/au.com.my.ap.debug D: initialize: OAuth2 client detected
2021-10-22 19:21:09.790 24582-24741/au.com.my.ap.debug D: Inspecting user state details
2021-10-22 19:21:41.091 24916-25038/au.com.my.ap.debug D: Using the SignInProviderConfig from `awsconfiguration.json`.
2021-10-22 19:21:41.177 24916-25038/au.com.my.ap.debug D: initialize: OAuth2 client detected
2021-10-22 19:21:41.208 24916-25038/au.com.my.ap.debug D: Inspecting user state details
2021-10-22 19:27:23.215 24916-25053/au.com.my.ap.debug I: onResult: OAuth2 callback occurred, exchanging code for token
2021-10-22 19:27:23.889 24916-25053/au.com.my.ap.debug D: _federatedSignIn: Putting provider and token in store
2021-10-22 19:27:23.906 24916-25567/au.com.my.ap.debug D: Inspecting user state details
2021-10-22 19:27:23.908 24916-25567/au.com.my.ap.debug D: hasFederatedToken: false provider: placeholder
2021-10-22 19:27:23.908 24916-25567/au.com.my.ap.debug D: hasFederatedToken: false provider: placeholder
2021-10-22 19:27:23.908 24916-25567/au.com.my.ap.debug W: Failed to federate the tokens.
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.setNotDeveloperAuthenticated()' on a null object reference
        at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1846)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1075)
        at com.amazonaws.mobile.client.AWSMobileClient$25$1$1$1.onError(AWSMobileClient.java:3312)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
        at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1801)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)
2021-10-22 19:27:23.915 24916-25571/au.com.my.ap.debug D: Inspecting user state details
2021-10-22 19:27:23.915 24916-25571/au.com.my.ap.debug D: hasFederatedToken: false provider: placeholder
2021-10-22 19:27:23.915 24916-25571/au.com.my.ap.debug D: hasFederatedToken: false provider: placeholder
2021-10-22 19:27:23.921 24916-25571/au.com.my.ap.debug W: Failed to federate the tokens.
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.setNotDeveloperAuthenticated()' on a null object reference
        at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1846)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1075)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:897)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:894)
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
        at java.lang.Thread.run(Thread.java:919)
2021-10-22 19:27:23.953 24916-25578/au.com.my.ap.debug D: Inspecting user state details
2021-10-22 19:27:23.960 24916-25578/au.com.my.ap.debug D: hasFederatedToken: false provider: placeholder
2021-10-22 19:27:23.960 24916-25578/au.com.my.ap.debug D: hasFederatedToken: false provider: placeholder
2021-10-22 19:27:23.960 24916-25578/au.com.my.ap.debug W: Failed to federate the tokens.
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.setNotDeveloperAuthenticated()' on a null object reference
        at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1846)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1075)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:897)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:894)
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
        at java.lang.Thread.run(Thread.java:919)
```

</details>

### amplifyconfiguration.json

```json
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "CognitoUserPool": {
          "Default": {
            "MigrationEnabled": true,
            "PoolId": "PoolId",
            "AppClientId": "AppClientId",
            "Region": "Region"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_PASSWORD_AUTH",
            "OAuth": {
              "AppClientId": "AppClientId",
              "WebDomain": "X.X.X.X",
              "TokenURI": "X.X.X.X/oauth2/token",
              "SignInURI": "X.X.X.X/oauth2/authorize",
              "SignOutURI": "myapp://",
              "SignOutURIQueryParameters": {
                "client_id": "client_id",
                "returnTo": "myapp://"
              },
              "SignInRedirectURI": "myapp://",
              "SignOutRedirectURI": "myapp://",
              "Scopes": [
                "openid"
              ]
            }
          }
        }
      }
    }
  }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots
The iOS team is using the same amplifyconfiguration.json and same call to the SDK but they are able to sign in successfully and also get the access token, leading me to believe that this is an Android SDK issue. Moreover, the error log I'm getting has `java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobile.client.AWSMobileClientCognitoIdentityProvider.setNotDeveloperAuthenticated()' on a null object reference`, AWSMobileClientCognitoIdentityProvider is built from Cognito Identity config, I don't use Cognito Identity Pool so I don't have it in my amplifyconfiguration.json, and since it works on iOS without Cognito Identity, it should work on Android as well

**Comment by changxu0306** [comment]
Hi @longthanhle91 ,
Thanks for reporting the issue and provide the configuration file. I'm working on reproducing the issue and trying to find the root cause. It would be good if you can also provide iOS logs of calling `fetchAuthSession()` so that I can better understand the inconsistency between Android and iOS.

**Comment by longthanhle91** [comment]
HI @changxu0306, sorry for the delayed response, I was able to solve this from my end. The main issue is with the amplify config, we've been told that we need to use the same config as iOS which contains stuffs like token uri, sign in uri, sign out uri and the sign out params, those are needed on ios but when putting in android, the sdk switches to a different flow which uses Identity Pool. Our AWS developers said they don't use Identity Pool at all so I had another look at the config mentioned here https://docs.amplify.aws/lib/auth/existing-resources/q/platform/android/ and removed the above mentioned params and was able to login and fetch auth session as normal

**Comment by Papashkin** [comment]
@longthanhle91 hi!
Could you please explain what params did you remove from the config file?
Did you mean these:
```
"IdentityManager": {
    "Default": {}
},
"CredentialsProvider": {
    "CognitoIdentity": {
        "Default": {
            "PoolId": "[COGNITO IDENTITY POOL ID]",
            "Region": "[REGION]"
        }
    }
},
```

**Comment by long-le-tfnsw** [comment]
Hi @Papashkin, my project doesn't use Identity pool so I never have those params to begin with. As mentioned in my previous comment, I removed token uri, sign in uri, sign out uri and the sign out params from the original config that I posted, the final config looks like this:
```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "CognitoUserPool": {
          "Default": {
            "MigrationEnabled": true,
            "PoolId": "PoolId",
            "AppClientId": "AppClientId",
            "Region": "Region"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_PASSWORD_AUTH",
            "OAuth": {
              "AppClientId": "AppClientId",
              "WebDomain": "X.X.X.X",
              "SignInRedirectURI": "myapp://",
              "SignOutRedirectURI": "myapp://",
              "Scopes": ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"]
            }
          }
        }
      }
    }
  }
}
```

**Comment by longthanhle91** [comment]
Hi @Papashkin, my project doesn't use Identity pool so I never have those params to begin with. As mentioned in my previous comment, I removed token uri, sign in uri, sign out uri and the sign out params from the original config that I posted, the final config looks like this:
```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "CognitoUserPool": {
          "Default": {
            "MigrationEnabled": true,
            "PoolId": "PoolId",
            "AppClientId": "AppClientId",
            "Region": "Region"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_PASSWORD_AUTH",
            "OAuth": {
              "AppClientId": "AppClientId",
              "WebDomain": "X.X.X.X",
              "SignInRedirectURI": "myapp://",
              "SignOutRedirectURI": "myapp://",
              "Scopes": ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"]
            }
          }
        }
      }
    }
  }
}
```
