### ISSUE TITLE
Sign-in with web UI failed. Browser with custom tabs support not found.

### ISSUE THREAD

**Issue by Tin-moon** [aws-amplify/amplify-android#1587]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, RxJava

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
def amplify_version = '1.30.0'
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
implementation "com.amplifyframework:aws-api:$amplify_version"
implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
implementation "com.amplifyframework:rxbindings:$amplify_version"
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.12 (Oracle Corporation 11.0.12+8-LTS-237)

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android/#update-androidmanifestxml

### Describe the bug

When trying to log in using any social network (Sign in with web UI).
Try with Samsung galaxy s7 Android 7.0 and Redmi Note 6 Pro Android 9
Samsung the following browsers are installed: Chrome, Opera and standard browser
Redmi Note 6 Pro the following browsers are installed: Chrome, Opera and standard browser
I get an error:
```
W/System.err: AuthException{message=Sign-in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.CustomTabsNotSupportedException: Browser with custom tabs support not found., recoverySuggestion=See attached exception for more details}
W/System.err:     at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$22.onError(AWSCognitoAuthPlugin.java:1235)
W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$26$1$3.run(AWSMobileClient.java:3463)
W/System.err:     at java.lang.Thread.run(Thread.java:762)
W/System.err: Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.CustomTabsNotSupportedException: Browser with custom tabs support not found.
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.launchCustomTabs(AuthClient.java:805)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.launchCognitoAuth(AuthClient.java:712)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.getSession(AuthClient.java:270)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.getSession(AuthClient.java:221)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.Auth.getSession(Auth.java:678)
W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$26.run(AWSMobileClient.java:3481)
W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/System.err: 	... 1 more
```

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
W/System.err: AuthException{message=Sign-in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.CustomTabsNotSupportedException: Browser with custom tabs support not found., recoverySuggestion=See attached exception for more details}
W/System.err:     at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$22.onError(AWSCognitoAuthPlugin.java:1235)
W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$26$1$3.run(AWSMobileClient.java:3463)
W/System.err:     at java.lang.Thread.run(Thread.java:762)
W/System.err: Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.CustomTabsNotSupportedException: Browser with custom tabs support not found.
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.launchCustomTabs(AuthClient.java:805)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.launchCognitoAuth(AuthClient.java:712)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.getSession(AuthClient.java:270)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.getSession(AuthClient.java:221)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoauth.Auth.getSession(Auth.java:678)
W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$26.run(AWSMobileClient.java:3481)
W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
W/System.err: 	... 1 more

```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

I did a little research
In com.amazonaws.mobileconnectors.cognitoauth.AuthClient
```
    private void launchCustomTabs(final Uri uri, final Activity activity, final String browserPackage) {
    	try {
            if(!isBrowserInstalled()) {
                userHandler.onFailure(new BrowserNotInstalledException("No browsers installed."));
                return;
            }
            if(!isCustomTabSupported()) {
                userHandler.onFailure(new CustomTabsNotSupportedException("Browser with custom tabs support not found."));
                return;
            }
...........
```
```
    private boolean isCustomTabSupported() {
        if (isCustomTabSupported) {
            return true;
        }
        if (getSupportedBrowserPackage().size() > 0) {
            isCustomTabSupported = true;
            return true;
        }
        return false;
    }

    private Collection<String> getSupportedBrowserPackage(){
        PackageManager packageManager = context.getPackageManager();
        // Get default VIEW intent handler.
        Intent activityIntent = new Intent()
                .setAction(Intent.ACTION_VIEW)
                .addCategory(Intent.CATEGORY_BROWSABLE)
                .setData(Uri.fromParts("http", "", null));

        // Get all apps that can handle VIEW intents.
        List<ResolveInfo> resolvedActivityList = packageManager.queryIntentActivities(activityIntent, 0); <-------------------Bug?
        List<String> packageNamesSupportingCustomTabs = new ArrayList<>();
        for (ResolveInfo info : resolvedActivityList) {
            Intent serviceIntent = new Intent()
                    .setAction(ACTION_CUSTOM_TABS_CONNECTION)
                    .setPackage(info.activityInfo.packageName);
            // Check if this package also resolves the Custom Tabs service.
            if(packageManager.resolveService(serviceIntent, 0) != null) {
                packageNamesSupportingCustomTabs.add(info.activityInfo.packageName);
            }
        }
        return packageNamesSupportingCustomTabs;
    }
```
it seems to me that the problem is related to the fact that we do not get all installed browsers, but only the first one. 
Most likely this will solve the problem (it return 3 apps for me)
```
List<ResolveInfo> resolvedActivityList = packageManager.queryIntentActivities(activityIntent, PackageManager.MATCH_ALL)
```
or most full
```
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
            pm.queryIntentActivities(intent, PackageManager.MATCH_ALL);
        } else {
            pm.queryIntentActivities(intent, 0);
        }
```

**Comment by eeatonaws** [comment]
Hi @Tin-moon, thank you for reporting this issue. We released a fix for a similar issue as part of the AWS SDK for Android version 2.37.1. Please try upgrading to version 1.31.1 of Amplify Android, which uses version 2.37.1 of the AWS SDK for Android, to see if this fixes the issue.

**Comment by Tin-moon** [comment]
Hi @eeatonaws yes, now the browser opens

**Comment by eeatonaws** [comment]
Closing this issue since upgrading the Amplify version resolved the error.
