### ISSUE TITLE
FEDERATED LOGIN : Access Token does not have required scopes 

### ISSUE THREAD

**Issue by taouichaimaa** [aws-amplify/amplify-android#1592]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

Authentication, GraphQL API, DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line

2.35.0
```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I'm trying to get the name and email of a user that signin with google. the Social sign in itself goes well, I have the user in the Userpool and the google group, it shows up on my amplify admin user management console but I can't get the name and email of the user.
I tried ```Auth.fetchUserAttributes``` but it gives the USER NOT AUTHORIZED ERROR.
My mapping is correct in the federated identities section.

### Reproduction steps (if applicable)

-social login with hosted UI
-USER IS IN USERPOOL
-fetchUserAttributes
-error

### Code Snippet

```kotlin
fun googleSignin(){

    binding.googleSign.setOnClickListener {
        // For Google
        // For Google
        val hostedUIOptions = HostedUIOptions.builder()
            .scopes("openid", "email")
            .identityProvider("Google")
            .build()


        val signInUIOptions = SignInUIOptions.builder()
            .hostedUIOptions(hostedUIOptions)
            .build()
        AWSMobileClient.getInstance()
            .showSignIn(
                this.requireActivity(),
                signInUIOptions,
                object : Callback<UserStateDetails?> {

                    override fun onError(e: java.lang.Exception?) {
                        Log.e(TAG, "onError: ", e)
                    }

                    override fun onResult(result: UserStateDetails?) {
                        Log.d(TAG, "onResult: ${result!!.userState.name}")

                        when (result!!.userState.name) {
                             "SIGNED_IN"-> {

                                 Log.i("userStateGOOGLE", "user is signed in ")
                                // listening()
                             }
                             "SIGNED_OUT"->Log.i("userState", "user is signed out")
                        }
                    }
                })
    }

}
private fun checkIfFirstTime(): Boolean {
    var isFirstTime=false
    val userID=Auth.currentUser //this gives the userID and username (aws_googleXYZ)
     Log.i("AmplifyApp", "UserID: $userID")


     Auth.fetchAuthSession(
         {
             val session = it as AWSCognitoAuthSession
             when (session.identityId.type) {
                 AuthSessionResult.Type.SUCCESS ->
                     Log.i("AuthQuickStartttt", "IDtoken = ${session.userPoolTokens}") // also gives tokens
                 AuthSessionResult.Type.FAILURE ->
                     Log.w("AuthQuickStart", "IdentityId not found", session.identityId.error)
             }
         },
         { Log.e("AuthQuickStart", "Failed to fetch session", it) }
     )
     Amplify.Auth.fetchUserAttributes(
         { attributes->Log.i("AuthDemo", "User attributes = $attributes") },// error 
         { Log.e("AuthDemo", "Failed to fetch user attributes", it) }
     )

}

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

E/AuthDemo: Failed to fetch user attributes
    NotAuthorizedException{message=Failed since user is not authorized., cause=com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Access Token does not have required scopes (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: d3e05427-4445-4191-872e-2395042b2146), recoverySuggestion=Check whether the given values are correct and the user is authorized to perform the operation.}
        at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:103)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$15.onError(AWSCognitoAuthPlugin.java:828)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
        at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
        at com.amazonaws.mobile.client.AWSMobileClient$20$1.onFailure(AWSMobileClient.java:2657)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getDetails(CognitoUser.java:1478)
        at com.amazonaws.mobile.client.AWSMobileClient$20.run(AWSMobileClient.java:2649)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Access Token does not have required scopes (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: d3e05427-4445-4191-872e-2395042b2146)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6779)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.getUser(AmazonCognitoIdentityProviderClient.java:4249)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getUserDetailsInternal(CognitoUser.java:1492)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getDetails(CognitoUser.java:1475)
        at com.amazonaws.mobile.client.AWSMobileClient$20.run(AWSMobileClient.java:2649) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:919) 
E/AuthDemo: Failed to fetch user attributes
    NotAuthorizedException{message=Failed since user is not authorized., cause=com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Access Token does not have required scopes (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: f0e8bb3a-50d6-4f69-8ce9-affb5c78c578), recoverySuggestion=Check whether the given values are correct and the user is authorized to perform the operation.}
        at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:103)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$15.onError(AWSCognitoAuthPlugin.java:828)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
        at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
        at com.amazonaws.mobile.client.AWSMobileClient$20$1.onFailure(AWSMobileClient.java:2657)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getDetails(CognitoUser.java:1478)
        at com.amazonaws.mobile.client.AWSMobileClient$20.run(AWSMobileClient.java:2649)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Access Token does not have required scopes (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: f0e8bb3a-50d6-4f69-8ce9-affb5c78c578)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6779)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.getUser(AmazonCognitoIdentityProviderClient.java:4249)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getUserDetailsInternal(CognitoUser.java:1492)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getDetails(CognitoUser.java:1475)
        at com.amazonaws.mobile.client.AWSMobileClient$20.run(AWSMobileClient.java:2649) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:919) 
E/AuthDemo: Failed to fetch user attributes
    NotAuthorizedException{message=Failed since user is not authorized., cause=com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Access Token does not have required scopes (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 86ad7944-da62-4a8f-9194-b0a88e37c9ae), recoverySuggestion=Check whether the given values are correct and the user is authorized to perform the operation.}
        at com.amplifyframework.auth.cognito.util.CognitoAuthExceptionConverter.lookup(CognitoAuthExceptionConverter.java:103)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$15.onError(AWSCognitoAuthPlugin.java:828)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
        at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
        at com.amazonaws.mobile.client.AWSMobileClient$20$1.onFailure(AWSMobileClient.java:2657)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getDetails(CognitoUser.java:1478)
        at com.amazonaws.mobile.client.AWSMobileClient$20.run(AWSMobileClient.java:2649)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Access Token does not have required scopes (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 86ad7944-da62-4a8f-9194-b0a88e37c9ae)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6779)
        at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.getUser(AmazonCognitoIdentityProviderClient.java:4249)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getUserDetailsInternal(CognitoUser.java:1492)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getDetails(CognitoUser.java:1475)
        at com.amazonaws.mobile.client.AWSMobileClient$20.run(AWSMobileClient.java:2649) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by taouichaimaa** [comment]
I've been stuck on this for two days now, has no one tried anything else other than adding the  user.admin scopes? Because I've already did that and mapped the attributes. Please help.

**Comment by taouichaimaa** [comment]
Has no one been assigned to this ? it's been a week.

**Comment by poojamat** [comment]
@taouichaimaa  please share your awsConfiguration.json and AmplifyConfiguration.json.
Also while going through the CLI step:
" Do you want to specify the user attributes this app can read and write?"
what did you select?

**Comment by taouichaimaa** [comment]
I don't remember , how can I check?

**Comment by poojamat** [comment]
Go to [YourApp]/amplify/backend/auth/[appname]/cli-inputs.json
If you had select read on user attributes you will see something like this:
    "userpoolClientWriteAttributes": [
      "email"
    ],
    "userpoolClientReadAttributes": [
      "birthdate",
      "email"
    ],

**Comment by taouichaimaa** [comment]
This is what I found for the CLI steps :
`  "userpoolClientWriteAttributes": [
        "email",
        "name"
    ],
    "userpoolClientReadAttributes": [
        "email"
    ],`
 And this is my AwsConfiguration.json file:
`
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "domain",
                "AppClientId": "myidkey",
                "SignInRedirectURI": "myapp://",
                "SignOutRedirectURI": "myapp://",
                "Scopes": [
                    "phone",
                    "email",
                    "openid",
                    "profile",
                    "aws.cognito.signin.user.admin"
                ]
            },
            "authenticationFlowType": "USER_SRP_AUTH",
            "loginMechanisms": [
                "EMAIL"
            ],
            "signupAttributes": [
                "EMAIL",
                "NAME"
            ],
            "passwordProtectionSettings": {
                "passwordPolicyMinLength": 8,
                "passwordPolicyCharacters": []
            },
            "mfaConfiguration": "OFF",
            "mfaTypes": [
                "SMS"
            ],
            "verificationMechanisms": [
                "EMAIL"
            ],
            "socialProviders": [
                "FACEBOOK"
            ],
            "usernameAttributes": [
                "EMAIL"
            ]
        }
    },
    
}`
and my AmplifyConf.json file:
`"Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "domain",
                            "AppClientId": "xxxxxxxxxxxxxx",
                            "SignInRedirectURI": "myapp://",
                            "SignOutRedirectURI": "myapp://",
                            "Scopes": [
                                "phone",
                                "email",
                                "openid",
                                "profile",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "loginMechanisms": [
                            "EMAIL"
                        ],
                        "signupAttributes": [
                            "EMAIL",
                            "NAME"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ],
                        "socialProviders": [
                            "FACEBOOK"
                        ],
                        "usernameAttributes": [
                            "EMAIL"
                        ]
                    }
                },`

**Comment by taouichaimaa** [comment]
any update on this?

**Comment by eeatonaws** [comment]
@taouichaimaa sorry for the delayed response. You currently have email setup as the only user pool attribute the app is allowed to read (defined by "userpoolClientReadAttributes"). To read the name attribute as well, you need to explicitly allow this attribute to be read (name should be included in "userpoolClientReadAttributes"). The user pool attributes that are allowed to be read can be updated by running `amplify update auth`, choosing "Walkthrough all the auth configurations", and selecting both the email and name attributes when prompted to "Specify read attributes".

**Comment by taouichaimaa** [comment]
I see, I will try it and update this. Thank you.

**Comment by gpanshu** [comment]
Closing due to inactivity. Please feel free to reopen or log another issue if the issue persists. Thank you.
