### ISSUE TITLE
Crash caused by NullPointerException when parsing GraphQLResponse.Error with null/missing message

### ISSUE THREAD

**Issue by millsjustin** [aws-amplify/amplify-android#1599]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

GraphQL API

### Gradle script dependencies

<details>

```groovy
implementation 'com.amplifyframework:core:1.24.1'
implementation 'com.amplifyframework:aws-api:1.24.1'
```

</details>

### Environment information

<details>

```text
------------------------------------------------------------
Gradle 6.8.2
------------------------------------------------------------

Build time:   2021-02-05 12:53:00 UTC
Revision:     b9bd4a5c6026ac52f690eaf2829ee26563cad426

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (JetBrains s.r.o. 11.0.10+0-b96-7281165)
OS:           Mac OS X 11.6.1 x86_64
```

</details>

### Describe the bug

Yesterday during the US-EAST-1 outage I was seeing app crashes caused by a `NullPointerException` thrown while deserializing `GraphQLResponse.Error`. The full stacktrace is:

```
Fatal Exception: java.lang.NullPointerException
       at java.util.Objects.requireNonNull(Objects.java:220)
       at com.amplifyframework.api.graphql.GraphQLResponse$Error.<init>(GraphQLResponse.java:138)
       at com.amplifyframework.api.graphql.GsonResponseAdapters$ErrorDeserializer.deserialize(GsonResponseAdapters.java:216)
       at com.amplifyframework.api.graphql.GsonResponseAdapters$ErrorDeserializer.deserialize(GsonResponseAdapters.java:156)
       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:1003)
       at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
       at com.amplifyframework.api.aws.GsonGraphQLResponseFactory$IterableDeserializer.toList(GsonGraphQLResponseFactory.java:152)
       at com.amplifyframework.api.aws.GsonGraphQLResponseFactory$IterableDeserializer.deserialize(GsonGraphQLResponseFactory.java:141)
       at com.amplifyframework.api.aws.GsonGraphQLResponseFactory$IterableDeserializer.deserialize(GsonGraphQLResponseFactory.java:75)
       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:1003)
       at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
       at com.amplifyframework.api.graphql.GsonResponseAdapters$ResponseDeserializer.parseErrors(GsonResponseAdapters.java:148)
       at com.amplifyframework.api.graphql.GsonResponseAdapters$ResponseDeserializer.deserialize(GsonResponseAdapters.java:84)
       at com.amplifyframework.api.graphql.GsonResponseAdapters$ResponseDeserializer.deserialize(GsonResponseAdapters.java:59)
       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.amplifyframework.api.aws.GsonGraphQLResponseFactory.buildResponse(GsonGraphQLResponseFactory.java:65)
       at com.amplifyframework.api.graphql.GraphQLOperation.wrapResponse(GraphQLOperation.java:53)
       at com.amplifyframework.api.aws.AppSyncGraphQLOperation.access$100(AppSyncGraphQLOperation.java:50)
       at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:147)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

The stacktrace indicates the error `message` was either `null` or missing. I would not expect this to cause a crash. Instead a default message could to be supplied or an exception thrown and handled. 

Here are two possible fixes for the crash. Each has a fix and a test to verify the fix.

https://github.com/millsjustin/amplify-android/compare/main...jm/provide-default-message-when-null

https://github.com/millsjustin/amplify-android/compare/main...jm/throw-api-exception-for-null-message

I can provide any additional info you need and open a PR with a fix if you would like.

### Reproduction steps (if applicable)

See unit tests in links provided above.

**Comment by aladine** [comment]
My team also observed the same NullPointerException in GraphQLResponse when AWS outage happened last week. 
Our amplify-android version is 1.28.1

**Comment by sktimalsina** [comment]
@millsjustin Would you be able to create a pull request on amplify-android repo? It would make things easier as I don't have access to your forked repo if it gets outdated from amplify-android repo.
