### ISSUE TITLE
SessionExpired thrown right after sign in

### ISSUE THREAD

**Issue by brunovsiqueira** [aws-amplify/amplify-android#1635]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Not applicable

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Hi there. I opened this issue on Amplify Flutter github, but they asked me to open it here since it is happening on Android devices. (you can view it here: https://github.com/aws-amplify/amplify-flutter/issues/1271)

We have two android (AFAIK) users in production which are not being able to use our app because Amplify returns session expired right after signIn when we call fetchAuthSession.

Inspecting this user's logs, what I see is the following:

1- We check user session by calling (Amplify.Auth.getCurrentUser(), Amplify.Auth.fetchAuthSession) when the app is opened. We consider session expired if InvalidStateException or SessionExpiredException is thrown and then we call Amplify.Auth.signOut() if session has expired. In the mentioned case, this user session is considered expired and he is logged out.

2- After that, the user called signIn successfully and "isSignedIn" flag returned true.

3- Right after signIn (sequentially), Amplify.Auth.fetchAuthSession is called in order to get user token (JWT) to call one of our APIs. When fetchAuthSession is called, this is the result according to the logs:
(message: Your session has expired., recoverySuggestion: Please sign in and reattempt the operation., underlyingException: null)
Because user session has expired right after signIn, the user is not able to get the token and consequently is not able to consume none of our APIs.

This behavior is completely weird since the user has just logged in and is getting session expired. I was not able to reproduce it.

Since we have production users facing this problem, can anyone please help me understand/solve the problem?

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line

SessionExpiredException(message: Your session has expired., recoverySuggestion: Please sign in and reattempt the operation., underlyingException: null)
#0      AmplifyAuthCognitoMethodChannel.fetchAuthSession (package:amplify_auth_cognito\/method_channel_auth_cognito.dart:246)
<asynchronous suspension>
#1      AmplifyAuthCognito.fetchAuthSession (package:amplify_auth_cognito\/amplify_auth_cognito.dart:121)
<asynchronous suspension>
#2      SessionService._fetchSession (package:btg_auth_core\/src\/services\/session_service.dart:23)
<asynchronous suspension>
#3      SessionService.getAccessJWTToken (package:btg_auth_core\/src\/services\/session_service.dart:34)
<asynchronous suspension>
#4      BasicAPI.getHeaders (package:btg_auth_core\/src\/services\/api\/basic_api.dart:27)
<asynchronous suspension>
#5      BasicAPI.httpGet (package:btg_auth_core\/src\/services\/api\/basic_api.dart:136)
<asynchronous suspension>
#6      GkRemoteDatasourceImpl.getSelfUser (package:btg_auth_core\/src\/datasources\/gk_remote_datasource.dart:23)
<asynchronous suspension>
#7      UserServiceImpl.getSelfUser (package:btg_auth_core\/src\/services\/user_service_impl.dart:28)
<asynchronous suspension>
#8      UserViewModel.fetchCurrentUserData (package:btg_auth_core\/src\/viewmodels\/user_viewmodel.dart:33)
<asynchronous suspension>
#9      LoginViewModel.login (package:btg_login\/src\/viewmodels\/login_viewmodel.dart:218)
<asynchronous suspension>
#10     _LoginPasswordPageState.build.<anonymous closure> (package:btg_login\/src\/pages\/login_password_page.dart:72)
<asynchronous suspension>
```

</details>

### amplifyconfiguration.json
```

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "${getPoolIdForEnv()}",
                        "AppClientId": "${getAppClientIdForEnv()}",
                        "Region": "${getRegionForEnv()}"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
               
            }
        }
    }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by dorontal** [comment]
Possibly related to this issue: https://github.com/aws-amplify/amplify-flutter/issues/1204

**Comment by brunovsiqueira** [comment]
@poojamat any updates? It's critical since it is affecting our production users. Now happening in Samsung SM-G996B and Samsung SM-G975F.

**Comment by gpanshu** [comment]
From the [linked](https://github.com/aws-amplify/amplify-flutter/issues/1204) issue it appears this might be a CLI bug. Please follow that thread to see the resolution.

**Comment by brunovsiqueira** [comment]
@gpanshu I don't think the issues are the same.
I can try the CLI workaround, but I could not find it in the related issue.
I don't think it can be closed.

**Comment by gpanshu** [comment]
Understood. I will remove the closing soon tag then. Please try the workaround to see if that works and either way please respond here so that we can move forward. Thank you.

**Comment by brunovsiqueira** [comment]
Following the issue to see if there is any workaround.

**Comment by dorontal** [comment]
FYI I'm the one who opened the other issue. We've recently determined it's specifically related to "attributes for access control" and not to Flutter, so it was re-opened in a clearer way in a more appropriate repository - `amplify-cli` - here: https://github.com/aws-amplify/amplify-cli/issues/9747 -- as far as I know there is no workaround yet, other than stopping to use attributes for access control.

**Comment by brunovsiqueira** [comment]
@dorontal what do you mean by "attributes for access control"? I don't think we use it.

**Comment by dorontal** [comment]
@brunovsiqueira I mean following steps 1-2 of this, for example: https://github.com/aws-amplify/amplify-js/issues/54#issuecomment-876455852

You can read more about it here: https://docs.aws.amazon.com/cognito/latest/developerguide/using-afac-with-cognito-identity-pools.html

**Comment by brunovsiqueira** [comment]
Digging deep into the problem, I found out a pattern. The users' devices who gets this problem right after signIn are not being listed in "Device tracking log" even though their events are shown as "Sign-in passed" in "User event history". Look at this user:
![MicrosoftTeams-image (32)](https://user-images.githubusercontent.com/18200284/158590732-2c3541d7-5d5b-4ab8-b099-7a26a645f993.png)

If you see, the user tried to log in using two different devices: an iPhone and a SM-G9600 (Android). However, the only device which is listed in "Device tracking log" is the iPhone. It is a pattern, all user who had this problem I can observe the same behavior: I see the sign in event in "User event history" but I don't see the device which I see the logs in "Device tracking log".

**Comment by div5yesh** [comment]
I don't think session expired has anything to do with device tracking. 

One thing to point out is that signIn is an asynchronous call. Calling fetchAuthSession sequentially after signIn will not return valid tokens as signing is not yet complete. Try using fetchAuthSession in success callback of signIn method and see if it fixes your issue.

**Comment by div5yesh** [comment]
Closing this issue due to inactivity. Please open a new issue if you are still facing this issue.
