### ISSUE TITLE
Null DataStoreException on Windows

### ISSUE THREAD

**Issue by jdt11** [aws-amplify/amplify-android#1641]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line

    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.1'

    implementation 'com.amplifyframework:aws-api:1.29.1'
    implementation 'com.amplifyframework:aws-datastore:1.29.0'
    implementation 'com.amplifyframework:aws-auth-cognito:1.29.1'

    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

```

</details>

### Environment information

<details>

```
# Put output below this line

------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          16 (Oracle Corporation 16+36-2231)
OS:           Mac OS X 10.15.7 x86_64

```

</details>

### Describe the bug

Amplify connects in Android Studio on Mac machine, move code to Windows machine with same setup and code fails

### Reproduction steps (if applicable)

1. Create blank android studio project.
2. Follow Amplify-AWS set up tutorial instructions.
3. Attempt to add item to database model.
4. Run app.

### Code Snippet

```java
// Put your code below this line.

public class DataManager {

    //A formatter which ensures dates are in the correct database format
    private DateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");

    /**
     * The constructor initialises a connection to the database using the Amplify libraries.
     * @param applicationContext The context of the android application.
     */
    public DataManager(Context applicationContext){
        try {
            Amplify.addPlugin(new AWSApiPlugin());
            Amplify.addPlugin(new AWSDataStorePlugin());
            Amplify.configure(applicationContext);
            System.out.println("Initialized Amplify");
        } catch (AmplifyException failure) {
            System.err.println("Could not initialize Amplify: " + failure);
        }
    }

    /**
     * A method which allows us to add a Trip to the database.
     * @param start The start location of the trip.
     * @param end The end location of the trip.
     * @param method The travel method of the trip using the TravelMethod enumerator.
     * @return The trip object.
     */
    public Trip addTrip(String start, String end, TravelMethod method){
        Trip item = Trip.builder()
                .startLocation(start)
                .endLocation(end)
                .travelMethod(method)
                .build();
        Amplify.DataStore.save(
                item,
                success -> System.out.println("Saved Trip item: " + success.item().getId()),
                error -> System.err.println("Could not save Trip item to DataStore. " + error)
        );

        return item;
    }

```

### Log output

<details>

```
// Put your logs below this line

022-01-27 11:32:16.274 6769-6836/com.example.journeymapper E/amplify:aws-datastore: Failure encountered while attempting to start API sync.
DataStoreException{message=Error during subscription., cause=ApiException{message=Connection failed., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:328)
at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$797ziDK0io-qXODzROLOA77stS8.accept(Unknown Source:4)
at com.amplifyframework.api.aws.SubscriptionOperation.lambda$null$1$SubscriptionOperation(SubscriptionOperation.java:87)
at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$l9lC7Ew6niNmyszMXQSUKS6YhwE.accept(Unknown Source:4)
at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:144)
at com.amplifyframework.api.aws.Subscri
```

</details>

### amplifyconfiguration.json

{
    "profile": "default",
    "envName": "amplify",
    "syncEnabled": true
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line

enum TravelMethod {
  CAR
  ESCOOTER
  CARPOOL
  BIKE
  EBIKE
  BUS
  FERRY
  TRAIN
  WALK
  SCOOTER
  MOTORCYCLE
}

type Trip @model @auth(rules: [{allow: public}]) {
  id: ID!
  startLocation: String
  endLocation: String
  travelMethod: TravelMethod
  Breadcrumbs: [Coordinates] @connection(keyName: "byTrip", fields: ["id"])
}

type Coordinate {
  Latitude: Float
  Longitude: Float
}

type Coordinates @model @auth(rules: [{allow: public}]) @key(name: "byTrip", fields: ["tripID"]) {
  id: ID!
  coord: Coordinate!
  timestamp: AWSDateTime!
  tripID: ID!
  trip: Trip! @connection(fields: ["tripID"])
}
 

```

</details>

**Comment by poojamat** [comment]
@jdt11 Sorry that you are experiencing this problem. Could you please try to go to AppSync console, navigate to Queries section from the side navigation bar, to execute the sync<TheNameOfTheModelThatHasProblem> see if you can see all data entries or any errors. Also make sure your id's are UUId.

**Comment by jdt11** [comment]
Hi, all that seems to be working, but I'm still having the same problem.

**Comment by poojamat** [comment]
Could you confirm that all your ID's are UUID's?

**Comment by jdt11** [comment]
As far as I can see they are (I have attached schema file
[schema.txt](https://github.com/aws-amplify/amplify-android/files/7973987/schema.txt)
)

**Comment by jdt11** [comment]
Hi I still haven't got this resolved?

**Comment by poojamat** [comment]
@jdt11 sorry to hear that you are still having problems on windows machine. When you configure amplify on your project root folder does it finish successfully till "amplify push"
