### ISSUE TITLE
App Crashes When Saving Item to DataStore

### ISSUE THREAD

**Issue by rayshi67** [aws-amplify/amplify-android#1667]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line
def amplify_version = "1.32.0"

implementation "com.amplifyframework:core:$amplify_version"
implementation "com.amplifyframework:aws-api:$amplify_version"
implementation "com.amplifyframework:aws-datastore:$amplify_version"
implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
implementation "com.amplifyframework:aws-storage-s3:$amplify_version"

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.8 (Oracle Corporation 11.0.8+10-LTS)
OS:           Mac OS X 10.15.7 x86_64


```

</details>

### Describe the bug

My app saves the current location coordinates to datastore every five seconds.

It works as expected for a few minutes. And the saved items get synchronised to the backend successfully. However the app then crashes with exceptions thrown from datastore mutations.

The Android tablet has reasonable internet connection through WI-FI.

Seems the issue #1273 is similar to the above error that I am getting, except the Android tablets used in the testing all have good WI-FI connections. 

### Code Snippet

```java
// Put your code below this line.
Amplify.DataStore.query(
       Taximeter::class.java,
        Where.id(taximeterId),
        { matches ->
                if (matches.hasNext()) {
                       val taximeter = matches.next()
                       val edited = taximeter.copyOfBuilder()
                              .currentLat(location.lat!!)
                              .currentLng(location.lng!!)
                              .build()

                       Amplify.DataStore.save(edited,
                           { Timber.i("Updated latest location to meter") },
                            { Timber.e("Failed to save latest location to meter", it) }
                       )
                 }
          },
          { Timber.e("Failed to load meter details", it) }
)
```

### Log output

<details>

```
// Put your logs below this line
2022-02-22 13:52:55.567 10952-11035/? W/amplify:aws-datastore: Error ended observation of mutation outbox: 
    DataStoreException{message=Failed to process PendingMutation{mutatedItem=SerializedModel{id='594456c1-67c1-4db4-9e1d-87bd273be8a9', serializedData={currentLat=-37.8753898, currentLng=145.1590711, id=594456c1-67c1-4db4-9e1d-87bd273be8a9}, modelName=Taximeter}, mutationType=UPDATE, mutationId=8313b7b5-938a-11ec-b256-81956814cc36, predicate=MatchAllQueryPredicate}, cause=null, recoverySuggestion=Check your internet connection.}
        at com.amplifyframework.datastore.syncengine.MutationProcessor.drainMutationOutbox(MutationProcessor.java:119)
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$startDrainingMutationOutbox$1$MutationProcessor(MutationProcessor.java:101)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$E9H2I0qolxIT6NJns5-WPOBrLCY.apply(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2022-02-22 13:52:55.583 10952-11039/? I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=SerializedModel{id='594456c1-67c1-4db4-9e1d-87bd273be8a9', serializedData={currentLat=-37.8753924, currentLng=145.1590666, id=594456c1-67c1-4db4-9e1d-87bd273be8a9}, modelName=Taximeter}, mutationType=UPDATE, mutationId=890c09b6-938a-11ec-b256-29d1dbfa7eca, predicate=MatchAllQueryPredicate}
2022-02-22 13:52:55.586 10952-11216/? W/System.err: io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | DataStoreException{message=Failure during mutation., cause=ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}, recoverySuggestion=Check details.}
2022-02-22 13:52:55.587 10952-11216/? W/System.err:     at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
2022-02-22 13:52:55.587 10952-11216/? W/System.err:     at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:82)
2022-02-22 13:52:55.587 10952-11216/? W/System.err:     at com.amplifyframework.datastore.syncengine.-$$Lambda$H2kP2N9w3X0gYQg1QzSwv0s9uXc.accept(Unknown Source:4)
2022-02-22 13:52:55.587 10952-11216/? W/System.err:     at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$5(AppSyncClient.java:358)
2022-02-22 13:52:55.587 10952-11216/? W/System.err:     at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$FfgHx1XvivjmTcZhtf9BjbrAq_M.accept(Unknown Source:4)
2022-02-22 13:52:55.587 10952-11216/? W/System.err:     at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:161)
2022-02-22 13:52:55.588 10952-11216/? W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
2022-02-22 13:52:55.588 10952-11216/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-02-22 13:52:55.588 10952-11216/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-02-22 13:52:55.588 10952-11216/? W/System.err:     at java.lang.Thread.run(Thread.java:764)
2022-02-22 13:52:55.588 10952-11216/? W/System.err: Caused by: DataStoreException{message=Failure during mutation., cause=ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}, recoverySuggestion=Check details.}
2022-02-22 13:52:55.589 10952-11216/? W/System.err: 	... 7 more
2022-02-22 13:52:55.589 10952-11216/? W/System.err: Caused by: ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}
2022-02-22 13:52:55.589 10952-11216/? W/System.err: 	... 5 more
2022-02-22 13:52:55.589 10952-11216/? W/System.err: Caused by: java.net.SocketTimeoutException: timeout
2022-02-22 13:52:55.590 10952-11216/? W/System.err:     at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
2022-02-22 13:52:55.590 10952-11216/? W/System.err:     at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
2022-02-22 13:52:55.590 10952-11216/? W/System.err:     at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
2022-02-22 13:52:55.590 10952-11216/? W/System.err:     at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
2022-02-22 13:52:55.590 10952-11216/? W/System.err:     at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
2022-02-22 13:52:55.590 10952-11216/? W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
2022-02-22 13:52:55.590 10952-11216/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-02-22 13:52:55.590 10952-11216/? W/System.err:     at com.amplifyframework.api.aws.UserAgentInterceptor.intercept(UserAgentInterceptor.java:56)
2022-02-22 13:52:55.591 10952-11216/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-02-22 13:52:55.591 10952-11216/? W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
2022-02-22 13:52:55.591 10952-11216/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-02-22 13:52:55.591 10952-11216/? W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2022-02-22 13:52:55.591 10952-11216/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-02-22 13:52:55.591 10952-11216/? W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2022-02-22 13:52:55.591 10952-11216/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-02-22 13:52:55.592 10952-11216/? W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2022-02-22 13:52:55.592 10952-11216/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2022-02-22 13:52:55.592 10952-11216/? W/System.err:     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2022-02-22 13:52:55.592 10952-11216/? W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
2022-02-22 13:52:55.592 10952-11216/? W/System.err: 	... 3 more


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by joekiller** [comment]
Perhaps try not manipulating the data within the predicate. I think that is more for filtering and returning than doing mutations.

https://docs.amplify.aws/lib/datastore/data-access/q/platform/android/#predicates
