### ISSUE TITLE
AppSync doesn't working with Datastore for GraphQL Transformer V2 schema

### ISSUE THREAD

**Issue by shantanu-csedu** [aws-amplify/amplify-android#1668]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation "com.amplifyframework:core:1.32.0"
implementation "com.amplifyframework:aws-auth-cognito:1.32.0"
implementation "com.amplifyframework:aws-datastore:1.32.0"
implementation "com.amplifyframework:aws-api:1.32.0"

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Amazon.com Inc. 11.0.12+7-LTS)
OS:           Mac OS X 12.2.1 x86_64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/cli/migration/transformer-migration/

### Describe the bug

I have created a new Amplify app with **ToDo** sample model. But **Datastore** cannot start the **AppSync**.  Datastore is looking for `_delete` and `_lastChangedAt` fields but those fields are undefined in GraphQL Transformer V2.

### Reproduction steps (if applicable)

- Create new Amplify App
- Update Schema with ToDo model
- Config Android app
- Start Datastore Sync using Amplify.DataStore.start
- Datastore throw exception on AppSync

### Code Snippet

```java
// Put your code below this line.
class AmplifyConfig(private val context: Context) {
    fun init(){
        try {
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.addPlugin(
                AWSDataStorePlugin())
            Amplify.configure(context)
            startSync()
        } catch (failure: AmplifyException) {
            failure.printStackTrace()
        }
    }

    private fun startSync(){
        Amplify.DataStore.start(
            {


            },
            { error ->
                error.printStackTrace()
            }
        )
    }
}
```

### Log output

<details>

```
// Put your logs below this line
Failure encountered while attempting to start API sync.
    GraphQLResponseException{message=Subscription error for Todo: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_deleted' in type 'Todo' is undefined @ 'onUpdateTodo/_deleted'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Todo' is undefined @ 'onUpdateTodo/_lastChangedAt'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_version' in type 'Todo' is undefined @ 'onUpdateTodo/_version'', locations='null', path='null', extensions='null'}], errors=[GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_deleted' in type 'Todo' is undefined @ 'onUpdateTodo/_deleted'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_lastChangedAt' in type 'Todo' is undefined @ 'onUpdateTodo/_lastChangedAt'', locations='null', path='null', extensions='null'}, GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field '_version' in type 'Todo' is undefined @ 'onUpdateTodo/_version'', locations='null', path='null', extensions='null'}], recoverySuggestion=See attached list of GraphQLResponse.Error objects.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$2(AppSyncClient.java:321)
        at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda5.accept(Unknown Source:8)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchNextMessage(SubscriptionEndpoint.java:425)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.notifySubscriptionData(SubscriptionEndpoint.java:248)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.access$700(SubscriptionEndpoint.java:61)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.processJsonMessage(SubscriptionEndpoint.java:603)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onMessage(SubscriptionEndpoint.java:509)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line
# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Todo @model {
  id: ID!
  name: String!
  description: String
}

```

</details>

**Comment by HuiSF** [comment]
When you created the new Amplify App, did you enable conflict detection while adding API category? This is required to use the schema with DataStore category.

**Comment by eeatonaws** [comment]
Closing this issue due to inactivity. Please comment or reopen this issue if you have additional questions.
