### ISSUE TITLE
Usage of API 24+ API in DataStore crashes App when running on API 22 while minSdkVersion saying API 16 is required

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-android#1693]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

In `gradle.build` the `minSdkVersion` is defined as `16`, meaning API 16 is require to run the App built with `amplify-android`.

https://github.com/aws-amplify/amplify-android/blob/880a182814514f9bce2c914ced44756f8af52f40/build.gradle#L56-L58

However, usage of API provided by API 24+ exists in the codebase, e.g.

https://github.com/aws-amplify/amplify-android/blob/880a182814514f9bce2c914ced44756f8af52f40/aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/SyncProcessor.java#L248-L250

The `AtomicReference#accumulateAndGet` [was added in API 24](https://developer.android.com/reference/java/util/concurrent/atomic/AtomicReference#getAndAccumulate(V,%20java.util.function.BinaryOperator%3CV%3E)).

And when developer tries to deploy App and run, e.g. on API 22, App crashes.

```
Fatal Exception: java.lang.NoClassDefFoundError: com.amplifyframework.datastore.syncengine.SyncProcessor$$ExternalSyntheticLambda13
       at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$syncModel$13(SyncProcessor.java:249)
       at com.amplifyframework.datastore.syncengine.SyncProcessor.$r8$lambda$2cJLxw0MiDnoj5SD1yHgXEAXleg(SyncProcessor.java)
       at com.amplifyframework.datastore.syncengine.SubscriptionProcessor$$InternalSyntheticLambda$0$dad4a5859176b69f01dda9628153ddd3768e4a48c8c9943a26aea231e4ca30ff$3.test$bridge(SubscriptionProcessor.java)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableTakeUntilPredicate$InnerSubscriber.onNext(FlowableTakeUntilPredicate.java:60)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
       at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:92)
       at io.reactivex.rxjava3.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
```

The `minSdkVersion` should reflect the actual required API level.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
The issue here is that Java8 and desugaring have not been enabled. If these options are configured as instructed in the documentation, API 21+ will work. There is another issue in DataStore not supporting down to 16 due to an OkHttp 4 dependency.

https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android/#install-amplify-libraries
