### ISSUE TITLE
"Failed to instantiate AWSMobileClient within 10 seconds" in Application.onCreate()

### ISSUE THREAD

**Issue by patrickhoette** [aws-amplify/amplify-android#1727]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication, REST API

### Gradle script dependencies

<details>

```groovy
def amplify_version = '1.31.1'
implementation "com.amplifyframework:core:$amplify_version"
implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
implementation "com.amplifyframework:aws-api:$amplify_version"
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_322 (Temurin 25.322-b06)
OS:           Mac OS X 10.16 x86_64
```

</details>

### Describe the bug

In Firebase we see a concerning amount of crashes caused by:
```
java.lang.RuntimeException: Unable to create application {insert app package}.CustomApplication: AuthException{message=Failed to instantiate AWSMobileClient within 10 seconds, cause=null, recoverySuggestion=Check network connectivity}
```

According to the Firebase crash report 100% of the issues are happening while the app is in the background. The last 90 days we have had 1512 occurrences, which considering our current user base is an alarming amount.  We cannot use a `try catch` as we need the Amplify SDK in order to make critical API calls (so the only way to recover would be to close the app). This crash has been around since our initial introduction of Amplify SDK.

### Reproduction steps (if applicable)

Cannot reproduce it. Tried it opening the app with Wi-Fi and data turned off but this will not cause a crash. This crash also doesn't happen for all users.

### Code Snippet

Relevant code from `CustomApplication`, Dagger is used for injection.
```kotlin
@Inject
lateinit var amplifyConfig: AmplifyConfiguration

private fun initAmplify() {
    authSessionHubSubscriber.subscribe()
    Amplify.addPlugin(AWSCognitoAuthPlugin())
    val apiPlugin: AWSApiPlugin = AWSApiPlugin.builder()
        .configureClient(AMPLIFY_API_NAME) { clientBuilder ->
            clientBuilder.addInterceptor(HttpLoggingInterceptor().apply { level = BASIC })
            clientBuilder.addInterceptor(chuckerInterceptor)
            clientBuilder.connectTimeout(AMPLIFY_TIMEOUT_SECONDS, SECONDS)
            clientBuilder.writeTimeout(AMPLIFY_TIMEOUT_SECONDS, SECONDS)
            clientBuilder.readTimeout(AMPLIFY_TIMEOUT_SECONDS, SECONDS)
        }
        .build()
    Amplify.addPlugin(apiPlugin)
    Amplify.configure(amplifyConfig, applicationContext)
}

companion object {

    private const val AMPLIFY_API_NAME = "***********"
    private const val AMPLIFY_TIMEOUT_SECONDS = 20L
}

// Provide function for the amplifyConfig
@Provides
fun provideAmplifyConfig(context: Context): AmplifyConfiguration {
    return AmplifyConfiguration.builder(context)
        .devMenuEnabled(false)
        .build()
}
```

### Log output

<details>

```
Fatal Exception: java.lang.RuntimeException: Unable to create application {insert app package}.CustomApplication: AuthException{message=Failed to instantiate AWSMobileClient within 10 seconds, cause=null, recoverySuggestion=Check network connectivity}
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6250)
       at android.app.ActivityThread.access$1200(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Caused by com.amplifyframework.auth.AuthException: Failed to instantiate AWSMobileClient within 10 seconds
       at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:88)
       at com.amplifyframework.core.category.Category.configure(Category.java:61)
       at com.amplifyframework.core.Amplify.configure(Amplify.java:75)
       at {insert app package}.initAmplify(CustomApplication.java:50)
       at {insert app package}.onCreate(CustomApplication.java:15)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6245)
       at android.app.ActivityThread.access$1200(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1787)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

</details>

### amplifyconfiguration.json

```json
{
  "api": {
    "plugins": {
      "awsAPIPlugin": {
        "gateway": {
          "endpointType": "REST",
          "endpoint": "***********",
          "region": "********",
          "authorizationType": "AWS_IAM"
        }
      }
    }
  },
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "**********",
              "Region": "***********"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "***************",
            "AppClientId": "************",
            "AppClientSecret": "***************",
            "Region": "************"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Firebase device information:
![Screenshot 2022-05-02 at 2 23 02 pm](https://user-images.githubusercontent.com/29642163/166233083-ee40f219-5efd-4e23-8e15-4b038608b202.png)
![Screenshot 2022-05-02 at 2 22 56 pm](https://user-images.githubusercontent.com/29642163/166233087-b265d9f3-a33b-4a64-b459-a70a5b805acb.png)
![Screenshot 2022-05-02 at 2 22 47 pm](https://user-images.githubusercontent.com/29642163/166233092-fb8480be-276f-4f60-9bca-2e804ae55ad7.png)

**Comment by div5yesh** [comment]
Does the app have services running when it's in background? Could you please provide us the details on why the app is trying to configure amplify while it's in background? The amplify categories should be configured on the onCreate of the application.

**Comment by patrickhoette** [comment]
The only place where amplify is configured is in the onCreate of the application and nowhere else. We do have services running in the background but they do not need amplify

**Comment by div5yesh** [comment]
I'd suggest looking for code snippets like `Amplify.configure()` or `AWSMobileClient.initialize()` in the background service to verify if Amplify is not being configured in the background. 

Also, try enabling verbose logs by adding `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))` before Amplify.configure and see if it shows any useful info to debug this case.

**Comment by div5yesh** [comment]
In the callstack I see:

```
 at {insert app package}.initAmplify(CustomApplication.java:50)
 at {insert app package}.onCreate(CustomApplication.java:15)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
```

which points that `initAmplify` is being called in the background leading to Amplify.configure.

**Comment by sktimalsina** [comment]
@patrickhoette Apologies to get back to you late. I am not sure if you have found any headways, but It seems really difficult to reproduce this issue even by throttling the network or even turning it off. 
As you can notice the [code here](https://github.com/aws-amplify/amplify-android/blob/c31de90f764c490223024d163001a653d96f3d54/aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java#L175), all Amplify cognito is trying to do is setup underlying `AWSMobileClient` and callbacks. One of the reasons the latch fails could be that either of those callbacks don't return within time limit currently set to 10s. 
To actually understand what is going around there, we need to look at what `AWSMobileClient` was doing. Were you able to observe any logs with `AWSMobileClient` to understand the context around the issue and share with us.

P.S. I still recommend to surround Amplify configure and add plugin code block with try catch and present the user with informative screen as it can fail due to other (valid) reasons as well.

**Comment by patrickhoette** [comment]
@sktimalsina Thank you for getting back to me. I will discuss the possibility of showing a screen when this failure is detected with our UX designer. Besides this I will see if I can increase the amount of logging that is put into Firebase. I have not recently had much time to look further into this issue but can see from our Crashlytics reports that it is still a problem. We haven't been able to reproduce this issue ourselves either unfortunately.

**Comment by RoustamManookian** [comment]
I have the same issue.
In my case, it's happening every time I run the app in debug mode. want to mention not sometimes BUT "EVERY TIME"
 !!!!

**Comment by RoustamManookian** [comment]
This is the log of android studio, maybe it will be helpful
![amplifyError](https://user-images.githubusercontent.com/75514218/177691217-060c8d78-027d-4e12-9708-f40331a1d027.png)
.

`***W/m.manookian.sc: Suspending all threads took: 5.795ms
***W/m.manookian.sc: Verification of void 
com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.signInWithWebUIHelper(com.amplifyframework.auth.AuthProvider, android.app.Activity, com.amplifyframework.auth.options.AuthWebUISignInOptions, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer) took 113.654ms (1337.39 bytecodes/s) (4320B approximate peak alloc)
***W/m.manookian.sc: Verification of void com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.forgetDevice(com.amplifyframework.core.Action, com.amplifyframework.core.Consumer) took 167.188ms (89.72 bytecodes/s) (1864B approximate peak alloc)
***W/m.manookian.sc: Verification of void com.amazonaws.mobile.client.AWSMobileClient.registerConfigSignInProviders(com.amazonaws.mobile.config.AWSConfiguration) took 458.863ms (115.50 bytecodes/s) (2824B approximate peak alloc)
***W/m.manookian.sc: Verification of void com.amazonaws.mobile.client.AWSMobileClient.registerUserSignInProvidersWithPermissions() took 232.503ms (318.28 bytecodes/s) (2936B approximate peak alloc)
***W/m.manookian.sc: Verification of void com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$1.lambda$onResult$2$com-amplifyframework-auth-cognito-AWSCognitoAuthPlugin$1(com.amazonaws.mobile.client.UserStateDetails) took 186.007ms (655.89 bytecodes/s) (3584B approximate peak alloc)
***D/AWSMobileClient: Using the SignInProviderConfig from `awsconfiguration.json`.
***D/SCS_TAG# MainActivity(MainActivity.kt:111): Could not initialize Amplify ERROR: Failed to instantiate AWSMobileClient within 10 seconds
***I/Choreographer: Skipped 1056 frames!  The application may be doing too much work on its main thread.
***D/AWSMobileClient: initialize: Cognito HostedUI client detected
***D/AWSMobileClient: Inspecting user state details`

**Comment by sktimalsina** [comment]
Closing this due to inactivity. Please reopen this or start a new one if you are still facing the issue with the additional information.

**Comment by danielwilson1702** [comment]
I wish I could reproduce this, @patrickhoette did you ever find a resolution? Do you use WorkManager? I am seeing this happen from WM calls a lot.

**Comment by danielwilson1702** [comment]
I noticed in my logs for certain users the onCreate for the Application class (**only**) is often called by itself a second time _randomly_ with a very short gap between the two invocations (15-30 secs). I have a WorkManager task to check a local log file once every 60 mins but I don't think it's related.

Looking through the merged manifest I can see an entry for:
```    
<activity android:name="com.google.android.play.core.missingsplits.PlayCoreMissingSplitsActivity" 
android:enabled="false" 
android:exported="false" 
android:process=":playcore_missing_splits_activity" 
android:launchMode="singleInstance" android:stateNotNeeded="true"/>
```
 Part of `com.google.android.play:core:1.9.1`, itself a dependency in `com.amplifyframework:core:1.37.3`:
 
 ```
 |    |    |    +--- com.amplifyframework:aws-auth-cognito:1.37.3
|    |    |    |    +--- com.amplifyframework:core:1.37.3
|    |    |    |    |    +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
|    |    |    |    |    +--- androidx.legacy:legacy-support-v4:1.0.0
|    |    |    |    |    +--- androidx.navigation:navigation-ui-ktx:2.3.4 -> 2.5.0-alpha03
|    |    |    |    |    |    +--- androidx.navigation:navigation-ui:2.5.0-alpha03 (*)
|    |    |    |    |    |    \--- androidx.navigation:navigation-runtime-ktx:2.5.0-alpha03 (*)
|    |    |    |    |    \--- androidx.navigation:navigation-dynamic-features-fragment:2.3.4
|    |    |    |    |         +--- androidx.navigation:navigation-dynamic-features-runtime:2.3.4
|    |    |    |    |         |    +--- androidx.navigation:navigation-runtime-ktx:2.3.4 -> 2.5.0-alpha03 (*)
|    |    |    |    |         |    +--- com.google.android.play:core:1.9.1
|    |    |    |    |         |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.71 -> 1.7.10 (*)
|    |    |    |    |         +--- androidx.navigation:navigation-fragment-ktx:2.3.4 -> 2.5.0-alpha03 (*)
|    |    |    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.71 -> 1.7.10 (*)
```

My target devices do not have Google Play or Play services.

The reason I think this extra onCreate call is an issue, and that a secondary process might be involved is because one of my device log files shows that the app was fine uploading logs and hitting amplify.configure multiple times every day until this point:

```
2022-08-30 15:04:41 1: -- AWS OnResult exception -- Failed to instantiate AWSMobileClient within 10 seconds
2022-08-30 15:04:41 1: Creating work request to upload extra logs...ts=60
2022-08-30 15:05:23 1: -- AWS OnResult exception -- Failed to instantiate AWSMobileClient within 10 seconds
2022-08-30 15:05:23 1: Creating work request to upload extra logs...ts=60
```

The timestamps is what are interesting, the device literally did nothing except sit there all day with a WorkManager request being executed every 60 mins on the half hour. At 12.30, 13.30, 14.30 and 15.30 it did some work. At 15.04 it very randomly woke up with no interaction from the user and twice called the app onCreate (1 is the thread ID, unfortunately I don't log the pid).

When it failed to configure Amplify, it did not manage to succeed again until `2022-09-01 14:15:46 1: Amplify configured`. My devices reboot themselves every 24 hours at around 3 AM. That means it got into a state that even 2 reboots across 48 hours did not fix it. 

I will update if I learn more about what is calling a second `onCreate` and if a separate process is involved. I could be completely wrong but for sure we need an update in this SDK to better handle this error. Does it reach out to the network? [This question remains unanswered. ](https://stackoverflow.com/questions/64313461/does-amplify-configure-require-network-connection)

**Comment by patrickhoette** [comment]
@danielwilson1702 Sorry for the late reply I have been busy with other things and this issue got deprioritized in the process. We have not found a solution to this issue yet. We tried running the initialization asynchronously on another thread but this did not help. I did some digging into the SDK but as far as I can see it doesn't make any network calls during initialization however I am not 100% sure of this as the code is a bit of a maze. I did see it make some file system read operations however I find it hard to believe that they would be dead locked for even so much as 1-2s. 

Interresting findings on your part. Seeing as we have not heard active complaints about any frequent crashes of the app (which we should have had considering the frequency with which they happen according to Firebase Crashlytics) you might be correct in thinking that its triggered by something that is entirely in the background. Its hard to confirm this though as any crashes that happen in the `onCreate` of the `Application` class will be reported as being in the background. 

I have asked one of my colleagues to have a look at this issue as well and he proposed that we used a heavily throttle internet connection or even something with a login portal to test if its network related. We need to get some assistance from one of our testers to help in setting up the testing. I hope to find the time for this somewhere this week.

While I don't think we actively use the work manager it might be added by one of our dependencies. I will double check with another colleague to see if he knows any instances where the work manager is used, if not I will check our bigger dependencies to see if they use it. However if I am not mistaken the SDK should throw a different exception if you try to initialize it when its already initialized. From looking through the code that specific exception only gets thrown when the timeout runs out.

**Comment by danielwilson1702** [comment]
Thanks @patrickhoette yes it is not high priority enough / affecting enough users for me to spent too much time on but if I find anything I will let you know 👍

**Comment by danielwilson1702** [comment]
Another small update, I think something might have changed in Amplify to exacerbate the problem on devices running KitKat. I am running several apps across hundreds of POS devices ranging from Android 4.2.2 to 10. Right now we are rolling out a release and I can see 35 users are currently in a completely broken state:

![image](https://user-images.githubusercontent.com/5859421/194962312-5f246c23-d973-4646-a861-3c83e49fd166.png)

100% of them are on Android 4.4.2, trying to upload on a worker task but failing because the call to configure failed. Unfortunately I don't have a 4.4.2 device myself but will attempt to setup an emulator to make sure it's not something very obvious. I will also try and dig down into the versions and see if I can tell what's changed to cause this spike.

**Comment by amitind49** [comment]
@danielwilson1702 @tjleing @sktimalsina @div5yesh @patrickhoette Do you guys get an answer that how we can fix this issue?

I'm using the Cognito version 
   ```
 implementation 'com.amplifyframework:core:1.36.1'
    implementation 'com.amplifyframework:aws-auth-cognito:1.36.1'
```

**Comment by patrickhoette** [comment]
@amitind49 No unfortunately we never managed to figure out why this was happening. Currently the project we had this issue for is not actively being worked on by anyone so sadly I cannot be of much assistance in helping to further debug this issue. If you do end up finding a fix please let me know though.
