### ISSUE TITLE
BrowserNotInstallException when Targeting Android 30+ 

### ISSUE THREAD

**Issue by codeversed** [aws-amplify/amplify-android#1730]
**Framework**
```
implementation("com.amplifyframework:core-kotlin:0.19.3")
implementation("com.amplifyframework:aws-auth-cognito:1.35.3")
```

**Device Tested**
Pixel 6 Pro - Android 12, latest update

**Exception**
`BrowserNotInstallException`

**Stacktrace**
```
AuthException{message=Sign-in with web UI failed, cause=com.amazonaws.mobileconnectors.cognitoauth.exceptions.BrowserNotInstalledException: No browsers installed., recoverySuggestion=See attached exception for more details}
	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$23.onError(AWSCognitoAuthPlugin.java:1271)
	at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
	at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
	at com.amazonaws.mobile.client.AWSMobileClient$27$1$3.run(AWSMobileClient.java:3544)
	at java.lang.Thread.run(Thread.java:920)
Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.BrowserNotInstalledException: No browsers installed.
	at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.launchCustomTabs(AuthClient.java:797)
	at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.launchCognitoAuth(AuthClient.java:711)
	at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.getSession(AuthClient.java:269)
	at com.amazonaws.mobileconnectors.cognitoauth.AuthClient.getSession(AuthClient.java:220)
	at com.amazonaws.mobileconnectors.cognitoauth.Auth.getSession(Auth.java:678)
	at com.amazonaws.mobile.client.AWSMobileClient$27.run(AWSMobileClient.java:3562)
	at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
	... 1 more
```

**Behavior**
When using the auth framework mentioned above and targeting Android 30+, the SDK reports back a `BrowserNotInstallException`. This is caused by the change in the Android 11 (SDK 30) [package visibility](https://developer.android.com/about/versions/11/privacy/package-visibility).

**Bad Solution**
When adding `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />` to your manifest, the web browser launches as expected. Without this, you get the exception. 

Adding the `QUERY_ALL_PACKAGES` permission is not the answer but it seems like the SDK needs an update to not query to check if a browser is installed or to implement a new, non-permission friendly, way to check if the browser intent can be handled. I think removing this check and allowing the developer to handle a regular thrown Intent exception if needed would be the better way to go. 

**Possible Solution**
If we add queries to the manifest, this allows the failing line of code to work.
The check to see if the browser is installed fails on `intentWeb.resolveActivity(context.getPackageManager()) != null`. 

Adding to the root of the manifest:
```
<queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
    </queries>
```

This allows Android to properly query the installed browsers. Is this the solution? 

**Expected Behavior**
I would expect the SDK to just try to launch a web Intent rather than check if a browser is installed first. My Pixel 6 Pro does have a browser installed so I would expect it to launch it and not throw the exception. 

**Also tested**
Using `AuthWebUISignInOptions` I also tested specifically adding a `browserPackage` but this did not work either. It's still a permission issue check that happens even with setting these options. 

**NOTE**
This does not seem to be the case for Samsung Android 12 on One UI v 4.1 _(at least for my S21 Ultra 5G)_. On this S21, it seems to not throw an exception and works as expected. 

Please let me know if you require any other information. 

Thanks!

**Comment by div5yesh** [comment]
Yes, add queries tag to `AndroidManifest.xml` file. Please refer our docs: https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android/#update-androidmanifestxml
