### ISSUE TITLE
Fatal Exception: com.amazonaws.AmazonClientException: Failed to get credentials from Cognito Identity

### ISSUE THREAD

**Issue by parkerZhangLumoX** [aws-amplify/amplify-android#1818]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication, REST API

### Gradle script dependencies

<details>

```groovy
// Put output below this line
implementation 'com.amplifyframework:core-kotlin:0.20.2'
    implementation 'com.amplifyframework:core:1.36.2'
    implementation 'com.amplifyframework:aws-api:1.36.2'
    implementation 'com.amplifyframework:aws-storage-s3:1.36.2'
    implementation 'com.amplifyframework:aws-auth-cognito:1.36.2'

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I got the crash when send a request with an unavailable network.  The rest api's authorizationType is AWS_IAM.
How to handle this exception? the try/catch is not work

the code like this:
```kotlin
Amplify.addPlugin(AWSApiPlugin())
Amplify.addPlugin(AWSCognitoAuthPlugin())
Amplify.configure(application)
applicationScope.launch{
  try{
     val request = RestOptions.builder().addPath("/xxxx").build()
     val response = Amplify.API.get(request, "xxxx")
  } catch(ex: Exception){
  }
}
```
the crash log:
```
Fatal Exception: com.amazonaws.AmazonClientException: Failed to get credentials from Cognito Identity
       at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:407)
       at com.amplifyframework.api.aws.auth.IamRequestDecorator.decorate(IamRequestDecorator.java:105)
       at com.amplifyframework.api.aws.AWSApiPlugin.lambda$configure$0(AWSApiPlugin.java:161)
       at com.amplifyframework.api.aws.AWSApiPlugin$$ExternalSyntheticLambda1.intercept(:4)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

Caused by com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.ca-central-1.amazonaws.com": No address associated with hostname
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:750)
       at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:791)
       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:703)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:482)
       at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:400)
       at com.amplifyframework.api.aws.auth.IamRequestDecorator.decorate(IamRequestDecorator.java:105)
       at com.amplifyframework.api.aws.AWSApiPlugin.lambda$configure$0(AWSApiPlugin.java:161)
       at com.amplifyframework.api.aws.AWSApiPlugin$$ExternalSyntheticLambda1.intercept(:4)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by eeatonaws** [comment]
Thank you for reporting this issue. A fix for the issue is included in Amplify Android 1.36.3 and Amplify Android Kotlin Facade 0.20.3.
