### ISSUE TITLE
DataStore (v1.37.5) Exception in App Start-up 

### ISSUE THREAD

**Issue by rayshi67** [aws-amplify/amplify-android#2066]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy

    def amplify_version = "1.37.5"

    // amplify
    implementation "com.amplifyframework:core:$amplify_version"
    implementation "com.amplifyframework:aws-api:$amplify_version"
    implementation "com.amplifyframework:aws-datastore:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
    implementation "com.amplifyframework:aws-storage-s3:$amplify_version"

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.8 (Oracle Corporation 11.0.8+10-LTS)
OS:           Mac OS X 10.15.7 x86_64


```

</details>

### Describe the bug

App was working fine before upgrading Amplify libraries from v1.34.2 to v1.37.5.

It throws the following exception when app starts up,

```
2022-10-27 14:13:02.814 10020-10316/com.jiesoft.tam.driver.debug E/SQLiteLog: (1) no such column: ModelMetadata.__typename
2022-10-27 14:13:02.905 10020-10318/com.jiesoft.tam.driver.debug E/SQLiteLog: (1) no such column: __typename
2022-10-27 14:13:02.953 10020-10318/com.jiesoft.tam.driver.debug E/amplify:aws-datastore: Error encountered in the DataStore.
    DataStoreException{message=Initial cloud sync failed for Timeslot., cause=DataStoreException{message=Error in saving the model: ModelMetadata[primaryKey =Timeslot|095e0cc0-5b24-4366-9ed8-8dfb4984a042], cause=android.database.sqlite.SQLiteException: no such column: __typename (code 1): , while compiling: UPDATE `ModelMetadata` SET `id` = ?, `__typename` = ?, `_deleted` = ?, `_lastChangedAt` = ?, `_version` = ? WHERE `ModelMetadata`.`id` = ?;, recoverySuggestion=See attached exception for details.}, recoverySuggestion=Check your internet connection.}
        at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$createHydrationTask$7$SyncProcessor(SyncProcessor.java:171)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$SyncProcessor$AqYR2hSIvdFyh8TFv_9xDScS02s.accept(Unknown Source:6)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:88)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:117)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle$ToSingle.onError(CompletableToSingle.java:73)
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:156)
        at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapCompletable$ConcatMapCompletableObserver.innerError(FlowableConcatMapCompletable.java:166)
        at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapCompletable$ConcatMapCompletableObserver$ConcatMapInnerObserver.onError(FlowableConcatMapCompletable.java:260)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableOnErrorComplete$OnError.onError(CompletableOnErrorComplete.java:66)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:95)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeFlatMapCompletable$FlatMapCompletableObserver.onError(MaybeFlatMapCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:91)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.onError(CompletableCreate.java:77)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$wibDnzZq5mJOXI5qd8Wh_zsWeGQ.accept(Unknown Source:4)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:386)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$0Q4t2Se5oVsIb4pxkwWPcTH3ADs.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2022-10-27 14:13:02.960 10020-10318/com.jiesoft.tam.driver.debug E/amplify:aws-datastore: Caused by: DataStoreException{message=Error in saving the model: ModelMetadata[primaryKey =Timeslot|095e0cc0-5b24-4366-9ed8-8dfb4984a042], cause=android.database.sqlite.SQLiteException: no such column: __typename (code 1): , while compiling: UPDATE `ModelMetadata` SET `id` = ?, `__typename` = ?, `_deleted` = ?, `_lastChangedAt` = ?, `_version` = ? WHERE `ModelMetadata`.`id` = ?;, recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:382)
        	... 6 more
     Caused by: android.database.sqlite.SQLiteException: no such column: __typename (code 1): , while compiling: UPDATE `ModelMetadata` SET `id` = ?, `__typename` = ?, `_deleted` = ?, `_lastChangedAt` = ?, `_version` = ? WHERE `ModelMetadata`.`id` = ?;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:890)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:501)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1070)
        at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.execute(SQLCommandProcessor.java:73)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:773)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:365)
        	... 6 more
2022-10-27 14:13:02.975 10020-10092/com.jiesoft.tam.driver.debug E/amplify:aws-datastore: Failure encountered while attempting to start API sync.
    DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.lang.RuntimeException: DataStoreException{message=Error in saving the model: ModelMetadata[primaryKey =Timeslot|095e0cc0-5b24-4366-9ed8-8dfb4984a042], cause=android.database.sqlite.SQLiteException: no such column: __typename (code 1): , while compiling: UPDATE `ModelMetadata` SET `id` = ?, `__typename` = ?, `_deleted` = ?, `_lastChangedAt` = ?, `_version` = ? WHERE `ModelMetadata`.`id` = ?;, recoverySuggestion=See attached exception for details.}, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:324)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$PVk58tU0K8ndPJYnH_tRmf4RGwE.subscribe(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: DataStoreException{message=Error in saving the model: ModelMetadata[primaryKey =Timeslot|095e0cc0-5b24-4366-9ed8-8dfb4984a042], cause=android.database.sqlite.SQLiteException: no such column: __typename (code 1): , while compiling: UPDATE `ModelMetadata` SET `id` = ?, `__typename` = ?, `_deleted` = ?, `_lastChangedAt` = ?, `_version` = ? WHERE `ModelMetadata`.`id` = ?;, recoverySuggestion=See attached exception for details.}
        at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
        at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1461)
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:320)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$PVk58tU0K8ndPJYnH_tRmf4RGwE.subscribe(Unknown Source:2) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: DataStoreException{message=Error in saving the model: ModelMetadata[primaryKey =Timeslot|095e0cc0-5b24-4366-9ed8-8dfb4984a042], cause=android.database.sqlite.SQLiteException: no such column: __typename (code 1): , while compiling: UPDATE `ModelMetadata` SET `id` = ?, `__typename` = ?, `_deleted` = ?, `_lastChangedAt` = ?, `_version` = ? WHERE `ModelMetadata`.`id` = ?;, recoverySuggestion=See attached exception for details.}
2022-10-27 14:13:02.979 10020-10092/com.jiesoft.tam.driver.debug E/amplify:aws-datastore:     at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:382)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$0Q4t2Se5oVsIb4pxkwWPcTH3ADs.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        	... 3 more
     Caused by: android.database.sqlite.SQLiteException: no such column: __typename (code 1): , while compiling: UPDATE `ModelMetadata` SET `id` = ?, `__typename` = ?, `_deleted` = ?, `_lastChangedAt` = ?, `_version` = ? WHERE `ModelMetadata`.`id` = ?;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:890)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:501)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1070)
        at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.execute(SQLCommandProcessor.java:73)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:773)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:365)
        	... 6 more

```

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by rayshi67** [comment]
Sorry the amplify version was upgraded from v1.32.1 to v1.37.5.

And with Amplify DataStore v1.37.5 on Android 8.1, it throws the SQLiteException as per the above bug description.

**Comment by joekiller** [comment]
I've seen this between 1.35.4 and 1.37.5 as well. The table is different because of the custom primary key feature and since the tables already exist I guess there isn't a migration of table columns to get that new column unless you delete your datastore.

**Comment by joekiller** [comment]
This is a similar problem to #1925 which was unresolved.

**Comment by joekiller** [comment]
The bug most likely came from the https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.37.0 release with #1650. When a mutation is removed from the outbox and the application goes to update the ModelMetadata table, there will not be a column __typename.

**Comment by rayshi67** [comment]
Thanks for looking into it.

Could someone please advice a work-around or a timeframe for the fix.

**Comment by lawmicha** [comment]
Thank you for bringing this to our attention @rayshi67 and for the links @joekiller, the PR's change to ModelMetadata table is here https://github.com/aws-amplify/amplify-android/pull/1650/files#diff-5cdf2885642e1d230ebe77616604dc89e3ed4deb7975f34b69159e0affd9dc27 It looks like we tried to reproduce the issue over in https://github.com/aws-amplify/amplify-android/issues/1925 but could not. A cursory glance appears that the upgrade scenario without a call to clear will cause this issue. Upgrading to the latest Android library with CPK changes, starting DataStore's sync process, will break since existing ModelMetadata items will fail to be inserted (attempting to insert __typename for a table that does not have the column) and, maybe fail to retrieve. Querying for previous ModelMetadata items and deserializing that to the new ModelMetadata object may be fine if the deserialization produces an object with `null` __typename property, however may cause additional issues after deserialization if the value is expected to exist and be used in subsequent code after deserialization.

### Repro steps
1. Reproduce this on an older version, say start with `v1.34.4`, launch the app and call `DataStore.start()` to create the ModelMetadata table, without __typename column
2. toggle wifi off, submit a few mutation events, so they don't get dequeued as there's no network to sync them to AppSync
3. Upgrade to `v1.37.5`, launch the app, and see if the outgoing queue of events are failing to reconcile after being synced to AppSync. Reconciliation should extract part of the mutation response from AppSync for creating and saving the ModelMetadata object containing __typename, but the existing table created in step 1 does not contain this column.
4. Call `DataStore.clear()` to delete the old table
5. Call `start()` to create the new table with the updated column
6. Submit a mutation event through `save()` and see that it gets synced to AppSync, reconciled to the local ModelMetadata table successfully with the __typename

### Option 1. Migration script
On DataStore.start(), run a migration script that 
1. Checks if the local database exists, if does not, finish migration (since no data needs to be migrated)
2. If it exists, check if ModelMetadataTable should be migrated (check if column exists?), if does not, finish
3. If it needs to be migrated, create a ModelMetadataCopy (containing __typename)
4. query for the data from the existing ModelMetadata
5. insert the queried data into ModelMetadataCopy where __typename comes from the `id` of the data. If i recall, ModelMetadata table's id column is a formatted string containing "<ModelName>|<identifier>`. 
6. Delete ModelMetadata and rename ModelMetadataCopy as ModelMetadata, finish migration

### Option 2. Investigate removing `__typename` from ModelMetadata table
Why was this added? Where is this being used? And how to achieve the same functionality without it? Once we have a code fix for this, developers can upgrade past `v1.37.5` to a release that has this fix.

**Comment by AnilMaktala** [comment]
Hey @rayshi67, Please retest with latest version and let us know if you still see the same issue.
