### ISSUE TITLE
Unauthorized access to 

### ISSUE THREAD

**Issue by omar-faruk01** [aws-amplify/amplify-android#2124]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

GraphQL API, DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line

plugins {
    id 'com.android.application'
}

android {
    compileSdk 32

    defaultConfig {
        applicationId "edu.oakland.destaurants"
        minSdk 25
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        // Support for Java 8 features
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    def lifecycle_version = "2.5.1"
    implementation "androidx.lifecycle:lifecycle-viewmodel:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"


    // Amplify core dependency
    implementation 'com.amplifyframework:core:1.37.6'
    // AWS Auth Cognito dependency
    implementation 'com.amplifyframework:aws-auth-cognito:1.37.6'
    // DataStore dependency
    implementation 'com.amplifyframework:aws-datastore:1.37.6'
    // S3 storage dependency
    implementation 'com.amplifyframework:aws-storage-s3:1.37.6'
    // API AppSync
    implementation 'com.amplifyframework:aws-api:1.37.6'
    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
    // event bus open source
    implementation 'org.greenrobot:eventbus:3.3.1'

}
```

</details>

### Environment information

<details>

```
# Put output below this line
Welcome to Gradle 7.3.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html


------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_291 (Oracle Corporation 25.291-b10)
OS:           Windows 10 10.0 amd64


```

</details>

### Please include any relevant guides or documentation you're referencing

Amplify android docs, youtube videos

### Describe the bug

User is confirmed and authenticated using Amplify Auth. When user visits authenticated activity, the user is unable to create an API mutation or DataStore save. The debug shows federated tokens as true, signed-in message, and auth session. However, when the onclick method is ran to post, debug shows an error stating:

 W/amplify:aws-datastore: Unauthorized failure:ON_CREATE Restaurant 

then 

Started subscription processor for models: [Restaurant, Review] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
W/amplify:aws-datastore: Initial cloud sync failed for Review.
    DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Not Authorized to access syncReviews on type ModelReviewConnection', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncReviews'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}

### Reproduction steps (if applicable)

1. Login to the app
2. Access authenticated activity 
3. Click the button on click listener which runs the datastore post

### Code Snippet

```java
// Put your code below this line.
package edu.oakland.destaurants;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import com.amazonaws.mobile.client.AWSMobileClient;
import com.amplifyframework.auth.AuthUser;
import com.amplifyframework.core.Amplify;
import com.amplifyframework.datastore.generated.model.Restaurant;
import com.amplifyframework.datastore.generated.model.Review;

import org.greenrobot.eventbus.EventBus;
import org.greenrobot.eventbus.Subscribe;
import org.greenrobot.eventbus.ThreadMode;


public class AccountActivity extends AppCompatActivity {

    EditText nameET, addressET, cityET, stateET, zipET, countryET;
    Button submitBtn, signOutBtn;
    TextView usernameTV;
    private static final String TAG = "AmplifyApp";
    private AWSMobileClient mobileClient;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_account);

        nameET = findViewById(R.id.nameET);
        addressET = findViewById(R.id.addrET);
        cityET = findViewById(R.id.cityET);
        stateET = findViewById(R.id.stateET);
        zipET = findViewById(R.id.zipET);
        countryET = findViewById(R.id.countryET);
        submitBtn = findViewById(R.id.submitBtn);
        usernameTV = findViewById(R.id.usernameTV);
        signOutBtn = findViewById(R.id.signOutBtn);




    }

    @Override
    public void onStart() {
        super.onStart();
        Log.i(TAG, "MainActivity, onStart()");
        EventBus.getDefault().register(this);
    }

    @Override
    public void onStop() {
        EventBus.getDefault().unregister(this);
        Log.i(TAG, "MainActivity, onStop()");
        super.onStop();
    }

    @Override
    protected void onResume() {
        super.onResume();
        String username = Amplify.Auth.getCurrentUser().getUsername();

        usernameTV.setText("Hello " + username);

        signOutBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Amplify.Auth.signOut(
                        () -> {
                            Log.i(TAG, "Signed out this device successfully");
                            Intent loginIntent = new Intent(AccountActivity.this, LoginActivity.class);
                            startActivity(loginIntent);
                        },
                        error -> Log.i(TAG, error.toString())
                );
            }
        });

        Restaurant restaurant = Restaurant.builder()
                .name("Curryest")
                .address("12532 Conant st")
                .city("Hamtramck")
                .country("USA")
                .category("Desi")
                .username(Amplify.Auth.getCurrentUser().getUsername())
//                .restrictions(list)
                .build();

        Review review = Review.builder()
                .restaurantId(restaurant.getId())
                .rating(5.0)
                .comment("Great food")
                .build();

        submitBtn.setOnClickListener(view -> {

            Amplify.DataStore.save(
                    restaurant,
                    savedRestaurant -> {
                        Log.i("MyAmplifyApp", "restaurant saved.");
                    },
                    error -> Log.e("MyAmplifyApp",  "Error creating post", error)
            );
        });



    }

    @Subscribe(sticky = true, threadMode = ThreadMode.MAIN)
    public void onEvent(GreenRobotEvents.MobileClientEvent event) {
        Log.i(TAG, "AuthenticatedUsersActivity, got mobile client event....");
        mobileClient = event.awsMobileClient;
    }

}
```

### Log output

<details>

```
// Put your logs below this line


Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore: Setting currentState to SYNC_VIA_API
I/amplify:aws-datastore: Starting API synchronization mode.
I/amplify:aws-datastore: Orchestrator lock released.
I/amplify:aws-datastore: Starting processing subscription events.
I/MyAmplifyApp: restaurant saved.
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=SerializedModel{id='eb5a4c05-0175-4999-8e9c-23e3dd8e6ff8', serializedData={country=USA, zipCode=null, address=12532 Conant st, city=Hamtramck, picture1=null, restrictions=null, picture2=null, createdAt=null, name=Curryest, id=eb5a4c05-0175-4999-8e9c-23e3dd8e6ff8, state=null, category=Desi, updatedAt=null, username=faruk.or01@gmail.com}, modelName=Restaurant}, mutationType=CREATE, mutationId=27eb6207-6708-11ed-8d95-cf799651d801, predicate=MatchAllQueryPredicate}
I/and.destaurant: Background concurrent copying GC freed 33783(2509KB) AllocSpace objects, 21(632KB) LOS objects, 49% free, 5365KB/10MB, paused 1.264ms total 111.030ms
W/and.destaurant: Long monitor contention with owner pool-4-thread-1 (5053) at void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action)(SubscriptionEndpoint.java:187) waiters=0 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 2.536s
W/amplify:aws-datastore: Unauthorized failure:ON_CREATE Review
W/and.destaurant: Long monitor contention with owner pool-4-thread-1 (5053) at void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action)(SubscriptionEndpoint.java:187) waiters=1 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 2.801s
W/amplify:aws-datastore: Unauthorized failure:ON_UPDATE Review
W/and.destaurant: Long monitor contention with owner pool-4-thread-1 (5053) at void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action)(SubscriptionEndpoint.java:187) waiters=2 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 3.015s
W/amplify:aws-datastore: Unauthorized failure:ON_DELETE Review
W/and.destaurant: Long monitor contention with owner pool-4-thread-1 (5053) at void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action)(SubscriptionEndpoint.java:187) waiters=3 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 3.246s
W/amplify:aws-datastore: Unauthorized failure:ON_CREATE Restaurant
W/and.destaurant: Long monitor contention with owner pool-4-thread-1 (5053) at void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action)(SubscriptionEndpoint.java:187) waiters=4 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 3.531s
W/amplify:aws-datastore: Unauthorized failure:ON_UPDATE Restaurant
W/amplify:aws-datastore: Unauthorized failure:ON_DELETE Restaurant
I/amplify:aws-datastore: Started subscription processor for models: [Restaurant, Review] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
W/amplify:aws-datastore: Initial cloud sync failed for Review.
    DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Not Authorized to access syncReviews on type ModelReviewConnection', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncReviews'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0(AppSyncClient.java:116)
        at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda4.accept(Unknown Source:6)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:151)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
E/amplify:aws-datastore: Error encountered in the DataStore.
    DataStoreException{message=Initial cloud sync failed for Review., cause=DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Not Authorized to access syncReviews on type ModelReviewConnection', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncReviews'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check your internet connection.}
        at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$createHydrationTask$7$com-amplifyframework-datastore-syncengine-SyncProcessor(SyncProcessor.java:171)
        at com.amplifyframework.datastore.syncengine.SyncProcessor$$ExternalSyntheticLambda18.accept(Unknown Source:6)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:88)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:117)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle$ToSingle.onError(CompletableToSingle.java:73)
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:156)
        at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapCompletable$ConcatMapCompletableObserver.onError(FlowableConcatMapCompletable.java:129)
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:94)
        at io.reactivex.rxjava3.internal.util.HalfSerializer.onError(HalfSerializer.java:67)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.onError(FlowableConcatMap.java:199)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runBackfused(FlowableObserveOn.java:449)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:172)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Not Authorized to access syncReviews on type ModelReviewConnection', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncReviews'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0(AppSyncClient.java:116)
        at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda4.accept(Unknown Source:6)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:151)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
E/amplify:aws-datastore: Failure encountered while attempting to start API sync.
    DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.lang.RuntimeException: DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Not Authorized to access syncReviews on type ModelReviewConnection', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncReviews'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$com-amplifyframework-datastore-syncengine-Orchestrator(Orchestrator.java:324)
        at com.amplifyframework.datastore.syncengine.Orchestrator$$ExternalSyntheticLambda5.subscribe(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.RuntimeException: DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Not Authorized to access syncReviews on type ModelReviewConnection', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncReviews'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
        at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1461)
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$com-amplifyframework-datastore-syncengine-Orchestrator(Orchestrator.java:320)
        at com.amplifyframework.datastore.syncengine.Orchestrator$$ExternalSyntheticLambda5.subscribe(Unknown Source:2) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51) 
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2850) 
        at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64) 
        at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) 
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
E/amplify:aws-datastore: Caused by: DataStoreException{message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Not Authorized to access syncReviews on type ModelReviewConnection', locations='[GraphQLLocation{line='2', column='3'}]', path='[GraphQLPathSegment{value='syncReviews'}]', extensions='{errorInfo=null, data=null, errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0(AppSyncClient.java:116)
        at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda4.accept(Unknown Source:6)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:151)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        	... 3 more


```

</details>

### amplifyconfiguration.json

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "destaurants": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://56cjt5pdbbb3bi47pvin4nhj4u.appsync-api.us-west-2.amazonaws.com/graphql",
                    "region": "us-west-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-west-2:28b186bd-7589-4648-9629-3463dd940d31",
                            "Region": "us-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-west-2_iLDPApZKt",
                        "AppClientId": "3kul3o6v648hf5p95v2v25b6m4",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [],
                        "usernameAttributes": [],
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://56cjt5pdbbb3bi47pvin4nhj4u.appsync-api.us-west-2.amazonaws.com/graphql",
                        "Region": "us-west-2",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "destaurants_AMAZON_COGNITO_USER_POOLS"
                    }
                }
            }
        }
    }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line

type Restaurant @model
@auth(rules: [{ allow: owner, ownerField: "username", operations: [create, delete, update] }])
{
  id: ID!
  name: String
  address: String
  city: String
  state: String
  zipCode: String
  country: String
  picture1: String
  picture2: String
  username: ID
  restrictions: [String]
  category: String
  review: [Review] @hasMany(indexName: "byRestaurant", fields: ["id"])
}

type Review @model
@auth(rules: [{ allow: owner, ownerField: "username", operations: [create, delete, update] }])
{
  id: ID!
  rating: Float
  comment: String
  username: ID
  restaurantId: ID! @index(name: "byRestaurant", sortKeyFields: ["comment"])
}



```

</details>

### Additional information and screenshots

Removing the owner field from auth still causes the same error

**Comment by omar-faruk01** [comment]
Kindly respond to this issue with urgency

**Comment by omar-faruk01** [comment]
Takahiro Suzuki helped resolve

**Comment by jamesclement** [comment]
What was the solution here ?
