### ISSUE TITLE
Fatal Exception: com.amplifyframework.auth.AuthException: Sign-in with web UI failed

### ISSUE THREAD

**Issue by ngallazzi** [aws-amplify/amplify-android#2125]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
implementation "com.amplifyframework:aws-auth-cognito:1.36.1"
implementation "com.amplifyframework:aws-api:1.37.1"
implementation 'com.amazonaws:aws-android-sdk-appsync:3.3.2'
implementation "com.amplifyframework:core-kotlin:0.20.1"
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          18.0.1.1 (Oracle Corporation 18.0.1.1+2-6)
OS:           Mac OS X 13.0.1 x86_64


```

</details>

### Describe the bug

Random uncatched runtime crashes

### Code Snippet

```java

 Amplify.Auth.signInWithSocialWebUI(
            provider = provider,
            callingActivity = activity
        )
```

### Log output

```
# Crashlytics - Stack trace
# Application: 
# Platform: android
# Version: 16.0.1 (1224)
# Issue: 506f6dcdd015a7b4c1054344debb4f21
# Session: 6376B8F0030C00013D027297E07145F4_DNE_0_v2
# Date: Thu Nov 17 2022 23:43:30 GMT+0100 (Central European Standard Time)

Fatal Exception: com.amplifyframework.auth.AuthException: Sign-in with web UI failed
       at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$23.onError(AWSCognitoAuthPlugin.java:1275)
       at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
       at com.amazonaws.mobile.client.internal.InternalCallback.onError(InternalCallback.java:67)
       at com.amazonaws.mobile.client.AWSMobileClient$27$1$3.run(AWSMobileClient.java:3544)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.net.UnknownHostException: Unable to resolve host "vtp-format.auth.eu-west-1.amazoncognito.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at com.android.okhttp.Dns$1.lookup(Dns.java:41)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:192)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
       at com.amazonaws.mobileconnectors.cognitoauth.util.AuthHttpClient.httpPost(AuthHttpClient.java:70)
       at com.amazonaws.mobileconnectors.cognitoauth.AuthClient$1.run(AuthClient.java:467)
       at java.lang.Thread.run(Thread.java:923)

Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)

```

### amplifyconfiguration.json
```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "[my_pool_id]",
            "AppClientId": "[my_app_client_id]",
            "Region": "eu-west-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "OAuth": {
              "WebDomain": "vtp-format.auth.eu-west-1.amazoncognito.com",
              "AppClientId": "[my_app_client_id]",
              "SignInRedirectURI": "myapp://signin",
              "SignOutRedirectURI": "myapp://signout",
              "Scopes": [
                "email",
                "profile",
                "openid"
              ]
            }
          }
        }
      }
    }
  }
}
```

**Comment by tylerjroach** [comment]
@ngallazzi, are you seeing 100% failure rate here? It looks like you are using the Kotlin Facade to make the API calls. As shown in the Kotlin Coroutines sample, this call should be wrapped in a try/catch to catch the AuthException.

The issue here is that the the Custom Tab attempted to load the WebDomain in the amplifyconfiguration.json file, and failed to resolve the host. 

If you are seeing this failure 100% of the time, the `WebDomain` may be incorrect. If this is an occasional failure, this would indicate a load failure.

**Comment by ngallazzi** [comment]
@tylerjroach thank you for the quick reply. No actually I'm not getting a 100% failure rate, it's probably due to unresolved host from time to time. 
We wrapped the Auth call and now we are able to catch the exception. We didn't see the possibility of an exception in the first place unfortunately :(

**Comment by tylerjroach** [comment]
@ngallazzi Glad this resolved your issue. All Kotlin Coroutine Facades should be try/caught. Instead of having an `onError` callback like the standard API's, errors are exposed as exceptions.
