### ISSUE TITLE
Getting SocketTimeoutException error after calling Amplify.API.query and set the limit more than 1_000

### ISSUE THREAD

**Issue by KevinLam0308** [aws-amplify/amplify-android#2136]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

GraphQL API

### Gradle script dependencies

Used version:

    implementation 'com.amplifyframework:core:1.37.6'
    implementation 'com.amplifyframework:aws-api:1.37.6'

### Environment information

Welcome to Gradle 5.1.1!

Here are the highlights of this release:
 - Control which dependencies can be retrieved from which repositories
 - Production-ready configuration avoidance APIs

For more details see https://docs.gradle.org/5.1.1/release-notes.html

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Windows 10 10.0 amd64

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/android/#list-items

### Describe the bug

I'm getting below error message after calling Amplify.API.query and set the limit more than 1_000

2022-11-21 11:45:29.186 22116-22285/com.example.mainactivity E/MyAmplifyApp: Query failed.
    ApiException{message=OkHttp client request failed., cause=java.net.SocketTimeoutException: timeout, recoverySuggestion=See attached exception for more details.}
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:161)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at com.amplifyframework.api.aws.UserAgentInterceptor.intercept(UserAgentInterceptor.java:56)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

### Reproduction steps (if applicable)

1. create a new App on Amplify console
2. create 4 data models and all have relation, below is the schema

type Page4 @model @auth(rules: [{allow: public}]) {
  id: ID!
  date: String
  time: String
  count: Int
  checksum: String
  page3ID: ID! @index(name: "byPage3")
  page3: Page3 @belongsTo(fields: ["page3ID"])
}

type Page3 @model @auth(rules: [{allow: public}]) {
  id: ID!
  date: String
  time: String
  count: Int
  checksum: String
  page2ID: ID! @index(name: "byPage2")
  Page4s: [Page4] @hasMany(indexName: "byPage3", fields: ["id"])
  page2: Page2 @belongsTo(fields: ["page2ID"])
}

type Page2 @model @auth(rules: [{allow: public}]) {
  id: ID!
  date: String
  time: String
  count: Int
  checksum: String
  page1ID: ID! @index(name: "byPage1")
  Page3s: [Page3] @hasMany(indexName: "byPage2", fields: ["id"])
  page1: Page1 @belongsTo(fields: ["page1ID"])
}

type Page1 @model @auth(rules: [{allow: public}]) {
  id: ID!
  date: String
  time: String
  count: Int
  checksum: String
  Page2s: [Page2] @hasMany(indexName: "byPage1", fields: ["id"])
}

3. build an Android App and send data to Amplify by Amplify.API.mutate
4. after sending more than 1000 set of data, then query by Amplify.API.query

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by KevinLam0308** [comment]
additional information:

SocketTimeoutException error is only happen when qurey Page 4's data, query Page 1, 2, 3 doesn't encounter this problem.

**Comment by AnilMaktala** [comment]
Hey @KevinLam0308 👋 , Thank you for raising this. Are you experiencing this when you use pagination with the 1K limit?

**Comment by KevinLam0308** [comment]
Hello @AnilMaktala , 

No, I use pagination more than 1k limit in order to reduce the query time, but finally got above error.

**Comment by AnilMaktala** [comment]
Hi @KevinLam0308, looks like the result set is exceeding the Appsync default limit. As a workaround, you can set the pagination (recommended) limit to 1k and let us know if it resolves the issue.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please create a new issue or reopen this issue if you have additional questions.
