### ISSUE TITLE
Subscription is not working with Cognito User Pools

### ISSUE THREAD

**Issue by shiroyama** [aws-amplify/amplify-android#214]
`Amplify.API.subscribe` works pretty well with API Key, but not with Cognito User Pools.
I changed my `amplifyconfiguration.json` like below to make use of Cognito User Pools.

```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "api": {
    "plugins": {
      "awsAPIPlugin": {
        "amplifyDatasource": {
          "endpointType": "GraphQL",
          "endpoint": "https://xxx.appsync-api.ap-northeast-1.amazonaws.com/graphql",
          "region": "ap-northeast-1",
          "authorizationType": "AMAZON_COGNITO_USER_POOLS",
        }
      }
    }
  }
}
```

And I started to get the error like this and subscription started not working.

```
2019-12-29 08:40:07.705 4492-4492/us.shiroyama.amplifyforandroid E/MainActivity: Subscription not acknowledged.
    com.amplifyframework.api.ApiException: Subscription not acknowledged.
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionReady(SubscriptionEndpoint.java:369)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:120)
        at com.amplifyframework.api.aws.SubscriptionOperation.start(SubscriptionOperation.java:84)
        at com.amplifyframework.api.aws.AWSApiPlugin.subscribe(AWSApiPlugin.java:445)
        at com.amplifyframework.api.aws.AWSApiPlugin.subscribe(AWSApiPlugin.java:404)
        at com.amplifyframework.api.aws.AWSApiPlugin.subscribe(AWSApiPlugin.java:376)
        at com.amplifyframework.api.ApiCategory.subscribe(ApiCategory.java:197)
        at us.shiroyama.amplifyforandroid.MainActivity.subscribe(MainActivity.kt:277)
        at us.shiroyama.amplifyforandroid.MainActivity.onStart(MainActivity.kt:91)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

I tried to look into the source code, and figured out `SubscriptionEndpoint#requestSubscription()` timed out because it failed to make a valid WebSocket connection. It seemed like the class `SubscriptionAuthorizationHeader` in charge of creating request header only supported API key for now. 

```
final class SubscriptionAuthorizationHeader {
    static JSONObject from(ApiConfiguration apiConfiguration) throws ApiException {
        final String host = Uri.parse(apiConfiguration.getEndpoint()).getHost();
        final String apiKey = apiConfiguration.getApiKey();
        try {
            return new JSONObject()
                .put("host", host)
                .put("x-amz-date", Iso8601Timestamp.now())
                .put("x-api-key", apiKey);
```

I tied to add `apiKey` in `amplifyconfiguration.json` as well, but this workaround seemed not working because the class `AWSApiPluginConfigurationReader` only allowed this configuration when the  authorizationType  equals `AuthorizationType.API_KEY`.

```
    private static AWSApiPluginConfiguration parseConfigurationJson(JSONObject configurationJson)
            throws ApiException {
                ...
                if (AuthorizationType.API_KEY.equals(authorizationType)) {
                    apiConfigBuilder.apiKey(apiSpec.getString(ConfigKey.API_KEY.key()));
                }
    }
```

Is there any workaround with this issue? Are you going to support subscription with Cognito User Pools? Thanks.

**Comment by jamesonwilliams** [comment]
Thanks @shiroyama for reporting this issue. In the `0.9` preview release of Amplify, API key is the only supported authorization method for subscriptions.  We have an existing issue open to track this needed feature work (#185).

**Comment by TrekSoft** [comment]
Yeah already recorded in that other issue and working on it now.
