### ISSUE TITLE
MFA Authentication with Authenticator app is broken in Amplify Android 2.0.0

### ISSUE THREAD

**Issue by keyrunHORNET** [aws-amplify/amplify-android#2142]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line

implementation "com.amplifyframework:core:2.0.0"
implementation "com.amplifyframework:aws-auth-cognito:2.0.0"
```

</details>

### Environment information

<details>

```
# Put output below this line
Gradle 7.4

```

</details>

### Describe the bug

MFA Authentication with both the authenticator app and SMS is working in version 1.37.6, but only SMS works in 2.0.0. Trying to authenticate with an account with TOTP enabled as MFA Throws `UnknownException{message=Sign in failed., cause=java.lang.Exception: Response did not contain sign in info., recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}` while calling `Amplify.Auth.signIn(userName, userPassword, { // AuthSignInResult },{ //AuthException } )`

### Code Snippet

```kotlin
// Put your code below this line.
 suspend fun signIn(
        userName: String,
        userPassword: String
    ): Result<AuthSignInStep> {
        return try {
            val result = suspendCoroutine<AuthSignInStep> { continuation ->
                Amplify.Auth.signIn(userName, userPassword, {
                    continuation.resume(it)
                }, {
                    continuation.resumeWithException(it)
                })
            }
            Result.success(result.nextStep.signInStep)
        } catch (authException: Exception) {
            Result.failure(authException)
        }
    }
```

### Log output

<details>

```
// Put your logs below this line

UnknownException{message=Sign in failed., cause=java.lang.Exception: Response did not contain sign in info., recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.auth.cognito.CognitoAuthExceptionConverter$Companion.lookup(CognitoAuthExceptionConverter.kt:91)
        at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$_signIn$1.invoke(RealAWSCognitoAuthPlugin.kt:501)
        at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$_signIn$1.invoke(RealAWSCognitoAuthPlugin.kt:481)
        at com.amplifyframework.statemachine.StateMachine.notifySubscribers(StateMachine.kt:176)
        at com.amplifyframework.statemachine.StateMachine.process(StateMachine.kt:191)
        at com.amplifyframework.statemachine.StateMachine.access$process(StateMachine.kt:49)
        at com.amplifyframework.statemachine.StateMachine$send$1.invokeSuspend(StateMachine.kt:160)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.lang.Exception: Response did not contain sign in info.
        at com.amplifyframework.auth.cognito.helpers.SignInChallengeHelper.evaluateNextStep(SignInChallengeHelper.kt:89)
        at com.amplifyframework.auth.cognito.helpers.SignInChallengeHelper.evaluateNextStep$default(SignInChallengeHelper.kt:40)
        at com.amplifyframework.auth.cognito.actions.SRPCognitoActions$verifyPasswordSRPAction$$inlined$invoke$1.execute(Action.kt:108)
        at com.amplifyframework.auth.cognito.actions.SRPCognitoActions$verifyPasswordSRPAction$$inlined$invoke$1$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by banji180** [comment]
The team is already aware of [this](https://github.com/aws-amplify/amplify-swift/issues/2572#issuecomment-1330705338) and will let you know soon as we have any update.

**Comment by keyrunHORNET** [comment]
any idea when this fix will be available? We are planning to release our product with this feature in Jan of 2023 and our release plan depends on this fix!

**Comment by gpanshu** [comment]
Hi @keyrunHORNET unfortunately I do not have a timeline for you but once we implement this in the library we will comment it out here.

**Comment by gpanshu** [comment]
Hi @keyrunHORNET you can use the MFA guide to setup and use MFA successfully on Android : https://docs.amplify.aws/lib/auth/mfa/q/platform/android/ . Thank you so much for your patience on this.
