### ISSUE TITLE
[API] Gson serializer does not handle timezone offset in seconds

### ISSUE THREAD

**Issue by raphkim** [aws-amplify/amplify-android#221]
`AWSDate` supports seconds field in the timezone offset, which is not supported by ISO8601 format. This causes Gson to fail to parse date such as "1970-01-01-01:00:00". 

Sample code to reproduce:
```
Gson gson = new Gson();
gson.fromJson("\"1970-01-01-01:00:00\"", Date.class);
```

logcat report from integration test (breaks CircleCI workflow):
```
    --------- beginning of crash
2020-01-06 16:59:13.548 31371-31406/com.amplifyframework.api.aws.test E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.amplifyframework.api.aws.test, PID: 31371
    com.google.gson.JsonSyntaxException: 1970-01-01-07:00:39
        at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:87)
        at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:75)
        at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:46)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:1003)
        at com.google.gson.Gson.fromJson(Gson.java:975)
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory.parseDataAsList(GsonGraphQLResponseFactory.java:198)
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory.buildSingleArrayResponse(GsonGraphQLResponseFactory.java:132)
        at com.amplifyframework.api.graphql.GraphQLOperation.wrapMultiResultResponse(GraphQLOperation.java:71)
        at com.amplifyframework.api.aws.SingleArrayResultOperation.access$100(SingleArrayResultOperation.java:47)
        at com.amplifyframework.api.aws.SingleArrayResultOperation$OkHttpCallback.onResponse(SingleArrayResultOperation.java:140)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.text.ParseException: Failed to parse date ["1970-01-01-07:00:39"]: Mismatching time zone indicator: GMT-07:00:39 given, resolves to GMT
        at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:274)
        at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:85)
        at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:75) 
        at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:46) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.Gson.fromJson(Gson.java:932) 
        at com.google.gson.Gson.fromJson(Gson.java:1003) 
        at com.google.gson.Gson.fromJson(Gson.java:975) 
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory.parseDataAsList(GsonGraphQLResponseFactory.java:198) 
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory.buildSingleArrayResponse(GsonGraphQLResponseFactory.java:132) 
        at com.amplifyframework.api.graphql.GraphQLOperation.wrapMultiResultResponse(GraphQLOperation.java:71) 
        at com.amplifyframework.api.aws.SingleArrayResultOperation.access$100(SingleArrayResultOperation.java:47) 
        at com.amplifyframework.api.aws.SingleArrayResultOperation$OkHttpCallback.onResponse(SingleArrayResultOperation.java:140) 
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.IndexOutOfBoundsException: Mismatching time zone indicator: GMT-07:00:39 given, resolves to GMT
        at com.google.gson.internal.bind.util.ISO8601Utils.parse(ISO8601Utils.java:240)
        at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:85) 
        at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:75) 
        at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:46) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.Gson.fromJson(Gson.java:932) 
        at com.google.gson.Gson.fromJson(Gson.java:1003) 
        at com.google.gson.Gson.fromJson(Gson.java:975) 
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory.parseDataAsList(GsonGraphQLResponseFactory.java:198) 
        at com.amplifyframework.api.aws.GsonGraphQLResponseFactory.buildSingleArrayResponse(GsonGraphQLResponseFactory.java:132) 
        at com.amplifyframework.api.graphql.GraphQLOperation.wrapMultiResultResponse(GraphQLOperation.java:71) 
        at com.amplifyframework.api.aws.SingleArrayResultOperation.access$100(SingleArrayResultOperation.java:47) 
        at com.amplifyframework.api.aws.SingleArrayResultOperation$OkHttpCallback.onResponse(SingleArrayResultOperation.java:140) 
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by raphkim** [comment]
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
^ This looks like a potential solution to this problem on Java side.
```
DateTimeFormatter dateTimeFormatter = DateTimeFormatter
        .ofPattern("yyyy-MM-dd'T'HH:mm[:ss[.SSS]]XXXXX");
DateTimeFormatter dateFormatter = DateTimeFormatter
        .ofPattern("yyyy-MM-dd[XXXXX]");
DateTimeFormatter timeFormatter = DateTimeFormatter
        .ofPattern("HH:mm[:ss[.SSS]][XXXXX]");

System.out.println(ZonedDateTime.parse("1970-01-01T12:00:00+01:00:00", dateTimeFormatter));
System.out.println(LocalDate.parse("1970-01-01+10:00", dateFormatter));
System.out.println(LocalTime.parse("12:00:05.123Z", timeFormatter));

// Print:
// 1970-01-01T12:00+01:00
// 1970-01-01
// 12:00:05.123
```

**Comment by raphkim** [comment]
Edit: We decided against using Java 8 :(

**Comment by jamesonwilliams** [comment]
@richardmcclellan resolved this with work in [`Temporal.java`](https://github.com/aws-amplify/amplify-android/blob/master/core/src/main/java/com/amplifyframework/core/model/temporal/Temporal.java#L32-L36) and [`TemporalDeserializers.java`](https://github.com/aws-amplify/amplify-android/blob/master/aws-api/src/main/java/com/amplifyframework/api/aws/TemporalDeserializers.java#L28).
