### ISSUE TITLE
signInWithSocialWebUI not working on 2.1.0 but working on 1.37.5

### ISSUE THREAD

**Issue by JurajBegovac** [aws-amplify/amplify-android#2234]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

RxJava

### Amplify Categories

Authentication

### Gradle script dependencies

I use .toml file for dependencies
<details>

```toml
[versions]
amplify = "2.1.0"

[libraries]
amplify-cognito = { module = "com.amplifyframework:aws-auth-cognito", version.ref = "amplify" }
amplify-core = { module = "com.amplifyframework:core", version.ref = "amplify" }
amplify-rxbindings = { module = "com.amplifyframework:rxbindings", version.ref = "amplify" }
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.16.1 (Homebrew 11.0.16.1+0)
OS:           Mac OS X 12.6.1 aarch64


```

</details>

### Describe the bug

When I call (e.g.):
```
signInWithSocialWebUI(AuthProvider.google(), activity)
```

It works on `1.37.5` but not on `2.1.0`.

On `2.1.0` it let me choose google account and then when it was redirected back I get this:
```
                                          ServiceException{message=invalid_client, cause=ServiceException{message=invalid_client, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
                                          	at com.amplifyframework.auth.cognito.helpers.HostedUIHttpHelper.parseTokenResponse(HostedUIHttpHelper.kt:102)
                                          	at com.amplifyframework.auth.cognito.helpers.HostedUIHttpHelper.fetchTokens(HostedUIHttpHelper.kt:69)
                                          	at com.amplifyframework.auth.cognito.HostedUIClient.fetchToken(HostedUIClient.kt:119)
                                          	at com.amplifyframework.auth.cognito.actions.HostedUICognitoActions$fetchHostedUISignInToken$$inlined$invoke$1.execute(Action.kt:73)
                                          	at com.amplifyframework.statemachine.ConcurrentEffectExecutor$execute$1$1.invokeSuspend(ConcurrentEffectExecutor.kt:26)
                                          	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                          	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                          	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                          	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                          	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                          	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                          Caused by: ServiceException{message=invalid_client, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}§
```

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

![Screenshot 2023-01-18 at 23 01 18](https://user-images.githubusercontent.com/8510212/213304989-f5037844-d561-4527-8337-44086171b109.png)

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
Hi @JurajBegovac, I just created a new project to test `signInWithSocialWebUI` with Google and was able to sign in successfully. V1 Amplify may have been pulling some values from awsconfiguration.json, where v2 pulls exclusively from amplifyconfiguration.json. Can you double check that you have the expected values for your app client and secret, and that they match between the two files?

**Comment by JurajBegovac** [comment]
Hi, but I don't use `amplifyconfiguration.json` - I add config manually because I want to dynamically add cognito config.
Like this:
```
// This is amplify json config where we can have different clientIds for e.g. different product flavors
val CognitoConfig.awsConfigurationJson: String
    get() = """
            {
                "auth":
                {
                    "plugins":
                    {
                        "awsCognitoAuthPlugin":
                        {
                            "Auth":
                            {
                                "Default":
                                {
                                    "authenticationFlowType": "USER_SRP_AUTH",
                                    "OAuth":
                                    {
                                        "AppClientId": "$clientId",
                                        "AppClientSecret": "$clientSecret",
                                        "Scopes":
                                        [
                                            "email"
                                        ],
                                        "SignInRedirectURI": "$signInRedirectURI",
                                        "SignOutRedirectURI": "$signOutRedirectURI",
                                        "WebDomain": "$webDomain"
                                    },
                                    "socialProviders":
                                    [
                                        "GOOGLE",
                                        "APPLE",
                                        "FACEBOOK"
                                    ]
                                }
                            },
                            "CognitoUserPool":
                            {
                                "Default":
                                {
                                    "AppClientId": "$clientId",
                                    "AppClientSecret": "$clientSecret",
                                    "PoolId": "$poolId",
                                    "Region": "$region"
                                }
                            }
                        }
                    }
                }
            }
        """.trimIndent()


// And this is how I initialize amplify
        RxAmplify.addPlugin(AWSCognitoAuthPlugin())
        val amplifyConfig = AmplifyConfiguration.builder(JSONObject(cognitoConfig.awsConfigurationJson))
            .build()
        RxAmplify.configure(amplifyConfig, context)
```

**Comment by tylerjroach** [comment]
@JurajBegovac Thank you for the report. I'm working on a fix now. In scenarios where "AppClientSecret" is required, the required Authorization header is not being attached properly.

**Comment by thehoneymad** [comment]
I just ran into this one with `signInWithWebUI` function. Is that due the same reason? :)

**Comment by tylerjroach** [comment]
@thehoneymad Do you have appSecret being used for hosted UI? If so, this would be the reason. The fix has been merged and will be in an upcoming release.

**Comment by thehoneymad** [comment]
Yes. I configured an AppSecret for my OAuth client. Should I refrain from it?

**Comment by tylerjroach** [comment]
@JurajBegovac and @thehoneymad Amplify for Android v2.2.0 has been released with the included fix. Please let me know if this addressed the issue.

**Comment by thehoneymad** [comment]
Thank you! This helps a lot!

**Comment by JurajBegovac** [comment]
> @JurajBegovac and @thehoneymad Amplify for Android v2.2.0 has been released with the included fix. Please let me know if this addressed the issue.

Thank you. Will let you know if something is not working 😄

**Comment by MrBenjoo** [comment]
I just tried the latest version (v2.2.0) and im getting a similar error when im trying to sign in with google using social web ui: 

`java.lang.NullPointerException
                                                                                                    	at com.amplifyframework.auth.cognito.actions.AuthorizationCognitoActions$initializeFetchAuthSession$$inlined$invoke$1.execute(Action.kt:89)
                                                                                                    	at com.amplifyframework.statemachine.ConcurrentEffectExecutor$execute$1$1.invokeSuspend(ConcurrentEffectExecutor.kt:26)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c4f97ba, Dispatchers.Default]`

**Comment by JurajBegovac** [comment]
I have decided not to update the current version (1.x.x) as it is functioning well and I don't have the time to troubleshoot any potential issues that may arise. I plan to update it in a few months when I have more time to spare. At present, I don't see any clear benefits in updating.

**Comment by sdhuka** [comment]
@MrBenjoo Could you please open a new issue with more details? Original issue was fixed and looking at the stacktrace you posted it looks like a different issue so we will investigate it separately once you provide more details.

**Comment by MrBenjoo** [comment]
@sdhuka I just created a new issue #2282. I can try to add more info if its required.
