### ISSUE TITLE
AWSDataStorePlugin failed to start and caused app crash

### ISSUE THREAD

**Issue by aladine** [aws-amplify/amplify-android#2263]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

RxJava

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```kotlin
        val amplifyVersion = "1.37.11"
        api("com.amplifyframework:aws-api") { version { strictly (amplifyVersion) } }
        api("com.amplifyframework:aws-api-appsync") { version { strictly (amplifyVersion) } }
        api("com.amplifyframework:core") { version { strictly (amplifyVersion) } }
        api("com.amplifyframework:aws-datastore") { version { strictly (amplifyVersion) } }
        api("com.amplifyframework:rxbindings") { version { strictly (amplifyVersion) } } 
```

</details>

### Environment information

<details>

```
gradle-6.9


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android/#initialize-amplify-datastore

### Describe the bug

I could see the crash from Google Play console but it it is not able to reprod by normal testing.
Our AWS amplify client add AWSDatastorePlugin as the documentation. We use Functional auth when initiating.
The crash doesn't show any line from our code base so I guess it was failed when a thread from AWSDataStorePlugin got error. The issue was not seen when we use 1.37.2 version.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line

01-27 08:28:58.256 13150 19245 E Logger: UNEXPECTED_SHUTDOWN: io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | DataStoreException{message=Failed to start DataStore., cause=DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}, recoverySuggestion=Retry.}
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onError(ObservableSingleSingle.java:94)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:74)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchIfEmpty$SwitchIfEmptyObserver.onError(ObservableSwitchIfEmpty.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableFromCompletable$FromCompletableObserver.onError(ObservableFromCompletable.java:86)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate$Emitter.tryOnError(CompletableCreate.java:91)
	at com.amplifyframework.rx.-$$Lambda$zIZyqfgIH9KQDY-bajp7xiM2ACg.accept(Unknown Source:4)
	at com.amplifyframework.datastore.AWSDataStorePlugin.lambda$start$11(AWSDataStorePlugin.java:304)
	at com.amplifyframework.datastore.-$$Lambda$AWSDataStorePlugin$cggRMfd1LBrEzQR62lPbVtwdUwY.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:64)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$NextObserver.onError(CompletableAndThenCompletable.java:104)
	at io.reactivex.rxjava3.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:73)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableError.subscribeActual(CompletableError.java:29)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout$TimeOutObserver.onComplete(CompletableTimeout.java:87)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:47)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableTimeout.subscribeActual(CompletableTimeout.java:53)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: DataStoreException{message=Failed to start DataStore., cause=DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}, recoverySuggestion=Retry.}
	... 25 more
Caused by: DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}
	at com.amplifyframework.datastore.syncengine.Orchestrator.performSynchronized(Orchestrator.java:177)
	at com.amplifyframework.datastore.syncengine.Orchestrator.start(Orchestrator.java:149)
	at com.amplifyframework.datastore.AWSDataStorePlugin.start(AWSDataStorePlugin.java:300)
	at com.amplifyframework.datastore.AWSDataStorePlugin.save(AWSDataStorePlugin.java:375)
	at com.amplifyframework.datastore.AWSDataStorePlugin.save(AWSDataStorePlugin.java:363)
	at com.amplifyframework.datastore.DataStoreCategory.save(DataStoreCategory.java:61)
	at com.amplifyframework.rx.RxDataStoreBinding.lambda$save$0$RxDataStoreBinding(RxDataStoreBinding.java:56)
	at com.amplifyframework.rx.-$$Lambda$RxDataStoreBinding$_miUz4-Bg75GLR5c5oaiezNkebY.emitTo(Unknown Source:4)
	at com.amplifyframework.rx.RxDataStoreBinding.lambda$toCompletable$18(RxDataStoreBinding.java:208)
	at com.amplifyframework.rx.-$$Lambda$RxDataStoreBinding$njh8Iy6bOexefkSlyPeXXcGfmPE.emitTo(Unknown Source:2)
	at com.amplifyframework.rx.RxAdapters$VoidBehaviors.lambda$toCompletable$0(RxAdapters.java:117)
	at com.amplifyframework.rx.-$$Lambda$RxAdapters$VoidBehaviors$IPp24bguRxQVVQNZ2xI-beu2Avs.subscribe(Unknown Source:2)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableToObservable.subscribeActual(CompletableToObservable.java:34)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchIfEmpty.subscribeActual(ObservableSwitchIfEmpty.java:31)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onError(ObservableOnErrorNext.java:96)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchIfEmpty$SwitchIfEmptyObserver.onError(ObservableSwitchIfEmpty.java:63)
	at io.reactivex.rxjava3.observers.SerializedObserver.onError(SerializedObserver.java:155)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableConcatMap$SourceObserver.onError(ObservableConcatMap.java:141)
	at io.reactivex.rxjava3.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableTake$TakeObserver.onError(ObservableTake.java:80)
	at io.reactivex.rxjava3.internal.operators.mixed.SingleFlatMapObservable$FlatMapObserver.onError(SingleFlatMapObservable.java:74)
	at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:95)
	at com.amplifyframework.rx.-$$Lambda$PGv9Bk6mR9azAqZU5AAIY6a0sPo.accept(Unknown Source:4)
```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by dengdan154** [comment]
I was able to reproduce this issue with high confidence. I found that calling `DataStore.save` within the callback of `DataStore.stop` **repeatedly** would lead to DataStoreException. 
```
for (int i = 0; i < 100; i++) {
            Amplify.DataStore.stop(
                    () -> Amplify.DataStore.save(todo,
                            saved -> Log.i("MyAmplifyApp", "Saved a post."),
                            failure -> Log.e("MyAmplifyApp", "Save failed.", failure)
                    ),
                    error -> Log.e("MyAmplifyApp", "Error stopped DataStore", error)
            );
        }
```
A [previous commit](https://github.com/aws-amplify/amplify-android/pull/2209/files#) seemed to fix the issue of calling `DataStore.stop` within the callback of `DataStore.save` but it appears to not cover other cases.
``` 
Caused by: DataStoreException{message=Timed out acquiring orchestrator lock., cause=null, recoverySuggestion=Retry your request.}
    at com.amplifyframework.datastore.syncengine.Orchestrator.performSynchronized(Orchestrator.java:177)
    at com.amplifyframework.datastore.syncengine.Orchestrator.stop(Orchestrator.java:169)
    at com.amplifyframework.datastore.AWSDataStorePlugin.stop(AWSDataStorePlugin.java:314)
    at com.amplifyframework.datastore.DataStoreCategory.stop(DataStoreCategory.java:225)
    at com.example.myamplifyapp.MainActivity.stopThenStart(MainActivity.java:38)
    at com.example.myamplifyapp.MainActivity.lambda$onCreate$3$com-example-myamplifyapp-MainActivity(MainActivity.java:32)
    at com.example.myamplifyapp.MainActivity$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass)
    at android.view.View.performClick(View.java:5610)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1219)
    at android.view.View$PerformClick.run(View.java:22265)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)

**Comment by mattcreaser** [comment]
I believe @dengdan154's code will always throw since there is no synchronization between the starts and stops. That being said, there is indeed an error in the PR he linked. By removing the `doOnFinally` operator and using `andThen` instead, we will no longer release the semaphore if an error occurs during start/stop.

My plan is to just add a `doOnError` to release the semaphore if start/stop emits an error.

**Comment by mattcreaser** [comment]
This has been release in Amplify 2.8.0. Please let us know if you have any problems.
