### ISSUE TITLE
Crash on Application start when calling method Amplify.configure

### ISSUE THREAD

**Issue by MrJorgeXavier** [aws-amplify/amplify-android#2297]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
implementation("com.squareup.okhttp3:okhttp:5.0.0-alpha.11")
implementation("com.amplifyframework:aws-auth-cognito:2.2.1")
implementation("com.amplifyframework:core-kotlin:2.2.1")
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_361 (Oracle Corporation 25.361-b09)
OS:           Mac OS X 13.1 x86_64

```

</details>

### Describe the bug

Our crash monitoring are reporting some occurrences of a crash that happens in the application initialization when calling the amplify's configure method. 
I couldn't reproduce the issue in any way, but the rare users that find this problem can reproduce it frequently.

### Code Snippet

```java
class AppApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        try {
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.configure(context) // The crash happens here in this call
        } catch (exception: AmplifyException) {
            loggingManager.logNonFatalException(exception)
        }
    }
}

```

### Log output

<details>

```
Caused by java.lang.IllegalArgumentException: port must be in between 1 and 65536
       at aws.smithy.kotlin.runtime.http.Url.<init>(Url.kt:36)
       at aws.smithy.kotlin.runtime.http.Url.<init>(Url.kt:24)
       at aws.smithy.kotlin.runtime.http.engine.EnvironmentProxySelectorKt.resolveProxyByProperty(EnvironmentProxySelectorKt.java:60)
       at aws.smithy.kotlin.runtime.http.engine.EnvironmentProxySelectorKt.access$resolveProxyByProperty(EnvironmentProxySelectorKt.java:1)
       at aws.smithy.kotlin.runtime.http.engine.EnvironmentProxySelector.<init>(EnvironmentProxySelector.kt:29)
       at aws.smithy.kotlin.runtime.http.engine.EnvironmentProxySelector.<init>(EnvironmentProxySelector.kt:27)
       at aws.smithy.kotlin.runtime.http.engine.HttpClientEngineConfig$Builder.<init>(HttpClientEngineConfig.kt:133)
       at aws.smithy.kotlin.runtime.http.engine.HttpClientEngineConfig.<clinit>(HttpClientEngineConfig.kt:29)
       at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:27)
       at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineJVMKt.newDefaultHttpEngine(DefaultHttpEngineJVMKt.java:13)
       at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine(DefaultHttpEngineKt.java:12)
       at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine$default(DefaultHttpEngineKt.java:11)
       at aws.sdk.kotlin.runtime.auth.credentials.DefaultChainCredentialsProvider.<init>(DefaultChainCredentialsProvider.kt:49)
       at aws.sdk.kotlin.runtime.auth.credentials.DefaultChainCredentialsProvider.<init>(DefaultChainCredentialsProvider.kt:41)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config.getCredentialsProvider(CognitoIdentityProviderClient.kt:265)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config.<init>(CognitoIdentityProviderClient.kt:12)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config$Builder.build(CognitoIdentityProviderClient.java:319)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Companion.invoke(CognitoIdentityProviderClient.java:244)
       at com.amplifyframework.auth.cognito.AWSCognitoAuthService$Companion.fromConfiguration$aws_auth_cognito_release(AWSCognitoAuthService.kt:31)
       at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.kt:114)
       at com.amplifyframework.core.category.Category.configure(Category.java:91)
       at com.amplifyframework.core.Amplify.configure(Amplify.java:156)
       at com.amplifyframework.core.Amplify.configure(Amplify.java:126)
       at com.amplifyframework.kotlin.core.Amplify$Companion.configure(Amplify.kt:66)


```

</details>

### amplifyconfiguration.json

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "********",
                        "AppClientId": "********",
                        "Region": "******"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "*******",
                            "AppClientId": "*******",
                            "SignInRedirectURI": "*******",
                            "SignOutRedirectURI": "*******",
                            "Scopes": [
                                "aws.cognito.signin.user.admin",
                                "email",
                                "openid",
                                "phone",
                                "profile"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "FACEBOOK",
                            "GOOGLE",
                            "APPLE"
                        ],
                        "usernameAttributes": [],
                        "signupAttributes": [],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_UPPERCASE",
                                "REQUIRES_NUMBERS",
                                "REQUIRES_SYMBOLS"
                            ]
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Hi @MrJorgeXavier Is there a particular phone/OS that this error frequently happens on?

**Comment by gpanshu** [comment]
I have checked this and this happens when the url that you are connecting to has an invalid port number. I copy pasted your amplifyconfiguration into mine with my userpool and I was unable to reproduce this error. 
We can get on a call in discord to troubleshoot this realtime if you believe your endpoint is not the issue here.

**Comment by gpanshu** [comment]
A few questions that may help us find the root cause: 
1. Can you paste exact model numbers of the samsung phones with their OS versions and I can run my app on those to see I can reproduce?
2. Do you know if your customers restart their application does the problem go away or they are unable to use your app at all because of this issue?

**Comment by MrJorgeXavier** [comment]
1. Yesterday a motorola phone also registered the issue, so these are the devices:
  - Samsung Galaxy J8 - Android 10
  - Samsung Galaxy A11 - Android 12
  - Samsung Galaxy S20 FE  - Android 13
  - Moto E6 Play - Android 9
2. The issue happens with few users, however it happens dozens of times with these users. So it seems they are unable  to use the app at all because of this crash.

**Comment by dengdan154** [comment]
@MrJorgeXavier Can you check if you have proxies configured in your environment variables or elsewhere?

**Comment by gpanshu** [comment]
@MrJorgeXavier check for http.proxyHost or https.proxyHost or something like that in your code. This is what will trigger that condition. Try removing it and seeing it this will fix the issue.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please create a new issue or reopen this issue if you have additional questions.

**Comment by reisfernanda** [comment]
@eeatonaws @gpanshu @dengdan154
Hi, the developer who opened this issue is not working on this project anymore, that's why there was no activity since then. I work on the same project and we are still having this crash caught by Crashlytics.

- The current AWS Amplify SDK version used on the project is 2.5.0.
- There is no `http.proxyHost` or `https.proxyHost` or any other proxy configured on our code.
- We're still unable to reproduce the issue, but here is a list of some devices that faced it:

1. Redmi Note 9 Pro - Android 11
2. Galaxy A9 (2018) - Android 10
3. Galaxy M62 - Android 13
4. Galaxy A11 - Android 12
5. Galaxy J8 - Android 10
6. Galaxy F41 - Android 12

Any help here would be appreciated. Thank you!
