### ISSUE TITLE
Amplify.configure(getApplicationContext()) crash:Failed to create storage service., cause=java.lang.IllegalStateException: WorkManager is not initialized properly. 

### ISSUE THREAD

**Issue by waertf** [aws-amplify/amplify-android#2300]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line
 def amplify_version = "2.2.2"
    // Amplify core dependency
    //implementation "com.amplifyframework:core:$amplify_version"
    implementation "com.amplifyframework:aws-storage-s3:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"

```

</details>

### Environment information

<details>

```
# Put output below this line

下午 01:45:30: Executing 'buildEnvironment'...

Executing tasks: [buildEnvironment] in project D:\job\sourceCode\platerecognizer_demo_unitech

Configuration on demand is an incubating feature.

> Task :buildEnvironment

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
+--- com.android.tools.build:gradle:4.0.1
|    +--- com.android.tools.build:builder:4.0.1
|    |    +--- com.android.tools.build:builder-model:4.0.1
|    |    |    \--- com.android.tools:annotations:27.0.1
|    |    +--- com.android.tools.build:builder-test-api:4.0.1
|    |    |    \--- com.android.tools.ddms:ddmlib:27.0.1
|    |    |         +--- com.android.tools:common:27.0.1
|    |    |         |    +--- com.android.tools:annotations:27.0.1
|    |    |         |    +--- com.google.guava:guava:28.1-jre
|    |    |         |    |    +--- com.google.guava:failureaccess:1.0.1
|    |    |         |    |    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    |    |         |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |         |    |    +--- org.checkerframework:checker-qual:2.8.1
|    |    |         |    |    +--- com.google.errorprone:error_prone_annotations:2.3.2
|    |    |         |    |    +--- com.google.j2objc:j2objc-annotations:1.3
|    |    |         |    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.18
|    |    |         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72
|    |    |         |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 -> 1.4.0
|    |    |         |         |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.0
|    |    |         |         |    \--- org.jetbrains:annotations:13.0
|    |    |         |         \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72
|    |    |         |              \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72 -> 1.4.0 (*)
|    |    |         \--- net.sf.kxml:kxml2:2.3.0
|    |    +--- com.android.tools:sdklib:27.0.1
|    |    |    +--- com.android.tools.layoutlib:layoutlib-api:27.0.1
|    |    |    |    +--- com.android.tools:common:27.0.1 (*)
|    |    |    |    +--- net.sf.kxml:kxml2:2.3.0
|    |    |    |    +--- com.android.tools:annotations:27.0.1
|    |    |    |    \--- org.jetbrains:annotations:13.0
|    |    |    +--- com.android.tools:dvlib:27.0.1
|    |    |    |    \--- com.android.tools:common:27.0.1 (*)
|    |    |    +--- com.android.tools:repository:27.0.1
|    |    |    |    +--- com.android.tools:common:27.0.1 (*)
|    |    |    |    +--- com.sun.activation:javax.activation:1.2.0
|    |    |    |    +--- org.apache.commons:commons-compress:1.12
|    |    |    |    +--- org.glassfish.jaxb:jaxb-runtime:2.3.1
|    |    |    |    |    +--- javax.xml.bind:jaxb-api:2.3.1
|    |    |    |    |    |    \--- javax.activation:javax.activation-api:1.2.0
|    |    |    |    |    +--- org.glassfish.jaxb:txw2:2.3.1
|    |    |    |    |    +--- com.sun.istack:istack-commons-runtime:3.0.7
|    |    |    |    |    +--- org.jvnet.staxex:stax-ex:1.8
|    |    |    |    |    +--- com.sun.xml.fastinfoset:FastInfoset:1.2.15
|    |    |    |    |    \--- javax.activation:javax.activation-api:1.2.0
|    |    |    |    +--- com.google.jimfs:jimfs:1.1
|    |    |    |    |    \--- com.google.guava:guava:18.0 -> 28.1-jre (*)
|    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    |    |    +--- com.google.code.gson:gson:2.8.5
|    |    |    +--- org.apache.commons:commons-compress:1.12
|    |    |    +--- org.apache.httpcomponents:httpmime:4.5.6
|    |    |    |    \--- org.apache.httpcomponents:httpclient:4.5.6
|    |    |    |         +--- org.apache.httpcomponents:httpcore:4.4.10
|    |    |    |         +--- commons-logging:commons-logging:1.2
|    |    |    |         \--- commons-codec:commons-codec:1.10
|    |    |    \--- org.apache.httpcomponents:httpcore:4.4.10
|    |    +--- com.android.tools:sdk-common:27.0.1
|    |    |    +--- com.android.tools:sdklib:27.0.1 (*)
|    |    |    +--- com.android.tools.build:builder-test-api:4.0.1 (*)
|    |    |    +--- com.android.tools.build:builder-model:4.0.1 (*)
|    |    |    +--- com.android.tools.ddms:ddmlib:27.0.1 (*)
|    |    |    +--- com.android.tools.analytics-library:shared:27.0.1
|    |    |    |    +--- com.android.tools.analytics-library:protos:27.0.1
|    |    |    |    |    \--- com.google.protobuf:protobuf-java:3.10.0
|    |    |    |    +--- com.android.tools:annotations:27.0.1
|    |    |    |    +--- com.android.tools:common:27.0.1 (*)
|    |    |    |    +--- com.google.guava:guava:28.1-jre (*)
|    |    |    |    +--- com.google.code.gson:gson:2.8.5
|    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    |    |    +--- org.bouncycastle:bcpkix-jdk15on:1.56
|    |    |    |    \--- org.bouncycastle:bcprov-jdk15on:1.56
|    |    |    +--- org.bouncycastle:bcprov-jdk15on:1.56
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    |    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.72 -> 1.4.0
|    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
|    |    |    +--- com.google.protobuf:protobuf-java:3.10.0
|    |    |    +--- javax.inject:javax.inject:1
|    |    |    +--- org.jetbrains.trove4j:trove4j:20160824
|    |    |    \--- com.android.tools.build:aapt2-proto:0.4.0 -> 4.0.1-6197926
|    |    |         \--- com.google.protobuf:protobuf-java:3.10.0
|    |    +--- com.android.tools:common:27.0.1 (*)
|    |    +--- com.android.tools.build:manifest-merger:27.0.1
|    |    |    +--- com.android.tools:common:27.0.1 (*)
|    |    |    +--- com.android.tools:sdklib:27.0.1 (*)
|    |    |    +--- com.android.tools:sdk-common:27.0.1 (*)
|    |    |    +--- com.google.code.gson:gson:2.8.5
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    |    |    \--- net.sf.kxml:kxml2:2.3.0
|    |    +--- com.android.tools.ddms:ddmlib:27.0.1 (*)
|    |    +--- com.android:zipflinger:4.0.1
|    |    |    +--- com.google.guava:guava:27.0.1-jre -> 28.1-jre (*)
|    |    |    \--- com.android.tools:common:27.0.1 (*)
|    |    +--- com.android:signflinger:4.0.1
|    |    |    +--- com.android.tools.build:apksig:4.0.1
|    |    |    \--- com.android:zipflinger:4.0.1 (*)
|    |    +--- com.android.tools.analytics-library:protos:27.0.1 (*)
|    |    +--- com.android.tools.analytics-library:tracker:27.0.1
|    |    |    +--- com.android.tools:annotations:27.0.1
|    |    |    +--- com.android.tools:common:27.0.1 (*)
|    |    |    +--- com.android.tools.analytics-library:protos:27.0.1 (*)
|    |    |    +--- com.android.tools.analytics-library:shared:27.0.1 (*)
|    |    |    +--- com.google.protobuf:protobuf-java:3.10.0
|    |    |    +--- com.google.guava:guava:28.1-jre (*)
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    |    +--- com.android.tools.build:apksig:4.0.1
|    |    +--- com.android.tools.build:apkzlib:4.0.1
|    |    |    +--- com.google.code.findbugs:jsr305:1.3.9 -> 3.0.2
|    |    |    +--- com.google.guava:guava:23.0 -> 28.1-jre (*)
|    |    |    +--- org.bouncycastle:bcpkix-jdk15on:1.56 (*)
|    |    |    +--- org.bouncycastle:bcprov-jdk15on:1.56
|    |    |    \--- com.android.tools.build:apksig:4.0.1
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    |    +--- com.squareup:javawriter:2.5.0
|    |    +--- org.bouncycastle:bcpkix-jdk15on:1.56 (*)
|    |    +--- org.bouncycastle:bcprov-jdk15on:1.56
|    |    +--- org.ow2.asm:asm:7.0
|    |    +--- org.ow2.asm:asm-tree:7.0
|    |    |    \--- org.ow2.asm:asm:7.0
|    |    +--- javax.inject:javax.inject:1
|    |    +--- org.ow2.asm:asm-commons:7.0
|    |    |    +--- org.ow2.asm:asm:7.0
|    |    |    +--- org.ow2.asm:asm-tree:7.0 (*)
|    |    |    \--- org.ow2.asm:asm-analysis:7.0
|    |    |         \--- org.ow2.asm:asm-tree:7.0 (*)
|    |    +--- org.ow2.asm:asm-util:7.0
|    |    |    +--- org.ow2.asm:asm:7.0
|    |    |    +--- org.ow2.asm:asm-tree:7.0 (*)
|    |    |    \--- org.ow2.asm:asm-analysis:7.0 (*)
|    |    +--- it.unimi.dsi:fastutil:7.2.0
|    |    +--- net.sf.jopt-simple:jopt-simple:4.9
|    |    \--- com.googlecode.json-simple:json-simple:1.1
|    +--- com.android.tools.build:aaptcompiler:4.0.1
|    |    +--- com.android.tools.build:aapt2-proto:4.0.1-6197926 (*)
|    |    +--- com.android.tools.layoutlib:layoutlib-api:27.0.1 (*)
|    |    +--- com.google.guava:guava:28.1-jre (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    +--- com.android.tools.analytics-library:crash:27.0.1
|    |    +--- com.android.tools:annotations:27.0.1
|    |    +--- com.google.guava:guava:28.1-jre (*)
|    |    +--- org.apache.httpcomponents:httpmime:4.5.6 (*)
|    |    +--- org.apache.httpcomponents:httpcore:4.4.10
|    |    \--- org.apache.httpcomponents:httpclient:4.5.6 (*)
|    +--- com.android.tools.lint:lint-gradle-api:27.0.1
|    |    +--- com.android.tools:sdklib:27.0.1 (*)
|    |    +--- com.android.tools.build:builder-model:4.0.1 (*)
|    |    +--- com.android.tools.build:gradle-api:4.0.1
|    |    |    +--- com.android.tools.build:builder-test-api:4.0.1 (*)
|    |    |    +--- com.google.guava:guava:28.1-jre (*)
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.72 -> 1.4.0 (*)
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    |    \--- com.google.guava:guava:28.1-jre (*)
|    +--- com.android.tools.build:gradle-api:4.0.1 (*)
|    +--- androidx.databinding:databinding-compiler-common:4.0.1
|    |    +--- androidx.databinding:databinding-common:4.0.1
|    |    +--- com.android.databinding:baseLibrary:4.0.1
|    |    +--- org.antlr:antlr4:4.5.3
|    |    +--- commons-io:commons-io:2.4
|    |    +--- com.googlecode.juniversalchardet:juniversalchardet:1.0.3
|    |    +--- com.google.guava:guava:28.1-jre (*)
|    |    +--- com.squareup:javapoet:1.10.0
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    |    +--- com.google.code.gson:gson:2.8.5
|    |    +--- org.glassfish.jaxb:jaxb-runtime:2.3.1 (*)
|    |    +--- com.android.tools:annotations:27.0.1
|    |    \--- com.android.tools.build.jetifier:jetifier-core:1.0.0-beta09
|    |         +--- com.google.code.gson:gson:2.8.0 -> 2.8.5
|    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.60 -> 1.4.0 (*)
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72 (*)
|    +--- com.android.tools.build:transform-api:2.0.0-deprecated-use-gradle-api
|    +--- org.ow2.asm:asm:7.0
|    +--- org.ow2.asm:asm-analysis:7.0 (*)
|    +--- org.ow2.asm:asm-commons:7.0 (*)
|    +--- org.ow2.asm:asm-util:7.0 (*)
|    +--- net.sf.jopt-simple:jopt-simple:4.9
|    +--- net.sf.proguard:proguard-gradle:6.0.3
|    |    \--- net.sf.proguard:proguard-base:6.0.3
|    +--- com.android.tools.build:bundletool:0.13.2
|    |    +--- com.android.tools.build:aapt2-proto:0.4.0 -> 4.0.1-6197926 (*)
|    |    +--- com.google.auto.value:auto-value-annotations:1.6.2
|    |    +--- com.google.errorprone:error_prone_annotations:2.3.1 -> 2.3.2
|    |    +--- com.google.guava:guava:27.0.1-jre -> 28.1-jre (*)
|    |    +--- com.google.protobuf:protobuf-java:3.4.0 -> 3.10.0
|    |    \--- com.google.protobuf:protobuf-java-util:3.4.0 -> 3.10.0
|    |         +--- com.google.protobuf:protobuf-java:3.10.0
|    |         +--- com.google.guava:guava:28.0-android -> 28.1-jre (*)
|    |         +--- com.google.errorprone:error_prone_annotations:2.3.2
|    |         \--- com.google.code.gson:gson:2.8.5
|    +--- com.android.tools.build.jetifier:jetifier-core:1.0.0-beta09 (*)
|    +--- com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta09
|    |    +--- com.android.tools.build.jetifier:jetifier-core:1.0.0-beta09 (*)
|    |    +--- org.ow2.asm:asm:6.0 -> 7.0
|    |    +--- org.ow2.asm:asm-util:6.0 -> 7.0 (*)
|    |    +--- org.ow2.asm:asm-commons:6.0 -> 7.0 (*)
|    |    +--- org.jdom:jdom2:2.0.6
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.60 -> 1.4.0 (*)
|    +--- com.google.protobuf:protobuf-java:3.10.0
|    +--- com.google.protobuf:protobuf-java-util:3.10.0 (*)
|    \--- com.google.crypto.tink:tink:1.3.0-rc2
|         +--- com.google.protobuf:protobuf-java:3.10.0
|         \--- org.json:json:20180813
\--- org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0
     +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.0
     |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     |    +--- org.jetbrains.kotlin:kotlin-script-runtime:1.4.0
     |    +--- org.jetbrains.kotlin:kotlin-reflect:1.4.0 (*)
     |    +--- org.jetbrains.kotlin:kotlin-daemon-embeddable:1.4.0
     |    \--- org.jetbrains.intellij.deps:trove4j:1.0.20181211
     +--- org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.4.0
     |    +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.0 (*)
     |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     +--- org.jetbrains.kotlin:kotlin-android-extensions:1.4.0
     |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.0 (*)
     +--- org.jetbrains.kotlin:kotlin-compiler-runner:1.4.0
     |    +--- org.jetbrains.kotlin:kotlin-build-common:1.4.0
     |    +--- org.jetbrains.kotlin:kotlin-daemon-client:1.4.0
     |    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.4.0 (*)
     |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7
     |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.71 -> 1.4.0 (*)
     |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.71 -> 1.4.0
     |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7 (*)
     +--- org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.4.0
     |    +--- org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.4.0
     |    |    +--- org.jetbrains.kotlin:kotlin-scripting-common:1.4.0
     |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     |    |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7 (*)
     |    |    +--- org.jetbrains.kotlin:kotlin-scripting-jvm:1.4.0
     |    |    |    +--- org.jetbrains.kotlin:kotlin-script-runtime:1.4.0
     |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     |    |    |    \--- org.jetbrains.kotlin:kotlin-scripting-common:1.4.0 (*)
     |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7 (*)
     |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     +--- org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.4.0 (*)
     +--- org.jetbrains.kotlin:kotlin-reflect:1.4.0 (*)
     +--- org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.4.0
     |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     +--- org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.4.0
     |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     +--- org.jetbrains.kotlin:kotlin-util-klib:1.4.0
     |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     |    \--- org.jetbrains.kotlin:kotlin-util-io:1.4.0
     |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.0 (*)
     +--- com.google.code.gson:gson:2.8.5
     +--- de.undercouch:gradle-download-task:4.0.2
     \--- com.github.gundy:semver4j:0.16.4
          \--- org.antlr:antlr4-runtime:4.5.2-1

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 396ms
1 actionable task: 1 executed

Build Analyzer results available
下午 01:45:31: Execution finished 'buildEnvironment'.

```

</details>

### Describe the bug

cannot initialize amplify when run
Amplify.configure(getApplicationContext());

### Code Snippet

```java
// Put your code below this line.
package com.unitech.platerecognizer;


import android.app.Application;
import android.content.res.Resources;
import android.util.Log;

import com.amplifyframework.AmplifyException;
import com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin;
import com.amplifyframework.core.Amplify;
import com.amplifyframework.logging.AndroidLoggingPlugin;
import com.amplifyframework.logging.LogLevel;
import com.amplifyframework.storage.s3.AWSS3StoragePlugin;

public class MyApplication extends Application {
    private static MyApplication mInstance;
    private static Resources res;
    @Override
    public void onCreate() {
        super.onCreate();
        try {
            mInstance = this;
            res = getResources();
            // Add these lines to add the AWSCognitoAuthPlugin and AWSS3StoragePlugin plugins
            Amplify.addPlugin(new AndroidLoggingPlugin(LogLevel.VERBOSE));
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.configure(getApplicationContext());

            Log.i("MyAmplifyApp", "Initialized Amplify");
        } catch (AmplifyException error) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error);
        }
    }
    public static MyApplication getInstance() {
        return mInstance;
    }

    public static Resources getRes() {
        return res;
    }
}

```

### Log output

<details>

```
// Put your logs below this line

2023-02-22 13:27:49.040 14995-15071 amplify:aw...AuthPlugin com.unitech.platerecognizer          V  Auth State Change: NotConfigured(id=)
2023-02-22 13:27:49.044 14995-15094 amplify:aw...AuthPlugin com.unitech.platerecognizer          V  Auth State Change: ConfiguringAuth(id=)
2023-02-22 13:27:49.045 14995-15071 amplify:aw...AuthPlugin com.unitech.platerecognizer          V  InitAuthConfig Starting execution
2023-02-22 13:27:49.053 14995-15071 amplify:aw...AuthPlugin com.unitech.platerecognizer          V  Credential Store State Change: NotConfigured(id=)
2023-02-22 13:27:49.061 14995-15097 amplify:aw...AuthPlugin com.unitech.platerecognizer          V  Credential Store State Change: MigratingLegacyStore(id=)
2023-02-22 13:27:49.065 14995-15072 amplify:aw...AuthPlugin com.unitech.platerecognizer          V  MigrateLegacyCredentials Starting execution
2023-02-22 13:27:49.124 14995-14995 MyAmplifyApp            com.unitech.platerecognizer          E  Could not initialize Amplify
                                                                                                    StorageException{message=Failed to create storage service., cause=java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider., recoverySuggestion=Did you make sure to add AWSCognitoAuthPlugin to Amplify? Check the attached exception for more details.}
                                                                                                    	at com.amplifyframework.storage.s3.AWSS3StoragePlugin.configure(AWSS3StoragePlugin.java:216)
                                                                                                    	at com.amplifyframework.core.category.Category.configure(Category.java:91)
                                                                                                    	at com.amplifyframework.core.Amplify.configure(Amplify.java:156)
                                                                                                    	at com.amplifyframework.core.Amplify.configure(Amplify.java:126)
                                                                                                    	at com.unitech.platerecognizer.MyApplication.onCreate(MyApplication.java:28)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6494)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:220)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7412)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
                                                                                                    Caused by: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
                                                                                                    	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:173)
                                                                                                    	at androidx.work.WorkManager.getInstance(WorkManager.java:184)
                                                                                                    	at com.amplifyframework.storage.s3.transfer.TransferManager.<init>(TransferManager.kt:49)
                                                                                                    	at com.amplifyframework.storage.s3.service.AWSS3StorageService.<init>(AWSS3StorageService.kt:59)
                                                                                                    	at com.amplifyframework.storage.s3.AWSS3StoragePlugin.lambda$new$0(AWSS3StoragePlugin.java:125)
                                                                                                    	at com.amplifyframework.storage.s3.-$$Lambda$AWSS3StoragePlugin$Uf1cxOAcWTbGKdgkbFkNUTueXUY.create(Unknown Source:2)
                                                                                                    	at com.amplifyframework.storage.s3.AWSS3StoragePlugin.configure(AWSS3StoragePlugin.java:214)
                                                                                                    	at com.amplifyframework.core.category.Category.configure(Category.java:91) 
                                                                                                    	at com.amplifyframework.core.Amplify.configure(Amplify.java:156) 
                                                                                                    	at com.amplifyframework.core.Amplify.configure(Amplify.java:126) 
                                                                                                    	at com.unitech.platerecognizer.MyApplication.onCreate(MyApplication.java:28) 
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6494) 
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:220) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:214) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7412) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
2023-02-22 13:27:49.129 14995-15072 amplify:aw...AuthPlugin com.unitech.platerecognizer          V  MigrateLegacyCredentials Sending event LoadCredentialStore
2023-02-22 13:27:49.130 14995-15097 amplify:aw...AuthPlugin com.unitech.platerecognizer          V  Credential Store State Change: LoadingStoredCredentials(id=)
2023-02-22 13:27:49.131 14995-15072 amplify:aw...AuthPlugin com.unitech.platerecognizer          V  LoadCredentialStore Starting execution

```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

`

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    implementation 'org.tensorflow:tensorflow-lite:2.9.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.9.0'
    implementation 'org.tensorflow:tensorflow-lite-hexagon:2.9.0'

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    def amplify_version = "2.2.2"
    // Amplify core dependency
    //implementation "com.amplifyframework:core:$amplify_version"
    implementation "com.amplifyframework:aws-storage-s3:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

    def room_version = "2.5.0"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

    def work_version = "2.8.0"

    // (Java only)
    implementation "androidx.work:work-runtime:$work_version"
    // Kotlin + coroutines
    implementation "androidx.work:work-runtime-ktx:$work_version"
    implementation "androidx.concurrent:concurrent-futures:1.1.0"
}
`

**Comment by waertf** [comment]
the application is the AIDL service

**Comment by waertf** [comment]
found that the root cause is set android:process in manifest file in application->service block
after removing android:process, the issue disappeared

**Comment by tylerjroach** [comment]
Please open a new issue with updates to the versions you are now using for Amplify and work manager. Please also provide your merged manifest to understand what could be disabling work manager.

FYI, this message: "You have explicitly disabled WorkManagerInitializer in your manifest" does not come from our library. This is coming directly from WorkManager, stating it was explicitly disabled.
