### ISSUE TITLE
SignedInException happens even though isSignedIn function returns false 

### ISSUE THREAD

**Issue by androidcodehunter** [aws-amplify/amplify-android#2319]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication, Storage

### Gradle script dependencies

```
com.amplifyframework:core-kotlin:2.2.2
com.amplifyframework:aws-auth-cognito:2.2.2
com.amplifyframework:aws-storage-s3:2.2.2
```

### Environment information

<details>

```
# Put output below this line

Gradle 7.5
Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_281 (Oracle Corporation 25.281-b09)
OS:           Windows 10 10.0 amd64

```

</details>

### Describe the bug

I am trying to determine if the user is signed in.  I am using this snippet of code.  It is saying the user is not signed in.  I am then login in since the code indicates the user is not signed in.  It is throwing an Exception saying I am already signed in.  It seems the snippet of code and login aren't checking the same condition as they are giving me completely different status on the user's current state.

    private suspend fun isUserSignedIn(): Boolean {
        return try {
            (Amplify.Auth.fetchAuthSession() as AWSCognitoAuthSession).isSignedIn
        } catch (exception: AuthException) {
            false
        }
    }

This is what I am getting as an exception,

```
com.amplifyframework.auth.cognito.exceptions.invalidstate.SignedInException: There is already a user signed in.
    at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$signIn$1.invoke(RealAWSCognitoAuthPlugin.kt:479)
    at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$signIn$1.invoke(RealAWSCognitoAuthPlugin.kt:466)
    at com.amplifyframework.statemachine.StateMachine$getCurrentState$1.invokeSuspend(StateMachine.kt:121)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
```

Is it a bug or what will be the correct approach to see if user actually logged in or not. I haven't find any documentation in the amplify library. Can you suggest what would be the right approach to check user signedIn state.  

**`Note:`** Previously I used older amplify library[Version "1.35.4"] with `getCurrentUser != null` gave us signedIn state correctly but with newer library I started to see widespread SignedInException. 

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Hi @androidcodehunter what is the output of the fetchAuthSession ? 
In V2 you can also use getCurrentUser and it will give you either a signedoutexception or the current user if you are actually signed in. Give that a try and paste that output here too and we can help troubleshoot.

**Comment by androidcodehunter** [comment]
> Hi @androidcodehunter what is the output of the fetchAuthSession ? In V2 you can also use getCurrentUser and it will give you either a signedoutexception or the current user if you are actually signed in. Give that a try and paste that output here too and we can help troubleshoot.
Here is the AuthSession and the user I am getting, 
`AuthSession = AWSCognitoAuthSession(isSignedIn=false, identityIdResult=AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=NotAuthorizedException(message=Refresh Token has expired), recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, awsCredentialsResult=AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=NotAuthorizedException(message=Refresh Token has expired), recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userSubResult=AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=NotAuthorizedException(message=Refresh Token has expired), recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userPoolTokensResult=AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=NotAuthorizedException(message=Refresh Token has expired), recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}) `

The user -> `CurrentUser = null` 

But if I call login function with username and password I am getting the below error, 
```
com.amplifyframework.auth.cognito.exceptions.invalidstate.SignedInException: There is already a user signed in.
    at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$signIn$1.invoke(RealAWSCognitoAuthPlugin.kt:479)
    at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$signIn$1.invoke(RealAWSCognitoAuthPlugin.kt:466)
    at com.amplifyframework.statemachine.StateMachine$getCurrentState$1.invokeSuspend(StateMachine.kt:121)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    at java.lang.Thread.run(Thread.java:1012)
```

**Comment by gpanshu** [comment]
You are signed in but your session has expired. You will either have to force refresh the credentials or sign out first and sign in again.

**Comment by androidcodehunter** [comment]
> You are signed in but your session has expired. You will either have to force refresh the credentials or sign out first and sign in again.

Thanks for the reply. Is there any way to know if I am signed in with a simple method without checking all of the details.

**Comment by brian-pinwheel** [comment]
@gpanshu what do you mean by "force refresh the credentials"?  

Definitely seems like an odd design that login only works for only one session token period and requires logging out and back in instead of using the refresh token...

**Comment by tylerjroach** [comment]
@brian-pinwheel This is not intended. In this case the refresh token is also expired `message=Refresh Token has expired)`.  @androidcodehunter Possibly check how long your refresh tokens are set to last if they seem to be expiring early.

**Comment by androidcodehunter** [comment]
@tylerjroach Looks like my Refresh token expiration is 30 days.

**Comment by brian-pinwheel** [comment]
> @brian-pinwheel This is not intended. In this case the refresh token is also expired `message=Refresh Token has expired)`. @androidcodehunter Possibly check how long your refresh tokens are set to last if they seem to be expiring early.

@tylerjroach Thanks for the explanation, that makes complete sense!

**Comment by tylerjroach** [comment]
If no calls were made that updated the refresh token in that 30 day period, you will need to re-authenticate the user on seeing the above expiration error.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please create a new issue or reopen this issue if you have additional questions.

**Comment by Xenoamor** [comment]
> If no calls were made that updated the refresh token in that 30 day period, you will need to re-authenticate the user on seeing the above expiration error.

How are you supposed to re-authenticate the user if you keep getting "SignedInException: There is already a user signed in." when you try to sign in?

**Comment by manuelfrancogravity** [comment]
Same problem here.

I can't sign in because token has expired.
