### ISSUE TITLE
Tokens are invalid, please sign-in again. after successful login when I killed application and restart. no cache session error.

### ISSUE THREAD

**Issue by DavinderUpgame** [aws-amplify/amplify-android#2334]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line

implementation 'com.amplifyframework:aws-auth-cognito:2.3.0'

```

</details>

### Environment information

<details>

```
# Put output below this line
(gradle:7.3.1)
```

</details>

### Please include any relevant guides or documentation you're referencing

it is working fine in 1.37.5 but when I update to 2.2.3 its not working

### Describe the bug

CognitoUserSession is not valid because idToken is null.
signalTokensNotAvailable
signalTokensNotAvailable
Tokens are invalid, please sign-in again.
 java.lang.Exception: No cached session.
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient$12$1.signalTokensNotAvailable(AWSMobileClient.java:2068)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient$12$1.getAuthenticationDetails(AWSMobileClient.java:2048)
                                                                                                    	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1035)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient$12.run(AWSMobileClient.java:2029)
                                                                                                    	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1995)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1119)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient.waitForSignIn(AWSMobileClient.java:977)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:395)
                                                                                                    	at com.amazonaws.services.s3.AmazonS3Client.generatePresignedUrl(AmazonS3Client.java:3437)
                                                                                                    	at technologies.waltado.upgame_pro.models.AwsModelKotlin.fetchContentAndSgIndexData$lambda$69(AwsModelKotlin.kt:4717)
                                                                                                    	at technologies.waltado.upgame_pro.models.AwsModelKotlin.$r8$lambda$PEviijKeclS0YCRzE0gYQuCZUys(Unknown Source:0)
                                                                                                    	at technologies.waltado.upgame_pro.models.AwsModelKotlin$$ExternalSyntheticLambda14.run(Unknown Source:14)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

### Reproduction steps (if applicable)

install application
initilize AWS 
configure amplify
login successful
kill app 
again restart
No cached session.
Tokens are invalid, please sign-in again.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by DavinderUpgame** [comment]
CognitoUserSession is not valid because idToken is null.
signalTokensNotAvailable
Tokens are invalid, please sign-in again.

java.lang.Exception: No cached session.
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient$12$1.signalTokensNotAvailable(AWSMobileClient.java:2068)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient$12$1.getAuthenticationDetails(AWSMobileClient.java:2048)
                                                                                                    	at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1035)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient$12.run(AWSMobileClient.java:2029)
                                                                                                    	at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1995)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1119)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:899)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:896)
                                                                                                    	at com.amazonaws.mobile.client.internal.ReturningRunnable.await(ReturningRunnable.java:31)
                                                                                                    	at com.amazonaws.mobile.client.AWSMobileClient.currentUserState(AWSMobileClient.java:878)
                                                                                                    	at technologies.waltado.upgame_pro.models.AwsModelKotlin.getUserDataOrStateFromCognito$lambda$0(AwsModelKotlin.kt:123)
                                                                                                    	at technologies.waltado.upgame_pro.models.AwsModelKotlin.$r8$lambda$9y7RVFA8S2u_EtWP3mcxB41Fpa4(Unknown Source:0)
                                                                                                    	at technologies.waltado.upgame_pro.models.AwsModelKotlin$$ExternalSyntheticLambda11.run(Unknown Source:4)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by gpanshu** [comment]
Hi @DavinderUpgame are you consistently able to reproduce this error? Is this on a physical device or an emulator?

Whats the type of sign in method you are using? Please paste your sign in snippet as well. 

If you are indeed on an emulator please make sure your date and time are correct.

**Comment by gpanshu** [comment]
A few questions for you: 

1. Are you consistently able to reproduce this error?
2. Are you on an emulator or real device
3. Please paste your sign in snippet as well
4. What happens if you try to sign in after you get this error?

**Comment by DavinderUpgame** [comment]
it is working fine if I use 1.37.5 version but after updating 2.2.3 I am getting error every time when I killed app and restart.
I think it is related to auth plugin because without adding auth plugin to amplify it works but apis which are dependent on this plugin are not responding.
I am dependent on both AwsMobileClient and Amplify

**Comment by tylerjroach** [comment]
@DavinderUpgame AWSMobileClient and Amplify v2 are incompatible with each other. Amplify for Android v2 is considered an upgrade of Amplify for Android v1 and the AWS Android SDK. v2 migrates data from v1/sdk and they use a different local storage mechanism to securely store credentials.

**Comment by DavinderUpgame** [comment]
@tylerjroach for signup and signing we use AwsMobileClient and to update attributes like email or sending verification code we use Amplify. if AWSMobileClient and Amplify v2 are incompatible with each other then how we can maintain session or is there any other approach?

**Comment by tylerjroach** [comment]
All use cases you have described should be compatible with Amplify v2. Please see the v2 documentation for each of your use-cases.

https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/

**Comment by DavinderUpgame** [comment]
@tylerjroach we already implemented this approach. but no luck with maintaining user session

**Comment by dengdan154** [comment]
Hey @DavinderUpgame, if you are still seeing this issue while only using Amplify v2, please create a separate ticket and provide us with the error log so we can look into it further. Be sure that you are not using both Amplify v2 and AWSMobileClient.

**Comment by ranshine** [comment]
I am facing same issue with amplify android library with 1.38.3v, killing the app and after some time if i open the app Amplify.Auth.fetchAuthSession is not retrieving tokens.

**Comment by dengdan154** [comment]
@ranshine please open a separate ticket and we can further look into it.
