### ISSUE TITLE
InvalidStateException when calling `fetchAuthSession` right after `configure`, like in the tutorial

### ISSUE THREAD

**Issue by shlusiak** [aws-amplify/amplify-android#2341]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
// Put output below this line
    implementation 'com.amplifyframework:aws-auth-cognito:2.3.0'

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.18 (Homebrew 11.0.18+0)
OS:           Mac OS X 13.1 aarch64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/#initialize-amplify-auth

### Describe the bug

There seems to be a race condition when calling `configure` in 2.3.0. I am following the tutorial, my code looks like this:

```kotlin
Amplify.addPlugin(AWSCognitoAuthPlugin())
        Amplify.configure(app)

// uncomment this line to "fix" the crash:
//        Thread.sleep(1)

        Amplify.Auth.fetchAuthSession(
            { Log.i("AmplifyQuickstart", "Auth session = $it") },
            { error -> Log.e("AmplifyQuickstart", "Failed to fetch auth session", error) }
        )
```

Without the sleep, I am getting the exception `InvalidStateException{message=Auth state is an invalid state, cannot process the request., cause=null, recoverySuggestion=Operation performed is not a valid operation for the current auth state.}`

With the sleep in it, I am getting `Auth session = AWSCognitoAuthSession(isSignedIn=false, [...]`, as expected.

Popping the bonnet of the `Amplify.configure` call reveals that `beginInitialization` launches a Thread to initialize the category (auth), so the call returns before configuration has completed, and if you call `fetchAuthSession` too quickly, auth is not in a good state.

Is there a callback I am meant to use to find out whether configuration has completed or auth is ready? I was expecting that after the call to `configure`, the categories would be configured. 

### Reproduction steps (if applicable)

- Follow the tutorial at https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/#initialize-amplify-auth
- Call `fetchAuthSession` right after calling `configure(app)`

### Code Snippet

```kotlin
// Put your code below this line.

        Amplify.addPlugin(AWSCognitoAuthPlugin())
        Amplify.configure(app)

//        Thread.sleep(1)

        // crash without the sleep, works better with the sleep
        Amplify.Auth.fetchAuthSession(
            { Log.i("AmplifyQuickstart", "Auth session = $it") },
            { error -> Log.e("AmplifyQuickstart", "Failed to fetch auth session", error) }
        )

```

### Log output

<details>

```
// Put your logs below this line

Failed to fetch auth session
                                                                          InvalidStateException{message=Auth state is an invalid state, cannot process the request., cause=null, recoverySuggestion=Operation performed is not a valid operation for the current auth state.}
                                                                          	at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$fetchAuthSession$1.invoke(RealAWSCognitoAuthPlugin.kt:982)
                                                                          	at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$fetchAuthSession$1.invoke(RealAWSCognitoAuthPlugin.kt:931)
                                                                          	at com.amplifyframework.statemachine.StateMachine$getCurrentState$1.invokeSuspend(StateMachine.kt:121)
                                                                          	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                          	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                          	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                                                                          	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                          	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                          	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                          	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                          	at java.lang.Thread.run(Thread.java:1012)


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
HI @shlusiak are you calling amplify.configure from your activity of application file ? 

The reason why I am asking is that the documentation asks you to put the configure code in the application and the fetchAuthSession in Activity. Here is the [link](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android/#4-initialize-amplify-in-the-application) where it mentions that.

**Comment by shlusiak** [comment]
The `Amplify.configure` is of course run in my business layer, which is dagger injected in various places. Effectively the code runs as part of the `Application.onCreate()` where it is instantiated by dagger. 

I am running the `fetchAuthSession` in the same place and right afterwards. I have no doubt that running this in the Activity instead puts enough other work between the two calls for the configure thread to do its work, similar to my `sleep(1)`, thus alleviating the race condition. 

The code in question is https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/core/Amplify.java#L165, which does not seem to give me any guarantees as to when initialization of the category is complete.

**Comment by gpanshu** [comment]
Amplify.configure does a lot of things and it needs that time to configure within which no calls to amplify will succeed. Can you advise why you are running a fetch auth session inside the application class?

**Comment by shlusiak** [comment]
@gpanshu that is ok, but is there any way of knowing when configure has finished it's job? I can't see a callback or a suspend function that will allow me to know precicely when I am allowed to make API calls.

The class where I am calling this does not matter, I am calling this during initialisation of my app, and part of the initialisation process is to figure out whether the user is logged in or not. Moving the code from `Application` into `Activity` seems like a poor man's workaround to me, just adding additional work to allow the worker thread to hopefully finish initialising the plugin. This is still a race, am I not mistaken, and this would still not be correct.

What guarantee would there be that initialisation is complete by the time the Activity is launched?

**Comment by gpanshu** [comment]
Amplify.configure is a blocking call.

I am going to check into what is causing the state to be invalid to give you a little more information here.

**Comment by shlusiak** [comment]
The `configure(configuration, context)` call calls `beginInitialization(category, context)`, which launches a background thread to run `category.initialize(context)`. So the `configure()` call returns before the category has been initialized and there seems to be no way to tell that the category initialization has finished. 

https://github.com/aws-amplify/amplify-android/blob/main/core/src/main/java/com/amplifyframework/core/Amplify.java#L160

**Comment by tylerjroach** [comment]
@shlusiak Thank you for the report. We are investigating a fix.

**Comment by tylerjroach** [comment]
@shlusiak We have merged in a fix for this issue and it will go live in the next Amplify release. Thank you for your report!

**Comment by shlusiak** [comment]
Thanks so much for fixing this so quickly! So while the `configure` call is still async and non-blocking, any auth call will block/suspend until auth configure has settled, right?

**Comment by gpanshu** [comment]
Yes that is correct. Closing this issue as this has fixed the problem you originally opened the issue about. If you are still facing a problem please feel to create a new issue.
