### ISSUE TITLE
User signed out automatically after closing the app, and then opening it and calling Auth.fetchSession()

### ISSUE THREAD

**Issue by MrBenjoo** [aws-amplify/amplify-android#2372]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
com.amplifyframework:core-kotlin:2.5.0
com.amplifyframework:aws-auth-cognito:2.5.0
```
</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_275 (AdoptOpenJDK 25.275-b01)
OS:           Windows 10 10.0 amd64


```

</details>

### Describe the bug

When you successfully sign in with `Amplify.Auth.signIn(emailAddress, password)` and then after 2-5 seconds you close app and then re-open it again and then call `Amplify.Auth.fetchAuthSession()`, the Amplify.Hub will emit a SIGNED_OUT indicating that the user has been signed out and this is is the response i get followed by that: 

> AWSCognitoAuthSession(isSignedIn=false, identityIdResult=AuthSessionResult{value=eu-west-1..., error=null, type=SUCCESS}, awsCredentialsResult=AuthSessionResult{value=com.amplifyframework.auth.AWSTemporaryCredentials@dede75, error=null, type=SUCCESS}, userSubResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userPoolTokensResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE})

### Code Snippet

```java
 suspend fun getCognitoToken(): Result<String> = withContext(Dispatchers.IO) {
        return@withContext try {
            val session = Amplify.Auth.fetchAuthSession() as AWSCognitoAuthSession
            when (session.userPoolTokensResult.type) {
                AuthSessionResult.Type.SUCCESS -> {
                    session.userPoolTokensResult.value?.accessToken?.let {
                        Result.success(it)
                    } ?: Result.failure(AuthException("null is token", ""))
                }
                AuthSessionResult.Type.FAILURE -> Result.failure(
                    session.userPoolTokensResult.error ?: AuthException("Failure -> Unknown error", "")
                )
                else -> Result.failure(AuthException("Unknown error", ""))
            }
        } catch (error: Exception) {
            Result.failure(AuthException(error.message.toString(), ""))
        }
    }
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

```
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "$poolIdCredentialsProvider",
              "Region": "$region"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "$poolIdCognito",
            "AppClientId": "$clientId",
            "AppClientSecret": "$clientSecret",
            "Region": "$region"
          }
        },
        "Auth": {
          "Default": {
            "OAuth": {
              "WebDomain": "$webDomain",
              "AppClientId": "$clientId",
              "AppClientSecret": "$clientSecret",
              "SignInRedirectURI": "$signInRedirectURI",
              "SignOutRedirectURI": "$signOutRedirectURI",
              "Scopes": [
                "email"
              ]
            },
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by gpanshu** [comment]
Can you enable the Android debugger `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE)` as the top level plugin and paste the response when you close the app from a fetchAuthSession call?

**Comment by div5yesh** [comment]
@MrBenjoo, Also can you verify if see the user as signedIn in fetchAuthSession before closing the app?

**Comment by ranshine** [comment]
I am facing same issue with amplify android library with 1.38.3v, killing the app and after some time if i open the app Amplify.Auth.fetchAuthSession is not retrieving tokens.

**Comment by MrBenjoo** [comment]
> Can you enable the Android debugger `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE)` as the top level plugin and paste the response when you close the app from a fetchAuthSession call?

I just realized that I can only reproduce this bug when i stop the application and then run from Android Studio. 
Also, I have removed the identityId from the IdentityPool along with the credentials, here is the log:

```
13:58:32.783  V  Auth State Change: Configured(authNState=SigningOut(signOutState=NotStarted(id=)), authZState=SigningOut(amplifyCredential=IdentityPool(identityId=eu-west..., credentials=AWSCredentials(accessKeyId = ***, secretAccessKey = ***, sessionToken = ***, expiration = 1681217764000))))
13:58:32.783  V  InitSignOut Starting execution
13:58:32.784  V  InitSignOut Sending event SignOutLocally
13:58:32.785  V  Auth State Change: Configured(authNState=SigningOut(signOutState=SigningOutLocally(signedInData=null)), authZState=StoringCredentials(amplifyCredential=com.amplifyframework.statemachine.codegen.data.AmplifyCredential$Empty@90c4d6f))
13:58:32.785  V  LocalSignOut Starting execution
13:58:32.785  V  LocalSignOut Sending event SignedOutSuccess
13:58:32.785  V  PersistCredentials Starting execution
13:58:32.786  V  Auth State Change: Configured(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=StoringCredentials(amplifyCredential=com.amplifyframework.statemachine.codegen.data.AmplifyCredential$Empty@90c4d6f))
13:58:32.787  V  Credential Store State Change: Idle(id=)
13:58:32.788  V  Credential Store State Change: StoringCredentials(id=)
13:58:32.789  V  StoreCredentials Starting execution
13:58:32.792  V  StoreCredentials Sending event CompletedOperation
13:58:32.794  V  Credential Store State Change: Success(storedCredentials=com.amplifyframework.statemachine.codegen.data.AmplifyCredential$Empty@90c4d6f)
13:58:32.794  V  MoveToIdleState Starting execution
13:58:32.794  V  MoveToIdleState Sending event MoveToIdleState
13:58:32.794  V  Credential Store State Change: Idle(id=)
13:58:32.795  V  PersistCredentials Sending event ReceivedCachedCredentials
13:58:32.795  V  Auth State Change: Configured(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=Configured(id=))
13:58:32.799  D  Amplify Auth channel event: SIGNED_OUT
13:58:32.800  V  Auth State Change: Configured(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=FetchingUnAuthSession(fetchAuthSessionState=NotStarted(id=)))
13:58:32.800  V  InitFetchUnAuthSession Starting execution
13:58:32.801  D  Amplify Auth channel event: SIGNED_OUT
13:58:32.802  V  InitFetchUnAuthSession Sending event FetchIdentity
13:58:32.805  V  Auth State Change: Configured(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=FetchingUnAuthSession(fetchAuthSessionState=FetchingIdentity(logins=UnAuthLogins(logins={}))))
13:58:32.805  V  FetchIdentity Starting execution
13:58:33.259  V  FetchIdentity Sending event FetchAwsCredentials
13:58:33.262  V  Auth State Change: Configured(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=FetchingUnAuthSession(fetchAuthSessionState=FetchingAWSCredentials(identityId=eu-west..., logins=UnAuthLogins(logins={}))))
13:58:33.262  V  FetchAWSCredentials Starting execution
13:58:33.360  V  FetchAWSCredentials Sending event Fetched
13:58:33.361  V  Auth State Change: Configured(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=FetchingUnAuthSession(fetchAuthSessionState=Fetched(id=)))
13:58:33.361  V  NotifySessionEstablished Starting execution
13:58:33.362  V  NotifySessionEstablished Sending event Fetched
13:58:33.362  V  Auth State Change: Configured(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=StoringCredentials(amplifyCredential=IdentityPool(identityId=eu-west..., credentials=AWSCredentials(accessKeyId = ***, secretAccessKey = ***, sessionToken = ***, expiration = 1681217911))))
13:58:33.363  V  PersistCredentials Starting execution
13:58:33.363  V  Credential Store State Change: Idle(id=)
13:58:33.363  V  Credential Store State Change: StoringCredentials(id=)
13:58:33.363  V  StoreCredentials Starting execution
13:58:33.366  V  StoreCredentials Sending event CompletedOperation
13:58:33.367  V  Credential Store State Change: Success(storedCredentials=IdentityPool(identityId=eu-west..., credentials=AWSCredentials(accessKeyId = ***, secretAccessKey = ***, sessionToken = ***, expiration = 1681217911)))
13:58:33.367  V  MoveToIdleState Starting execution
13:58:33.367  V  MoveToIdleState Sending event MoveToIdleState
13:58:33.367  V  Credential Store State Change: Idle(id=)
13:58:33.367  V  PersistCredentials Sending event ReceivedCachedCredentials
13:58:33.367  V  Auth State Change: Configured(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=SessionEstablished(amplifyCredential=IdentityPool(identityId=eu-west..., credentials=AWSCredentials(accessKeyId = ***, secretAccessKey = ***, sessionToken = ***, expiration = 1681217911))))
13:58:33.368  V  AWSCognitoAuthSession(isSignedIn=false, identityIdResult=AuthSessionResult{value=eu-west..., error=null, type=SUCCESS}, awsCredentialsResult=AuthSessionResult{value=com.amplifyframework.auth.AWSTemporaryCredentials@a23065e, error=null, type=SUCCESS}, userSubResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userPoolTokensResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE})
13:58:33.368  V  Sign out success
```

**Comment by MrBenjoo** [comment]
> @MrBenjoo, Also can you verify whether you see the user as signedIn in fetchAuthSession before closing the app?

I tried calling fetchAuthSession when closing the app, this is what i get: 

```
Could not retrieve Identity ID
                 ConfigurationException{message=Could not retrieve Identity ID, cause=null, recoverySuggestion=Cognito Identity not configured. Please check amplifyconfiguration.json file.}
                 	at com.amplifyframework.auth.cognito.AWSCognitoAuthSessionKt.getCognitoSession(AWSCognitoAuthSession.kt:98)
                 	at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$_fetchAuthSession$1.invoke(RealAWSCognitoAuthPlugin.kt:1015)
                 	at com.amplifyframework.auth.cognito.RealAWSCognitoAuthPlugin$_fetchAuthSession$1.invoke(RealAWSCognitoAuthPlugin.kt:993)
                 	at com.amplifyframework.statemachine.StateMachine.notifySubscribers(StateMachine.kt:176)
                 	at com.amplifyframework.statemachine.StateMachine.process(StateMachine.kt:191)
                 	at com.amplifyframework.statemachine.StateMachine.access$process(StateMachine.kt:49)
                 	at com.amplifyframework.statemachine.StateMachine$send$1.invokeSuspend(StateMachine.kt:160)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                 	at java.lang.Thread.run(Thread.java:920)
```

**Comment by div5yesh** [comment]
Code snippet from issue description mentions that you are using username/password to sign in. These logs https://github.com/aws-amplify/amplify-android/issues/2372#issuecomment-1503213731 suggest that the user was signed out before fetchAuthSession while logs here https://github.com/aws-amplify/amplify-android/issues/2372#issuecomment-1503214993 show that the use was logged in with hosted UI. Im unable to understand what the actual issue is. I would love to reproduce this on my setup.

Can you provide us more info on how your user pool and identity pool is configured? Also can you provide code snippets of Amplify APIs that you are calling in your app? Please do provide logs where ever possible.

**Comment by MrBenjoo** [comment]
@div5yesh Sorry for being unclear, let me try to clarify.

1. Sign in with username/password
2. Force close the app
3. Navigate to screen where the getCognitoToken() is called

I am using a samsung s10 and i am able to reproduce this issue consistently. However, my colleague, using a Xiaomi device, could not reproduce it all the time - it occurred after some time.

#### Logs after sign in:
```
2023-05-05 16:59:15.556  V  AWSCognitoAuthSession(isSignedIn=false, identityIdResult=AuthSessionResult{value=eu-west-1:f0b..., error=null, type=SUCCESS}, awsCredentialsResult=AuthSessionResult{value=com.amplifyframework.auth.AWSTemporaryCredentials@c4c3a, error=null, type=SUCCESS}, userSubResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userPoolTokensResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE})
2023-05-05 16:59:15.562  V  signing in with email: benjamin@gmail.com
2023-05-05 16:59:15.577  V  Auth State Change: Configured(authNState=SigningIn(signInState=NotStarted(id=)), authZState=SigningIn(id=))
2023-05-05 16:59:15.578  V  InitiateSignInAction Starting execution
2023-05-05 16:59:15.579  V  InitiateSignInAction Sending event InitiateSignInWithSRP
2023-05-05 16:59:15.580  V  Auth State Change: Configured(authNState=SigningIn(signInState=SigningInWithSRP(srpSignInState=NotStarted(id=))), authZState=SigningIn(id=))
2023-05-05 16:59:15.581  V  StartSRPAuth Starting execution
2023-05-05 16:59:15.581  V  StartSRPAuth Sending event InitiateSRP
2023-05-05 16:59:15.586  V  Auth State Change: Configured(authNState=SigningIn(signInState=SigningInWithSRP(srpSignInState=InitiatingSRPA(id=))), authZState=SigningIn(id=))
2023-05-05 16:59:15.586  V  InitSRPAuth Starting execution
2023-05-05 16:59:15.623  V  Credential Store State Change: LoadingStoredCredentials(id=)
2023-05-05 16:59:15.623  V  LoadCredentialStore Starting execution
2023-05-05 16:59:15.623  V  Credential Store State Change: Idle(id=)
2023-05-05 16:59:15.637  V  LoadCredentialStore Sending event CompletedOperation
2023-05-05 16:59:15.638  V  Credential Store State Change: Success(storedCredentials=ASFDevice(id=0ad447f1-0e46-4d93-9cf1-2b28f4092082:1683290666820))
2023-05-05 16:59:15.639  V  MoveToIdleState Starting execution
2023-05-05 16:59:15.639  V  MoveToIdleState Sending event MoveToIdleState
2023-05-05 16:59:15.641  V  Credential Store State Change: Idle(id=)
2023-05-05 16:59:15.651  V  Credential Store State Change: LoadingStoredCredentials(id=)
2023-05-05 16:59:15.652  V  Credential Store State Change: Idle(id=)
2023-05-05 16:59:15.653  V  LoadCredentialStore Starting execution
2023-05-05 16:59:15.656  V  LoadCredentialStore Sending event CompletedOperation
2023-05-05 16:59:15.657  V  Credential Store State Change: Success(storedCredentials=DeviceData(deviceMetadata=com.amplifyframework.statemachine.codegen.data.DeviceMetadata$Empty@92c2892))
2023-05-05 16:59:15.657  V  MoveToIdleState Starting execution
2023-05-05 16:59:15.657  V  MoveToIdleState Sending event MoveToIdleState
2023-05-05 16:59:15.658  V  Credential Store State Change: Idle(id=)
2023-05-05 16:59:16.188  V  InitSRPAuth Sending event RespondPasswordVerifier
2023-05-05 16:59:16.193  V  Auth State Change: Configured(authNState=SigningIn(signInState=SigningInWithSRP(srpSignInState=RespondingPasswordVerifier(id=))), authZState=SigningIn(id=))
2023-05-05 16:59:16.194  V  VerifyPasswordSRP Starting execution
2023-05-05 16:59:16.207  V  Credential Store State Change: Idle(id=)
2023-05-05 16:59:16.207  V  Credential Store State Change: LoadingStoredCredentials(id=)
2023-05-05 16:59:16.207  V  LoadCredentialStore Starting execution
2023-05-05 16:59:16.209  V  LoadCredentialStore Sending event CompletedOperation
2023-05-05 16:59:16.210  V  Credential Store State Change: Success(storedCredentials=ASFDevice(id=0ad447f1-0e46-4d93-9cf1-2b28f4092082:1683290666820))
2023-05-05 16:59:16.211  V  MoveToIdleState Starting execution
2023-05-05 16:59:16.211  V  MoveToIdleState Sending event MoveToIdleState
2023-05-05 16:59:16.211  V  Credential Store State Change: Idle(id=)
2023-05-05 16:59:20.143  V  VerifyPasswordSRP Sending event SignInCompleted
2023-05-05 16:59:20.147  V  Auth State Change: Configured(authNState=SignedIn(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), deviceMetadata=com.amplifyframework.statemachine.codegen.data.DeviceMetadata$Empty@92c2892), authZState=FetchingAuthSession(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), fetchAuthSessionState=NotStarted(id=)))
2023-05-05 16:59:20.148  V  InitFetchAuthSession Starting execution
2023-05-05 16:59:20.149  V  InitFetchAuthSession Sending event FetchIdentity
2023-05-05 16:59:20.154  V  Auth State Change: Configured(authNState=SignedIn(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), deviceMetadata=com.amplifyframework.statemachine.codegen.data.DeviceMetadata$Empty@92c2892), authZState=FetchingAuthSession(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), fetchAuthSessionState=FetchingIdentity(logins=CognitoUserPoolLogins(region=eu-west-1, poolId=eu-west-1_tXs..., idToken=eyJ...))))
2023-05-05 16:59:20.154  V  FetchIdentity Starting execution
2023-05-05 16:59:20.567  V  FetchIdentity Sending event FetchAwsCredentials
2023-05-05 16:59:20.573  V  Auth State Change: Configured(authNState=SignedIn(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), deviceMetadata=com.amplifyframework.statemachine.codegen.data.DeviceMetadata$Empty@92c2892), authZState=FetchingAuthSession(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), fetchAuthSessionState=FetchingAWSCredentials(identityId=eu-west-1:bf0..., logins=CognitoUserPoolLogins(region=eu-west-1, poolId=eu-west-1_tXs..., idToken=eyJ...))))
2023-05-05 16:59:20.575  V  FetchAWSCredentials Starting execution
2023-05-05 16:59:20.722  V  FetchAWSCredentials Sending event Fetched
2023-05-05 16:59:20.725  V  Auth State Change: Configured(authNState=SignedIn(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), deviceMetadata=com.amplifyframework.statemachine.codegen.data.DeviceMetadata$Empty@92c2892), authZState=FetchingAuthSession(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), fetchAuthSessionState=Fetched(id=)))
2023-05-05 16:59:20.726  V  NotifySessionEstablished Starting execution
2023-05-05 16:59:20.727  V  NotifySessionEstablished Sending event Fetched
2023-05-05 16:59:20.731  V  Auth State Change: Configured(authNState=SignedIn(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), deviceMetadata=com.amplifyframework.statemachine.codegen.data.DeviceMetadata$Empty@92c2892), authZState=StoringCredentials(amplifyCredential=UserAndIdentityPool(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), identityId=eu-west-1:bf0..., credentials=AWSCredentials(accessKeyId = ASIA5***, secretAccessKey = H/FjB***, sessionToken = IQoJb***, expiration = 1683302360))))
2023-05-05 16:59:20.732  V  PersistCredentials Starting execution
2023-05-05 16:59:20.734  V  Credential Store State Change: Idle(id=)
2023-05-05 16:59:20.735  V  Credential Store State Change: StoringCredentials(id=)
2023-05-05 16:59:20.736  V  StoreCredentials Starting execution
2023-05-05 16:59:20.748  V  StoreCredentials Sending event CompletedOperation
2023-05-05 16:59:20.750  V  Credential Store State Change: Success(storedCredentials=UserAndIdentityPool(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), identityId=eu-west-1:bf0..., credentials=AWSCredentials(accessKeyId = ASIA5***, secretAccessKey = H/FjB***, sessionToken = IQoJb***, expiration = 1683302360)))
2023-05-05 16:59:20.751  V  MoveToIdleState Starting execution
2023-05-05 16:59:20.751  V  MoveToIdleState Sending event MoveToIdleState
2023-05-05 16:59:20.752  V  Credential Store State Change: Idle(id=)
2023-05-05 16:59:20.754  V  PersistCredentials Sending event ReceivedCachedCredentials
2023-05-05 16:59:20.755  V  Auth State Change: Configured(authNState=SignedIn(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), deviceMetadata=com.amplifyframework.statemachine.codegen.data.DeviceMetadata$Empty@92c2892), authZState=SessionEstablished(amplifyCredential=UserAndIdentityPool(signedInData=SignedInData(userId=026..., username=026..., signedInDate=Fri May 05 16:59:20 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), identityId=eu-west-1:bf0..., credentials=AWSCredentials(accessKeyId = ASIA5***, secretAccessKey = H/FjB***, sessionToken = IQoJb***, expiration = 1683302360))))
2023-05-05 16:59:20.759  V  AuthSignInResult{isSignedIn=true, nextStep=AuthNextSignInStep{signInStep=DONE, additionalInfo={}, codeDeliveryDetails=null}}
2023-05-05 16:59:20.814  D  Amplify Auth channel event: SIGNED_IN
2023-05-05 16:59:20.819  D  Amplify Auth channel event: SIGNED_IN
2023-05-05 16:59:20.828  D  Amplify.Auth.fetchAuthSession() = AWSCognitoAuthSession(isSignedIn=true, identityIdResult=AuthSessionResult{value=eu-west-1:bf0..., error=null, type=SUCCESS}, awsCredentialsResult=AuthSessionResult{value=com.amplifyframework.auth.AWSTemporaryCredentials@354deaa, error=null, type=SUCCESS}, userSubResult=AuthSessionResult{value=026..., error=null, type=SUCCESS}, userPoolTokensResult=AuthSessionResult{value=AWSCognitoUserPoolTokens(accessToken=eyJ..., idToken=eyJ..., refreshToken=eyJ...
```

#### Logs after I close the app (onPause):
```
2023-05-05 17:04:39.645  D  Amplify.Auth.fetchAuthSession() = AWSCognitoAuthSession(isSignedIn=true, identityIdResult=AuthSessionResult{value=eu-west-1:bf0..., error=null, type=SUCCESS}, awsCredentialsResult=AuthSessionResult{value=com.amplifyframework.auth.AWSTemporaryCredentials@d76fe9c, error=null, type=SUCCESS}, userSubResult=AuthSessionResult{value=026dc95f-c8f7-4f6b-b21b-83123dea3ae8, error=null, type=SUCCESS}, userPoolTokensResult=AuthSessionResult{value=AWSCognitoUserPoolTokens(accessToken=eyJ..., idToken=eyJ..., refreshToken=eyJ...
```

#### Logs when I re-open the app after the force close:
```
2023-05-05 17:05:32.131 V  Auth State Change: NotConfigured(id=)
2023-05-05 17:05:32.132 V  Auth State Change: ConfiguringAuth(id=)
2023-05-05 17:05:32.132 V  InitAuthConfig Starting execution
2023-05-05 17:05:32.134 V  Credential Store State Change: MigratingLegacyStore(id=)
2023-05-05 17:05:32.134 V  Credential Store State Change: NotConfigured(id=)
2023-05-05 17:05:32.135 V  MigrateLegacyCredentials Starting execution
2023-05-05 17:05:32.404 V  MigrateLegacyCredentials Sending event LoadCredentialStore
2023-05-05 17:05:32.406 V  Credential Store State Change: LoadingStoredCredentials(id=)
2023-05-05 17:05:32.406 V  LoadCredentialStore Starting execution
2023-05-05 17:05:32.415 V  LoadCredentialStore Sending event CompletedOperation
2023-05-05 17:05:32.416 V  Credential Store State Change: Success(storedCredentials=IdentityPool(identityId=eu-west-1:c00..., credentials=AWSCredentials(accessKeyId = ASIA5***, secretAccessKey = WQDdv***, sessionToken = IQoJb***, expiration = 1683302323000)))
2023-05-05 17:05:32.416 V  MoveToIdleState Starting execution
2023-05-05 17:05:32.416 V  MoveToIdleState Sending event MoveToIdleState
2023-05-05 17:05:32.417 V  Credential Store State Change: Idle(id=)
2023-05-05 17:05:32.418 V  InitAuthConfig Sending event ConfigureAuthentication
2023-05-05 17:05:32.419 V  Auth State Change: ConfiguringAuthentication(authNState=NotConfigured(id=))
2023-05-05 17:05:32.419 V  InitAuthNConfig Starting execution
2023-05-05 17:05:32.421 V  InitAuthNConfig Sending event Configure
2023-05-05 17:05:32.423 V  Auth State Change: ConfiguringAuthentication(authNState=Configured(id=))
2023-05-05 17:05:32.424 V  ConfigureAuthN Starting execution
2023-05-05 17:05:32.426 V  ConfigureAuthN Sending event InitializedSignedOut
2023-05-05 17:05:32.426 V  ConfigureAuthN Sending event ConfiguredAuthentication
2023-05-05 17:05:32.426 V  Auth State Change: ConfiguringAuthentication(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)))
2023-05-05 17:05:32.428 V  Auth State Change: ConfiguringAuthorization(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=NotConfigured(id=))
2023-05-05 17:05:32.428 V  InitAuthZConfig Starting execution
2023-05-05 17:05:32.428 V  InitAuthZConfig Sending event CachedCredentialsAvailable
2023-05-05 17:05:32.430 V  Auth State Change: ConfiguringAuthorization(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=SessionEstablished(amplifyCredential=IdentityPool(identityId=eu-west-1:c00..., credentials=AWSCredentials(accessKeyId = ASIA5***, secretAccessKey = WQDdv***, sessionToken = IQoJb***, expiration = 1683302323000))))
2023-05-05 17:05:32.431 V  ConfigureAuthZ Starting execution
2023-05-05 17:05:32.431 V  ConfigureAuthZ Sending event ConfiguredAuthorization
2023-05-05 17:05:32.432 V  Auth State Change: Configured(authNState=SignedOut(signedOutData=SignedOutData(lastKnownUsername=null, hostedUIErrorData=null, globalSignOutErrorData=null, revokeTokenErrorData=null)), authZState=SessionEstablished(amplifyCredential=IdentityPool(identityId=eu-west-1:c00..., credentials=AWSCredentials(accessKeyId = ASIA5***, secretAccessKey = WQDdv***, sessionToken = IQoJb***, expiration = 1683302323000))))
2023-05-05 17:05:35.191 D  Amplify.Auth.fetchAuthSession() = AWSCognitoAuthSession(isSignedIn=false, identityIdResult=AuthSessionResult{value=eu-west-1:c00..., error=null, type=SUCCESS}, awsCredentialsResult=AuthSessionResult{value=com.amplifyframework.auth.AWSTemporaryCredentials@53daee, error=null, type=SUCCESS}, userSubResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userPoolTokensResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE})
```

**Comment by MrBenjoo** [comment]
Is there any more information i need to provide that might be missing? This is currently a deal breaker and i'll have to revert to a previous version probably before 2.0 when it was working fine.

**Comment by div5yesh** [comment]
Thank you for letting us know. Glad that your issue is resolved now. I will make a note of this in case other customers face a similar issue.
