### ISSUE TITLE
Crash on Application start when calling method Amplify.configure

### ISSUE THREAD

**Issue by reisfernanda** [aws-amplify/amplify-android#2401]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
implementation("com.squareup.okhttp3:okhttp:5.0.0-alpha.11")
implementation("com.amplifyframework:aws-auth-cognito:2.7.0")
implementation("com.amplifyframework:core-kotlin:2.7.0")

```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Oracle Corporation 11.0.12+8-LTS-237)
OS:           Windows 10 10.0 amd64

```

</details>

### Describe the bug

Our crash monitoring is reporting some occurrences of a crash that happens in the application initialization when calling the amplify's configure method.
I couldn't reproduce the issue in any way, but the rare users that find this problem can reproduce it frequently.

`java.lang.IllegalArgumentException - port must be in range [1, 65535]`

This issue is a duplication of https://github.com/aws-amplify/amplify-android/issues/2297 which was closed due to inactivity. I added a comment on the other issue but nobody replied.

### Reproduction steps (if applicable)

We couldn't reproduce the issue but it happens a lot for a few users according to our crash monitoring.

### Code Snippet

```java
class AppApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        try {
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.configure(context) // The crash happens here in this call
        } catch (exception: AmplifyException) {
            loggingManager.logNonFatalException(exception)
        }
    }
}

```

### Log output

<details>

```
Fatal Exception: java.lang.ExceptionInInitializerError:
       at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:27)
       at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineJVMKt.newDefaultHttpEngine(DefaultHttpEngineJVM.kt:16)
       at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine(DefaultHttpEngine.kt:12)
       at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine$default(DefaultHttpEngine.kt:11)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config.<init>(CognitoIdentityProviderClient.kt:265)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config.<init>(CognitoIdentityProviderClient.kt:9)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config$Builder.build(CognitoIdentityProviderClient.kt:385)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config$Builder.build(CognitoIdentityProviderClient.kt:298)
       at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:20)
       at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:13)
       at aws.smithy.kotlin.runtime.client.SdkClientFactory$DefaultImpls.invoke(SdkClientFactory.java:32)
       at aws.sdk.kotlin.runtime.config.AbstractAwsSdkClientFactory.invoke(AbstractAwsSdkClientFactory.java:23)
       at com.amplifyframework.auth.cognito.AWSCognitoAuthService$Companion.fromConfiguration$aws_auth_cognito_release(AWSCognitoAuthService.kt:32)
       at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.kt:123)
       at com.amplifyframework.core.category.Category.configure(Category.java:91)
       at com.amplifyframework.core.Amplify.configure(Amplify.java:159)
       at com.amplifyframework.core.Amplify.configure(Amplify.java:129)
       at com.amplifyframework.kotlin.core.Amplify$Companion.configure(Amplify.kt:68)
       at amaro.amaroandroid.loginRegister.socialLogin.SocialLoginManagerImpl.init(SocialLoginManagerImpl.kt:38)
       at amaro.amaroandroid.presentation.AmaroApplication.setupSocialLogin(AmaroApplication.kt:62)
       at amaro.amaroandroid.presentation.AmaroApplication.onCreate(AmaroApplication.kt:49)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6905)
       at android.app.ActivityThread.access$1300(ActivityThread.java:269)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2010)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Caused by java.lang.IllegalArgumentException: port must be in range [1, 65535]
       at aws.smithy.kotlin.runtime.net.Url.<init>(Url.kt:38)
       at aws.smithy.kotlin.runtime.net.Url.<init>(Url.kt:26)
       at aws.smithy.kotlin.runtime.http.engine.EnvironmentProxySelectorKt.resolveProxyByProperty(EnvironmentProxySelector.kt:61)
       at aws.smithy.kotlin.runtime.http.engine.EnvironmentProxySelectorKt.access$resolveProxyByProperty(EnvironmentProxySelector.kt:1)
       at aws.smithy.kotlin.runtime.http.engine.EnvironmentProxySelector.<init>(EnvironmentProxySelector.kt:30)
       at aws.smithy.kotlin.runtime.http.engine.EnvironmentProxySelector.<init>(EnvironmentProxySelector.kt:28)
       at aws.smithy.kotlin.runtime.http.engine.HttpClientEngineConfig$Builder.<init>(HttpClientEngineConfig.kt:141)
       at aws.smithy.kotlin.runtime.http.engine.HttpClientEngineConfig.<clinit>(HttpClientEngineConfig.kt:31)
       at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:27)
       at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineJVMKt.newDefaultHttpEngine(DefaultHttpEngineJVM.kt:16)
       at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine(DefaultHttpEngine.kt:12)
       at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine$default(DefaultHttpEngine.kt:11)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config.<init>(CognitoIdentityProviderClient.kt:265)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config.<init>(CognitoIdentityProviderClient.kt:9)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config$Builder.build(CognitoIdentityProviderClient.kt:385)
       at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Config$Builder.build(CognitoIdentityProviderClient.kt:298)
       at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:20)
       at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:13)
       at aws.smithy.kotlin.runtime.client.SdkClientFactory$DefaultImpls.invoke(SdkClientFactory.java:32)
       at aws.sdk.kotlin.runtime.config.AbstractAwsSdkClientFactory.invoke(AbstractAwsSdkClientFactory.java:23)
       at com.amplifyframework.auth.cognito.AWSCognitoAuthService$Companion.fromConfiguration$aws_auth_cognito_release(AWSCognitoAuthService.kt:32)
       at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.kt:123)
       at com.amplifyframework.core.category.Category.configure(Category.java:91)
       at com.amplifyframework.core.Amplify.configure(Amplify.java:159)
       at com.amplifyframework.core.Amplify.configure(Amplify.java:129)
       at com.amplifyframework.kotlin.core.Amplify$Companion.configure(Amplify.kt:68)
       at amaro.amaroandroid.loginRegister.socialLogin.SocialLoginManagerImpl.init(SocialLoginManagerImpl.kt:38)
       at amaro.amaroandroid.presentation.AmaroApplication.setupSocialLogin(AmaroApplication.kt:62)
       at amaro.amaroandroid.presentation.AmaroApplication.onCreate(AmaroApplication.kt:49)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6905)
       at android.app.ActivityThread.access$1300(ActivityThread.java:269)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2010)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

</details>

### amplifyconfiguration.json

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "********",
                        "AppClientId": "********",
                        "Region": "******"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "*******",
                            "AppClientId": "*******",
                            "SignInRedirectURI": "*******",
                            "SignOutRedirectURI": "*******",
                            "Scopes": [
                                "aws.cognito.signin.user.admin",
                                "email",
                                "openid",
                                "phone",
                                "profile"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "socialProviders": [
                            "FACEBOOK",
                            "GOOGLE",
                            "APPLE"
                        ],
                        "usernameAttributes": [],
                        "signupAttributes": [],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_UPPERCASE",
                                "REQUIRES_NUMBERS",
                                "REQUIRES_SYMBOLS"
                            ]
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

- There is no `http.proxyHost` or `https.proxyHost` or any other proxy or port configuration on our code.
- We're still unable to reproduce the issue, but here is a list of some devices that faced it:

  1. Redmi Note 9 Pro - Android 11
  2. Galaxy A9 (2018) - Android 10
  3. Galaxy M62 - Android 13
  4. Galaxy A11 - Android 12
  5. Galaxy J8 - Android 10
  6. Galaxy F41 - Android 12

**Comment by gpanshu** [comment]
Hello @reisfernanda is it possible that these users are using a VPN to access your app's services? I agree this still should not happen and we are trying to figure out what we can do from a library perspective to fix this but wanted to understand the use case a bit better. Additionally if you can try logging the port information or [http proxy](https://developer.android.com/reference/android/net/LinkProperties#getHttpProxy()) that they might be using would help in troubleshooting this issue.

**Comment by reisfernanda** [comment]
Hi @gpanshu I don't know if these users are using a VPN, but I just released a new version of the app today and added a log with the port information. So when this crash happens again, I'll be able to get the port information.

**Comment by gpanshu** [comment]
Thank you. Please message here once you have more information. We are also going to add more logging on our side to determine the port information that is being received into our underlying SDK. Once that is released I will report back here as well.

**Comment by reisfernanda** [comment]
Hi @gpanshu, there were 3 occurrences of this crash with a Samsung Galaxy M62 (Android 13) and the logs of ProxyInfo show that the port was -1.

![image](https://user-images.githubusercontent.com/1676272/235512116-4d944a58-5fc1-4fa6-b0e0-3025655f05a5.png)

**Comment by gpanshu** [comment]
@reisfernanda thank you so much for your response. Based on this the proxy port is invalid. To get around this if the users have a proxy on you can force them to use a valid port which can be set using a system property : 

```
JVM system property https.proxyPort (for HTTPS connections)
JVM system property http.proxyPort (for HTTP connections)
Environment variable HTTPS_PROXY (for HTTPS connections, a full URL containing both host and port)
Environment variable HTTP_PROXY (for HTTP connections, a full URL containing both host and port)
```
Please respond here if you would like more information or have questions but for now I am closing this issue.

**Comment by gpanshu** [comment]
Hi @Gesraha101 The fix that we added was to give developers more information on the proxy port their user was using when this error is sent so that the developers can better triage the problem and solution. The port is read from the JVM property that is `http.port` or `https.port`. Can you paste the error message you are seeing from your customers after this logging fix was added to the library. 

Note: Comments on closed issues could get missed or have delayed responses. Please open a new issue if this still remains to be a concern.
