### ISSUE TITLE
Could not find aws.sdk.kotlin:aws-http:0.16.2.

### ISSUE THREAD

**Issue by Tin-moon** [aws-amplify/amplify-android#2416]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
    def amplify_version = '2.8.0'
    implementation "com.amplifyframework:aws-api:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:$amplify_version"
    implementation "com.amplifyframework:rxbindings:$amplify_version"
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Oracle Corporation 11.0.12+8-LTS-237)
OS:           Windows 10 10.0 amd64

```

</details>

### Describe the bug

Build apk file with version 2.7.0 -> all fine
Change version to 2.8.0 -> crash

   > Could not find aws.sdk.kotlin:aws-http:0.16.2.
     Required by:
         project :app > com.amplifyframework:aws-auth-cognito:2.8.0

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by kyptov** [comment]
Same problem. I forced to use latest available version, project builded successfully, but crashed runtime
```
configurations.all {
    resolutionStrategy {
        force("aws.sdk.kotlin:aws-http:0.16.0")
    }
}
```

**Comment by tylerjroach** [comment]
@Tin-moon, @kyptov At what point are you seeing a crash? Can you please post a stacktrace.

**Comment by kyptov** [comment]
```java.lang.NoClassDefFoundError: Failed resolution of: Laws/smithy/kotlin/runtime/util/Platform;
	at aws.sdk.kotlin.runtime.http.AwsUserAgentMetadata$Companion.fromEnvironment(AwsUserAgentMetadata.kt:41)
	at aws.sdk.kotlin.services.cognitoidentityprovider.DefaultCognitoIdentityProviderClient.<init>(DefaultCognitoIdentityProviderClient.kt:146)
	at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Builder.newClient(CognitoIdentityProviderClient.kt:261)
	at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Builder.newClient(CognitoIdentityProviderClient.kt:259)
	at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:20)
	at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:13)
	at aws.smithy.kotlin.runtime.client.SdkClientFactory$DefaultImpls.invoke(SdkClientFactory.kt:32)
	at aws.sdk.kotlin.runtime.config.AbstractAwsSdkClientFactory.invoke(AbstractAwsSdkClientFactory.kt:23)
	at com.amplifyframework.auth.cognito.AWSCognitoAuthService$Companion.fromConfiguration$aws_auth_cognito_release(AWSCognitoAuthService.kt:36)
	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.kt:129)
	at com.amplifyframework.core.category.Category.configure(Category.java:91)
	at com.amplifyframework.core.Amplify.configure(Amplify.java:159)
	at com.amplifyframework.kotlin.core.Amplify$Companion.configure(Amplify.kt:85)
	at com.tms42.android.data.network.AmplifyWrapper.configure(AmplifyWrapper.kt:64)
	at com.tms42.android.data.network.AmplifyWrapper.access$configure(AmplifyWrapper.kt:20)
	at com.tms42.android.data.network.AmplifyWrapper$configure$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:513)
	at kotlinx.coroutines.sync.MutexImpl$LockCont.completeResumeLockWaiter(Mutex.kt:392)
	at kotlinx.coroutines.sync.MutexImpl.unlock(Mutex.kt:342)
	at io.realm.kotlin.internal.RealmImpl.updateRealmPointer(RealmImpl.kt:318)
	at io.realm.kotlin.internal.RealmImpl.access$updateRealmPointer(RealmImpl.kt:53)
	at io.realm.kotlin.internal.RealmImpl$2$1.emit(RealmImpl.kt:138)
	at io.realm.kotlin.internal.RealmImpl$2$1.emit(RealmImpl.kt:137)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ClassNotFoundException: Didn't find class "aws.smithy.kotlin.runtime.util.Platform" on path: DexPathList[[zip file "/data/app/~~241EzqgHTHdedgYTqxEVvQ==/com.tms42.android.debug-E1a23FQbVm6D8yGpkoRIog==/base.apk"],nativeLibraryDirectories=[/data/app/~~241EzqgHTHdedgYTqxEVvQ==/com.tms42.android.debug-E1a23FQbVm6D8yGpkoRIog==/lib/x86_64, /data/app/~~241EzqgHTHdedgYTqxEVvQ==/com.tms42.android.debug-E1a23FQbVm6D8yGpkoRIog==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at aws.sdk.kotlin.runtime.http.AwsUserAgentMetadata$Companion.fromEnvironment(AwsUserAgentMetadata.kt:41) 
	at aws.sdk.kotlin.services.cognitoidentityprovider.DefaultCognitoIdentityProviderClient.<init>(DefaultCognitoIdentityProviderClient.kt:146) 
	at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Builder.newClient(CognitoIdentityProviderClient.kt:261) 
	at aws.sdk.kotlin.services.cognitoidentityprovider.CognitoIdentityProviderClient$Builder.newClient(CognitoIdentityProviderClient.kt:259) 
	at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:20) 
	at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:13) 
	at aws.smithy.kotlin.runtime.client.SdkClientFactory$DefaultImpls.invoke(SdkClientFactory.kt:32) 
	at aws.sdk.kotlin.runtime.config.AbstractAwsSdkClientFactory.invoke(AbstractAwsSdkClientFactory.kt:23) 
	at com.amplifyframework.auth.cognito.AWSCognitoAuthService$Companion.fromConfiguration$aws_auth_cognito_release(AWSCognitoAuthService.kt:36) 
	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.kt:129) 
	at com.amplifyframework.core.category.Category.configure(Category.java:91) 
	at com.amplifyframework.core.Amplify.configure(Amplify.java:159) 
	at com.amplifyframework.kotlin.core.Amplify$Companion.configure(Amplify.kt:85) 
	at com.tms42.android.data.network.AmplifyWrapper.configure(AmplifyWrapper.kt:64) 
	at com.tms42.android.data.network.AmplifyWrapper.access$configure(AmplifyWrapper.kt:20) 
	at com.tms42.android.data.network.AmplifyWrapper$configure$1.invokeSuspend(Unknown Source:14) 
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234) 
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190) 
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161) 
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397) 
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:513) 
	at kotlinx.coroutines.sync.MutexImpl$LockCont.completeResumeLockWaiter(Mutex.kt:392) 
	at kotlinx.coroutines.sync.MutexImpl.unlock(Mutex.kt:342) 
	at io.realm.kotlin.internal.RealmImpl.updateRealmPointer(RealmImpl.kt:318) 
	at io.realm.kotlin.internal.RealmImpl.access$updateRealmPointer(RealmImpl.kt:53) 
	at io.realm.kotlin.internal.RealmImpl$2$1.emit(RealmImpl.kt:138) 
	at io.realm.kotlin.internal.RealmImpl$2$1.emit(RealmImpl.kt:137) 
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383) 
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15) 
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
	at java.lang.Thread.run(Thread.java:1012) 
```

**Comment by tylerjroach** [comment]
@kyptov Thank you for the prompt response. Can you post all AWS dependencies you have listed out in build.gradle? Also, is the crash happening immediately on calling `Amplify.configure`? Can you post the code you are using to call configure?

**Comment by tylerjroach** [comment]
> Same problem. I forced to use latest available version, project builded successfully, but crashed runtime
> 
> ```
> configurations.all {
>     resolutionStrategy {
>         force("aws.sdk.kotlin:aws-http:0.16.0")
>     }
> }
> ```

Just noticing here you have 0.16.0, when 0.16..2 is expected. Lets remove that line while we are diagnosing.

**Comment by kyptov** [comment]
> Just noticing here you have 0.16.0, when 0.16.2 is expected. Lets remove that line while we are diagnosing.

When I try to sync it shows 
```
Failed to resolve: aws.sdk.kotlin:aws-http:0.16.2
Show in Project Structure dialog
Affected Modules: android
```

But it builds successfully.

**Comment by kyptov** [comment]
I used `gradle build --refresh-dependencies` to clear gradle cache

And now I have
```
Execution failed for task ':android:kaptGenerateStubsDebugAndroidTestKotlin'.
> Could not resolve all files for configuration ':android:debugAndroidTestCompileClasspath'.
   > Could not find aws.sdk.kotlin:aws-http:0.16.2.
     Required by:
         project :android > com.amplifyframework:aws-auth-cognito:2.8.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by mattcreaser** [comment]
This fix was released in version 2.8.2 - please let us know if you have any further issues!

**Comment by Bayramali1999** [comment]
> configurations.all {
>     resolutionStrategy {
>         force("aws.sdk.kotlin:aws-http:0.21.1-beta")
>     }
> }

Hi guests where need to add

**Comment by tylerjroach** [comment]
@Bayramali1999 Please use the newest version of Amplify and that block should not be necessary. That was a temporary workaround for a build that had a bad config in gradle.
