### ISSUE TITLE
Host app crashes when triggering Amplify.addPlugin(AWSCognitoAuthPlugin()) inside my android library

### ISSUE THREAD

**Issue by Dave-London** [aws-amplify/amplify-android#2445]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin, Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

// these are the dependencies in my library. the host app has no amplify dependencies
    api 'com.amplifyframework:core:2.8.2'
    api 'com.amplifyframework:aws-api:2.8.2'
    api 'com.amplifyframework:aws-auth-cognito:2.8.2'

</details>

### Environment information

<details>

```
# Put output below this line

------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          13.0.1 (Oracle Corporation 13.0.1+9)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Describe the bug

I have setup amplify in my android library, using the dependencies i provided and using amplify CLI - init -> add auth -> add api. the library exposes a public function that when called triggers the configuration of amplify before it can be used.
here is the function that is triggered in my library:
`fun configure(context: Context): Boolean {
        return try {
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.configure(context)
            Log.i("AmplifyQuickstart", "Amplify is successfully configured")
            true
        } catch (e: AmplifyException) {
            Log.e("AmplifyQuickstart", "Amplify failed to configure", e)
            false
        }
    }`

i build and publish the library to a local maven repository. 
I created an android app that has my published library as a gradle dependency and when i run the app and use my library's public configure function that triggers the internal code detailed above, the app crashes with the following error:
`  E  FATAL EXCEPTION: main
                                  Process: com.example.sdkdev, PID: 22547
                                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amplifyframework/auth/cognito/AWSCognitoAuthPlugin;
                                  	at ***********.configure(AmplifyServiceImpl.kt:126)
                                  	at ... 
                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin" on path: DexPathList[[dex file "/data/data/com.example.sdkdev/code_cache/.overlay/base.apk/classes.dex", zip file "/data/app/~~fWzk5OtFyzZ-S177EjuyeA==/com.example.sdkdev-uJiOhEiFTQL1wN0wfRIobg==/base.apk"],nativeLibraryDirectories=[/data/app/~~fWzk5OtFyzZ-S177EjuyeA==/com.example.sdkdev-uJiOhEiFTQL1wN0wfRIobg==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                  	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line

fun configure(context: Context): Boolean {
        return try {
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.configure(context)
            Log.i("AmplifyQuickstart", "Amplify is successfully configured")
            true
        } catch (e: AmplifyException) {
            Log.e("AmplifyQuickstart", "Amplify failed to configure", e)
            false
        }
    }
```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by Dave-London** [comment]
sorry, guys - my bad.
seems that when i published my library, the created POM file did not include all of the used dependencies (such as amplify).
the fix in case some future guy needs this is adding the following block in your pom section in your library gradle file:
`// Add this block to include dependencies in the POM file
                withXml {
                    def dependenciesNode = asNode().appendNode('dependencies')
                    configurations.implementation.allDependencies.each {
                        if (it.group != null && it.name != null) {
                            def dependencyNode = dependenciesNode.appendNode('dependency')
                            dependencyNode.appendNode('groupId', it.group)
                            dependencyNode.appendNode('artifactId', it.name)
                            dependencyNode.appendNode('version', it.version)
                        }
                    }
                }`
