### ISSUE TITLE
Data Store throws exception on saving a record for version 2.8.4

### ISSUE THREAD

**Issue by ZubairAkber** [aws-amplify/amplify-android#2453]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Amplify dependencies
    implementation 'com.amplifyframework:core:2.8.4'
    implementation 'com.amplifyframework:aws-api:2.8.4'
    implementation 'com.amplifyframework:aws-datastore:2.8.4'
    implementation 'com.amplifyframework:aws-auth-cognito:2.8.4'
    implementation 'com.amplifyframework:aws-storage-s3:2.8.4'

```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I have updated to 2.8.4 and i get exception while creating a record in amplify, this issue is not happening in version 2.8.2

    amplify:aws-datastore    W  Non-retryable exception.
                                           GraphQLResponseException{message=Mutation failed. Failed mutation = PendingMutation{mutatedItem=SerializedModel{id='96581369-7714-473c-8726-4ee1c867b042', serializedData={automationId=0, sub=44e14e3f-3e1e-4382-99d9-c2485f9922c4, cpuId=MHA401868000003, pending=true, dayLightSensitivity=0, createdAt=null, enable=true, sensorType=, startTime=1.6841268E12, id=96581369-7714-473c-8726-4ee1c867b042, alwaysOn=false, suppressionTime=1, updatedAt=null, sensorBleAddress=, devices={}, selectedSensor={}, pendingStatus=pending, pendingPayload={"cmd":1,"payload":"{}","devices":"{}","sid":297}, timeStamp=0, condition=schedule, scheduleType=specific, name=I am Home, days=127, endTime=1.6841268E12}, modelName=Automations}, mutationType=CREATE, mutationId=ed31f3e0-f2f0-11ed-87c2-9f977a0a7662, predicate=MatchAllQueryPredicate}. AppSync response contained errors = [GraphQLResponse.Error{message='Variable 'startTime' has an invalid value.', locations='[GraphQLLocation{line='1', column='28'}]', path='null', extensions='null'}], errors=[GraphQLResponse.Error{message='Variable 'startTime' has an invalid value.', locations='[GraphQLLocation{line='1', column='28'}]', path='null', extensions='null'}], recoverySuggestion=See attached list of GraphQLResponse.Error objects.}
                                         	  at 
    com.amplifyframework.datastore.syncengine.MutationProcessor.handleResponseErrors(MutationProcessor.java:386)
                                         	  at 
    com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$publishWithStrategy$18$com-amplifyframework-datastore-syncengine-MutationProcessor(MutationProcessor.java:345)
                                         	  at com.amplifyframework.datastore.syncengine.MutationProcessor$$ExternalSyntheticLambda14.apply(Unknown Source:6)
                                         	  at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)
                                         	  at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
                                         	  at com.amplifyframework.datastore.syncengine.ConflictResolver$$ExternalSyntheticLambda1.accept(Unknown Source:4)
                                         	  at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$3(AppSyncClient.java:345)
                                         	  at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda2.accept(Unknown Source:4)
                                         	  at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:152)
                                         	  at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
                                         	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                         	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                         	  at java.lang.Thread.run(Thread.java:923)
                                         	  
                                

![image](https://github.com/aws-amplify/amplify-android/assets/15378288/abfbbba7-89f3-4aaf-b4ec-69b50e909a32)

    amplify:aws-datastore    E  Error encountered in the DataStore.
                                         GraphQLResponseException{message=Mutation failed. Failed mutation = PendingMutation{mutatedItem=SerializedModel{id='96581369-7714-473c-8726-4ee1c867b042', serializedData={automationId=0, sub=44e14e3f-3e1e-4382-99d9-c2485f9922c4, cpuId=MHA401868000003, pending=true, dayLightSensitivity=0, createdAt=null, enable=true, sensorType=, startTime=1.6841268E12, id=96581369-7714-473c-8726-4ee1c867b042, alwaysOn=false, suppressionTime=1, updatedAt=null, sensorBleAddress=, devices={}, selectedSensor={}, pendingStatus=pending, pendingPayload={"cmd":1,"payload":"{}","devices":"{}","sid":297}, timeStamp=0, condition=schedule, scheduleType=specific, name=I am Home, days=127, endTime=1.6841268E12}, modelName=Automations}, mutationType=CREATE, mutationId=ed31f3e0-f2f0-11ed-87c2-9f977a0a7662, predicate=MatchAllQueryPredicate}. AppSync response contained errors = [GraphQLResponse.Error{message='Variable 'startTime' has an invalid value.', locations='[GraphQLLocation{line='1', column='28'}]', path='null', extensions='null'}], errors=[GraphQLResponse.Error{message='Variable 'startTime' has an invalid value.', locations='[GraphQLLocation{line='1', column='28'}]', path='null', extensions='null'}], recoverySuggestion=See attached list of GraphQLResponse.Error objects.}
                                         	at com.amplifyframework.datastore.syncengine.MutationProcessor.handleResponseErrors(MutationProcessor.java:386)
                                         	at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$publishWithStrategy$18$com-amplifyframework-datastore-syncengine-MutationProcessor(MutationProcessor.java:345)
                                         	at com.amplifyframework.datastore.syncengine.MutationProcessor$$ExternalSyntheticLambda14.apply(Unknown Source:6)
                                         	at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)
                                         	at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
                                         	at com.amplifyframework.datastore.syncengine.ConflictResolver$$ExternalSyntheticLambda1.accept(Unknown Source:4)
                                         	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$3(AppSyncClient.java:345)
                                         	at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda2.accept(Unknown Source:4)
                                         	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:152)
                                         	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                         	at java.lang.Thread.run(Thread.java:923)

![image](https://github.com/aws-amplify/amplify-android/assets/15378288/38aabee3-78aa-415c-8201-1ac2b3c2d149)

**Comment by eeatonaws** [comment]
In the logs you shared, it says `Variable 'startTime' has an invalid value` and the value of `startTime` for that particular mutation is `1.6841268E12`. What data type is `startTime` defined as in your schema? Please provide your GraphQL schema, as this will help us reproduce the issue.

**Comment by ZubairAkber** [comment]
@eeatonaws it is AWSTimestamp & it is working fine for version 2.8.2 and lower versions

<img width="270" alt="image" src="https://github.com/aws-amplify/amplify-android/assets/15378288/a1fa431f-376c-453b-a72f-06c8db1b7f35">

**Comment by tylerjroach** [comment]
Hi @ZubairAkber Can you post your schema for the model, as well as the generated model file? 

I ran a sample project that added `startTime: AWSTimestamp` in the schema and after running `amplify codegen models`, the resulting startTime type was Temporal.Timestamp:

```
private final @ModelField(targetType="AWSTimestamp", isRequired = true) Temporal.Timestamp startTime;
```

Upon adding a new item, the logs show the startTime as:
`startTime=Temporal.Timestamp{timestamp=1684263490}`.

This differs from your logs where startTime appears to just be a Long.

**Comment by ZubairAkber** [comment]
This is the exact data type define in model, if you need complete model do let me know.

![image](https://github.com/aws-amplify/amplify-android/assets/15378288/a15dabdd-7e6b-49e9-a52f-2007e03c889f)

This is what i have defined in my data model

![image](https://github.com/aws-amplify/amplify-android/assets/15378288/956d6769-2b9a-4f3d-896f-0f871a00a1af)

And this is how i am setting it in my Automation 

![image](https://github.com/aws-amplify/amplify-android/assets/15378288/71a382e8-ac3c-40c6-9ff2-f083fea5c29a)

**Comment by ZubairAkber** [comment]
@tylerjroach i will check and let you know but i am using it in 2.8.2 and it works fine for me, i will share exact values on which this issue is happening. Thanks

**Comment by ZubairAkber** [comment]
@tylerjroach yes you are right, i have converted it to MilliSeconds and it works fine, but strange thing is it works fine for the 2.8.2 and rest of the versions. Any ways you can close this issue Thanks

**Comment by ZubairAkber** [comment]
@tylerjroach i am storing 1685682000000 UTC that is in milli seconds, when i use Temporal.Timestamp(automation.startTime, TimeUnit.MILLISECONDS) to store in Temporal object then it convert that value to seconds 1685682000 but i want to be save in milli seconds in amplify, how can i achieve this. Thanks in advance
