### ISSUE TITLE
[DataStore] Not getting results on the first query after a fresh login

### ISSUE THREAD

**Issue by hamidgh** [aws-amplify/amplify-android#2455]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Not applicable

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Amplify
    implementation 'com.amplifyframework:core-kotlin:0.15.1'
    implementation 'com.amplifyframework:aws-api:1.31.1'
    // Datastore
    implementation 'com.amplifyframework:aws-datastore:1.31.3'
    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
    // Cognito
    implementation 'com.amplifyframework:aws-auth-cognito:1.31.1'

```

</details>

### Environment information

<details>

```
# Put output below this line
Welcome to Gradle 7.2!

Here are the highlights of this release:
 - Toolchain support for Scala
 - More cache hits when Java source files have platform-specific line endings
 - More resilient remote HTTP build cache behavior

For more details see https://docs.gradle.org/7.2/release-notes.html


------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          17.0.1 (Oracle Corporation 17.0.1+12-39)
OS:           Mac OS X 12.1 aarch64

```

</details>

### Please include any relevant guides or documentation you're referencing

https://github.com/aws-amplify/amplify-android/issues/1660

### Describe the bug

The original issue that got closed without any response is here. I am creating a new one since the other one got closed due to inactivity. [eeatonaws](https://github.com/eeatonaws) 
https://github.com/aws-amplify/amplify-android/issues/1660

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line
> Before event subscription

> On First login (local db empty):

I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator transitioning from STOPPED to SYNC_VIA_API
I/amplify:aws-datastore: Starting to observe local storage changes.
I/amplify:aws-datastore: Now observing local storage. Local changes will be enqueued to mutation outbox.
I/amplify:aws-datastore: Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore: Setting currentState to SYNC_VIA_API
I/amplify:aws-datastore: Orchestrator lock released.
I/AmplifyService: DataStore started
I/amplify:aws-datastore: Starting API synchronization mode.
I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator lock released.
I/amplify:aws-datastore: Starting processing subscription events.
I/amplify:aws-datastore: Started subscription processor for models: [Site, Customer,  Animal] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
W/amplify:aws-datastore: Sync failed: foreign key constraint violation: ModelWithMetadata{model=Site {id=34567890, owner=1234561, ……, customer=Customer {id=12345, owner=13243, ….’}, syncMetadata=ModelMetadata{id='Site|12345916b', _deleted=null, _version=2, _lastChangedAt=Temporal.Timestamp{timestamp=1644537738124}}}

    DataStoreException{message=Invalid SQL statement: INSERT INTO `Site` (`id`, `createdAt`, `owner`, …………, `updatedAt`, `customer_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), cause=android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY), recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
        at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.dataStoreException(SQLCommandProcessor.java:86)
        at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.execute(SQLCommandProcessor.java:81)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:759)
2022-02-15 13:46:36.923 20291-20700/com.example.onecupai W/amplify:aws-datastore:     at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$com-amplifyframework-datastore-storage-sqlite-SQLiteStorageAdapter(SQLiteStorageAdapter.java:364)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter$$ExternalSyntheticLambda5.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:569)
        at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
        at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
        at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.execute(SQLCommandProcessor.java:77)
        	... 8 more
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
W/amplify:aws-datastore: Sync failed: foreign key constraint violation: ModelWithMetadata{model=Animal …………..




> On Second Login (local db already populated on first login:

I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator transitioning from STOPPED to SYNC_VIA_API
I/amplify:aws-datastore: Starting to observe local storage changes.
I/amplify:aws-datastore: Now observing local storage. Local changes will be enqueued to mutation outbox.
I/amplify:aws-datastore: Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore: Setting currentState to SYNC_VIA_API
I/amplify:aws-datastore: Orchestrator lock released.
I/AmplifyService: DataStore started
I/amplify:aws-datastore: Starting API synchronization mode.
I/amplify:aws-datastore: Starting processing subscription events.
I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator lock released.
D/DataStore: Query completed successfully.: id: 12345 name:  Firstname Lastname
I/amplify:aws-datastore: Started subscription processor for models: [Site, Customer, Animal] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Starting processing subscription data buffer.
I/amplify:aws-datastore: Started the orchestrator in API sync mode.
I/amplify:aws-datastore: Started processing the mutation outbox. Pending mutations will be published to the cloud.





> With Subscription event: (1 query followed by nested query inside Subscription event)

> First login:

I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator transitioning from STOPPED to SYNC_VIA_API
I/amplify:aws-datastore: Starting to observe local storage changes.
I/amplify:aws-datastore: Now observing local storage. Local changes will be enqueued to mutation outbox.
I/amplify:aws-datastore: Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore: Setting currentState to SYNC_VIA_API
I/amplify:aws-datastore: Orchestrator lock released.
I/AmplifyService: DataStore started
I/amplify:aws-datastore: Starting API synchronization mode.
I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator lock released.
I/amplify:aws-datastore: Starting processing subscription events.
I/amplify:aws-datastore: Started subscription processor for models: [Site, Customer, Animal] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
W/amplify:aws-datastore: Sync failed: foreign key constraint violation: ModelWithMetadata{model=Animal {......
W/amplify:aws-datastore: DataStoreException{message=Invalid SQL statement: INSERT INTO `Animal` (`id`, ..... `customer_id`, `herd_id`, `site_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), cause=android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY), recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
    at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.dataStoreException(SQLCommandProcessor.java:86)
        at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.execute(SQLCommandProcessor.java:81)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:759)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$com-amplifyframework-datastore-storage-sqlite-SQLiteStorageAdapter(SQLiteStorageAdapter.java:364)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter$$ExternalSyntheticLambda5.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:569)
        at android.database.sqlite.SQLiteSession.execute(SQLiteSession.java:619)
        at android.database.sqlite.SQLiteStatement.execute(SQLiteStatement.java:44)
        at com.amplifyframework.datastore.storage.sqlite.SQLCommandProcessor.execute(SQLCommandProcessor.java:77)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.writeData(SQLiteStorageAdapter.java:759) 
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$com-amplifyframework-datastore-storage-sqlite-SQLiteStorageAdapter(SQLiteStorageAdapter.java:364) 
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter$$ExternalSyntheticLambda5.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
W/amplify:aws-datastore: Sync failed: foreign key constraint violation: ModelWithMetadata{model=Animal ........
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator lock released.
I/amplify:aws-datastore: Starting processing subscription data buffer.
I/amplify:aws-datastore: Started the orchestrator in API sync mode.
I/amplify:aws-datastore: Started processing the mutation outbox. Pending mutations will be published to the cloud.
D/DataStore: Query completed successfully.: id: 123456 name:  Firstname Lastname


> On second/consecutive logins:

I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator transitioning from STOPPED to SYNC_VIA_API
I/amplify:aws-datastore: Starting to observe local storage changes.
I/amplify:aws-datastore: Now observing local storage. Local changes will be enqueued to mutation outbox.
I/amplify:aws-datastore: Setting currentState to LOCAL_ONLY
I/amplify:aws-datastore: Setting currentState to SYNC_VIA_API
I/amplify:aws-datastore: Orchestrator lock released.
I/AmplifyService: DataStore started
I/amplify:aws-datastore: Starting API synchronization mode.
I/amplify:aws-datastore: Starting processing subscription events.
I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator lock released.
D/DataStore: IGNORE RESULTS Query completed successfully.: id: 12345 name:  Firstname Lastname
I/amplify:aws-datastore: Started subscription processor for models: [Site, Customer, Animal] of types [ON_CREATE, ON_UPDATE, ON_DELETE].
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Successfully sync'd down model state from cloud.
I/amplify:aws-datastore: Starting processing subscription data buffer.
I/amplify:aws-datastore: Started the orchestrator in API sync mode.
I/amplify:aws-datastore: Started processing the mutation outbox. Pending mutations will be published to the cloud.
D/DataStore: Query completed successfully.: id: 123456 name:  Firstname Lastname

```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by eeatonaws** [comment]
Thank you for creating a new issue to continue the discussion on issue #1660. Please see the comment [here](https://github.com/aws-amplify/amplify-android/issues/1660#issuecomment-1511516643) for an explanation of why no results are returned in the initial query after the user logs in. Could you please provide more details on what additional questions you have?

Looking at the original issue, I noticed you mentioned using `”@aws-amplify/datastore”:”^4.0.15”` and `”aws-amplify”:”^5.0.15”` which appear to be Amplify JS dependencies. Please let us know if this is the case and we can transfer this issue to the Amplify JS GitHub repository to help address any further questions you may have.

**Comment by tjleing** [comment]
@hamidgh Please let us know if you have additional questions -- in particular, if you have attempted what @eeatonaws mentions in [the comment on the original issue](https://github.com/aws-amplify/amplify-android/issues/1660#issuecomment-1511516643) about subscribing to a Hub event that the data is ready to be displayed.  Also, if you are using Amplify JS please [create an issue there](https://github.com/aws-amplify/amplify-js/issues).

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please let us know if you have any additional questions and we can reopen this issue.
