### ISSUE TITLE
DataStore Api Exception

### ISSUE THREAD

**Issue by ZubairAkber** [aws-amplify/amplify-android#2461]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Amplify dependencies
    implementation 'com.amplifyframework:core:2.8.2'
    implementation 'com.amplifyframework:aws-api:2.8.2'
    implementation 'com.amplifyframework:aws-datastore:2.8.2'
    implementation 'com.amplifyframework:aws-auth-cognito:2.8.2'
    implementation 'com.amplifyframework:aws-storage-s3:2.8.2'

    // AWS MQTT dependencies
    implementation 'com.amazonaws:aws-android-sdk-iot:2.69.0'
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.69.0'

    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'



```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

I am using the app and suddenly i get this exception and then it is not able to connect stuck in reconnect of MQTT but the internet is stable, Device is Samsung S20.

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


amplify:aws-api          W  Websocket connection failed.
                                         java.net.SocketException: Software caused connection abort
                                         	at java.net.SocketInputStream.socketRead0(Native Method)
                                         	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
                                         	at java.net.SocketInputStream.read(SocketInputStream.java:173)
                                         	at java.net.SocketInputStream.read(SocketInputStream.java:143)
                                         	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
                                         	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
                                         	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
                                         	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
                                         	at okio.InputStreamSource.read(JvmOkio.kt:94)
                                         	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
                                         	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
                                         	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
                                         	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
                                         	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
                                         	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
                                         	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
                                         	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
                                         	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                         	at java.lang.Thread.run(Thread.java:1012)
12:26:12.488 AWSIotMqttManager        W  connection is Lost





amplify:aws-datastore    W  API sync failed - transitioning to LOCAL_ONLY.
                                         DataStoreException{message=Error during subscription., cause=ApiException{message=Subscription failed., cause=java.net.SocketException: Software caused connection abort, recoverySuggestion=Check your Internet connection. Is your device online?}, recoverySuggestion=Evaluate details.}
                                         	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$2(AppSyncClient.java:321)
                                         	at com.amplifyframework.datastore.appsync.AppSyncClient$$ExternalSyntheticLambda5.accept(Unknown Source:4)
                                         	at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$1$com-amplifyframework-api-aws-SubscriptionOperation(SubscriptionOperation.java:87)
                                         	at com.amplifyframework.api.aws.SubscriptionOperation$$ExternalSyntheticLambda3.accept(Unknown Source:4)
                                         	at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchError(SubscriptionEndpoint.java:443)
                                         	at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:242)
                                         	at com.amplifyframework.api.aws.SubscriptionEndpoint.access$100(SubscriptionEndpoint.java:62)
                                         	at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onFailure(SubscriptionEndpoint.java:538)
                                         	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
                                         	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:197)
                                         	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                         	at java.lang.Thread.run(Thread.java:1012)
                                         Caused by: ApiException{message=Subscription failed., cause=java.net.SocketException: Software caused connection abort, recoverySuggestion=Check your Internet connection. Is your device online?}
                                         	at com.amplifyframework.api.aws.SubscriptionEndpoint.notifyError(SubscriptionEndpoint.java:242) 
                                         	at com.amplifyframework.api.aws.SubscriptionEndpoint.access$100(SubscriptionEndpoint.java:62) 
                                         	at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onFailure(SubscriptionEndpoint.java:538) 
                                         	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592) 
                                         	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:197) 
                                         	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539) 
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                         	at java.lang.Thread.run(Thread.java:1012) 
                                         Caused by: java.net.SocketException: Software caused connection abort
                                         	at java.net.SocketInputStream.socketRead0(Native Method)
                                         	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
                                         	at java.net.SocketInputStream.read(SocketInputStream.java:173)
                                         	at java.net.SocketInputStream.read(SocketInputStream.java:143)
                                         	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
                                         	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
                                         	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
                                         	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
                                         	at okio.InputStreamSource.read(JvmOkio.kt:94)
                                         	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
                                         	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
                                         	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
                                         	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
                                         	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
                                         	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
                                         	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
                                         	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
                                         	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539) 
                                         	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                         	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                         	at java.lang.Thread.run(Thread.java:1012) 




System.err               W  Connection lost (32109) - java.io.EOFException
12:26:21.607 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
12:26:21.607 System.err               W  	at java.lang.Thread.run(Thread.java:1012)
12:26:21.607 System.err               W  Caused by: java.io.EOFException
12:26:21.607 System.err               W  	at java.io.DataInputStream.readByte(DataInputStream.java:275)
12:26:21.607 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
12:26:21.607 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
12:26:21.607 System.err               W  	... 1 more



AWSIotMqttManager        W  Reconnect failed 
12:37:07.581 AWSIotMqttManager        I  schedule Reconnect attempt 1 of 10000 in 8 seconds.
12:37:07.582 MQTT                     I  Reconnecting, MqttException (0) - java.net.UnknownHostException: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com
12:37:07.582 System.err               W  MqttException (0) - java.net.UnknownHostException: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com
12:37:07.582 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
12:37:07.582 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
12:37:07.582 System.err               W  	at java.lang.Thread.run(Thread.java:1012)
12:37:07.583 System.err               W  Caused by: java.net.UnknownHostException: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com
12:37:07.583 System.err               W  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:208)
12:37:07.583 System.err               W  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
12:37:07.583 System.err               W  	at java.net.Socket.connect(Socket.java:646)
12:37:07.583 System.err               W  	at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
12:37:07.583 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
12:37:07.583 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:132)
12:37:07.583 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:63)
12:37:07.583 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
12:37:07.583 System.err               W  	... 1 more




AWSIotMqttManager        W  Reconnect failed 
12:55:26.663 AWSIotMqttManager        I  schedule Reconnect attempt 2 of 10000 in 8 seconds.
12:55:26.664 MQTT                     I  Reconnecting, MqttException (0) - java.net.UnknownHostException: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com
12:55:26.665 System.err               W  MqttException (0) - java.net.UnknownHostException: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com
12:55:26.665 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
12:55:26.665 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
12:55:26.665 System.err               W  	at java.lang.Thread.run(Thread.java:1012)
12:55:26.665 System.err               W  Caused by: java.net.UnknownHostException: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com
12:55:26.665 System.err               W  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:208)
12:55:26.665 System.err               W  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
12:55:26.665 System.err               W  	at java.net.Socket.connect(Socket.java:646)
12:55:26.665 System.err               W  	at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
12:55:26.665 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
12:55:26.665 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:132)
12:55:26.665 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:63)
12:55:26.665 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
12:55:26.665 System.err               W  	... 1 more



AWSIotMqttManager        W  Reconnect failed 
14:14:56.520 AWSIotMqttManager        I  schedule Reconnect attempt 3 of 10000 in 8 seconds.
14:14:56.524 MQTT                     I  Reconnecting, MqttException (0) - java.net.UnknownHostException: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com
14:14:56.524 System.err               W  MqttException (0) - java.net.UnknownHostException: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com
14:14:56.524 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
14:14:56.524 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
14:14:56.525 System.err               W  	at java.lang.Thread.run(Thread.java:1012)
14:14:56.525 System.err               W  Caused by: java.net.UnknownHostException: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com
14:14:56.525 System.err               W  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:208)
14:14:56.525 System.err               W  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
14:14:56.525 System.err               W  	at java.net.Socket.connect(Socket.java:646)
14:14:56.525 System.err               W  	at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
14:14:56.525 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
14:14:56.525 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:132)
14:14:56.525 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:63)
14:14:56.525 System.err               W  	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
14:14:56.525 System.err               W  	... 1 more

</details>


### amplifyconfiguration.json

_No response_

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by mattcreaser** [comment]
Hi @ZubairAkber - have you been able to reproduce this issue on any other device, or noticed any network instability with your connection? Is this error consistent or intermittent?

The logs suggest that a network disruption is the root cause of the problem. When this happens you could try executing a trace to the mentioned hostname (`a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com` in these logs) from the network the device is connected to to see if there is a reachability problem there.

**Comment by eeatonaws** [comment]
Closing due to inactivity. Please create a new issue or reopen this issue if you have additional questions.
