### ISSUE TITLE
Crash while uploading: `Tried to get a plugin but that plugin was not present. Check if the plugin was added originally or perhaps was already removed`

### ISSUE THREAD

**Issue by ygag-gopikrishnan** [aws-amplify/amplify-android#2465]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line
 api "com.amplifyframework:core-kotlin:2.8.2"
 api "com.amplifyframework:aws-storage-s3:2.8.2"
 api "com.amplifyframework:aws-auth-cognito:2.8.2"
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.6-rc-1
------------------------------------------------------------

Build time:   2022-10-28 07:52:11 UTC
Revision:     62973455a8df25d003949f3f573593cd10d083a3

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.18 (Homebrew 11.0.18+0)
OS:           Mac OS X 13.2.1 aarch64
```

</details>

### Describe the bug

App intermittently crashes while uploading a file to the storage. Attaching the stack trace below.

```
Fatal Exception: java.lang.IllegalStateException: Tried to get a plugin but that plugin was not present. Check if the plugin was added originally or perhaps was already removed.
       at com.amplifyframework.core.category.Category.getPluginIfConfiguredOrThrow(Category.java:220)
       at com.amplifyframework.core.category.Category.getSelectedPlugin(Category.java:215)
       at com.amplifyframework.storage.StorageCategory.uploadFile(StorageCategory.java:150)
       at com.amplifyframework.kotlin.storage.KotlinStorageFacade.uploadFile(KotlinStorageFacade.kt:93)
       at com.******.app.base.usecases.UploadFileUseCase.invoke-IoAF18A(UploadFileUseCase.kt:62)
       at com.*****.*****.ui.personalisationmediapicker.******Fragment$doUpload$1.invokeSuspend(*******Fragment.kt:279)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.internal.DispatchedContinuation.resumeUndispatchedWith(DispatchedContinuation.java:256)
       at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:282)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.java:126)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(BuildersKt__Builders_common.kt:56)
       at kotlinx.coroutines.BuildersKt.launch(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(BuildersKt__Builders_common.kt:47)
       at kotlinx.coroutines.BuildersKt.launch$default(Builders.kt:1)
```

### Reproduction steps (if applicable)

sorry we are unable to give a defined step to reproduce the issue. Not all the uploads end up in a crash but in an irregular manner.

### Code Snippet

This is how we initialize the amplify at start up.

```java
private suspend fun initAmplify(
        context: Context,
        config: ConfigurationDetails
    ) : AmplifyConfigurationResult{
        return withContext(Dispatchers.IO){
            try {
                Amplify.addPlugin(AWSCognitoAuthPlugin())
                Amplify.addPlugin(AWSS3StoragePlugin())
                Amplify.configure(
                    AmplifyConfiguration.fromJson(
                        JSONObject(
                            Gson().toJson(
                                config.loginConfig.androidAwsConfig,
                                ConfigurationDetails.LoginConfig.AndroidAwsConfig::class.java
                            )
                        )
                    ),
                    context
                )
            } catch (error: AmplifyException) {
              
            }
        }
    }

```

Also attaching the File upload code as well!

```java
    /**
     * Attempts to upload the file and return a [Result] that wraps a 'Key' corresponding to the
     * uploaded file.
     */
    suspend operator fun invoke(): Result<String> {
        showProgress()
        var uploadResult: Result<String>
        val key = uri.getUniqueKey()
        val options = StorageUploadFileOptions.defaultInstance()
        var progressJob: Deferred<Unit>? = null

        try {
            upload = Amplify.Storage.uploadFile(key, File(uri.path), options)

            progressJob = scope.async(Dispatchers.Main) {
                upload.progress().collect {
                    progress.setProgress((it.fractionCompleted * 100).toInt())
                }
            }
            upload.result()
            uploadResult = Result.success(key)
            progress.setProgress(100)
        } catch (error: AmplifyException) {
            uploadResult = Result.failure(YgagError(YgagError.DEFAULT_ERROR_MESSAGE))
        } finally {
            hideProgress()
            progressJob?.cancel()
        }
        return uploadResult
    }
```

### Log output

<details>

```
```

</details>

### amplifyconfiguration.json

```json
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_PASSWORD_AUTH",
            "OAuth": {
              "AppClientId": "**********",
              "AppCognitoWebDomain": "*****.auth.us-east-2.amazoncognito.com",
              "Scopes": [
                "phone",
                "email",
                "openid",
                "profile",
                "https://www.googleapis.com/auth/user.gender.read",
                "https://www.googleapis.com/auth/user.phonenumbers.read",
                "aws.cognito.signin.user.admin"
              ],
              "SignInRedirectURI": "ecomv2://",
              "SignOutRedirectURI": "ecomv2://",
              "WebDomain": "******.auth.us-east-2.amazoncognito.com"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "AppClientId": "*************",
            "PoolId": "ap-south-1_puReCIr7W",
            "Region": "ap-south-1"
          }
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "ap-south-1:22e4525b-39cb-4333-88ea-2047ca4fb867",
              "Region": "ap-south-1"
            }
          }
        }
      }
    }
  },
  "storage": {
    "plugins": {
      "awsS3StoragePlugin": {
        "bucket": "*****-cognito-production-1-tf",
        "region": "ap-south-1"
      }
    }
  },
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0"
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by mattcreaser** [comment]
Hi @ygag-gopikrishnan. This exception indicates that there is no plugin added for the storage category. I can see from your `initAmplify` function that you are adding the `AWSS3StoragePlugin()`, so I would take a look at that to see when it's being called. Typically we recommend doing this during the `onCreate` of your Application class to ensure that it is executed before you attempt to use any categories.

Can you please confirm that your `initAmplify` function is running to completion before you run your storage upload code?

**Comment by ygag-gopikrishnan** [comment]
@mattcreaser The amplify initialization occurs in the `LandingActivity/SplashScreen` not in the `Applications` `onCreate()` method. The `LandingActivity` of course is called on the startup, I see no chance of not initializing the `Amplify`.

Would you still recommend moving the initialization code to the `Application` class?

**Comment by mattcreaser** [comment]
That is our recommendation, unless there is a good reason to do it elsewhere. The early configuration reduces the chance of running into ordering problems using the library.

Could you try moving the Amplify configuration code into your Application `onCreate` (and also removing the surrounding coroutine - it should look like the example in our docs [here](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android/#4-initialize-amplify-in-the-application) - to see if the problem persists?

**Comment by ygag-gopikrishnan** [comment]
The initialization doesn't seem to be the culprit. 
Do you know if the above-mentioned issue can happen due to some other reasons?  @mattcreaser

**Comment by mattcreaser** [comment]
The Amplify initialization should be the only cause, unless you are also calling `removePlugin` somewhere. Can you check for that? Once the plugin is correctly added (and not removed) the above error will not occur.

Can you additional clarify what you mean by the app crashes intermittently? Do uploads sometimes work and then crash on subsequent uploads, or is it the first upload after app launch that sometimes crashes?

If possible, creating a minimal app that reproduces the issue would be the best option for us to investigate further.

**Comment by ygag-gopikrishnan** [comment]
You were right.
The entire initialization was not taking place inside the application class.
In cases where the app restarts (Like denying permission at run time), the amplify was only set up partially since some code was placed outside of the Application class.

Thanks for the guidance. @mattcreaser
