### ISSUE TITLE
Error The provided token has expired 

### ISSUE THREAD

**Issue by MohammedHassouna** [aws-amplify/amplify-android#2468]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line

//     Amplify core dependency
    implementation 'com.amplifyframework:core:2.8.5'
    implementation 'com.amplifyframework:aws-storage-s3:2.8.5'
    implementation 'com.amplifyframework:aws-auth-cognito:2.8.5'

```

</details>

### Environment information

<details>

```
# Put output below this line
        minSdkVersion 24
        targetSdkVersion 33

```

</details>

### Describe the bug

After upgrading to Amplify version 2, I get this error when I try to upload photos using Amplify library, What should I do to fix this issue

```
    SinglePartUploadWorker failed with exception: aws.sdk.kotlin.services.s3.model.S3Exception: The provided token has expired.
                                                                                                    	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt.throwPutObjectError(PutObjectOperationDeserializer.kt:66)
                                                                                                    	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt.access$throwPutObjectError(PutObjectOperationDeserializer.kt:1)
                                                                                                    	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt$throwPutObjectError$1.invokeSuspend(Unknown Source:13)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### Code Snippet

We added these lines in the MainApplication
```
           Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.configure(getApplicationContext());

```
And these fields in the res folder
```
amplifyconfiguration.json
awsconfiguration.json
```
Then we use this code to upload the images
```
Amplify.Storage.uploadInputStream(full_path, inputStream,
                                new Consumer<StorageUploadInputStreamResult>() {
                                    @Override
                                    public void accept(@NonNull StorageUploadInputStreamResult result) {
                                        Log.i("MyAmplifyApp", "Successfully uploaded: " + result.getKey());
                                       
                                    }
                                },
                                new Consumer<StorageException>() {
                                    @Override
                                    public void accept(@NonNull StorageException storageFailure) {
                                        Log.e("MyAmplifyApp", "Upload failed", storageFailure);
                                    }
                                }
                        );
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "change to my poolid",
                            "Region": "us-east-2"
                        }
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "change to myproject-public-prod",
                        "Region": "us-west-1"
                    }
                }
            }
        }
    },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "change to myproject-public-prod",
                "region": "us-west-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by SardharaRahul** [comment]
@sdhuka After adding Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE)) we are geeting SinglePartUploadWorker failed with exception: aws.sdk.kotlin.services.s3.model.S3Exception: The provided token has expired.
                 	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt.throwPutObjectError(PutObjectOperationDeserializer.kt:66)
                 	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt.access$throwPutObjectError(PutObjectOperationDeserializer.kt:1)
                 	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt$throwPutObjectError$1.invokeSuspend(Unknown Source:13)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by MohammedHassouna** [comment]
> @MohammedHassouna Looking at the error, it seems like the token has expired. Could you try sign-out and re-signin to confirm that this is not an auth issue? If the issue persists, could you please add `Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))` as the first Amplify plugin and provide these logs when the error occurs?

We use guest AccessLevel

We just added these lines into MainApplication
```
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.configure(getApplicationContext());
```
and the amplifyconfiguration.json to the res folder, then upload the images using Amplify.Storage.uploadInputStream

After I added this code in the MainApplication the error is gone but I'm not sure if this solves the issue!
```
Amplify.Auth.fetchAuthSession(
                    new com.amplifyframework.core.Consumer<AuthSession>() {
                        @Override
                        public void accept(@NonNull AuthSession result) {
                            Log.i("AmplifyQuickstart", result.toString());
                        }
                    },
                    new com.amplifyframework.core.Consumer<AuthException>() {
                        @Override
                        public void accept(@NonNull AuthException error) {
                            Log.e("AmplifyQuickstart", error.toString());
                        }
                    }
            );

```
Should I use this option in the MainApplication to force refresh the session for the guest user?
`AuthFetchSessionOptions options = AuthFetchSessionOptions.builder().forceRefresh(true).build();
`

**Comment by div5yesh** [comment]
The expected behavior for guest access is that the `fetchAuthSession` should auto-refresh the AWS credentials when they expire. Do you see different behavior?
