### ISSUE TITLE
S3 upload issue in android with kotlin

### ISSUE THREAD

**Issue by AbrahamCardenesAcid** [aws-amplify/amplify-android#2472]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Storage

### Gradle script dependencies

<details>

    const val version = "2.2.2"
    const val auth = "com.amplifyframework:aws-auth-cognito:$version"
    const val api = "com.amplifyframework:aws-api:$version"
    const val coreKotlin = "com.amplifyframework:core-kotlin:$version"
    const val dataStorage = "com.amplifyframework:aws-datastore:$version"
    const val s3 = "com.amplifyframework:aws-storage-s3:$version"

</details>

### Environment information

<details>

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4.1 (Homebrew 17.0.4.1+1)
OS:           Mac OS X 13.3.1 x86_64

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/storage/upload/q/platform/android/#upload-inputstream

### Describe the bug

Trying to upload an image from internal storage turns into an error, sometimes works sometimes not.

val upload = Amplify.Storage.uploadFile(s3Key, file)
val key = upload.result().key.

Also I tried with `uploadInputStream` and is the same thing. 

### Code Snippet

```
viewModelScope.launch(dispatcher) {
            useCases.uploadImages(images).collectLatest { result ->
           ....
           }
        }
        
//rep        
images.forEach { pair ->
      Log.d("MyAmplifyApp", "SENDING IMAGES")
      pair.value.media.forEach { it ->
          val s3Key =
              "example/s3/path"
          val file = File(it.uriString)
          val upload = Amplify.Storage.uploadFile(s3Key, file)
          val result = upload.result()
          Log.d("MyAmplifyApp", "Successfully uploaded: ${result.key}")
      }
```

### Log output

<details>

```
StorageException{message=Something went wrong with your AWS S3 Storage upload input stream operation, cause=java.lang.Exception: java.io.IOException: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=JobImpl{Completed}@26f1238, recoverySuggestion=See attached exception for more information and suggestions}
                                                                                                    	at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadInputStreamOperation$UploadTransferListener.onError(AWSS3StorageUploadInputStreamOperation.kt:242)
                                                                                                    	at com.amplifyframework.storage.s3.transfer.TransferStatusUpdater.updateOnError$lambda-11$lambda-10(TransferStatusUpdater.kt:158)
                                                                                                    	at com.amplifyframework.storage.s3.transfer.TransferStatusUpdater.$r8$lambda$8_B91MaKBcZlKKI1XwJ3y4uxvSI(Unknown Source:0)
                                                                                                    	at com.amplifyframework.storage.s3.transfer.TransferStatusUpdater$$ExternalSyntheticLambda3.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: java.lang.Exception: java.io.IOException: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=JobImpl{Completed}@26f1238
                                                                                                    	at com.amplifyframework.storage.s3.transfer.worker.BaseTransferWorker.doWork$suspendImpl(BaseTransferWorker.kt:119)
                                                                                                    	at com.amplifyframework.storage.s3.transfer.worker.BaseTransferWorker$doWork$1.invokeSuspend(Unknown Source:18)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    Caused by: java.io.IOException: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=JobImpl{Completed}@26f1238
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.ByteChannelRequestBody.writeTo(ByteChannelRequestBody.kt:39)
                                                                                                    	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:62)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at com.android.tools.appinspection.network.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.kt:52)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-06-08 15:49:21.604 22120-22227 MyAmplifyApp            com.xxx.xxx.staging            E  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:533)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=JobImpl{Completed}@26f1238


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by AbrahamCardenesAcid** [comment]
Hi, the issue appears always when I use the AppInspection utility in AndroidStudio guys, took me a while to get it :(

**Comment by gpanshu** [comment]
Are you saying this is an issue that does not happen in production and only when you have appinspector on ? @AbrahamCardenesAcid

**Comment by gpanshu** [comment]
Closing this issue as this is classified as a debugger issue and not a production issue or related to the library. If you are still experiencing issues please feel free to reopen to create a new issue.
