### ISSUE TITLE
Error in saving Model model:[primaryKey =]

### ISSUE THREAD

**Issue by minaairsupport** [aws-amplify/amplify-android#2484]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
 implementation 'com.amplifyframework:core:2.8.5'
    implementation 'com.amplifyframework:aws-datastore:2.8.5'
    implementation 'com.amplifyframework:aws-auth-cognito:2.8.5'
    implementation 'com.amplifyframework:aws-api:2.8.5'
    implementation 'com.amplifyframework:core-kotlin:0.19.4'

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 8.0.2
------------------------------------------------------------

Build time:   2023-03-03 16:41:37 UTC
Revision:     7d6581558e226a580d91d399f7dfb9e3095c2b1d

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_221 (Oracle Corporation 25.221-b11)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Please include any relevant guides or documentation you're referencing

error in saving the model: User[primarykey =]

### Describe the bug

I'm working on an Android project that involves two separate apps, app, and app2. Each app has its own Amplify configuration with Auth and API functionalities. I'm experiencing a problem when trying to save user data in the app after signing up in app2 using android service.

The flow is as follows:

1- In the MainActivity of app, I call initAws and perform signup using Amplify.Auth.signUp, which works successfully.
2-Then, I navigate to a service in app2 to perform signup using Amplify.Auth.signUp, and that also works successfully.
3- in the same service I called  Amplify.API.mutate to save User2 after signup and sign in and that also works successfully
4- Finally, when I go back to app to save User data thats where its failed 
 

### Code Snippet

```java
// Put your code below this line.
// Amplify configuration in app
fun initAws(context: Context, onSuccess: () -> Unit) {
    try {
       val datastorePlugin = AWSDataStorePlugin.builder().run {
            dataStoreConfiguration(
                DataStoreConfiguration.builder()
                    .syncInterval(30,TimeUnit.MINUTES)
                    .syncMaxRecords(5000)
                    .syncPageSize(1_000)
                    .conflictHandler { c, onDecision ->
                        Log.d("datastore init", "conflict: $c")
                        onDecision.accept(DataStoreConflictHandler.ConflictResolutionDecision.retryLocal())
                    }
                    .errorHandler {
                        Log.d("datastore init", "exception: $it")
                        FirebaseCrashlytics.getInstance().log("Datastore exception: $it")
                        AWS.amplifyRetry()
                    }
                    .build()
            ).build()
        }
        Amplify.addPlugin(datastorePlugin)
        Amplify.addPlugin(AWSApiPlugin())
        Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))
        Amplify.addPlugin(AWSCognitoAuthPlugin())
        Amplify.configure(
            AmplifyConfiguration.fromConfigFile(context,R.raw.amplifyconfiguration),context
        )
        AWS.hub()
        onSuccess()
    } catch (e: AmplifyException) {
        // Exception handling code
    }
}
// Amplify configuration in app2
private fun configureAws(onSuccess: () -> Unit) {
    try {
        // API and Auth plugins added
        Amplify.configure(AmplifyConfiguration.fromConfigFile(this, R.raw.amplifyconfiguration_2), this)
        onSuccess()
    } catch (e: AmplifyException) {
        // Exception handling code
    }
}

// how amplify works in app2 
 Amplify.Auth.signUp(email, pw, options,
                let@ {signUpResult->
                    val id = signUpResult?.userId
                    if (id==null){
                        onFailure("Sign up error occurred")
                        return@let
                    }
                    Amplify.Auth.signIn(email,pw,options2, {
                        if (it.isSignedIn) {
                            val u = User2.builder()
                                .sid(sid)
                                .id(id)
                                .age(age)
                                .email(email)
                                .build()

                            Amplify.API.mutate(
                                ModelMutation.create(u),
                                {
                                    Log.d("SignUpService", "User2 Created")
                                    onSuccess(id)
                                }, { exc ->
                                    Log.d("SignUpService", "signup exception: $exc")
                                    exc.localizedMessage?.let { it1 -> onFailure(it1) } ?: onFailure("error occurred")
                                }
                                )

```

### Log output

<details>

```
// Put your logs below this line
2023-06-18 01:08:38.166 24300-24345 amplify:aw...AuthPlugin com.example.sleeptracker             V  StoreCredentials Sending event CompletedOperation
2023-06-18 01:08:38.168 24300-24358 amplify:aw...AuthPlugin com.example.sleeptracker             V  Credential Store State Change: Success(storedCredentials=UserAndIdentityPool(signedInData=SignedInData(userId=ce60ec7d-6240-480c-bb40-9d4fc4780bbe, username=ce60ec7d-6240-480c-bb40-9d4fc4780bbe, signedInDate=Sun Jun 18 01:08:37 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), identityId=eu-west-2:56a3f7cf-30c8-47fa-a18c-40359313bace, credentials=AWSCredentials(accessKeyId = ASIAQ***, secretAccessKey = 6A9ih***, sessionToken = IQoJb***, expiration = 1687046918)))
2023-06-18 01:08:38.170 24300-24345 amplify:aw...AuthPlugin com.example.sleeptracker             V  MoveToIdleState Starting execution
2023-06-18 01:08:38.170 24300-24345 amplify:aw...AuthPlugin com.example.sleeptracker             V  MoveToIdleState Sending event MoveToIdleState
2023-06-18 01:08:38.174 24300-24358 amplify:aw...AuthPlugin com.example.sleeptracker             V  Credential Store State Change: Idle(id=)
2023-06-18 01:08:38.176 24300-24345 amplify:aw...AuthPlugin com.example.sleeptracker             V  PersistCredentials Sending event ReceivedCachedCredentials
2023-06-18 01:08:38.178 24300-24349 amplify:aw...AuthPlugin com.example.sleeptracker             V  Auth State Change: Configured(authNState=SignedIn(signedInData=SignedInData(userId=ce60ec7d-6240-480c-bb40-9d4fc4780bbe, username=ce60ec7d-6240-480c-bb40-9d4fc4780bbe, signedInDate=Sun Jun 18 01:08:37 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), deviceMetadata=com.amplifyframework.statemachine.codegen.data.DeviceMetadata$Empty@5dc7439), authZState=SessionEstablished(amplifyCredential=UserAndIdentityPool(signedInData=SignedInData(userId=ce60ec7d-6240-480c-bb40-9d4fc4780bbe, username=ce60ec7d-6240-480c-bb40-9d4fc4780bbe, signedInDate=Sun Jun 18 01:08:37 GMT+02:00 2023, signInMethod=ApiBased(authType=USER_SRP_AUTH), cognitoUserPoolTokens=CognitoUserPoolTokens(idToken = eyJra***, accessToken = eyJra***, refreshToken = eyJjd***)), identityId=eu-west-2:56a3f7cf-30c8-47fa-a18c-40359313bace, credentials=AWSCredentials(accessKeyId = ASIAQ***, secretAccessKey = 6A9ih***, sessionToken = IQoJb***, expiration = 1687046918))))
2023-06-18 01:08:38.179 24300-24345 SignUpActivity          com.example.sleeptracker             D  AppOne_SignIn_Successfully
2023-06-18 01:08:38.180 24300-24345 SignUpActivity          com.example.sleeptracker             D  AppOne_User_Data_User {id=ce60ec7d-6240-480c-bb40-9d4fc4780bbe, sid=77b6e616-b0a9-4b4d-aed9-ff16a18b0546, studyId=eeee0000, offDay=com.amplifyframework.datastore.generated.model.DayGroup@a4b09f97, workday=com.amplifyframework.datastore.generated.model.DayGroup@3c3cffa2, createdAt=null, updatedAt=null}
2023-06-18 01:08:38.181 24300-24345 amplify:aws-datastore   com.example.sleeptracker             I  Orchestrator lock acquired.
2023-06-18 01:08:38.184 24300-24375 amplify:aws-datastore   com.example.sleeptracker             I  DataStore plugin initialized.
2023-06-18 01:08:38.187 24300-24375 amplify:aws-datastore   com.example.sleeptracker             I  Orchestrator transitioning from STOPPED to SYNC_VIA_API
2023-06-18 01:08:38.187 24300-24375 amplify:aws-datastore   com.example.sleeptracker             I  Starting to observe local storage changes.
2023-06-18 01:08:38.194 24300-24505 amplify:aws-datastore   com.example.sleeptracker             V  SQLCommandProcessor rawQuery in 0 ms inTransaction: false SQL: SELECT `PersistentRecord`.`id` AS `PersistentRecord_id`, `PersistentRecord`.`containedModelClassName` AS `PersistentRecord_containedModelClassName`, `PersistentRecord`.`containedModelId` AS `PersistentRecord_containedModelId`, `PersistentRecord`.`serializedMutationData` AS `PersistentRecord_serializedMutationData` FROM `PersistentRecord`;
2023-06-18 01:08:38.194 24300-24505 amplify:aws-datastore   com.example.sleeptracker             D  Querying item for: PersistentRecord
2023-06-18 01:08:38.211 24300-24505 amplify:aws-datastore   com.example.sleeptracker             I  Now observing local storage. Local changes will be enqueued to mutation outbox.
2023-06-18 01:08:38.211 24300-24505 amplify:aws-datastore   com.example.sleeptracker             I  Setting currentState to LOCAL_ONLY
2023-06-18 01:08:38.218 24300-24375 amplify:aws-datastore   com.example.sleeptracker             I  Setting currentState to SYNC_VIA_API
2023-06-18 01:08:38.219 24300-24375 amplify:aws-datastore   com.example.sleeptracker             I  Orchestrator lock released.
2023-06-18 01:08:38.219 24300-24364 amplify:aws-datastore   com.example.sleeptracker             I  Starting API synchronization mode.
2023-06-18 01:08:38.233 24300-24364 amplify:aws-datastore   com.example.sleeptracker             I  Starting processing subscription events.
2023-06-18 01:08:38.248 24300-24508 SignUpActivity          com.example.sleeptracker             E  AppOne_User_failed: Error in saving the model: User[primaryKey =ce60ec7d-6240-480c-bb40-9d4fc4780bbe]
2023-06-18 01:08:38.249 24300-24508 SignUpActivity          com.example.sleeptracker             E  Stack trace: java.lang.Throwable
                                                                                                    	at com.example.sleeptracker.ui.signin.SignUpActivity$createUser$1$1.invoke(SignUpActivity.kt:223)
                                                                                                    	at com.example.sleeptracker.ui.signin.SignUpActivity$createUser$1$1.invoke(SignUpActivity.kt:212)
                                                                                                    	at com.example.sleeptracker.aws.AWS.save$lambda$8(AWS.kt:62)
                                                                                                    	at com.example.sleeptracker.aws.AWS.$r8$lambda$h7IU5Qfqj_AYXHe30lHhz_KwQkg(Unknown Source:0)
                                                                                                    	at com.example.sleeptracker.aws.AWS$$ExternalSyntheticLambda11.accept(Unknown Source:4)
                                                                                                    	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$com-amplifyframework-datastore-storage-sqlite-SQLiteStorageAdapter(SQLiteStorageAdapter.java:386)
                                                                                                    	at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter$$ExternalSyntheticLambda5.run(Unknown Source:12)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)



```

</details>

### amplifyconfiguration.json

{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "appone": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://xxxx-xxxx.appsync-api.eu-west-2.amazonaws.com/graphql",
                    "region": "eu-west-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS",
                    "apiKey": "xxxx-xxxx"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://xxxx-xxxx.appsync-api.eu-west-2.amazonaws.com/graphql",
                        "Region": "eu-west-2",
                        "AuthMode": "AMAZON_COGNITO_USER_POOLS",
                        "ClientDatabasePrefix": "appone_AMAZON_COGNITO_USER_POOLS"
                    },
                    "appone_AWS_IAM": {
                        "ApiUrl": "https://xxxx-xxxx.appsync-api.eu-west-2.amazonaws.com/graphql",
                        "Region": "eu-west-2",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "appone_AWS_IAM"
                    },
                    "appone_API_KEY": {
                        "ApiUrl": "https://xxxx-xxxxappsync-api.eu-west-2.amazonaws.com/graphql",
                        "Region": "eu-west-2",
                        "AuthMode": "API_KEY",
                        "ApiKey": "xxxx-xxxx",
                        "ClientDatabasePrefix": "appone_API_KEY"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "eu-west-2:53753264-xxxx-xxxx",
                            "Region": "eu-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-west-2_2xxxx-xxxx",
                        "AppClientId": "7v88xxxx-xxxx",
                        "Region": "eu-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": []
                        },
                        "signupAttributes": [
                            "EMAIL"
                        ],
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line
type Session @model @auth(rules: [{allow: private}]) {
  id: ID!
  start: String!
  end: String!
  trackerperiodID: ID! @index(name: "byTrackerPeriod")
}

type DeviceState @model @auth(rules: [{allow: private}]) {
  id: ID!
  Time: String!
  State: String!
  trackerperiodID: ID! @index(name: "byTrackerPeriod")
}

type SubPeriod @model @auth(rules: [{allow: private}]) {
  id: ID!
  Range: String!
  MovementCount: Int!
  trackerperiodID: ID! @index(name: "byTrackerPeriod")
}

type TrackerPeriod @model @auth(rules: [{allow: owner}]) {
  id: ID!
  WakeUpTime: String!
  SleepTime: String!
  AverageMovementCount: String
  SleepDuration: String
  DurationInNumbers: String
  DisturbancesCount: String
  TotalMovements: Int
  AccelerometerLastReading: Float
  createdAt: AWSDateTime!
  userID: ID @index(name: "byUser")
  Sessions: [Session] @hasMany(indexName: "byTrackerPeriod", fields: ["id"])
  DeviceStates: [DeviceState] @hasMany(indexName: "byTrackerPeriod", fields: ["id"])
  SubPeriods: [SubPeriod] @hasMany(indexName: "byTrackerPeriod", fields: ["id"])
  ActualSleepTime: String
  ActualWakeUpTime: String
}

type DayGroup {
  SleepTime: String!
  WakeUpTime: String!
  Days: [String]!
}

type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  sid: String!
  studyId: String!
  offDay: DayGroup!
  workday: DayGroup!
  tracker: [TrackerPeriod] @hasMany(indexName: "byUser", fields: ["id"])
}

```

</details>

### Additional information and screenshots

when I debugging I found in SQLiteStorageAdapter modelSchema returned with null as schemaRegistry dont contain User but its contain only User2 and thats cause that crash 
error in saving the model: User[primarykey =]

Source 
https://github.com/aws-amplify/amplify-android/blob/main/aws-datastore/src/main/java/com/amplifyframework/datastore/storage/sqlite/SQLiteStorageAdapter.java#L330

```
  try {
 final ModelSchema modelSchema = schemaRegistry.getModelSchemaForModelClass(item.getModelName());
 ......
catch (Exception someOtherTypeOfException) {
                String modelToString = item.getModelName() + "[primaryKey =" + item.getPrimaryKeyString() + "]";
                DataStoreException dataStoreException = new DataStoreException(
                    "Error in saving the model: " + modelToString,
                    someOtherTypeOfException, "See attached exception for details."
                );
                onError.accept(dataStoreException);
            }
```

for the whole log 
https://gist.github.com/minaairsupport/c9c6772b59116d9901ecbefc35603e43

**Comment by minaairsupport** [comment]
I figure this out after wasting more than 3 weeks 

if you have more than Amplify connect to your app you should make couple stuff

1- when using Amplify.configure dont make it with Application Context
  `Amplify.configure(AmplifyConfiguration.fromConfigFile(this, R.raw.amplifyconfiguration_2), this)`
2-  use a different file name for configuration example amplifyconfiguration_2 
3- AmplifyModelProvider thats the file which responsible of create the sqlite database locally 
  you must change its name example AmplifyModelProvider2
  
  happy coding
