### ISSUE TITLE
Android runtime Crash while calling Amplify.configure(getApplicationContext())

### ISSUE THREAD

**Issue by mohamedtawfik** [aws-amplify/amplify-android#2489]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Analytics

### Gradle script dependencies

<details>

implementation 'com.amplifyframework:aws-analytics-pinpoint:2.8.5'
implementation 'com.amplifyframework:aws-auth-cognito:2.8.5'

</details>

### Environment information

<details>

gradle version 7.4.2

</details>

### Describe the bug

When trying to initialize Amplify SDK in Application class it successfully build but when app open it crashes

**Initialization code** // ----------------------------------
Amplify.addPlugin(new AWSCognitoAuthPlugin());
Amplify.addPlugin(new AWSPinpointAnalyticsPlugin());
Amplify.configure(getApplicationContext());
// ------------------------------------------------------

**my app OkHttp version** is 4.10.0

**Crash**

FATAL EXCEPTION: DefaultDispatcher-worker-2
                 Process: com.example, PID: 29600
                 java.lang.NoSuchMethodError: No virtual method tag(Lkotlin/reflect/KClass;Ljava/lang/Object;)Lokhttp3/Request$Builder; in class Lokhttp3/Request$Builder; or its super classes (declaration of 'okhttp3.Request$Builder' appears in /data/app/~~37N_oyswBOuEP9uLqPoRoQ==/com.example-i1gEMxa3P0W6wQZZ1rY4ig==/base.apk!classes22.dex)
                 	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpUtilsKt.toOkHttpRequest(OkHttpUtils.kt:46)
                 	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.roundTrip(OkHttpEngine.kt:40)
                 	at aws.smithy.kotlin.runtime.http.engine.internal.ManagedHttpClientEngine.roundTrip(Unknown Source:2)
                 	at aws.smithy.kotlin.runtime.http.SdkHttpClient$executeWithCallContext$2.invokeSuspend(SdkHttpClient.kt:39)
                 	at aws.smithy.kotlin.runtime.http.SdkHttpClient$executeWithCallContext$2.invoke(Unknown Source:8)
                 	at aws.smithy.kotlin.runtime.http.SdkHttpClient$executeWithCallContext$2.invoke(Unknown Source:4)
                 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                 	at aws.smithy.kotlin.runtime.http.SdkHttpClient.executeWithCallContext(SdkHttpClient.kt:38)
                 	at aws.smithy.kotlin.runtime.http.SdkHttpClient.call(SdkHttpClient.kt:31)
                 	at aws.smithy.kotlin.runtime.http.SdkHttpClient.call(SdkHttpClient.kt:26)
                 	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt.httpTraceMiddleware(SdkOperationExecution.kt:317)
                 	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt.access$httpTraceMiddleware(SdkOperationExecution.kt:1)
                 	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$1.invoke(SdkOperationExecution.kt:153)
                 	at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$1.invoke(SdkOperationExecution.kt:153)
                 	at aws.smithy.kotlin.runtime.io.middleware.MiddlewareLambda.handle(Middleware.kt:30)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.http.operation.InterceptorTransmitMiddleware.handle(SdkOperationExecution.kt:340)
                 	at aws.smithy.kotlin.runtime.http.operation.InterceptorTransmitMiddleware.handle(SdkOperationExecution.kt:333)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.http.operation.HttpCallMiddleware.handle(SdkOperationExecution.kt:297)
                 	at aws.smithy.kotlin.runtime.http.operation.HttpCallMiddleware.handle(SdkOperationExecution.kt:288)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:64)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:265)
                 	at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:257)
                 	at aws.smithy.kotlin.runtime.http.operation.HttpAuthHandler.call(SdkOperationExecution.kt:253)
                 	at aws.smithy.kotlin.runtime.http.operation.HttpAuthHandler.call(SdkOperationExecution.kt:241)
                 	at aws.sdk.kotlin.runtime.http.middleware.AwsRetryHeaderMiddleware.handle(AwsRetryHeaderMiddleware.kt:39)
                 	at aws.sdk.kotlin.runtime.http.middleware.AwsRetryHeaderMiddleware.handle(AwsRetryHeaderMiddleware.kt:26)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:64)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware.tryAttempt-BWLJW6A(RetryMiddleware.kt:79)
                 	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware.access$tryAttempt-BWLJW6A(RetryMiddleware.kt:32)
16:01:21.128  E  	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware$handle$result$outcome$1$invokeSuspend$$inlined$withChildTraceSpan$1.invokeSuspend(CoroutineContextUtils.kt:238)
                 	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware$handle$result$outcome$1$invokeSuspend$$inlined$withChildTraceSpan$1.invoke(Unknown Source:8)
                 	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware$handle$result$outcome$1$invokeSuspend$$inlined$withChildTraceSpan$1.invoke(Unknown Source:4)
                 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                 	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware$handle$result$outcome$1.invokeSuspend(RetryMiddleware.kt:117)
                 	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware$handle$result$outcome$1.invoke(Unknown Source:8)
                 	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware$handle$result$outcome$1.invoke(Unknown Source:2)
                 	at aws.smithy.kotlin.runtime.retries.StandardRetryStrategy.doTryLoop(StandardRetryStrategy.kt:51)
                 	at aws.smithy.kotlin.runtime.retries.StandardRetryStrategy.retry(StandardRetryStrategy.kt:32)
                 	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware.handle(RetryMiddleware.kt:47)
                 	at aws.smithy.kotlin.runtime.http.middleware.RetryMiddleware.handle(RetryMiddleware.kt:32)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.http.operation.MutateHandler.call(SdkOperationExecution.kt:238)
                 	at aws.smithy.kotlin.runtime.http.operation.MutateHandler.call(SdkOperationExecution.kt:235)
                 	at aws.smithy.kotlin.runtime.io.middleware.ModifyRequestMiddleware.handle(ModifyRequest.kt:24)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.io.middleware.ModifyRequestMiddleware.handle(ModifyRequest.kt:24)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.io.middleware.ModifyRequestMiddleware.handle(ModifyRequest.kt:24)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:64)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.http.operation.SerializeHandler.call(SdkOperationExecution.kt:231)
                 	at aws.smithy.kotlin.runtime.http.operation.SerializeHandler.call(SdkOperationExecution.kt:209)
                 	at aws.smithy.kotlin.runtime.http.operation.InitializeHandler.call(SdkOperationExecution.kt:206)
                 	at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:60)
                 	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                 	at aws.smithy.kotlin.runtime.http.operation.OperationHandler.call(SdkOperationExecution.kt:190)
                 	at aws.smithy.kotlin.runtime.http.operation.OperationHandler.call(SdkOperationExecution.kt:183)
                 	at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.execute(SdkHttpOperation.kt:98)
                 	at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.roundTrip(SdkHttpOperation.kt:81)
                 	at aws.sdk.kotlin.services.cognitoidentity.DefaultCognitoIdentityClient$getId$$inlined$withRootTraceSpan$1.invokeSuspend(CoroutineContextUtils.kt:228)
                 	at aws.sdk.kotlin.services.cognitoidentity.DefaultCognitoIdentityClient$getId$$inlined$withRootTraceSpan$1.invoke(Unknown Source:8)
                 	at aws.sdk.kotlin.services.cognitoidentity.DefaultCognitoIdentityClient$getId$$inlined$withRootTraceSpan$1.invoke(Unknown Source:4)
                 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
16:01:21.129  E  	at aws.sdk.kotlin.services.cognitoidentity.DefaultCognitoIdentityClient.getId(DefaultCognitoIdentityClient.kt:1131)
                 	at com.amplifyframework.auth.cognito.actions.FetchAuthSessionCognitoActions$fetchIdentityAction$$inlined$invoke$1.execute(Action.kt:74)
                 	at com.amplifyframework.statemachine.ConcurrentEffectExecutor$execute$1$1.invokeSuspend(ConcurrentEffectExecutor.kt:26)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c8fe538, Dispatchers.Default]

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by sammy-f-s** [comment]
Hi, 

I am facing a similar crash using version 2.8.5 of this library. For desugaring I have the following line: 
`coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'`.

I simply followed the instructions in the docs to add auth to my app. First, it only happened when trying to sign up a user. Then it also occurred when trying to initialize AWS Amplify. 

Code for sigining up a user 
=======
`val options = AuthSignUpOptions.builder()
                    .userAttribute(AuthUserAttributeKey.email(), "my@email.com")
                    .build()
            Amplify.Auth.signUp("username", "Password123", options,
                    { Log.i("AuthQuickStart", "Sign up succeeded: $it") },
                    { Log.e ("AuthQuickStart", "Sign up failed", it) }
            )`

Code for initializing Amplify SDK
=======
`Amplify.addPlugin(AWSCognitoAuthPlugin())
        Amplify.configure(applicationContext)`

Current Kotlin Plugin version: 222-1.8.20-release-AS3739.54

This is the crash log:

`FATAL EXCEPTION: DefaultDispatcher-worker-3
                                                                                                    Process: de.combike, PID: 9892
                                                                                                    java.lang.NoSuchMethodError: No virtual method markNow-z9LOYto()J in class Lkotlin/time/TimeSource$Monotonic; or its super classes (declaration of 'kotlin.time.TimeSource$Monotonic' appears in /data/app/~~ez-Kn6ncKpE64K7j7RP5tA==/de.combike-QRwUMVHpiIgl1givvwfBVQ==/base.apk!classes20.dex)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.SerializeHandler.call(SdkOperationExecution.kt:356)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.SerializeHandler.call(SdkOperationExecution.kt:209)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.InitializeHandler.call(SdkOperationExecution.kt:206)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.Phase.handle(Phase.kt:60)
                                                                                                    	at aws.smithy.kotlin.runtime.io.middleware.DecoratedHandler.call(Middleware.kt:40)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.OperationHandler.call(SdkOperationExecution.kt:190)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.OperationHandler.call(SdkOperationExecution.kt:183)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.execute(SdkHttpOperation.kt:98)
                                                                                                    	at aws.smithy.kotlin.runtime.http.operation.SdkHttpOperationKt.roundTrip(SdkHttpOperation.kt:81)
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.DefaultCognitoIdentityClient$getId$$inlined$withRootTraceSpan$1.invokeSuspend(CoroutineContextUtils.kt:228)
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.DefaultCognitoIdentityClient$getId$$inlined$withRootTraceSpan$1.invoke(Unknown Source:8)
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.DefaultCognitoIdentityClient$getId$$inlined$withRootTraceSpan$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
                                                                                                    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.DefaultCognitoIdentityClient.getId(DefaultCognitoIdentityClient.kt:1131)
                                                                                                    	at com.amplifyframework.auth.cognito.actions.FetchAuthSessionCognitoActions$fetchIdentityAction$$inlined$invoke$1.execute(Action.kt:74)
                                                                                                    	at com.amplifyframework.statemachine.ConcurrentEffectExecutor$execute$1$1.invokeSuspend(ConcurrentEffectExecutor.kt:26)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e7a083a, Dispatchers.Default]`

**Comment by gpanshu** [comment]
@mohamedtawfik and @sammy-f-s can you please paste the entire dependencies block when it comes to amplify libraries? I suspect you are missing implementation 'com.amplifyframework:core:2.8.5'. This is mentioned [here](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android/#2-install-amplify-libraries)

**Comment by gpanshu** [comment]
Hi @mohamedtawfik and @sammy-f-s I tried to reproduce the error and I found the root cause. 

If you force resolve your okhttp version it will crash the app as the kotlin sdk which we depend on uses OKhttp `5.0.0-alpha.11`. 

If you have a line in your gradle code like ` force("com.squareup.okhttp3:okhttp:4.10.0")`  please remove and try again

**Comment by mohamedtawfik** [comment]
> Hi @mohamedtawfik and @sammy-f-s I tried to reproduce the error and I found the root cause.
> 
> If you force resolve your okhttp version it will crash the app as the kotlin sdk which we depend on uses OKhttp `5.0.0-alpha.11`.
> 
> If you have a line in your gradle code like ` force("com.squareup.okhttp3:okhttp:4.10.0")` please remove and try again

solved by adding

configurations.all {
    resolutionStrategy.force 'com.squareup.okhttp3:okhttp:5.0.0-alpha.11'
}

BUT I don't want to depend on alpha version as it is not stable yet. Any other solutions ?

**Comment by mohamedtawfik** [comment]
@gpanshu any suggestions please ?

**Comment by tylerjroach** [comment]
@mohamedtawfik 

From the OkHttp Changelog:

> The alpha releases in the 5.0.0 series have production-quality code and an unstable API. We expect to make changes to the APIs introduced in 5.0.0-alpha.X. These releases are safe for production use and 'alpha' strictly signals that we're still experimenting with some new APIs. If you're eager for the fixes or features below, please upgrade.

I hope this helps provide a bit of confidence in OkHttp v5 alpha builds. At this time, we have a dependency on a library that has updated to v5 alpha. We do not have any workarounds around this.

**Comment by mohamedtawfik** [comment]
OK thanks a lot.

**Comment by mohamedtawfik** [comment]
**There is a crash on Android 7.1.1 when calling Amplify.configure(getApplicationContext());**


 FATAL EXCEPTION: main
                                                                                                    Process: com.example, PID: 18460
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngineKt.buildClient(OkHttpEngine.kt:76)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngineKt.access$buildClient(OkHttpEngine.kt:1)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:35)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:27)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineJVMKt.newDefaultHttpEngine(DefaultHttpEngineJVM.kt:16)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine(DefaultHttpEngine.kt:12)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine$default(DefaultHttpEngine.kt:11)
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.CognitoIdentityClient$Config.<init>(CognitoIdentityClient.kt:112)
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.CognitoIdentityClient$Config.<init>(CognitoIdentityClient.kt)
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.CognitoIdentityClient$Config$Builder.build(CognitoIdentityClient.kt:232)
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.CognitoIdentityClient$Config$Builder.build(CognitoIdentityClient.kt:145)
                                                                                                    	at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:20)
                                                                                                    	at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:13)
                                                                                                    	at aws.smithy.kotlin.runtime.client.SdkClientFactory$DefaultImpls.invoke(SdkClientFactory.kt:32)
                                                                                                    	at aws.sdk.kotlin.runtime.config.AbstractAwsSdkClientFactory.invoke(AbstractAwsSdkClientFactory.kt:23)
                                                                                                    	at com.amplifyframework.auth.cognito.AWSCognitoAuthService$Companion.fromConfiguration$aws_auth_cognito_release(AWSCognitoAuthService.kt:53)
                                                                                                    	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.kt:129)
                                                                                                    	at com.amplifyframework.core.category.Category.configure(Category.java:91)
                                                                                                    	at com.amplifyframework.core.Amplify.configure(Amplify.java:159)
                                                                                                    	at com.amplifyframework.core.Amplify.configure(Amplify.java:129)
                                                                                                    	at com.example.MyApplication.initAmazonAnalytics(MyApplication.java:255)
                                                                                                    	at com.example.MyApplication.onCreate(MyApplication.java:152)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5662)
                                                                                                    	at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loop(Looper.java:203)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6410)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.example-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example-2/lib/arm64, /data/app/com.example-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngineKt.buildClient(OkHttpEngine.kt:76) 
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngineKt.access$buildClient(OkHttpEngine.kt:1) 
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:35) 
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:27) 
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineJVMKt.newDefaultHttpEngine(DefaultHttpEngineJVM.kt:16) 
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine(DefaultHttpEngine.kt:12) 
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine$default(DefaultHttpEngine.kt:11) 
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.CognitoIdentityClient$Config.<init>(CognitoIdentityClient.kt:112) 
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.CognitoIdentityClient$Config.<init>(CognitoIdentityClient.kt) 
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.CognitoIdentityClient$Config$Builder.build(CognitoIdentityClient.kt:232) 
                                                                                                    	at aws.sdk.kotlin.services.cognitoidentity.CognitoIdentityClient$Config$Builder.build(CognitoIdentityClient.kt:145) 
                                                                                                    	at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:20) 
                                                                                                    	at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:13) 
                                                                                                    	at aws.smithy.kotlin.runtime.client.SdkClientFactory$DefaultImpls.invoke(SdkClientFactory.kt:32) 
                                                                                                    	at aws.sdk.kotlin.runtime.config.AbstractAwsSdkClientFactory.invoke(AbstractAwsSdkClientFactory.kt:23) 
                                                                                                    	at com.amplifyframework.auth.cognito.AWSCognitoAuthService$Companion.fromConfiguration$aws_auth_cognito_release(AWSCognitoAuthService.kt:53) 
                                                                                                    	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.kt:129) 
                                                                                                    	at com.amplifyframework.core.category.Category.configure(Category.java:91) 
                                                                                                    	at com.amplifyframework.core.Amplify.configure(Amplify.java:159) 
                                                                                                    	at com.amplifyframework.core.Amplify.configure(Amplify.java:129) 
                                                                                                    	at com.example.MyApplication.initAmazonAnalytics(MyApplication.java:255) 
                                                                                                    	at com.example.MyApplication.onCreate(MyApplication.java:152) 
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5662) 
                                                                                                    	at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                                                    	at android.os.Looper.loop(Looper.java:203) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6410) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Comment by gpanshu** [comment]
Hi @mohamedtawfik can you verify you have `coreLibraryDesugaringEnabled ` enabled and added like the [documentation](https://docs.amplify.aws/lib/project-setup/create-application/q/platform/android/#2-install-amplify-libraries) shows ?

It should look something like this : 

`
android {
    compileOptions {
        // Support for Java 8 features
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
...
    // Support for Java 8 features
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}
`

**Comment by mohamedtawfik** [comment]
> coreLibraryDesugaring

crash fixed by adding 
coreLibraryDesugaringEnabled true
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'


**BUT on runtime I got this while the timezone and time are automatic on device. what is this error means and how to fix it ?**

PinpointException occurred during endpoint update:
                                                                                                    aws.sdk.kotlin.services.pinpoint.model.PinpointException: Signature not yet current: 20230724T094820Z is still later than 20230724T085205Z (20230724T084705Z + 5 min.)
                                                                                                    	at aws.sdk.kotlin.services.pinpoint.transform.UpdateEndpointOperationDeserializerKt.throwUpdateEndpointError(UpdateEndpointOperationDeserializer.kt:55)
                                                                                                    	at aws.sdk.kotlin.services.pinpoint.transform.UpdateEndpointOperationDeserializerKt.access$throwUpdateEndpointError(UpdateEndpointOperationDeserializer.kt:1)
                                                                                                    	at aws.sdk.kotlin.services.pinpoint.transform.UpdateEndpointOperationDeserializerKt$throwUpdateEndpointError$1.invokeSuspend(UpdateEndpointOperationDeserializer.kt)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

Failed to submit events aws.sdk.kotlin.services.pinpoint.model.PinpointException: Signature not yet current: 20230724T094850Z is still later than 20230724T085233Z (20230724T084733Z + 5 min.)

**Comment by mohamedtawfik** [comment]
Another question,
I use these dependencies only

implementation 'com.amplifyframework:aws-analytics-pinpoint:2.8.5'
implementation 'com.amplifyframework:aws-auth-cognito:2.8.5'

**should I add implementation 'com.amplifyframework:core:2.8.7' or not necessary ?**
