### ISSUE TITLE
No interface method signOut

### ISSUE THREAD

**Issue by tho9x** [aws-amplify/amplify-android#2509]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
        //amplify
        amplify             : "2.9.0",
        desugaring          : "1.1.5",
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18 (Oracle Corporation 18+36-2087)
OS:           Mac OS X 11.6.5 x86_64

```

</details>

### Describe the bug

throw an exception when calling the `signOut` method. This bug did not occur on the amplify version `1.37.3`

### Code Snippet

```
try {
    Amplify.Auth.signOut(AuthSignOutOptions.builder()
                        .globalSignOut(true)
                        .build())
} catch (e: Exception) {
                Timber.e(e)
}
```

### Log output

<details>

```
java.lang.NoSuchMethodError: No interface method signOut(Lcom/amplifyframework/auth/options/AuthSignOutOptions;Lcom/amplifyframework/core/Action;Lcom/amplifyframework/core/Consumer;)V in class Lcom/amplifyframework/auth/AuthCategoryBehavior; or its super classes (declaration of 'com.amplifyframework.auth.AuthCategoryBehavior' appears in /data/app/~~e6SdJvPsqpl5NBFctajD9g==/com.app.example-G1y_yjQThkO0nF3iCDL08A==/base.apk!classes34.dex)
	at com.amplifyframework.kotlin.auth.KotlinAuthFacade.signOut(KotlinAuthFacade.kt:317)
	at com.app.example.data.repository.user.DataRepository$logout$1.invokeSuspend(DataRepository.kt:589)
	at com.app.example..data.repository.user.UserDataRepository2$logout$1.invoke(Unknown Source:8)
	at com.app.example.data.repository.user.UserDataRepository2$logout$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

</details>

**Comment by tho9x** [comment]
@gpanshu here you are
```
amplify             : "2.9.0",
desugaring          : "1.1.5",
```

```
desugaring          : "com.android.tools:desugar_jdk_libs:${_libVersions.desugaring}",
amplifyCore         : "com.amplifyframework:core:${_libVersions.amplify}",
amplifyApi          : "com.amplifyframework:aws-api:${_libVersions.amplify}",
amplifyCognito      : "com.amplifyframework:aws-auth-cognito:${_libVersions.amplify}",
amplifyS3           : "com.amplifyframework:aws-storage-s3:${_libVersions.amplify}",
amplifyDataStore    : "com.amplifyframework:aws-datastore:${_libVersions.amplify}"
```

**Comment by gpanshu** [comment]
@tho9x those look fine to me. Can you also attach the snippet when you are adding the plugin in your application class?

This is how mine looks like : 

`Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.configure(applicationContext)`

**Comment by tho9x** [comment]
@gpanshu this is my amplify configuration
```
private fun configureAmplify() {
        try {
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.addPlugin(AWSDataStorePlugin())
            Amplify.addPlugin(AWSS3StoragePlugin())
            Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))
            val config = AmplifyConfiguration.builder(applicationContext)
                .build()
            Amplify.configure(config,applicationContext)
        } catch (ex: AmplifyException) {
            Log.e("Amplify", ex.message ?: "No message provided")
        }
    }
```

**Comment by gpanshu** [comment]
@tho9x a few questions: 

1. Is this configureAmplify() being called in the application class?

2. Can you also put the logging plugin in the very beginning before the auth plugin?

3. Just after Amplify.configure can you add ` Log.i("MyAmplifyApp", "Initialized Amplify")` and see if you see this in logs before your signout is called.

**Comment by mindgrub-medwards** [comment]
I am experiencing the same issue. This is initialized using Application context. I have no problems initializing amplify and have successfully used other commands to create, login, and verify auth. 

Dependencies

    def amplify_version = "2.8.7"
    implementation "com.amplifyframework:aws-api:$amplify_version"
    implementation "com.amplifyframework:aws-datastore:$amplify_version"
    implementation "com.amplifyframework:aws-auth-cognito:2.11.1"
    implementation "com.amplifyframework:core-kotlin:0.19.2"
    implementation 'com.amplifyframework:aws-storage-s3:1.35.4'

Snippet

    init {
        try {
            if (BuildConfig.DEBUG) {
                Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))
            }
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.addPlugin(AWSDataStorePlugin())
            Amplify.configure(context)
            Log.i(TAG, "Initialized Amplify")
        } catch (failure: AmplifyException) {
            Log.e(TAG, "Unable to initialize Amplify", failure.cause)
        }
    }

    override suspend fun logOut() = callbackFlow {
        val result = auth.signOut()
        trySend(result)
        close()
    }


Stacktrace

FATAL EXCEPTION: main
                                                            Process: com.hybridcalisthenics.app.develop, PID: 4775
                                                            java.lang.NoSuchMethodError: No interface method signOut(Lcom/amplifyframework/auth/options/AuthSignOutOptions;Lcom/amplifyframework/core/Action;Lcom/amplifyframework/core/Consumer;)V in class Lcom/amplifyframework/auth/AuthCategoryBehavior; or its super classes (declaration of 'com.amplifyframework.auth.AuthCategoryBehavior' appears in /data/app/~~rncwiq2jWryCYtOEIQUS7Q==/com.hybridcalisthenics.app.develop-8KAU2i3hq64CXLebcA_VZQ==/base.apk!classes17.dex)
                                                            	at com.amplifyframework.kotlin.auth.KotlinAuthFacade.signOut(KotlinAuthFacade.kt:317)
                                                            	at com.amplifyframework.kotlin.auth.Auth$DefaultImpls.signOut$default(Auth.kt:317)
                                                            	at com.hybridcalisthenics.app.data.amplify.AmplifyService$logOut$2.invokeSuspend(AmplifyService.kt:85)
                                                            	at com.hybridcalisthenics.app.data.amplify.AmplifyService$logOut$2.invoke(Unknown Source:12)
                                                            	at com.hybridcalisthenics.app.data.amplify.AmplifyService$logOut$2.invoke(Unknown Source:10)
                                                            	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:322)
                                                            	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Unknown Source:4)
                                                            	at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:336)
                                                            	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
                                                            	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                            	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                            	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
                                                            	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:376)
                                                            	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                            	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                            	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                            	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                            	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                            	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                            	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                            	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                            	at com.hybridcalisthenics.app.ui.app.home.HomeScreenViewModel.logout(HomeScreenViewModel.kt:34)
                                                            	at com.hybridcalisthenics.app.ui.app.home.HomeScreenKt$HomeScreen$1$1.invoke(HomeScreen.kt:66)
                                                            	at com.hybridcalisthenics.app.ui.app.home.HomeScreenKt$HomeScreen$1$1.invoke(HomeScreen.kt:66)
                                                            	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
                                                            	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
                                                            	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:234)
                                                            	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                            	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
                                                            	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
                                                            	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
                                                            	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
                                                            	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
                                                            	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
                                                            	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:566)
                                                            	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:456)
                                                            	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:469)


Logs - The logger doesn't generate anything before the exception throws but here is the successful init

23:55:16.770 AmplifyService     com...enics.app.develop  I  Initialized Amplify
23:55:16.796 amplify:...tastore                          I  DataStore plugin initialized.

**Comment by mindgrub-medwards** [comment]
Apologies. auth is just a local getter...

    private val auth get() = Amplify.Auth

**Comment by tylerjroach** [comment]
@mindgrub-medwards 

The issue is that you are mixing dependency versions of Amplify.

```def amplify_version = "2.8.7"
implementation "com.amplifyframework:aws-api:$amplify_version"
implementation "com.amplifyframework:aws-datastore:$amplify_version"
implementation "com.amplifyframework:aws-auth-cognito:2.11.1"
implementation "com.amplifyframework:core-kotlin:0.19.2"
implementation 'com.amplifyframework:aws-storage-s3:1.35.4'
```

Every dependency here should be using amplify_verison which happens to be 2.8.7. The `signout` method is not being found because the definitions differ between v1 of Amplify (which 0.19.2 of core Kotlin is using) and v2 of Amplify.

Amplify v1 and v2 cannot be mixed. It is also expected that all amplify plugins are using the same versions.

**Comment by tylerjroach** [comment]
@tho9x You may have the same issue. I see that you listed your dependencies, however, I don't see the core-kotlin dependency listed and it appears that you are using the coroutine methods. Is it possible this dependency is added elsewhere and was left using the v1 versions? In v2, core-kotlin matches the Amplify release version: ex: 2.9.0 in your case.

**Comment by mindgrub-medwards** [comment]
@tylerjroach That did solve my issue. Thank you.

**Comment by tho9x** [comment]
It has worked flawlessly after changing the core-kotlin version to `2.11.1`. But after signed-out, I cannot sign in again with `Amplify.Auth.signInWithSocialWebUI`, no logs are printed

**Comment by tho9x** [comment]
depencies: 
```
  desugaring          : "com.android.tools:desugar_jdk_libs:${_libVersions.desugaring}",
  amplifyCore         : "com.amplifyframework:core:${_libVersions.amplify}",
  amplifyApi          : "com.amplifyframework:aws-api:${_libVersions.amplify}",
  amplifyCognito      : "com.amplifyframework:aws-auth-cognito:${_libVersions.amplify}",
  amplifyS3           : "com.amplifyframework:aws-storage-s3:${_libVersions.amplify}",
  amplifyDataStore    : "com.amplifyframework:aws-datastore:${_libVersions.amplify}",
  amplifyKotlinCore   : "com.amplifyframework:core-kotlin:${_libVersions.amplify}",
```
method:
```
Amplify.Auth.signInWithSocialWebUI(
                    provider = AuthProvider.google(),
                    callingActivity = activity,
                ).apply {
                    if (isSignedIn) {
                        emit(State.Success())
                    } else {
                        emit(State.Error())
                    }
                }
```

**Comment by tylerjroach** [comment]
@tho9x, Can you make sure `signInWithSocialUI` is wrapped in a try/catch and verify the catch block is not capturing an error?

When you say it does nothing are you not seeing a browser flash open/close. FYI, due to the nature of Social Sign ins, a sign out is unable to clear the browser credentials. In the use case of clicking sign out, and then immediately calling `signInWithSocialWebUI` again, you should expect that the Google user signed in on the browser will be immediately signed back in.

**Comment by gpanshu** [comment]
Closing due to inactivity. Please feel free to create a new bug if you are still facing issues.
