### ISSUE TITLE
AWS Amplify Timeout Issue When Uploading Large Files (20MB+)

### ISSUE THREAD

**Issue by SrinivasKalagotla** [aws-amplify/amplify-android#2512]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line

    implementation 'com.amplifyframework:aws-auth-cognito:1.38.7'
    implementation 'com.amplifyframework:aws-storage-s3:1.38.7'
    implementation 'com.amplifyframework:core:1.38.7' 
```

</details>

### Environment information

<details>

```
# Put output below this line

Welcome to Gradle 7.5!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5/release-notes.html


------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Oracle Corporation 17.0.5+9-LTS-191)
OS:           Windows 11 10.0 amd64

```

</details>

### Describe the bug

I am developing a voice recorder application for android wear in which I am using AWS Amplify for file upload to S3. I am facing errors when uploading large files which are usually around (20MB+) but works fine for small files of less than 6MB.
I am getting Socket Timeout errors for large files. 
I have a strong network connectivity but still facing errors.

### Code Snippet

Amplify.Storage.uploadFile(
                                    fileName,
                                    tempFile,
                                    result -> {
                                        Log.i(TAG, "Successfully uploaded: " + result.getKey());
                                        // Update the upload status in the database
                                        updateUploadStatus(db, fileName, "UPLOADED");
                                    },
                                    error -> {
                                        if (error.getCause() instanceof AmazonClientException) {
                                            Log.e(TAG, "Upload failed due to network error. Retrying...");
                                            retries.getAndDecrement();
                                        } else {
                                            Log.e(TAG, "Upload failed", error);
                                        }
                                    }
                            );
                            
                            
*************************************************************************************************
public class AmplifyConfig extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        // Configure Amplify
        try {
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.configure(getApplicationContext());
            Log.i("MyApp", "Initialized Amplify");
        } catch (AmplifyException e) {
            Log.e("MyApp", "Could not initialize Amplify", e);
        }
    }
}

### Log output

<details>

```
Upload failed
                                                                                                    StorageException{message=Something went wrong with your AWS S3 Storage upload file operation, cause=java.util.concurrent.ExecutionException: com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout, recoverySuggestion=See attached exception for more information and suggestions}
                                                                                                    	at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:199)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:316)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7690)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
                                                                                                    Caused by: java.util.concurrent.ExecutionException: com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
                                                                                                    	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
                                                                                                    	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:177)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:109)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
                                                                                                    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456)
                                                                                                    	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
                                                                                                    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4835)
                                                                                                    	at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3821)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:63)
                                                                                                    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:31)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:923) 
                                                                                                    Caused by: java.net.SocketTimeoutException: timeout
                                                                                                    	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
                                                                                                    	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
                                                                                                    	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                                                    	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
                                                                                                    	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
                                                                                                    	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
                                                                                                    	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
                                                                                                    	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
                                                                                                    	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
                                                                                                    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:538)
                                                                                                    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:110)
                                                                                                    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:30)
                                                                                                    	at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:104)
                                                                                                    	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:97)
2023-07-12 15:46:06.343  4167-4167  FileUploadWorker        com.example.audio_recorder_wear      E  	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:386)
                                                                                                    	... 9 more
                                                                                                    Caused by: java.net.SocketException: Socket closed
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:209)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:144)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
                                                                                                    	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
                                                                                                    	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
                                                                                                    	... 24 more


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by SrinivasKalagotla** [comment]
Update: I have switched from v 1.38.7 to v2.9.0 for amplifyframework (core,auth,storage)

These are the new errors for uploading file (18MB file)

2023-07-13 14:24:31.768  6227-9497  amplify:aw...sferWorker com.example.audio_recorder_wear      E  PartUploadTransferWorker failed with exception: aws.smithy.kotlin.runtime.http.HttpException: java.net.SocketTimeoutException: timeout; HttpErrorCode(SOCKET_TIMEOUT)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.roundTrip(OkHttpEngine.kt:155)
                                                                                                    	at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine$roundTrip$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    Caused by: java.net.SocketTimeoutException: timeout
                                                                                                    	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147)
                                                                                                    	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:161)
                                                                                                    	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:339)
                                                                                                    	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
                                                                                                    	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
                                                                                                    	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
                                                                                                    	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:179)
                                                                                                    	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:111)
                                                                                                    	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:537)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.net.SocketException: Socket closed
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:209)
                                                                                                    	at java.net.SocketInputStream.read(SocketInputStream.java:144)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
                                                                                                    	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
                                                                                                    	at okio.InputStreamSource.read(JvmOkio.kt:94)
                                                                                                    	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
                                                                                                    	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427) 
                                                                                                    	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320) 
                                                                                                    	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29) 
                                                                                                    	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:179) 
                                                                                                    	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:111) 
                                                                                                    	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:95) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205) 
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:537) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:923)

**Comment by SrinivasKalagotla** [comment]
**Update**

I resolved my issue. This is for people using amplify for android wear devices. Wear devices restrict high-bandwidth network access by default to the apps. So we get timeout errors when uploading large files to S3 such as audio files. Please refer to the [link ](https://developer.android.com/training/wearables/data/network-access) and copy the "Request Wi-Fi connectivity" code into your main activity. This will make the app use high-bandwidth network making large file uploads easy. Here is a piece of code from my MainActivity

        ConnectivityManager connectivityManager = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
        ConnectivityManager.NetworkCallback callback = new ConnectivityManager.NetworkCallback() {
            public void onAvailable(Network network) {
                super.onAvailable(network);
                // The Wi-Fi network has been acquired. Bind it to use this network by default.
                connectivityManager.bindProcessToNetwork(network);
            }

            public void onLost(Network network) {
                super.onLost(network);
                // Called when a network disconnects or otherwise no longer satisfies this request or callback.
            }
        };
        connectivityManager.requestNetwork(
                new NetworkRequest.Builder()
                        .addTransportType(NetworkCapabilities.TRANSPORT_WIFI)
                        .addTransportType(NetworkCapabilities.TRANSPORT_CELLULAR)
                        .addCapability(NetworkCapabilities.NET_CAPABILITY_NOT_METERED)
                        .build(),
                callback
        );
        
        
Don't forget to add below permissions
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    
I hope this solves the issue for people facing error in android wear development.
Thanks to AWS Amplify team for this awesome service.
