### ISSUE TITLE
InitiateMultiPartUploadTransferWorker failed with exception: aws.sdk.kotlin.services.s3.model.S3Exception: The provided token has expired.

### ISSUE THREAD

**Issue by SrinivasKalagotla** [aws-amplify/amplify-android#2513]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
// Put output below this line

    implementation 'com.amplifyframework:aws-auth-cognito:2.9.0'
    implementation 'com.amplifyframework:aws-storage-s3:2.9.0'
    implementation 'com.amplifyframework:core:2.9.0' 
```

</details>

### Environment information

<details>

```
# Put output below this line

------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Oracle Corporation 17.0.5+9-LTS-191)
OS:           Windows 11 10.0 amd64

```

</details>

### Describe the bug

I am getting the below errors during file transfer to S3 in android wear application

2023-07-13 15:07:02.054  7639-15895 WM-WorkerWrapper        com.example.audio_recorder_wear      I  Worker result RETRY for Work [ id=34cb9a6b-0cc1-49d5-a4ac-cf8074ccdaa3, tags={ INITIATION_REQUEST_TAG_50, UPLOAD, awsS3StoragePlugin, 50, com.amplifyframework.storage.s3.transfer.worker.RouterWorker, MULTIPART_UPLOAD } ]
2023-07-13 15:07:02.058  7639-17151 amplify:aw...loadWorker com.example.audio_recorder_wear      E  SinglePartUploadWorker failed with exception: aws.sdk.kotlin.services.s3.model.S3Exception: The provided token has expired.
                                                                                                    	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt.throwPutObjectError(PutObjectOperationDeserializer.kt:66)
                                                                                                    	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt.access$throwPutObjectError(PutObjectOperationDeserializer.kt:1)
                                                                                                    	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt$throwPutObjectError$1.invokeSuspend(Unknown Source:13)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

*************************************************************************************
2023-07-13 15:03:43.294  7639-15895 WM-WorkerWrapper        com.example.audio_recorder_wear      I  Worker result RETRY for Work [ id=9daa58fe-013a-481d-8879-936c6a509a70, tags={ UPLOAD, awsS3StoragePlugin, com.amplifyframework.storage.s3.transfer.worker.RouterWorker, 43 } ]
2023-07-13 15:03:43.337  7639-16757 amplify:aw...sferWorker com.example.audio_recorder_wear      E  InitiateMultiPartUploadTransferWorker failed with exception: aws.sdk.kotlin.services.s3.model.S3Exception: The provided token has expired.
                                                                                                    	at aws.sdk.kotlin.services.s3.transform.CreateMultipartUploadOperationDeserializerKt.throwCreateMultipartUploadError(CreateMultipartUploadOperationDeserializer.kt:82)
                                                                                                    	at aws.sdk.kotlin.services.s3.transform.CreateMultipartUploadOperationDeserializerKt.access$throwCreateMultipartUploadError(CreateMultipartUploadOperationDeserializer.kt:1)
                                                                                                    	at aws.sdk.kotlin.services.s3.transform.CreateMultipartUploadOperationDeserializerKt$throwCreateMultipartUploadError$1.invokeSuspend(Unknown Source:13)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	

### Code Snippet

```java
    private void uploadRecordingToS3() throws FileNotFoundException {
        InputStream inputStream = getContentResolver().openInputStream(audioUri);
       // File audioFile = new File(audioUri.getPath());
        if (inputStream != null) {
            Amplify.Storage.uploadInputStream(
                    audioFileName,
                    inputStream,
                    result -> {
                        //Log.i(TAG, "Successfully uploaded file: " + result.getKey());
                        Log.d(TAG, "uploadRecordingToS3: audioFileName: " + audioFileName);
                        FileDatabase db = FileDatabase.getDatabase(this);
                        new Thread(() -> db.fileDao().updateUploadStatus(audioFileName, "UPLOADED")).start();
                    },
                    error -> Log.e(TAG, "Upload failed", error)
            );
        } else {
            Log.e(TAG, "uploadRecordingToS3: Failed to open input stream for audioUri");
        }
    }

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by SrinivasKalagotla** [comment]
Update:

I have removed the auth and added it again. This issue is now resolved.

Commands:
amplify remove auth
amplify push
amplify pull

amplify add auth
amplify push
amplify pull
