### ISSUE TITLE
AWS Pinpoint events error

### ISSUE THREAD

**Issue by mohamedtawfik** [aws-amplify/amplify-android#2526]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

Analytics

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
implementation 'com.amplifyframework:aws-analytics-pinpoint:2.8.5'
implementation 'com.amplifyframework:aws-auth-cognito:2.8.5'
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'
```

</details>

### Describe the bug

On runtime I got this while the timezone and time are automatic on device. what is this error means and how to fix it ?
Also I am getting same error on another device if I changed the timezone or time

Android 7.1.1

PinpointException occurred during endpoint update:
aws.sdk.kotlin.services.pinpoint.model.PinpointException: Signature not yet current: 20230724T094820Z is still later than 20230724T085205Z (20230724T084705Z + 5 min.)
at aws.sdk.kotlin.services.pinpoint.transform.UpdateEndpointOperationDeserializerKt.throwUpdateEndpointError(UpdateEndpointOperationDeserializer.kt:55)
at aws.sdk.kotlin.services.pinpoint.transform.UpdateEndpointOperationDeserializerKt.access$throwUpdateEndpointError(UpdateEndpointOperationDeserializer.kt:1)
at aws.sdk.kotlin.services.pinpoint.transform.UpdateEndpointOperationDeserializerKt$throwUpdateEndpointError$1.invokeSuspend(UpdateEndpointOperationDeserializer.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

Failed to submit events aws.sdk.kotlin.services.pinpoint.model.PinpointException: Signature not yet current: 20230724T094850Z is still later than 20230724T085233Z (20230724T084733Z + 5 min.)

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by sdhuka** [comment]
@mohamedtawfik Device time is ahead of the actual local time due to which sigv4 signing is failing on the Pinpoint service call. Please confirm that device time matches the local time and try again.

**Comment by mohamedtawfik** [comment]
> @mohamedtawfik Device time is ahead of the actual local time due to which sigv4 signing is failing on the Pinpoint service call. Please confirm that device time matches the local time and try again.

Time is not automatic as it is not correct we are now in summer time so when setting timezone automatic time for example is 10am but actually it is 11am.

is there is a way to make analytics work while user can change it's device time ?

**Comment by mattcreaser** [comment]
@mohamedtawfik our underlying Kotlin SDK does not currently support skewing the clock for this situation, please follow this issue for updates:  https://github.com/awslabs/aws-sdk-kotlin/issues/213

Until and unless that feature is available we do not offer a workaround beyond manually correcting the device time.
