### ISSUE TITLE
Amplify DataStore Sync TimeoutException

### ISSUE THREAD

**Issue by srivathsan7** [aws-amplify/amplify-android#2594]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line


```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Describe the bug

Experiencing Amplify Sync Timeout during Initial Sync, sync kept on failing due to timeout. Tried clearing cache, but the issue still persists.

```
Long monitor contention with owner pool-6-thread-2 (7906) at okhttp3.HttpUrl okhttp3.HttpUrl.parse(java.lang.String)(HttpUrl.java:901) waiters=0 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 2.648s
Long monitor contention with owner pool-6-thread-2 (7906) at okhttp3.HttpUrl okhttp3.HttpUrl.parse(java.lang.String)(HttpUrl.java:901) waiters=1 in void com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(com.amplifyframework.api.graphql.GraphQLRequest, com.amplifyframework.api.aws.AuthorizationType, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Consumer, com.amplifyframework.core.Action) for 3.011s
E/amplify:aws-datastore: Failure encountered while attempting to start API sync.
    DataStoreException{message=Initial sync during DataStore initialization failed., cause=java.util.concurrent.TimeoutException: Timed out while performing initial model sync., recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$startApiSync$3$Orchestrator(Orchestrator.java:327)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$to6jsrpqq5TGk-8kfWyEK_7WfwQ.subscribe(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2856)
```

Amplify DataStore version: 1.28.1

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by ankpshah** [comment]
Hello [srivathsan7](https://github.com/srivathsan7),
   Could you upgrade to latest version of Amplify Android here: https://github.com/aws-amplify/amplify-android/releases/tag/release_v2.13.2. Version 1.28.1 is now two years old and numerous bug fixes have been implemented since then.
   Let us know if upgrading to latest version resolves the issue you are facing

**Comment by tylerjroach** [comment]
Please let us know if you were able to upgrade. I'm going to mark this ticket as closing soon due due to the time since the last response.
