### ISSUE TITLE
Amplify and Okhttp

### ISSUE THREAD

**Issue by victorkifer** [aws-amplify/amplify-android#2632]
Hello!

There's a similar [closed issue](https://github.com/aws-amplify/amplify-android/issues/2489).

We're in the process to implement authentication with Cognito using Amplify Auth. At the moment however we are blocked with this sdk due to the usage of okhttp:5-alpha in it. Attached is the crash that we're getting in the runtime which is related to incompatibilities in okhttp versions.

```
The crash java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/Util;
at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:69)
at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.Util" on path: DexPathList[[zip file "/data/app/~~kHWq-VwP7-e5MpvJAmE_uw==/com.zegocover.zego.qa-1U5rJX4k6xbdkKhpFtLl-g==/base.apk"],nativeLibraryDirectories=[/data/app/~~kHWq-VwP7-e5MpvJAmE_uw==/com.zegocover.zego.qa-1U5rJX4k6xbdkKhpFtLl-g==/lib/arm64, /data/app/~~kHWq-VwP7-e5MpvJAmE_uw==/com.zegocover.zego.qa-1U5rJX4k6xbdkKhpFtLl-g==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:69) 
at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46) 
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
at java.lang.Thread.run(Thread.java:1012) 
```

We cannot use okhttp 5 cause other third-party sdks are built on top of okhttp 4.

So I wanted to ask if you know of any workarounds for this issue? Is there another SDK from amazon that doens't require okhttp 5?

**Comment by tylerjroach** [comment]
Unfortunately you would have to use Amplify v1, instead of Amplify v2 at the moment. We currently have a dependency on our AWS Kotlin SDK which uses OkHttp v5. Will relay this blocker to the team.

**Comment by victorkifer** [comment]
Is Amplify v1 still supported and maintained with at least security updates?

**Comment by gpanshu** [comment]
@victorkifer yes it is. 

Here is the note from our documentation: 

Amplify Android v1 is now in Maintenance Mode until May 31st, 2024. This means that we will continue to include updates to ensure compatibility with backend services and security. No new features will be introduced in v1. 

Please do not hesitate to reach out if you face any other issues.

**Comment by eligijusTrafi** [comment]
Hi there. What about forcing aws amplify to use okhttp 4.x.x with a https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html mechanism? Does aws amplify depends on new functionality of okhttp 5.0.0 ? Also, did you notice that 5.0.0-alpha11 was released more than a year ago and no new versions since then?

**Comment by tylerjroach** [comment]
You an attempt to force OkHttp to resolve to a lower version, but in our testing we have seen issues in trying this. Unfortunately, the 5.0.0-alpha11 version is being used in one of the libraries we depend on, so we are not able to bump down unless the dependency chooses to first bump their version back down to the latest stable.

**Comment by tylerjroach** [comment]
I'm going to go ahead and close this issue as there is currently not anything actionable. I will update if we become able to downgrade to v4.
