### ISSUE TITLE
Calling Amplify.Storage.uploadFile doesn't return progress, result, or error

### ISSUE THREAD

**Issue by jming** [aws-amplify/amplify-android#2737]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Storage

### Gradle script dependencies

<details>

```groovy
implementation 'com.amplifyframework:core:2.14.11'
implementation 'com.amplifyframework:aws-storage-s3:2.14.11'
implementation 'com.amplifyframework:aws-auth-cognito:2.14.11'
```

</details>

### Environment information

<details>

```
# Put output below this line


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/android/build-a-backend/storage/set-up-storage/

### Describe the bug

I was trying to run the Amplify.Storage.uploadFile example from the tutorial (https://docs.amplify.aws/android/build-a-backend/storage/set-up-storage/), but I did not get any feedback on whether the function was running or not--not even if there was an error.

Then I tried to use Cognito Auth and set the targetIdentityId in the StorageUploadFileOptions, but I'm still not getting any updates on whether the Storage function is running or not. I'm not sure if I'm missing anything else.

### Code Snippet

```java
Amplify.Auth.fetchAuthSession(
                authResult -> {
                    Log.i("Amplify", authResult.toString());

                    AWSCognitoAuthSession cognitoAuthSession = (AWSCognitoAuthSession) authResult;
                    switch(cognitoAuthSession.getIdentityIdResult().getType()) {
                        case SUCCESS:
                            Log.i("Amplify", "IdentityId: " + cognitoAuthSession.getIdentityIdResult().getValue());

                            StorageUploadFileOptions options = StorageUploadFileOptions.builder()
                                    .targetIdentityId(cognitoAuthSession.getIdentityIdResult().getValue())
                                    .build();

                            Log.i("Amplify", "StorageUploadOptions: " + options);

                            File exampleFile = new File(getApplicationContext().getFilesDir(), "ExampleKey.txt");

                            try {
                                BufferedWriter writer = new BufferedWriter(new FileWriter(exampleFile));
                                writer.append("Example file contents");
                                writer.close();
                            } catch (Exception exception) {
                                Log.e("Amplify", "Upload failed", exception);
                            }

                            Amplify.Storage.uploadFile(
                                    "ExampleKeyTest.txt",
                                    exampleFile,
                                    options,
//                                    StorageUploadFileOptions.defaultInstance(),
                                    storageProgress -> Log.i("Amplify", "Fraction completed: " + storageProgress.getFractionCompleted()),
                                    storageResult -> Log.i("Amplify", storageResult.toString()),
                                    storageError -> Log.e("Amplify", storageError.toString()));

                            break;
                        case FAILURE:
                            Log.i("AuthQuickStart", "IdentityId not present because: " + cognitoAuthSession.getIdentityIdResult().getError().toString());
                    }


                },
                authError -> Log.e("Amplify", authError.toString())
        );

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

```
{
  "storage": {
    "plugins": {
      "awsS3StoragePlugin": {
        "bucket": "XXX",
        "region": "XXX"
      }
    }
  },
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "XXX",
              "Region": "XXX"
            }
          }
        }
      }
    }
  }
}

```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by yuhengshs** [comment]
Hi @jming,

I will look into the issue and try to replicate it.

**Comment by yuhengshs** [comment]
Hi @jming ,

Can you provide some logs that shows how code is running?  Make sure that your network connection is active. 
Based on the code snippet you provided, I will not be able to see the result returning from `Amplify.Storage.uploadFile` 
when I turned on the airplane mode, I can only see logs up to `Log.i("Amplify", "StorageUploadOptions: " + options);`

**Comment by jming** [comment]
So I'm not getting even any logs! That is what is confusing to me. That is the last log that I get as well.

**Comment by tylerjroach** [comment]
@jming You can get verbose logs for all of amplify by adding the `AndroidLoggingPlugin(LogLevel.VERBOSE) as the first configured Amplify library. Please add this to debug and report back with any interesting findings.

**Comment by jming** [comment]
This is what I got:

```
---------------------------- PROCESS ENDED (30794) for package org.uniglobalunion.spotlight ----------------------------
---------------------------- PROCESS STARTED (29393) for package org.uniglobalunion.spotlight ----------------------------
2024-03-19 11:16:01.703 29393-29448 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: NotConfigured(id=)
2024-03-19 11:16:01.707 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: ConfiguringAuth(id=)
2024-03-19 11:16:01.708 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  InitAuthConfig Starting execution
2024-03-19 11:16:01.713 29393-29454 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Credential Store State Change: MigratingLegacyStore(id=)
2024-03-19 11:16:01.713 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  MigrateLegacyCredentials Starting execution
2024-03-19 11:16:01.713 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Credential Store State Change: NotConfigured(id=)
2024-03-19 11:16:01.734 29393-29393 Amplify                 org.uniglobalunion.spotlight         I  Initialized Amplify
2024-03-19 11:16:01.794 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  MigrateLegacyCredentials Sending event LoadCredentialStore
2024-03-19 11:16:01.796 29393-29454 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Credential Store State Change: LoadingStoredCredentials(id=)
2024-03-19 11:16:01.797 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  LoadCredentialStore Starting execution
2024-03-19 11:16:01.884 29393-29447 AndroidKeysetManager    org.uniglobalunion.spotlight         W  keyset not found, will generate a new one
                                                                                                    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist
                                                                                                    	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
                                                                                                    	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
                                                                                                    	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
                                                                                                    	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:123)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.getSharedPreferencesOrThrow(EncryptedKeyValueRepository.kt:110)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.getSharedPreferencesOrNull(EncryptedKeyValueRepository.kt:106)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.openKeystoreWithAmplifyMasterKey(EncryptedKeyValueRepository.kt:82)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.getOrCreateSharedPreferences(EncryptedKeyValueRepository.kt:64)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.access$getOrCreateSharedPreferences(EncryptedKeyValueRepository.kt:32)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository$sharedPreferences$2.invoke(EncryptedKeyValueRepository.kt:48)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository$sharedPreferences$2.invoke(EncryptedKeyValueRepository.kt:48)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.getSharedPreferences(EncryptedKeyValueRepository.kt:48)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.get(EncryptedKeyValueRepository.kt:51)
                                                                                                    	at com.amplifyframework.auth.cognito.data.AWSCognitoAuthCredentialStore.retrieveCredential(AWSCognitoAuthCredentialStore.kt:63)
                                                                                                    	at com.amplifyframework.auth.cognito.actions.CredentialStoreCognitoActions$loadCredentialStoreAction$$inlined$invoke$1.execute(Action.kt:70)
                                                                                                    	at com.amplifyframework.statemachine.ConcurrentEffectExecutor$execute$1$1.invokeSuspend(ConcurrentEffectExecutor.kt:26)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-03-19 11:16:01.941 29393-29447 AndroidKeysetManager    org.uniglobalunion.spotlight         W  keyset not found, will generate a new one
                                                                                                    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_value_keyset__ does not exist
                                                                                                    	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
                                                                                                    	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
                                                                                                    	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
                                                                                                    	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
                                                                                                    	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:128)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.getSharedPreferencesOrThrow(EncryptedKeyValueRepository.kt:110)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.getSharedPreferencesOrNull(EncryptedKeyValueRepository.kt:106)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.openKeystoreWithAmplifyMasterKey(EncryptedKeyValueRepository.kt:82)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.getOrCreateSharedPreferences(EncryptedKeyValueRepository.kt:64)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.access$getOrCreateSharedPreferences(EncryptedKeyValueRepository.kt:32)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository$sharedPreferences$2.invoke(EncryptedKeyValueRepository.kt:48)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository$sharedPreferences$2.invoke(EncryptedKeyValueRepository.kt:48)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.getSharedPreferences(EncryptedKeyValueRepository.kt:48)
                                                                                                    	at com.amplifyframework.core.store.EncryptedKeyValueRepository.get(EncryptedKeyValueRepository.kt:51)
                                                                                                    	at com.amplifyframework.auth.cognito.data.AWSCognitoAuthCredentialStore.retrieveCredential(AWSCognitoAuthCredentialStore.kt:63)
                                                                                                    	at com.amplifyframework.auth.cognito.actions.CredentialStoreCognitoActions$loadCredentialStoreAction$$inlined$invoke$1.execute(Action.kt:70)
                                                                                                    	at com.amplifyframework.statemachine.ConcurrentEffectExecutor$execute$1$1.invokeSuspend(ConcurrentEffectExecutor.kt:26)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-03-19 11:16:01.973 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  LoadCredentialStore Sending event CompletedOperation
2024-03-19 11:16:01.974 29393-29454 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Credential Store State Change: Success(storedCredentials=com.amplifyframework.statemachine.codegen.data.AmplifyCredential$Empty@d4d9d7f)
2024-03-19 11:16:01.975 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  MoveToIdleState Starting execution
2024-03-19 11:16:01.975 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  MoveToIdleState Sending event MoveToIdleState
2024-03-19 11:16:01.976 29393-29454 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Credential Store State Change: Idle(id=)
2024-03-19 11:16:01.977 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  InitAuthConfig Sending event ConfigureAuthorization
2024-03-19 11:16:01.979 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: ConfiguringAuthorization(authNState=NotConfigured(id=), authZState=NotConfigured(id=))
2024-03-19 11:16:01.980 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  InitAuthZConfig Starting execution
2024-03-19 11:16:01.981 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  InitAuthZConfig Sending event Configure
2024-03-19 11:16:01.983 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: ConfiguringAuthorization(authNState=NotConfigured(id=), authZState=Configured(id=))
2024-03-19 11:16:01.984 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  ConfigureAuthZ Starting execution
2024-03-19 11:16:01.984 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  ConfigureAuthZ Sending event ConfiguredAuthorization
2024-03-19 11:16:01.989 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: Configured(authNState=NotConfigured(id=), authZState=Configured(id=))
2024-03-19 11:16:43.850 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: Configured(authNState=NotConfigured(id=), authZState=FetchingUnAuthSession(fetchAuthSessionState=NotStarted(id=)))
2024-03-19 11:16:43.851 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  InitFetchUnAuthSession Starting execution
2024-03-19 11:16:43.851 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  InitFetchUnAuthSession Sending event FetchIdentity
2024-03-19 11:16:43.855 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: Configured(authNState=NotConfigured(id=), authZState=FetchingUnAuthSession(fetchAuthSessionState=FetchingIdentity(logins=UnAuthLogins(logins={}))))
2024-03-19 11:16:43.855 29393-29452 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  FetchIdentity Starting execution
2024-03-19 11:16:44.733 29393-29448 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  FetchIdentity Sending event FetchAwsCredentials
2024-03-19 11:16:44.734 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: Configured(authNState=NotConfigured(id=), authZState=FetchingUnAuthSession(fetchAuthSessionState=FetchingAWSCredentials(identityId=XX, logins=UnAuthLogins(logins={}))))
2024-03-19 11:16:44.735 29393-29448 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  FetchAWSCredentials Starting execution
2024-03-19 11:16:44.919 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  FetchAWSCredentials Sending event Fetched
2024-03-19 11:16:44.920 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: Configured(authNState=NotConfigured(id=), authZState=FetchingUnAuthSession(fetchAuthSessionState=Fetched(id=)))
2024-03-19 11:16:44.921 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  NotifySessionEstablished Starting execution
2024-03-19 11:16:44.921 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  NotifySessionEstablished Sending event Fetched
2024-03-19 11:16:44.922 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: Configured(authNState=NotConfigured(id=), authZState=StoringCredentials(amplifyCredential=IdentityPool(identityId=XX, credentials=AWSCredentials(accessKeyId = ASIAX***, secretAccessKey = XX, sessionToken = XX, expiration = 1710865005))))
2024-03-19 11:16:44.923 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  PersistCredentials Starting execution
2024-03-19 11:16:44.925 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Credential Store State Change: Idle(id=)
2024-03-19 11:16:44.925 29393-29454 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Credential Store State Change: StoringCredentials(id=)
2024-03-19 11:16:44.925 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  StoreCredentials Starting execution
2024-03-19 11:16:44.941 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  StoreCredentials Sending event CompletedOperation
2024-03-19 11:16:44.942 29393-29454 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Credential Store State Change: Success(storedCredentials=IdentityPool(identityId=XX, credentials=AWSCredentials(accessKeyId = XX, secretAccessKey = XX, sessionToken = XX, expiration = 1710865005)))
2024-03-19 11:16:44.943 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  MoveToIdleState Starting execution
2024-03-19 11:16:44.943 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  MoveToIdleState Sending event MoveToIdleState
2024-03-19 11:16:44.943 29393-29454 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Credential Store State Change: Idle(id=)
2024-03-19 11:16:44.944 29393-29447 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  PersistCredentials Sending event ReceivedCachedCredentials
2024-03-19 11:16:44.945 29393-29449 amplify:aw...AuthPlugin org.uniglobalunion.spotlight         V  Auth State Change: Configured(authNState=NotConfigured(id=), authZState=SessionEstablished(amplifyCredential=IdentityPool(identityId=XX, credentials=AWSCredentials(accessKeyId =XX, secretAccessKey = XX, sessionToken = XX, expiration = 1710865005))))
2024-03-19 11:16:44.948 29393-29447 Amplify                 org.uniglobalunion.spotlight         I  AWSCognitoAuthSession(isSignedIn=false, identityIdResult=AuthSessionResult{value=XX, error=null, type=SUCCESS}, awsCredentialsResult=AuthSessionResult{value=AWSTemporaryCredentials(accessKeyId=XX, secretAccessKey=XX, sessionToken=XX, expiration=2024-03-19T16:16:45Z), error=null, type=SUCCESS}, userSubResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userPoolTokensResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE})
2024-03-19 11:16:44.948 29393-29447 Amplify                 org.uniglobalunion.spotlight         I  IdentityId: XX
2024-03-19 11:16:44.948 29393-29447 Amplify                 org.uniglobalunion.spotlight         I  StorageUploadOptions: StorageUploadFileOptions {accessLevel=null, targetIdentityId=XX, contentType=null, metadata={}}
2024-03-19 11:16:57.992 29393-29448 Amplify                 org.uniglobalunion.spotlight         I  AWSCognitoAuthSession(isSignedIn=false, identityIdResult=AuthSessionResult{value=XX, error=null, type=SUCCESS}, awsCredentialsResult=AuthSessionResult{value=AWSTemporaryCredentials(accessKeyId=XX, secretAccessKey=XX, sessionToken=XX, expiration=2024-03-19T16:16:45Z), error=null, type=SUCCESS}, userSubResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}, userPoolTokensResult=AuthSessionResult{value=null, error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE})
2024-03-19 11:16:57.992 29393-29448 Amplify                 org.uniglobalunion.spotlight         I  IdentityId: XX
2024-03-19 11:16:57.993 29393-29448 Amplify                 org.uniglobalunion.spotlight         I  StorageUploadOptions: StorageUploadFileOptions {accessLevel=null, targetIdentityId=XX, contentType=null, metadata={}}

```

**Comment by jming** [comment]
I wonder if there is a problem with the amplifyconfiguration.json? Or maybe AWS reqiurements I'm importing?

Right now I'm importing these:

```
implementation 'com.amplifyframework:core:2.14.11'
    implementation 'com.amplifyframework:aws-storage-s3:2.14.11'
    implementation 'com.amplifyframework:aws-auth-cognito:2.14.11'
```

**Comment by jming** [comment]
I'm also wondering if it's the nested call from fetching the auth to the storage, though I also am getting no logs or any response when I'm calling the storage without the fetch surrounding it.

This makes me think it's related to the amplifyconfiguration or build.gradle dependencies?

**Comment by tylerjroach** [comment]
A few possibilities:

* Did you add the Storage Plugin in Amplify configuration? `Amplify.addPlugin(new AWSS3StoragePlugin());` I don't see any storage logs
* I'm assuming you have guest access enabled as it looks like you are getting an identityId. To confirm, have you tried signing in and seeing if it works when you are signed in, but not if you are a guest.
* Also, if both of the above are true, could you set a log line right before calling upload. Maybe there was an exception beore uploadFile being caught elsewhere.

**Comment by joon-won** [comment]
Closing this issue due to inactivity. Please feel free to open a new issue if required, thank you
