### ISSUE TITLE
Null Pointer Exception  on CustomTabsManagerActivity.onResume

### ISSUE THREAD

**Issue by Mohammed-Amleh** [aws-amplify/amplify-android#2818]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

Authentication

### Describe the bug

https://github.com/aws-amplify/amplify-android/issues/1090 exactly the same as this problem & the amplify version that i am using is `v2.14.6`,  i cant re-produce the problem i counter it on firebase crashlytic.
error :

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.app.t/com.amplifyframework.auth.cognito.activities.CustomTabsManagerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData(android.content.Context)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5378)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5444)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8779)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData(android.content.Context)' on a null object reference
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1799)
       at android.app.Activity.startActivityForResult(Activity.java:5596)
       at android.app.Activity.startActivityForResult(Activity.java:5554)
       at android.app.Activity.startActivity(Activity.java:6052)
       at android.app.Activity.startActivity(Activity.java:6019)
       at com.amplifyframework.auth.cognito.activities.CustomTabsManagerActivity.onResume(CustomTabsManagerActivity.kt:49)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1531)
       at android.app.Activity.performResume(Activity.java:8734)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5351)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5444)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8779)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by tylerjroach** [comment]
@Mohammed-Amleh This one is strange.

Would you have any data on these crashes to determine if Google Play Services is available on these devices? This looks to be the most common scenario that can cause this.

Would you happen to know if these devices are rooted?

If neither of these pieces of info are available, please post a few of the devices that have crashed with this info and we can see if we notice any patterns (ex: manufacturer, OS version, etc)

How many devices/users have you seen this issue on?

**Comment by Mohammad-amleh** [comment]
the crash appear for 18 users ,
see these : 
<img width="1268" alt="Screenshot 2024-05-13 at 5 47 51 PM" src="https://github.com/aws-amplify/amplify-android/assets/93711291/d5457ebd-3c39-4d65-94eb-a2925bfd96d8">
<img width="1275" alt="Screenshot 2024-05-13 at 5 48 02 PM" src="https://github.com/aws-amplify/amplify-android/assets/93711291/e7944aa9-72de-4bdd-8ea6-a67ab63d6cdb">

**Comment by Mohammed-Amleh** [comment]
@tylerjroach  the crash appear for 18 users , and i don't think its Google Play Services Availability 
see these : 
<img width="1268" alt="Screenshot 2024-05-13 at 5 47 51 PM" src="https://github.com/aws-amplify/amplify-android/assets/93711291/d5457ebd-3c39-4d65-94eb-a2925bfd96d8">
<img width="1275" alt="Screenshot 2024-05-13 at 5 48 02 PM" src="https://github.com/aws-amplify/amplify-android/assets/93711291/e7944aa9-72de-4bdd-8ea6-a67ab63d6cdb">

**Comment by Mohammed-Amleh** [comment]
@tylerjroach

**Comment by tylerjroach** [comment]
@Mohammed-Amleh  Is this a new app, or a crash that has appeared out of nowhere on an older app? Asking because we don't see any occurrences before May 3-4 on that chart.

Can you post any Amplify/AWS related code that you have added to your manifest, as well as show how you are launching signInWithWebUI or signInWithSocialWebUI sign ins?

**Comment by Mohammed-Amleh** [comment]
no its not a new app ,we was using amplify v1 ,, this error appear after upgrading to amplify v2 .
sorry but i can't share any code (i don't have the privilege for it).
 what what added to manifest :
```
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />

            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.support.customtabs.action.CustomTabsService" />
        </intent>
    </queries>

```

```
        <activity
            android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="my_app_name" />
            </intent-filter>
        </activity>
```

**Comment by tylerjroach** [comment]
@Mohammed-Amleh The <queries> block you posted is no longer needed in Amplify v2. Regardless, this wouldn't impact your application. 

Would you happen to know if these devices are eventually able to sign in or not? Curious if it is a transient issue for them or these devices failing 100% of time time. Do the devices failing all seem to be specific to a single region? Looking for any more data points that could help identity why this may be happening.

I've not seen this report before. I think I can try/catch to prevent the crash, but the scenario happening here should not be happening. A try/catch would still prevent hosted ui sign in from working correctly.

The crash appears to be the CustomTab intent is null on the first launch (which shouldn't happen since it created and passed directly when calling startActivity on the CustomTabsManagerActivity.

**Comment by Mohammed-Amleh** [comment]
@tylerjroach 

the problem is from `extractState` in `CustomTabsManagerActivity`

```
  private fun extractState(state: Bundle?) {
        if (state == null) {
            Log.d(TAG, "CustomTabsManagerActivity was created with a null state.")
            finish()
            return
        }
        customTabsIntent = state.getParcelable(CUSTOM_TABS_INTENT_KEY)
        customTabsLaunched = state.getBoolean(CUSTOM_TABS_LAUNCHED_KEY, false)
    }
```

<img width="810" alt="Screenshot 2024-06-24 at 6 04 46 PM" src="https://github.com/aws-amplify/amplify-android/assets/31358315/e635cbbd-079f-454f-bcab-75cfb24ca808">

We use a package for analytics that adds an extra intent for every launch activity. The issue arises in our specific case where the state will never be null, even if the **_customTabsIntentExtra_** is not provided. Consequently, the following lines of code can result in null values:

```
        customTabsIntent = state.getParcelable(CUSTOM_TABS_INTENT_KEY) // will be null 
        customTabsLaunched = state.getBoolean(CUSTOM_TABS_LAUNCHED_KEY, false) // will be null

```
To address this issue, modify the if statement to include a check for the customTabsIntent key:

`state == null || state.getParcelable(CUSTOM_TABS_INTENT_KEY) == null`

This ensures that u properly handle scenarios where the customTabsIntent is not provided, even though state is not null.

**Comment by tylerjroach** [comment]
Have you already tested this to work? In some places we launch with `startActivityForResult` and rely on the result to come back to continue. It may work but the implementation needs thought through a bit more.

> The issue arises in our specific case where the state will never be null, even if the customTabsIntentExtra is not provided.

This should never happen. We never launch without intent data. This was just meant to be a safety mechanism.

We don't always pass `CUSTOM_TABS_INTENT_KEY` ourselves. It is allowed to be null, for the response handling intent.

I'm still concerned about this analytics package that is injecting into our owned activities. Can we look into which library this is? Maybe there is a way to exclude individual activities. This is a headless activity ands its behavior is not meant to be modified by the app developer, nor any other 3rd party libraries.

**Comment by tylerjroach** [comment]
CustomTabsManagerActivity is intended to remain internal and should not be invoked by anything other than Amplify itself.

I'd like to look at the Analytics library in question and see exactly what is being done, to make sure that we have a stable and complete way of handling unintended outside interference.
