### ISSUE TITLE
Could not decode AmplifyOutputs

### ISSUE THREAD

**Issue by spiekermax** [aws-amplify/amplify-android#2880]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```toml
amplifyUiAuthenticator = "1.2.1"
amplifyCore = "2.20.0"

amplify-ui-authenticator = { group = "com.amplifyframework.ui", name = "authenticator", version.ref = "amplifyUiAuthenticator" }
amplify-core = { group = "com.amplifyframework", name = "core", version.ref = "amplifyCore" }
amplify-core-kotlin = { group = "com.amplifyframework", name = "core-kotlin", version.ref = "amplifyCore" }
```

</details>

### Environment information

<details>

```
Welcome to Gradle 8.7!

Here are the highlights of this release:
 - Compiling and testing with Java 22
 - Cacheable Groovy script compilation
 - New methods in lazy collection properties

For more details see https://docs.gradle.org/8.7/release-notes.html


------------------------------------------------------------
Gradle 8.7
------------------------------------------------------------

Build time:   2024-03-22 15:52:46 UTC
Revision:     650af14d7653aa949fce5e886e685efc9cf97c10

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.9 (Oracle Corporation 11.0.9+7-LTS)
OS:           Windows 10 10.0 amd64

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/android/start/quickstart/

### Describe the bug

I followed the quickstart for AWS Amplify Gen 2 on Android, however it does not work. When launching the app the login screen does not show up and instead the app runs into an error.

### Reproduction steps (if applicable)

1. Install the latest version of Android Studio.
2. Create a new Android project using Jetpack Compose.
3. Follow the steps described in the quickstart section for Amplify Gen 2 until the end of step 6.

### Code Snippet

```kotlin
Authenticator { state ->
    Column(modifier = modifier) {
        Text(
            text = "Hello ${state.user.username}!",
        )
        Button(onClick = {
            Amplify.Auth.signOut { }
        }) {
            Text(text = "Sign Out")
        }
    }
}
```

### Log output

<details>

```
Could not initialize Amplify
	AmplifyException{message=Could not decode AmplifyOutputs, cause=kotlinx.serialization.SerializationException: com.amplifyframework.core.configuration.AmplifyOutputsData.Auth.MfaConfiguration does not contain element with name 'OFF' at path $.auth.mfaConfiguration, recoverySuggestion=Ensure the AmplifyOutputs data is correct}
		at com.amplifyframework.core.configuration.AmplifyOutputsData$Companion.deserialize$com_amplifyframework_core_release(AmplifyOutputsData.kt:238)
		at com.amplifyframework.core.configuration.AmplifyOutputsData$Companion.deserialize(AmplifyOutputsData.kt:225)
		at com.amplifyframework.core.configuration.AmplifyOutputsData.deserialize(Unknown Source:2)
		at com.amplifyframework.core.Amplify.configure(Amplify.java:210)
		at my.package.MainActivity.onCreate(MainActivity.kt:30)
		at android.app.Activity.performCreate(Activity.java:8305)
		at android.app.Activity.performCreate(Activity.java:8284)
		at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
		at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
		at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
		at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
		at android.os.Handler.dispatchMessage(Handler.java:106)
		at android.os.Looper.loopOnce(Looper.java:201)
		at android.os.Looper.loop(Looper.java:288)
		at android.app.ActivityThread.main(ActivityThread.java:7872)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

</details>

### amplifyconfiguration.json

```json
{
  "auth": {
    "user_pool_id": "REDACTED",
    "aws_region": "eu-central-1",
    "user_pool_client_id": "REDACTED",
    "identity_pool_id": "REDACTED",
    "mfa_methods": [],
    "standard_required_attributes": [
      "email"
    ],
    "username_attributes": [
      "email"
    ],
    "user_verification_types": [
      "email"
    ],
    "mfa_configuration": "OFF",
    "password_policy": {
      "min_length": 8,
      "require_numbers": true,
      "require_lowercase": true,
      "require_uppercase": true,
      "require_symbols": true
    },
    "unauthenticated_identities_enabled": true
  },
  "data": {
    "url": "REDACTED",
    "aws_region": "eu-central-1",
    "api_key": "REDACTED",
    "default_authorization_type": "API_KEY",
    "authorization_types": [
      "AMAZON_COGNITO_USER_POOLS",
      "AWS_IAM"
    ],
    "model_introspection": {
      "version": 1,
      "models": {
        "Todo": {
          "name": "Todo",
          "fields": {
            "id": {
              "name": "id",
              "isArray": false,
              "type": "ID",
              "isRequired": true,
              "attributes": []
            },
            "content": {
              "name": "content",
              "isArray": false,
              "type": "String",
              "isRequired": false,
              "attributes": []
            },
            "createdAt": {
              "name": "createdAt",
              "isArray": false,
              "type": "AWSDateTime",
              "isRequired": false,
              "attributes": [],
              "isReadOnly": true
            },
            "updatedAt": {
              "name": "updatedAt",
              "isArray": false,
              "type": "AWSDateTime",
              "isRequired": false,
              "attributes": [],
              "isReadOnly": true
            }
          },
          "syncable": true,
          "pluralName": "Todos",
          "attributes": [
            {
              "type": "model",
              "properties": {}
            },
            {
              "type": "auth",
              "properties": {
                "rules": [
                  {
                    "allow": "public",
                    "provider": "apiKey",
                    "operations": [
                      "create",
                      "update",
                      "delete",
                      "read"
                    ]
                  }
                ]
              }
            }
          ],
          "primaryKeyInfo": {
            "isCustomPrimaryKey": false,
            "primaryKeyFieldName": "id",
            "sortKeyFieldNames": []
          }
        }
      },
      "enums": {},
      "nonModels": {}
    }
  },
  "version": "1"
}
```

### Additional information and screenshots

![image](https://github.com/user-attachments/assets/3ae9e381-9e00-4b85-81ef-0a4ee56724ed)

**Comment by mattcreaser** [comment]
Hi @spiekermax - this appears to be a bug in the Amplify CLI. Your `amplify_outputs.json` file has an `mfa_configuration` value of `OFF`, which is not valid. Valid values are `NONE`, `OPTIONAL`, and `REQUIRED`.

I am going to transfer this issue to the CLI repo to take a look at, but in the meantime you can manually change the `mfa_configuration` value to be `NONE` to resolve the error.
