### ISSUE TITLE
Update error message on attempt to delete not-present item

### ISSUE THREAD

**Issue by jamesonwilliams** [aws-amplify/amplify-android#292]
A model is saved, and then deleted.

A subsequent attempt is made to delete that same (already gone) model.

Expected: the error message says something like "failed to delete; model not found."

Actual: a generic message about a predicate failure.

```
2020-03-03 13:51:57.483 10975-11025/com.amplifyframework.ddsa I/MainActivity: Saved a post:Post{
      title=Title 6f56fc9d-1d63-4b99-a129-2ede1ff5c95e
      id=a08f9fd6-a26c-4dd4-98a6-41c533f769dd
      rating=1
      status=ACTIVE
    }
```
```
2020-03-03 13:52:03.266 10975-11025/com.amplifyframework.ddsa I/MainActivity: Deleted Post{
      title=Title 6f56fc9d-1d63-4b99-a129-2ede1ff5c95e
      id=a08f9fd6-a26c-4dd4-98a6-41c533f769dd
      rating=1
      status=ACTIVE
    }
```
```
2020-03-03 13:52:12.887 10975-11025/com.amplifyframework.ddsa I/MainActivity: com.amplifyframework.datastore.DataStoreException: Predicate condition not met.
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$5(SourceFile:45)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter$$Lambda$4.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-03-03 13:53:02.408 10975-10986/com.amplifyframework.ddsa I/yframework.dds: System.exit called, status: 1
2020-03-03 13:53:02.408 10975-10986/com.amplifyframework.ddsa I/AndroidRuntime: VM exiting with result code 1, cleanup skipped.
```

**Comment by jamesonwilliams** [comment]
We will not pursue this at this time.
