### ISSUE TITLE
IllegalStateException: Tried to get a plugin but that plugin was not present

### ISSUE THREAD

**Issue by atomicalsoftwares** [aws-amplify/amplify-android#378]
When my app crashes after [Issue 377](https://github.com/aws-amplify/amplify-android/issues/377) the following error comes up if I attempt to open my app and save a new item on DataStore:

```
java.lang.IllegalStateException: Tried to get a plugin but that plugin was not present. Check if the plugin was added originally or perhaps was already removed.
        at com.amplifyframework.core.category.Category.getSelectedPlugin(Category.java:15)
        at com.amplifyframework.datastore.DataStoreCategory.query(DataStoreCategory.java:2)
        at com.deepseed.VolumeDiscountActivity.onClick(VolumeDiscountActivity.java:546)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```

**Comment by jamesonwilliams** [comment]
@atomicalsoftwares As always - I appreciate the report! Can you include the code you're using to initialize `Amplify`? e.g., where and how you are doing `Amplify.addPlugin(...)`, `Amplify.configure(...)`, etc.? My guess it that this error is only happening because of the plugin initialization failure we saw in #377, though.

**Comment by atomicalsoftwares** [comment]
When the app crashes, somehow the Splash activity was missed. Therefor, I believe you're right. Will close for now.

**Comment by hexdecimal16** [comment]
I am also getting this error, I am following the tutorial. Could you help me.
`       Amplify.DataStore.save(
                item,
                success -> Log.i("Tutorial", "Saved item: " + success.item().getName()),
                error -> Log.e("Tutorial", "Could not save item to DataStore", error)
        );`
This code is generating this error.

**Comment by bpappin** [comment]
This is a major issue for us. it seem to mainly happen to QA of course, and we are definitely configuring the plugins in the application class

**Comment by jamesonwilliams** [comment]
@bpappin you raised #1003, which is a slightly different message. Do you see both messages, or just the one in #1003?

**Comment by simone40love** [comment]
Just got this.

2021-02-11 16:39:44.798 2453-2453/com.smartapps.amplifytest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smartapps.amplifytest, PID: 2453
    java.lang.IllegalStateException: Tried to get a plugin but that plugin was not present. Check if the plugin was added originally or perhaps was already removed.
        at com.amplifyframework.core.category.Category.getSelectedPlugin(Category.java:215)
        at com.amplifyframework.datastore.DataStoreCategory.save(DataStoreCategory.java:59)
        at com.smartapps.amplifytest.MainActivity$4.onClick(MainActivity.java:163)
        at android.view.View.performClick(View.java:6597)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

                Amplify.DataStore.save(word,
                        result -> Log.i("MyAmplifyApp", "Created a new post successfully"),
                        error -> Log.e("MyAmplifyApp", "Error creating post", error)

**Comment by jamesonwilliams** [comment]
@simone40love There are a two common scenarios where this message occurs. Please try the following tips to remedy.

1. Your code doesn't include any `addPlugin()` or `configure()` calls. To remedy this, review the Getting Started documentation.
2. Your program has crashed before this message is generated, due to another failure. To remedy this, resolve the earlier issue, first.
