### ISSUE TITLE
SQLiteException: no such table 

### ISSUE THREAD

**Issue by bryannevega** [aws-amplify/amplify-android#458]
Hello,

Why when I use "EQ" filter my query executes but when I use "contains" it gives me the error mentioned above?

```
com.amplifyframework.datastore.DataStoreException: Error in querying the model.
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:64)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$jJRyJ1jI1PnOmSf78Qfq5UwDppI.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.database.sqlite.SQLiteException: no such table: type_id (code 1): , while compiling:
```

**Comment by jamesonwilliams** [comment]
Hi @bryannevega Can you please include relevant portions of your schema and a code snippet? Also, looks like the stack trace is truncated a bit. Thanks!

**Comment by Andrew-Dickinson** [comment]
I'll chime in, since I'm having exactly the same issue

**My Schema**
```GraphQL
type GroceryItem @model {
  id: ID!
  checked: Boolean!
  name: String
  position: Int!
  aisle: Aisle! @connection(name: "AisleGroceries")
}

type Aisle @model {
  id: ID!
  name: String!
  position: Int!
  groceries: [GroceryItem!]! @connection(name: "AisleGroceries")
}
```

**WORKS**
```kotlin
 Amplify.DataStore.query(
            GroceryItem::class.java, QueryField.field("GroceryItem.name").eq(queryString),
            ...
```

**DOESN'T WORK**
```kotlin
 Amplify.DataStore.query(
            GroceryItem::class.java, QueryField.field("GroceryItem.name").contains(queryString),
            ...
```
**The full stacktrace**
```java
E/SQLiteLog: (1) no such table: GroceryItem.name
E/GetStarted: Query failed.
    com.amplifyframework.datastore.DataStoreException: Error in querying the model.
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:64)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$AjrOfcrdMfHSw-j3v03LxVCjqLw.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.database.sqlite.SQLiteException: no such table: GroceryItem.name (code 1 SQLITE_ERROR): , while compiling: SELECT GroceryItem.id AS GroceryItem_id, GroceryItem.checked AS GroceryItem_checked, GroceryItem.name AS GroceryItem_name, GroceryItem.position AS GroceryItem_position, GroceryItem.groceryItemAisleId AS GroceryItem_groceryItemAisleId, Aisle.id AS Aisle_id, Aisle.name AS Aisle_name, Aisle.position AS Aisle_position FROM GroceryItem INNER JOIN Aisle ON GroceryItem.groceryItemAisleId=Aisle.id WHERE ? IN GroceryItem.name;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1443)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1382)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.getQueryAllCursor(SQLiteStorageAdapter.java:101)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:1)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$AjrOfcrdMfHSw-j3v03LxVCjqLw.run(Unknown Source:10) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by bryannevega** [comment]
> 
> 
> I'll chime in, since I'm having exactly the same issue
> 
> **My Schema**
> 
> ```graphql
> type GroceryItem @model {
>   id: ID!
>   checked: Boolean!
>   name: String
>   position: Int!
>   aisle: Aisle! @connection(name: "AisleGroceries")
> }
> 
> type Aisle @model {
>   id: ID!
>   name: String!
>   position: Int!
>   groceries: [GroceryItem!]! @connection(name: "AisleGroceries")
> }
> ```
> 
> **WORKS**
> 
> ```kotlin
>  Amplify.DataStore.query(
>         GroceryItem::class.java, QueryField.field("GroceryItem.name").eq(queryString),
>         ...
> ```
> 
> **DOESN'T WORK**
> 
> ```kotlin
>  Amplify.DataStore.query(
>         GroceryItem::class.java, QueryField.field("GroceryItem.name").contains(queryString),
>         ...
> ```
> 
> **The full stacktrace**
> 
> ```java
> E/SQLiteLog: (1) no such table: GroceryItem.name
> E/GetStarted: Query failed.
>     com.amplifyframework.datastore.DataStoreException: Error in querying the model.
>         at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:64)
>         at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$AjrOfcrdMfHSw-j3v03LxVCjqLw.run(Unknown Source:10)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:919)
>      Caused by: android.database.sqlite.SQLiteException: no such table: GroceryItem.name (code 1 SQLITE_ERROR): , while compiling: SELECT GroceryItem.id AS GroceryItem_id, GroceryItem.checked AS GroceryItem_checked, GroceryItem.name AS GroceryItem_name, GroceryItem.position AS GroceryItem_position, GroceryItem.groceryItemAisleId AS GroceryItem_groceryItemAisleId, Aisle.id AS Aisle_id, Aisle.name AS Aisle_name, Aisle.position AS Aisle_position FROM GroceryItem INNER JOIN Aisle ON GroceryItem.groceryItemAisleId=Aisle.id WHERE ? IN GroceryItem.name;
>         at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
>         at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
>         at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
>         at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
>         at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
>         at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
>         at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
>         at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1443)
>         at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1382)
>         at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.getQueryAllCursor(SQLiteStorageAdapter.java:101)
>         at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:1)
>         at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$AjrOfcrdMfHSw-j3v03LxVCjqLw.run(Unknown Source:10) 
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:919) 
> ```
> 
> Edit: I'm using Kotlin, but the snippets are pretty simple. I can provide Java translations if you need.

Exactly the same :) (using latest available sdk)

**Comment by rjuliano** [comment]
A new version (1.1.0) has just been released that includes a fix for this. If you encounter this error, feel free to re-open this issue.
