### ISSUE TITLE
Crashes when subscribe fails

### ISSUE THREAD

**Issue by jpignata** [aws-amplify/amplify-android#466]
Currently, an Android application using DataStore and API crashes when subscribe fails. I can reproduce this by creating an API but not pushing it, or simulating low signal conditions using the emulator, with slightly different stack traces:

**No API available**

```
Caused by: com.amplifyframework.api.ApiException: There is no API configured for this plugin with matching endpoint type.
        at com.amplifyframework.api.aws.AWSApiPlugin.selectApiName(AWSApiPlugin.java:13)
```

**Low signal conditions**

```
Caused by: com.amplifyframework.api.ApiException: Subscription timed out waiting for acknowledgement
```

**Full log**

```
2020-05-13 20:21:59.317 16486-16486/? I/m.example.todo: Not late-enabling -Xcheck:jni (already on)
2020-05-13 20:21:59.461 16486-16486/? W/m.example.todo: Unexpected CPU variant for X86 using defaults: x86
2020-05-13 20:22:00.564 16486-16486/com.example.todo7 I/MultiDex: VM with version 2.1.0 has multidex support
2020-05-13 20:22:00.564 16486-16486/com.example.todo7 I/MultiDex: Installing application
2020-05-13 20:22:00.564 16486-16486/com.example.todo7 I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2020-05-13 20:22:00.867 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
2020-05-13 20:22:00.867 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
2020-05-13 20:22:00.867 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
2020-05-13 20:22:00.867 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
2020-05-13 20:22:00.867 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
2020-05-13 20:22:01.068 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
2020-05-13 20:22:01.068 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2020-05-13 20:22:01.113 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
2020-05-13 20:22:01.968 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (light greylist, reflection)
2020-05-13 20:22:01.968 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setHostname(Ljava/lang/String;)V (light greylist, reflection)
2020-05-13 20:22:01.968 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
2020-05-13 20:22:01.968 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
2020-05-13 20:22:02.016 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
2020-05-13 20:22:02.016 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
2020-05-13 20:22:02.016 16486-16486/com.example.todo7 W/m.example.todo: Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
2020-05-13 20:22:02.017 16486-16486/com.example.todo7 D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-05-13 20:22:02.064 16486-16486/com.example.todo7 I/Tutorial: Initialized Amplify
2020-05-13 20:22:02.260 16486-16526/com.example.todo7 W/m.example.todo: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
2020-05-13 20:22:25.821 16486-16526/com.example.todo7 W/amplify:aws-datastore: Could not find getLastSyncTime() on com.amplifyframework.datastore.syncengine.LastSyncMetadata. Fallback to direct field access.
2020-05-13 20:22:25.821 16486-16526/com.example.todo7 W/amplify:aws-datastore: Could not find getModelClassName() on com.amplifyframework.datastore.syncengine.LastSyncMetadata. Fallback to direct field access.
2020-05-13 20:22:25.910 16486-16526/com.example.todo7 I/Tutorial: ==== Todo ====
2020-05-13 20:22:25.910 16486-16526/com.example.todo7 I/Tutorial: Name: Tidy up the office
2020-05-13 20:22:25.910 16486-16526/com.example.todo7 I/Tutorial: Priority: NORMAL
2020-05-13 20:22:25.910 16486-16526/com.example.todo7 I/Tutorial: Description: Organize books, vaccuum, take out the trash
2020-05-13 20:22:25.910 16486-16526/com.example.todo7 I/Tutorial: ==== Todo ====
2020-05-13 20:22:25.910 16486-16526/com.example.todo7 I/Tutorial: Name: Build Android application
2020-05-13 20:22:25.910 16486-16526/com.example.todo7 I/Tutorial: Description: Build an Android Application using Amplify
2020-05-13 20:22:25.960 16486-16486/com.example.todo7 D/OpenGLRenderer: Skia GL Pipeline
2020-05-13 20:22:30.867 16486-16545/com.example.todo7 D/HostConnection: HostConnection::get() New Host Connection established 0xe1b99a60, tid 16545
2020-05-13 20:22:30.868 16486-16545/com.example.todo7 D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
2020-05-13 20:22:31.009 16486-16545/com.example.todo7 I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2020-05-13 20:22:31.011 16486-16545/com.example.todo7 I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2020-05-13 20:22:31.011 16486-16545/com.example.todo7 I/OpenGLRenderer: Initialized EGL, version 1.4
2020-05-13 20:22:31.011 16486-16545/com.example.todo7 D/OpenGLRenderer: Swap behavior 1
2020-05-13 20:22:31.012 16486-16545/com.example.todo7 W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2020-05-13 20:22:31.012 16486-16545/com.example.todo7 D/OpenGLRenderer: Swap behavior 0
2020-05-13 20:22:31.012 16486-16545/com.example.todo7 D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
2020-05-13 20:22:31.012 16486-16545/com.example.todo7 D/EGL_emulation: eglCreateContext: 0xe565d0e0: maj 3 min 0 rcv 3
2020-05-13 20:22:31.013 16486-16545/com.example.todo7 D/EGL_emulation: eglMakeCurrent: 0xe565d0e0: ver 3 0 (tinfo 0xe97d2d70)
2020-05-13 20:22:31.272 16486-16545/com.example.todo7 D/HostConnection: createUnique: call
2020-05-13 20:22:31.272 16486-16545/com.example.todo7 D/HostConnection: HostConnection::get() New Host Connection established 0xcdd74050, tid 16545
2020-05-13 20:22:31.361 16486-16545/com.example.todo7 D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
2020-05-13 20:22:31.361 16486-16545/com.example.todo7 E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
2020-05-13 20:22:31.409 16486-16545/com.example.todo7 D/EGL_emulation: eglMakeCurrent: 0xe565d0e0: ver 3 0 (tinfo 0xe97d2d70)
2020-05-13 20:22:31.412 16486-16545/com.example.todo7 D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 3 2
2020-05-13 20:22:37.219 16486-16527/com.example.todo7 W/amplify:aws-datastore: Error enqueuing mutation from subscription.
    com.amplifyframework.datastore.DataStoreException: Error during subscription.
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:27)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amplifyframework.api.ApiException: Subscription timed out waiting for acknowledgement
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:27) 
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4) 
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2020-05-13 20:22:48.172 16486-16528/com.example.todo7 W/System.err: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.amplifyframework.datastore.DataStoreException: Error during subscription.
2020-05-13 20:22:48.209 16486-16528/com.example.todo7 W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
2020-05-13 20:22:48.209 16486-16528/com.example.todo7 W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
2020-05-13 20:22:48.209 16486-16528/com.example.todo7 W/System.err:     at com.amplifyframework.datastore.syncengine.-$$Lambda$3JRr2oIVsg2CVfQ5dpNXlh4mgog.accept(Unknown Source:4)
2020-05-13 20:22:48.210 16486-16528/com.example.todo7 W/System.err:     at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
2020-05-13 20:22:48.210 16486-16528/com.example.todo7 W/System.err:     at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
2020-05-13 20:22:48.210 16486-16528/com.example.todo7 W/System.err:     at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:101)
2020-05-13 20:22:48.269 16486-16528/com.example.todo7 W/System.err:     at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4)
2020-05-13 20:22:48.269 16486-16528/com.example.todo7 W/System.err:     at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2)
2020-05-13 20:22:48.269 16486-16528/com.example.todo7 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020-05-13 20:22:48.269 16486-16528/com.example.todo7 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-05-13 20:22:48.269 16486-16528/com.example.todo7 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-05-13 20:22:48.269 16486-16528/com.example.todo7 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-05-13 20:22:48.270 16486-16528/com.example.todo7 W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-05-13 20:22:48.270 16486-16528/com.example.todo7 W/System.err: Caused by: com.amplifyframework.datastore.DataStoreException: Error during subscription.
2020-05-13 20:22:48.270 16486-16528/com.example.todo7 W/System.err: 	... 10 more
2020-05-13 20:22:48.270 16486-16528/com.example.todo7 W/System.err: Caused by: com.amplifyframework.api.ApiException: Subscription not acknowledged.
2020-05-13 20:22:48.271 16486-16528/com.example.todo7 W/System.err:     at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:100)
2020-05-13 20:22:48.271 16486-16528/com.example.todo7 W/System.err: 	... 7 more
2020-05-13 20:22:48.315 16486-16528/com.example.todo7 E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-2
    Process: com.example.todo7, PID: 16486
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.amplifyframework.datastore.DataStoreException: Error during subscription.
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$3JRr2oIVsg2CVfQ5dpNXlh4mgog.accept(Unknown Source:4)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:101)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amplifyframework.datastore.DataStoreException: Error during subscription.
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1) 
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4) 
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:101) 
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4) 
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: com.amplifyframework.api.ApiException: Subscription not acknowledged.
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:100)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4) 
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2020-05-13 20:22:48.512 16486-16528/com.example.todo7 I/Process: Sending signal. PID: 16486 SIG: 9
```

**Comment by jpignata** [comment]
Reopening.

Hmm, not in my testing. @rjuliano any thoughts?

**Comment by jpignata** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-android/issues/541 which appears to be the remaining problem -- please re-open if this is a distinct issue.

**Comment by woutermilants** [comment]
`W/System.err: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription completion not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$e4FRR6iHUV0ToSpRUkOM1VPObso.accept(lambda)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
W/System.err:     at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(lambda)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionCompleted(SubscriptionEndpoint.java:3)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(SubscriptionEndpoint.java:26)
        at com.amplifyframework.api.aws.SubscriptionOperation.cancel(SubscriptionOperation.java:3)
        at com.amplifyframework.datastore.AmplifyDisposables$1.dispose(AmplifyDisposables.java:3)
        at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.dispose(ObservableCreate.java:121)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:86)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:72)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$e4FRR6iHUV0ToSpRUkOM1VPObso.accept(lambda)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$2$AppSyncClient(AppSyncClient.java:4)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$KK1x1_fo5sffWREukMLi8z0goy4.accept(lambda)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchNextMessage(SubscriptionEndpoint.java:1)
W/System.err:     at com.amplifyframework.api.aws.SubscriptionEndpoint.processJsonMessage(SubscriptionEndpoint.java:44)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.access$100(SubscriptionEndpoint.java:1)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$1.onMessage(SubscriptionEndpoint.java:1)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
W/System.err: Caused by: AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription completion not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
    	... 26 more
W/System.err: Caused by: AmplifyException {message=Subscription completion not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionCompleted(SubscriptionEndpoint.java:2)
    	... 23 more
E/AndroidRuntime: FATAL EXCEPTION: OkHttp https://orcmuw6ilvgqnnsw4ybji6uz2a.appsync-realtime-api.eu-west-1.amazonaws.com/...
    Process: be.milants.loonskleinfruit, PID: 17964
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription completion not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$e4FRR6iHUV0ToSpRUkOM1VPObso.accept(lambda)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(lambda)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionCompleted(SubscriptionEndpoint.java:3)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(SubscriptionEndpoint.java:26)
        at com.amplifyframework.api.aws.SubscriptionOperation.cancel(SubscriptionOperation.java:3)
        at com.amplifyframework.datastore.AmplifyDisposables$1.dispose(AmplifyDisposables.java:3)
        at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.dispose(ObservableCreate.java:121)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:86)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:72)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$e4FRR6iHUV0ToSpRUkOM1VPObso.accept(lambda)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$2$AppSyncClient(AppSyncClient.java:4)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$KK1x1_fo5sffWREukMLi8z0goy4.accept(lambda)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchNextMessage(SubscriptionEndpoint.java:1)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.processJsonMessage(SubscriptionEndpoint.java:44)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.access$100(SubscriptionEndpoint.java:1)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$1.onMessage(SubscriptionEndpoint.java:1)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription completion not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1) 
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(lambda) 
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionCompleted(SubscriptionEndpoint.java:3) 
        at com.amplifyframework.api.aws.SubscriptionEndpoint.releaseSubscription(SubscriptionEndpoint.java:26) 
        at com.amplifyframework.api.aws.SubscriptionOperation.cancel(SubscriptionOperation.java:3) 
        at com.amplifyframework.datastore.AmplifyDisposables$1.dispose(AmplifyDisposables.java:3) 
        at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124) 
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.dispose(ObservableCreate.java:121) 
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:86) 
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:72) 
        at com.amplifyframework.datastore.syncengine.-$$Lambda$e4FRR6iHUV0ToSpRUkOM1VPObso.accept(lambda) 
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$2$AppSyncClient(AppSyncClient.java:4) 
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$KK1x1_fo5sffWREukMLi8z0goy4.accept(lambda) 
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchNextMessage(SubscriptionEndpoint.java:1) 
        at com.amplifyframework.api.aws.SubscriptionEndpoint.processJsonMessage(SubscriptionEndpoint.java:44) 
        at com.amplifyframework.api.aws.SubscriptionEndpoint.access$100(SubscriptionEndpoint.java:1) 
        at com.amplifyframework.api.aws.SubscriptionEndpoint$1.onMessage(SubscriptionEndpoint.java:1) 
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333) 
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245) 
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106) 
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293) 
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: AmplifyException {message=Subscription completion not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionCompleted(SubscriptionEndpoint.java:2)
        	... 23 more`

I still experience this issue. Without having any network related issues

**Comment by joekiller** [comment]
I finally fix this in https://github.com/aws-amplify/amplify-android/pull/1755
