### ISSUE TITLE
Subscription fails when following Getting Started doc steps

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-android#483]
I am building amplify-android from the sources, on master branch.

When following the steps in Next Doc's [Getting started doc](https://next-docs.amplify.aws/lib/getting-started/integrate/q/platform/android#configure-amplify-and-datastore), Amplify Datastore subscription fails with 

```
W/amplify:aws-datastore: An error occurred on the remote Todo subscription for model ON_CREATE.
    AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription timed out waiting for acknowledgement, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:27)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: AmplifyException {message=Subscription timed out waiting for acknowledgement, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:27) 
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4) 
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
W/amplify:aws-datastore: An error occurred on the remote Todo subscription for model ON_DELETE.
    AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:101)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: AmplifyException {message=Subscription not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:100)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4) 
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
W/amplify:aws-datastore: An error occurred on the remote Todo subscription for model ON_UPDATE.
    AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:1)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:101)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: AmplifyException {message=Subscription not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:100)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$0$SubscriptionOperation(SubscriptionOperation.java:4) 
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$FXgdmzMG9ubNhC1f2NTwXyG53uo.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

```

**Comment by sebsto** [comment]
I forgot how sensitive the Android simulator is to network changes (on / off VPN).  The simulator had no access to the internet.  My bad.

**Comment by jamesonwilliams** [comment]
@sebsto Thanks for following up - that's what I suspected based on this message:
```
Subscription not acknowledged.
```

We should have some improvements coming soon, for more gracefully handling network conditions.
