### ISSUE TITLE
Could not initialize Amplify - Neither Cognito Identity or Cognito UserPool was used.

### ISSUE THREAD

**Issue by Scarlett13** [aws-amplify/amplify-android#549]
Hi, I am developing android app using amplify framework right now, previously I setup my cognito using sample provided in: https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoYourUserPoolsDemo -- and right now I want to change the Auth process using this amplify-android and follows aws amplify for android latest documentation.

Issue:
I am getting this error on the log:
```
2020-06-01 16:04:28.522 7964-7964/com.example.testauthexample E/MyAmplifyApp: Could not initialize Amplify - 
    AmplifyException {message=Failed to instantiate AWSMobileClient, cause=java.lang.RuntimeException: Neither Cognito Identity or Cognito UserPool was used. At least one must be present to use AWSMobileClient., recoverySuggestion=See attached exception for more details}
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.configure(AWSCognitoAuthPlugin.java:87)
        at com.amplifyframework.core.category.Category.configure(Category.java:13)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:17)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:1)
        at com.cryptoscope_.cts_doctor.activity.SplashActivity.onCreate(SplashActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:7353)
        at android.app.Activity.performCreate(Activity.java:7344)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3140)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3303)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1991)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7258)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.RuntimeException: Neither Cognito Identity or Cognito UserPool was used. At least one must be present to use AWSMobileClient.
        at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:587)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
```
that error comes from:

```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        try {
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.configure(getApplicationContext());

            Log.i("MyAmplifyApp", "Initialized Amplify");
        } catch (AmplifyException error) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify - ", error);
        }
}
```
and this is my awsconfiguration.json look like:

```json
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "pool-id",
                "Region": "ap-southeast-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "pool-id",
            "AppClientId": "id",
            "AppClientSecret": "secret",
            "Region": "ap-southeast-1"
        }
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "CUSTOM_AUTH"
        }
    },
    "S3TransferUtility": {
        "Default": {
            "Bucket": "bucket-dev",
            "Region": "ap-southeast-1"
        }
    }
}
```
and for amplifyconfiguration.json:

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "bucket",
                "region": "ap-southeast-1",
                "defaultAccessLevel": "guest"
            }
        }
    }
}
```

my current amplify cli --v : 4.17.2

can you help me to solve this problem? Thanks in advance.

**Comment by Scarlett13** [comment]
When I tried to call Amplify.Auth.fetchAuthSession() it doesnt produce error, instead, it return 

AWSCognitoAuthSession{isSignedIn=false, awsCredentials=AuthSessionResult{value=null, error=AmplifyException {message=The account type you have configured doesn't support this operation., cause=null, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}, userSub='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}', identityId='AuthSessionResult{value=null, error=AmplifyException {message=The account type you have configured doesn't support this operation., cause=null, recoverySuggestion=Update your Auth configuration to an account type which supports this operation.}, type=FAILURE}', userPoolTokens='AuthSessionResult{value=null, error=AmplifyException {message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'}

**Comment by ducthinh2111** [comment]
I have this problem too. Hope someone can help

**Comment by TrekSoft** [comment]
Hey, so the new Amplify Auth category doesn't actually use awsconfiguration anymore. All its config data now is in amplifyconfiguration. To migrate is actually very simple. Simply take all (yes, literally all) the contents of the awsconfiguration file and insert them into the amplifyconfiguration file under these keys:

```json
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "auth": {
      "plugins": {
        "awsCognitoAuthPlugin": {
          <paste contents of awsconfiguration.json>
        }
    }
  }
}
```

**Comment by Scarlett13** [comment]
> Hey, so the new Amplify Auth category doesn't actually use awsconfiguration anymore. All its config data now is in amplifyconfiguration. To migrate is actually very simple. Simply take all (yes, literally all) the contents of the awsconfiguration file and insert them into the amplifyconfiguration file under these keys:
> 
> ```json
> {
>     "UserAgent": "aws-amplify-cli/2.0",
>     "Version": "1.0",
>     "auth": {
>       "plugins": {
>         "awsCognitoAuthPlugin": {
>           <paste contents of awsconfiguration.json>
>         }
>     }
>   }
> }
> ```

Man, I have a UAT tomorrow and you just helped me resolve my issue. Thank you so much, I can confirm your solution really solved the problem. 

I will close this issue, thanks and sorry for bugging you. Have a good day.!
