### ISSUE TITLE
App crashes when doing Amplify.DataStore.clear(...) after initilization

### ISSUE THREAD

**Issue by btdo** [aws-amplify/amplify-android#581]
Hi,

I get an exception when I try to clear the cache of the datastore right after initialization.  Here is my code 

```kotlin
try {
    val authProviders = ApiAuthProviders.builder()
        .oidcAuthProvider(AuthenticationServiceImpl)
        .build()
    Amplify.addPlugin(AWSDataStorePlugin())
    Amplify.addPlugin(AWSApiPlugin(authProviders)) // If using remote model synchronization
    Amplify.configure(applicationContext)
    Log.i("MyAmplifyApp", "Initialized Amplify")
    Amplify.DataStore.clear(Action { Timber.d("Cache Cleared") }, Consumer { Timber.e("Error while clearing cache") })
} catch (error: AmplifyException) {
    Log.e("MyAmplifyApp", "Could not initialize Amplify", error)
}.
```

Here is my exception:
```console
2020-06-15 21:51:25.086 31152-31216/com.wwm.trackappsyncapp E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-2
    Process: com.wwm.trackappsyncapp, PID: 31152
    java.lang.NullPointerException: next is null
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.Completable.andThen(Completable.java:1181)
        at com.amplifyframework.datastore.AWSDataStorePlugin.initialize(AWSDataStorePlugin.java:6)
        at com.amplifyframework.core.category.Category.initialize(Category.java:15)
        at com.amplifyframework.core.Amplify.lambda$beginInitialization$0(Amplify.java:1)
```

Thanks

**Comment by eeatonaws** [comment]
I get the same exception when completing the "Integrate in your app" section of the Amplify Getting Started tutorial, specifically when attempting to save an item to the datastore. The code (from the tutorial) is:
` Amplify.DataStore.save(
         item,
         success -> Log.i("Tutorial", "Saved item: " + success.item().getName()),
         error -> Log.e("Tutorial", "Could not save item to DataStore", error)
 );`

**Comment by rjuliano** [comment]
Apologies for the delay on this. I am actively focused on a fix for this issue. Will provide an update ASAP.

**Comment by rjuliano** [comment]
A new version (1.1.0) has just been released that includes a fix for this. If you encounter this error, feel free to re-open this issue.
