### ISSUE TITLE
Storage upload operation was interrupted

### ISSUE THREAD

**Issue by coolrukshan** [aws-amplify/amplify-android#583]
I'm getting an error while uploading a file to S3 by using Amplify:

```java
StorageUploadFileOptions options =
    StorageUploadFileOptions.builder()
        .accessLevel(StorageAccessLevel.PUBLIC)
        .build();
Amplify.Storage.uploadFile(
    type + "/" + file.getName(),
    file,
    options,
    result -> onFileUpload(result),
    storageFailure -> Log.e("MyAmplifyApp", "Upload failed", storageFailure)
);
```

> AmplifyException {message=Storage upload operation was interrupted., cause=null, recoverySuggestion=Please verify that you have a stable internet connection.}

The file size is 49KB.
My connection speed is totally OK.

**Comment by jamesonwilliams** [comment]
@coolrukshan Hm. Can you add this bit of code before you call `Amplify.addPlugin(...)`, and `Amplify.configure(...)`?

```java
List<Class<?>> classes = Arrays.asList(
    TransferUtility.class,
    TransferService.class,
    UploadTask.class,
    UploadPartTask.class
);
for (Class<?> clazz : classes) {
    LogFactory.getLog(clazz).setLevel(Level.ALL);
}
```

Then, can you watch the output of:
```console
adb logcat
```

while the `Amplify.Storage.uploadFile(...)` is executed?

**Comment by coolrukshan** [comment]
@jamesonwilliams 
UploadTask.class and UploadPartTask.class are not available for me. What is the dependency that I need to use?

**Comment by jamesonwilliams** [comment]
> @jamesonwilliams
> UploadTask.class and UploadPartTask.class are not available for me. What is the dependency that I need to use?

Apologies, I hadn't considered that those two files are _packge-private_-access in the SDK, at [`com.amazonaws.mobileconnectors.s3.transferutility`](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility).

You could still escalate their logging, but you'd have to create a file in your project under `src/main/java/com/amazonaws/mobileconnectors/s3/transferutility`:

```
package com.amazonaws.mobileconnectors.s3.transferutility;

public final class LogHack {
    private LogHack() {}

    public static void escalateLogging() {
        List<Class<?>> classes = Arrays.asList(
            TransferUtility.class,
            TransferService.class,
            UploadTask.class,
            UploadPartTask.class
        );
        for (Class<?> clazz : classes) {
            LogFactory.getLog(clazz).setLevel(Level.ALL);
        }
    }
}
```

**Comment by coolrukshan** [comment]
@jamesonwilliams 
try {
            LogHack.escalateLogging();
            Amplify.addPlugin(new AWSCognitoAuthPlugin());
            Amplify.addPlugin(new AWSS3StoragePlugin());
            Amplify.configure(getApplicationContext());
            L.i("MyAmplifyApp", "Initialized Amplify");
        } catch (AmplifyException error) {
            L.e("MyAmplifyApp", "Could not initialize Amplify" + error);
        }

add the class that you mention. but no response from the server. 

2020-06-17 20:47:51.551 9418-11170/com.wwi.doctornurse D/AWSMobileClient: Inspecting user state details
2020-06-17 20:47:51.552 9418-11170/com.wwi.doctornurse D/AWSMobileClient: waitForSignIn: userState:GUEST
2020-06-17 20:47:51.593 9418-11170/com.wwi.doctornurse I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-06-17 20:47:51.593 9418-11170/com.wwi.doctornurse I/System.out: (HTTPLog)-Static: isSBSettingEnabled false

**Comment by tendynewbies** [comment]
Hi,

I'm also facing similar issue in my app, while tried to upload file to S# bucket.
`Amplify.Storage.uploadFile("public/"+selectedFile.getName(),
                                        selectedFile,
                                        builder.build(),
                                        result -> uploadSuccess(result),
                                        storageFailure -> uploadFailed(storageFailure));`

**Exception Logs:**

```
AmplifyException {message=Something went wrong with your AWS S3 Storage upload file operation, cause=com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9AB2151FA54B14E0), S3 Extended Request ID: I1JGmENse9Ep7kRZpON/Hk5HaMJTN9WzHtE1kBy3jDdVWyiF5MCyE2c0Vgx+Vb2aDSl6pB2t3cQ=, recoverySuggestion=See attached exception for more information and suggestions}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:5)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:288)
...............

Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9AB2151FA54B14E0), S3 Extended Request ID: I1JGmENse9Ep7kRZpON/Hk5HaMJTN9WzHtE1kBy3jDdVWyiF5MCyE2c0Vgx+Vb2aDSl6pB2t3cQ=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4913)
        at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3702)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.initiateMultipartUpload(UploadTask.java:392)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:130)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:109)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)

.....................

 AmplifyException {message=Storage upload operation was interrupted., cause=null, recoverySuggestion=Please verify that you have a stable internet connection.}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onStateChanged(AWSS3StorageUploadFileOperation.java:10)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:206)

```

Don't know what's wrong. Please help if possible.

**Comment by jamesonwilliams** [comment]
@tendynewbies You've got an `Access Denied`, there, so that's different. Can you please open a separate issue?
