### ISSUE TITLE
Temporal date types don't work with DataStore category

### ISSUE THREAD

**Issue by tomasfelder** [aws-amplify/amplify-android#590]
Hi,
I'm having an issue while using the AWS DataStore. I need my datastore to sync with the cloud. In my schema I have some types that have a field of `AWSDateTime` data type. When I generate my models for android in Java it creates the objects and the `AWSDateTime` is parsed to a `Temporal.DateTime` object. I create the object and it is stored correctly to the de DataStore, but the problem occurs when it wants to sync it with the cloud. It seems like the automatic generated mutation is not able to parse the `DateTime` object correctly and it fails. I get the following error:

```console
AmplifyException {message=Mutation failed. Failed mutation = PendingMutation{mutatedItem=TecpronProject {id=0becde35-31e2-408e-bbab-6607a30162ed, name=TEC2020, startDate=Temporal.DateTime{offsetDateTime='2020-06-19T13:20:37.951Z'}}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.TecpronProject, mutationType=CREATE, mutationId=aa6cb76d-b22f-11ea-9c05-873b0e7d83c4, predicate=null}. AppSync response contained errors = [GraphQLResponse.Error{message='Variable 'startDate' has an invalid value. Unable to parse `{offsetDateTime={dateTime={date={day=19, month=6, year=2020}, time={hour=13, minute=20, nano=951000000, second=37}}, offset={totalSeconds=0}}}` as a valid DateTime Object.', locations='[GraphQLLocation{line='1', column='31'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Verify that your AppSync endpoint is able to store TecpronProject models.}
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$null$11(MutationProcessor.java:7)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$w1EW1gU2W9mWN5QztizneJ-zhAE.accept(Unknown Source:8)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$4$AppSyncClient(AppSyncClient.java:2)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$nKAFu77xjCuzuWw9lR7faFIdN9U.accept(Unknown Source:8)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:16)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

The problem is I can't change the form of the mutation because it is generated automatically. One solution i thought is to change the `AWSDateTime` type in the schema to String, but I was wondering if there is a better solution.

Thank you!

**Comment by richardmcclellan** [comment]
Hi @tomasfelder,  the `Temporal` types currently work with the `API` category but don't yet work the `DataStore` category.   As a workaround, if you need a solution now, you could store your date using a `String` type.    That said, we are currently working on adding proper support for the `Temporal` types in `DataStore`, which should be available soon.

**Comment by a-melnyk** [comment]
hi @richardissuperman, could you add this information to [DataSore docs](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android) please? it would have saved my team a few hours

**Comment by richardissuperman** [comment]
@a-melnyk i believe you tag the wrong richard @richardmcclellan  ;)

**Comment by richardmcclellan** [comment]
@tomasfelder @a-melnyk `Temporal` types are now supported with `DataStore`, in version `1.1.0`, which we just released today.   If you still have issues, feel free to comment on this issue with details.

**Comment by watanabethais** [comment]
Hi!
I'm testing the new Amplify library version `1.1.1` with DataStore cloud syncing using this schema:

```graphql
type WindTurbine @model
@auth(rules: [{allow: private}]) {
  id: ID!
  name: String!
  windFarm: String!
  brand: String!
  model: String!
  hydraulicUnitModel: String!
  author: String
  createdAt: AWSDateTime
}
```

When I create a new data, the method `Amplify.DataStore.save` runs fine using the code below:
```java
WindTurbine post = WindTurbine.builder()
                .name("test")
                .windFarm("test")
                .brand("test")
                .model("test")
                .hydraulicUnitModel("test")
                .author("test")
                .createdAt(new Temporal.DateTime("2020-01-08T13:55:01.114Z"))
                .build();

        Amplify.DataStore.save(post,
                saved -> Log.i(TAG, "Saved."),
                failure -> Log.e(TAG, "Save failed.", failure)
        );
```

But then I run the `Amplify.DataStore.query` method, it throws the error below:

```
E/MainActivity: Query failed.
    AmplifyException {message=Error in querying the model., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.time.LocalDateTime.toString()' on a null object reference, recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:413)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.time.LocalDateTime.toString()' on a null object reference
        at java.time.OffsetDateTime.toString(OffsetDateTime.java:1906)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.core.model.temporal.Temporal$DateTime.toString(Temporal.java:260)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at com.amplifyframework.datastore.generated.model.WindTurbine.hashCode(WindTurbine.java:111)
        at java.util.HashMap.hash(HashMap.java:338)
        at java.util.HashMap.put(HashMap.java:611)
        at java.util.HashSet.add(HashSet.java:219)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:407)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

Am I using the Temporal.DateTime correctly?
