### ISSUE TITLE
AmplifyException {message=Wanted 1 metadata for item with id =****, but had 0., cause=null}

### ISSUE THREAD

**Issue by bryannevega** [aws-amplify/amplify-android#623]
Hello,

Please see the following log:

https://pastebin.com/uBXu2RyY

I have no idea how this happened :(

Libraries: 
```
 implementation 'com.amplifyframework:core:1.0.0'
    implementation 'com.amplifyframework:aws-api:1.0.0' // If using cloud sync
    implementation 'com.amplifyframework:aws-datastore:1.0.0'
```

Android Studio Version 4.2 Canary 2

**Comment by richardmcclellan** [comment]
Hi @bryannevega, could you share the code that is causing this error?

**Comment by bryannevega** [comment]
> 
> 
> Hi @bryannevega, can you include the code you're using to setup/configure Amplify, as well as the code resulting in this error? Are you following a particular guide from the documentation?

This simply pops in my logs, doesn't crash my app or anything and I can continue to use Amplify as if nothing happened for some reason.

I can't actually precise how to replicate this issue but it does show often enough. If you have any more guidance I'm more than happy to share anything that can  be of help.

**Comment by richardmcclellan** [comment]
From your logs, I see you are getting this error:

```
PendingMutation{mutatedItem=com.amplifyframework.datastore.generated.model.Pour@899c9084, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Pour, mutationType=DELETE, mutationId=72f5e14c-beeb-11ea-8499-bdd318c05be8, predicate=null}
    AmplifyException {message=Wanted 1 metadata for item with id = d928a675-1443-4013-a180-49746b5c2ad3, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:25)
        at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:1)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$LCAIsERtpNmpH8Lb4RN9sRgYzuY.accept(Unknown Source:8)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:42)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$CxFeClFgMnCdkUir6dsRxPfXmiA.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

Looks like you are using the `DataStore` category, and a mutation is failing because there is no `_version` property in the VersionRepository.  When using DataStore, `_version` is used to resolve conflicts with your AppSync API when syncing. 

Make sure you have conflict detection enabled by doing the following:  Run `amplify update api`, choose `GraphQL`, then choose `Enable DataStore for entire API`.  If instead you see `Disable DataStore for entire API`, then disregard this suggestion as this is probably not the solution to your issue.
