### ISSUE TITLE
Access Denied | Store data in S3 bucket

### ISSUE THREAD

**Issue by tendynewbies** [aws-amplify/amplify-android#629]
I'm facing an issue while uploading a video via `Amplify.Storage`.

**Here's my issue:**

```
Amplify.Storage.uploadFile(
    "public/" + selectedFile.getName(),
    selectedFile,
    builder.build(),
    result -> uploadSuccess(result),
    storageFailure -> uploadFailed(storageFailure)
);
```

Exception logs:

```console
AmplifyException {message=Something went wrong with your AWS S3 Storage upload file operation, cause=com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9AB2151FA54B14E0), S3 Extended Request ID: I1JGmENse9Ep7kRZpON/Hk5HaMJTN9WzHtE1kBy3jDdVWyiF5MCyE2c0Vgx+Vb2aDSl6pB2t3cQ=, recoverySuggestion=See attached exception for more information and suggestions}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onError(AWSS3StorageUploadFileOperation.java:5)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$4.run(TransferStatusUpdater.java:288)
...............

Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9AB2151FA54B14E0), S3 Extended Request ID: I1JGmENse9Ep7kRZpON/Hk5HaMJTN9WzHtE1kBy3jDdVWyiF5MCyE2c0Vgx+Vb2aDSl6pB2t3cQ=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4913)
        at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3702)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.initiateMultipartUpload(UploadTask.java:392)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:130)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:109)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:59)

.....................

 AmplifyException {message=Storage upload operation was interrupted., cause=null, recoverySuggestion=Please verify that you have a stable internet connection.}
        at com.amplifyframework.storage.s3.operation.AWSS3StorageUploadFileOperation$UploadTransferListener.onStateChanged(AWSS3StorageUploadFileOperation.java:10)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:206)
```

Please help!!

Role of User in my Identity Pool did not have correct policy attached to it.

**Comment by tendynewbies** [comment]
User in my Identity Pool - Role did not have correct policy attached to it.

**Comment by jamesonwilliams** [comment]
Amplify Flutter

**Comment by jamesonwilliams** [comment]
It was reported to me that the Storage APIs will fire _two_ errors to the error consumer in this case. We should only ever fire one result XOR one error.
