### ISSUE TITLE
Support OIDC providers via @auth directive

### ISSUE THREAD

**Issue by btdo** [aws-amplify/amplify-android#667]
Hello,

I'm using amplify datastore to talk to an appsync api on the cloud. When I have "{ allow: owner, ownerField: "owner", provider: oidc, identityClaim: "sub" }" as a rule in the @auth annotation in my schema, it would crash about 10 seconds after I've started up my app with an "Subscription not acknowledged" exception.

Here's my schema
```
type TrackItem @model
@key(name: "byOwnerIdAndPin" fields: ["owner", "pin"] queryField: "itemsByOwnerIdAndPin")
@auth( rules: [ { allow: owner, ownerField: "owner", provider: oidc, identityClaim: "sub" },
                { allow: public, operations: [read, create, delete, update] } ])
{
    id: ID!
    pin: String!
    description: String
    type: String
    owner: String
    createdAt: AWSDateTime
}
```

Here's the exception that I've got 
``` 
2020-07-24 09:11:34.523 24938-25022/com.wwm.trackappsyncapp W/amplify:aws-datastore: An error occurred on the remote TrackItem subscription for model ON_UPDATE.
    io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
        at io.reactivex.internal.operators.observable.ObservableRetryBiPredicate$RetryBiObserver.onError(ObservableRetryBiPredicate.java:76)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.tryOnError(ObservableCreate.java:84)
        at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:72)
        at com.amplifyframework.datastore.syncengine.SubscriptionProcessor.lambda$null$2(SubscriptionProcessor.java:153)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$SubscriptionProcessor$yRs1vqJ5D9LjfDZzlfSxCR3K8no.accept(Unknown Source:6)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:339)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$null$1$SubscriptionOperation(SubscriptionOperation.java:94)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$EfR-sAOj2xzA_-vAoxWBdb2iFk8.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchError(SubscriptionEndpoint.java:377)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionReady(SubscriptionEndpoint.java:329)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:161)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$2$SubscriptionOperation(SubscriptionOperation.java:83)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$Uz-v98-sFPcWrrCLK25EF8LKbXo.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
      ComposedException 1 :
    	AmplifyException {message=Error during subscription., cause=AmplifyException {message=Subscription not acknowledged., cause=java.lang.RuntimeException: java.lang.InterruptedException, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:339)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$null$1$SubscriptionOperation(SubscriptionOperation.java:94)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$EfR-sAOj2xzA_-vAoxWBdb2iFk8.accept(Unknown Source:4)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchError(SubscriptionEndpoint.java:377)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionReady(SubscriptionEndpoint.java:329)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:161)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$2$SubscriptionOperation(SubscriptionOperation.java:83)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$Uz-v98-sFPcWrrCLK25EF8LKbXo.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-07-24 09:11:34.523 24938-25022/com.wwm.trackappsyncapp W/amplify:aws-datastore: 	Caused by: AmplifyException {message=Subscription not acknowledged., cause=java.lang.RuntimeException: java.lang.InterruptedException, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionReady(SubscriptionEndpoint.java:329)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:161)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$2$SubscriptionOperation(SubscriptionOperation.java:83) 
```

Here are my dependencies
```
implementation 'com.amplifyframework:core:1.1.1'
implementation 'com.amplifyframework:aws-api:1.1.1' // If using cloud sync
implementation 'com.amplifyframework:aws-datastore:1.1.1'
```
Thanks

**Comment by btdo** [comment]
hi @rjuliano ,  we talked in the android-help forum about this issue and I think you said you were able to recreate it.  I'm just creating this bug to keep track of it.   Thanks for your help.

**Comment by rjuliano** [comment]
Thanks for doing that. I'm juggling a few of these in parallel and certainly don't want to lose track of any of them.

For this particular issue, we're waiting for a [PR against the CLI](https://github.com/aws-amplify/amplify-cli/pull/4717) repo to be merged and released. The PR is approved and I'll try to check with the CLI team to see where they are.

**Comment by jamesonwilliams** [comment]
@btdo That PR was merged, and has been release in version [4.26.0](https://github.com/aws-amplify/amplify-cli/releases/tag/%40aws-amplify%2Fcli%404.26.0) of the CLI.

Can you verify if the latest CLI version resolves your issue?

```console
npm -g install @aws-amplify/cli
amplify -v 
Scanning for plugins...
Plugin scan successful
4.26.0
```

Please re-open if it does not!

**Comment by btdo** [comment]
hi @jamesonwilliams , it is working now.  Thank you!!!  

The only thing though, in the background, when I look at the log, I still see this exception intermittently from the log but the app is still running properly. Other than seeing this log intermittently, everything else seems good

2020-08-04 14:33:58.403 14523-14591/com.wwm.trackappsyncapp I/ApiQuickStart: Item create subscription received: null
2020-08-04 14:34:05.936 14523-14590/com.wwm.trackappsyncapp E/ApiQuickStart: Subscription failed
    AmplifyException {message=Subscription not acknowledged., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.awaitSubscriptionReady(SubscriptionEndpoint.java:329)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:161)
        at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$2$SubscriptionOperation(SubscriptionOperation.java:83)
        at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$Uz-v98-sFPcWrrCLK25EF8LKbXo.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by btdo** [comment]
hi @jamesonwilliams, Actually, I was wrong...The subscribe only works the first time.  After that, it doesn't trigger the call back for new updates

**Comment by jamesonwilliams** [comment]
I'm sorry, @btdo, I misspoke. The needed CLI change did _not_ make it into 4.26.0; it is still pending release:

https://github.com/aws-amplify/amplify-cli/compare/@aws-amplify/cli@4.26.0...master

**Comment by richardmcclellan** [comment]
Hi @btdo, the needed CLI change has been released in [version 4.27.0](https://github.com/aws-amplify/amplify-cli/releases/tag/%40aws-amplify%2Fcli%404.27.0) of the Amplify CLI.  You can update to the latest version by running `npm i -g @aws-amplify/cli`.

This update ensures that when you run `amplify codegen models`, the `@AuthRule` annotations are added to your generated models, if you have used the @auth directive on your GraphQL schema.    This will allow you use owner based auth with Cognito User Pools.

All that said, we still only support Cognito User Pools with the @auth directive, so I will keep this open as a feature request for supporting OIDC providers.

**Comment by btdo** [comment]
Thanks @richardmcclellan , please let me know when OIDC is supported with the @auth directive.  Being able to listen to changes is an important feature that's currently missing in the app I'm developing for my company.  

Thanks

**Comment by richardmcclellan** [comment]
@btdo, OIDC support has been added in the latest release, 1.5.0.
