### ISSUE TITLE
Initial sync during DataStore initialization exceeded timeout of 10000

### ISSUE THREAD

**Issue by pablitorun** [aws-amplify/amplify-android#688]
I have an app using 
```groovy
implementation 'com.amplifyframework:core:1.1.1'
implementation 'com.amplifyframework:aws-datastore:1.1.1'
implementation 'com.amplifyframework:aws-api:1.1.1'
```

That is working fine on my physical device, but when I try to run it on an emulated Pixel2 with API 30, I get this exception:

```console
E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-4
    Process: careband.android.carebandtoolbox, PID: 14984
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | AmplifyException {message=Initial sync during DataStore initialization exceeded timeout of 10000, cause=null, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
        at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
        at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:87)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: AmplifyException {message=Initial sync during DataStore initialization exceeded timeout of 10000, cause=null, recoverySuggestion=There is a possibility that there is a bug if this error persists. Please take a look at 
    https://github.com/aws-amplify/amplify-android/issues to see if there are any existing issues that 
    match your scenario, and file an issue with the details of the bug if there isn't.}
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$start$0$Orchestrator(Orchestrator.java:151)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$Ymbc40qPUW_5TQAqXBShpXSzmjo.run(Unknown Source:4)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
        at com.amplifyframework.datastore.syncengine.PersistentMutationOutbox.lambda$null$8$PersistentMutationOutbox(PersistentMutationOutbox.java:215)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$PersistentMutationOutbox$jX9RGb4pOz72fh11u53Mn7HCJZs.accept(Unknown Source:6)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:411)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        	... 3 more
```

**Comment by jamesonwilliams** [comment]
Hi @pablitorun -- I did a bit overall of the startup code in the DataStore in https://github.com/aws-amplify/amplify-android/pull/662. It will go out in the next release. Wondering if it will solve the issue you're encountering here.

If you wanted to, you can try the fix by [building against a development copy of the library](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#consuming-development-versions-of-the-framework), for now.

**Comment by pablitorun** [comment]
thanks @jamesonwilliams I don't know if I will get to try it out today but I will give it a try shortly.

**Comment by jamesonwilliams** [comment]
@pablitorun 1.1.2 is released. I suspect this issue will have been fixed; please let us know.

**Comment by pablitorun** [comment]
It seems to work fine with 1.1.2
