### ISSUE TITLE
"Validation error of type SubSelectionRequired" during sync

### ISSUE THREAD

**Issue by Diederikjh** [aws-amplify/amplify-android#702]
I am having trouble syncing with Datastore.

Here is a snippet of our schema:

```graphql
interface IEntity {
  id: ID!
  insightsId: Int
}

interface ITask {
  insightsId: Int
  type: TaskType!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  comment: String
  dueDate: AWSDateTime
  isAnytime: Boolean
  customerId: ID
  assigneeName: String!
  editedBy: String!
  reminder: Reminder
}

type Task implements ITask & IEntity {
  id: ID!
  insightsId: Int
  type: TaskType!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
  comment: String
  dueDate: AWSDateTime
  isAnytime: Boolean
  customerId: ID
  assigneeName: String!
  editedBy: String!
  reminder: Reminder
  visitId: Int
  endTime: String
  _version: Int!
  _deleted: Boolean
  _lastChangedAt: AWSTimestamp!
}

type Reminder {
  offSet: String
  date: AWSDateTime
}

enum TaskType {
  TASK
  SCHEDULED
}
```

When the app starts up with a valid signed-in user, the app shows the following log output:

```console
W/amplify:aws-datastore: Failed to sync down cloud state for model type = Task
AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type SubSelectionRequired: Sub selection required for type Reminder of field reminder @ 'syncTasks/items/reminder'', locations='[GraphQLLocation{line='14', column='7'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0$AppSyncClient(AppSyncClient.java:107)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$DAlM2A4r8A_52MV-BaSjc1SYWao.accept(lambda)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:140)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

It looks a lot like https://github.com/aws-amplify/amplify-ios/issues/529, marked as closed in the iOS library.  

When I run a `Task` query on the AppSync query page, it seems to respond with the correct data (though it looks like the editor specifies the leaf fields for you).

More log context:
```console
2020-08-06 08:45:38.032 8214-8947/com.skynamo.appid W/amplify:aws-datastore: Failed to sync down cloud state for model type = Task
    AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type SubSelectionRequired: Sub selection required for type Reminder of field reminder @ 'syncTasks/items/reminder'', locations='[GraphQLLocation{line='14', column='7'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0$AppSyncClient(AppSyncClient.java:107)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$DAlM2A4r8A_52MV-BaSjc1SYWao.accept(lambda)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:140)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2020-08-06 08:45:38.032 8214-8947/com.skynamo.appid W/amplify:aws-datastore: Initial cloud sync failed.
    AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type SubSelectionRequired: Sub selection required for type Reminder of field reminder @ 'syncTasks/items/reminder'', locations='[GraphQLLocation{line='14', column='7'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0$AppSyncClient(AppSyncClient.java:107)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$DAlM2A4r8A_52MV-BaSjc1SYWao.accept(lambda)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:140)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2020-08-06 08:45:38.032 8214-8947/com.skynamo.appid E/amplify:aws-datastore: Error encountered in the DataStore.
    AmplifyException {message=Initial cloud sync failed., cause=AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type SubSelectionRequired: Sub selection required for type Reminder of field reminder @ 'syncTasks/items/reminder'', locations='[GraphQLLocation{line='14', column='7'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check your internet connection.}
        at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$null$2$SyncProcessor(SyncProcessor.java:122)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$SyncProcessor$3L2KTfMEy6_59oCr_DedPu68KAo.accept(lambda)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:88)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onError(CompletableAndThenCompletable.java:62)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
        at io.reactivex.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onError(ObservableFlatMapCompletableCompletable.java:126)
        at io.reactivex.internal.operators.observable.ObservableFlattenIterable$FlattenIterableObserver.onError(ObservableFlattenIterable.java:125)
        at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
        at io.reactivex.internal.operators.observable.ObservableToList$ToListObserver.onError(ObservableToList.java:92)
        at io.reactivex.internal.operators.mixed.SingleFlatMapObservable$FlatMapObserver.onError(SingleFlatMapObservable.java:74)
        at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onError(SingleDoOnError.java:63)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onError(SingleDoOnSuccess.java:65)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:94)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:80)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$3TQsNIUgAvjdYqsJiM71fw48re0.accept(lambda)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0$AppSyncClient(AppSyncClient.java:106)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$DAlM2A4r8A_52MV-BaSjc1SYWao.accept(lambda)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:140)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type SubSelectionRequired: Sub selection required for type Reminder of field reminder @ 'syncTasks/items/reminder'', locations='[GraphQLLocation{line='14', column='7'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0$AppSyncClient(AppSyncClient.java:107)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$DAlM2A4r8A_52MV-BaSjc1SYWao.accept(lambda) 
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:140) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
2020-08-06 08:45:38.034 8214-8679/com.skynamo.appid I/amplify:aws-datastore: Starting processing subscription data buffer.
```

**Comment by saltonmassally** [comment]
I suspect this is similar to a question I asked in discord, copying it over here for reference: 

"Does datastore allow nested non-model fields? Looking at this com.amplifyframework.api.aws.SelectionSet#toString() I can see how it transverses nested model fields but I don't see that same walkthrough non-model fields"

Tried to reference the code in the datastore but it appears that WALK_DEPTH is also being applied to the "Reminder" field. I would think the desired outcomes if for its effect to be limited to field annotated with  @connection. As it is now, any data structure with nested objects will fail

**Comment by fayezsalhab** [comment]
I have the same issue on andoird:

schema

```graphql
type Media @model(
timestamps:{createdAt: "createdOn", updatedAt: "updatedOn"}
)
@key(fields: ["category","categorySerial","status"])

{
    id:ID!
    key:String!
    category:Category!
    name:[Name!]!
    categorySerial:Int!
    status:Status!
}

enum Category{
    athan
    quraan
    tasbeeh
    athkar
    names99
}

enum Locale{
    en
    ar
}

enum Status{

    active
    inactive
}

type Name{

    locale:Locale!
    text:String!
}
```

ListMedias Query produced by :

```java
ModelQuery.list(Media.class).getQuery()

```
is

```graphql
query ListMedia($limit: Int) {
      listMedias(limit: $limit) {
        items {
          category
          categorySerial
          id
          key
          name
          status
        }
        nextToken
      }
    }
```

and the result is :

```java
"Validation error of type SubSelectionRequired: Sub selection required for type null of field name @ 'listMedias/items/name"
```

**Comment by Diederikjh** [comment]
As I understand the problem (from the error message anyway) is that the GraphQL that gets generated for the initial downlad is invalid (doesn't query any leaf nodes for nested objects).  Is this the only problem, or is there a mapping issue for the Android code as well? (It looks like the generated .java files for the above model is generated correctly.

Am I right in saying the [iOS issue (linked above)](https://github.com/aws-amplify/amplify-ios/issues/529) does not have this problem, and can contain nested objects?

**Comment by jpignata** [comment]
Will be fixed in 1.3.0 which is pending release.

**Comment by endigo** [comment]
@jpignata Hello, is this change included in 1.3.0?

**Comment by jpignata** [comment]
Heya @endigo! My above message was a lie - we had to roll back the fix due to a failing test. We're working on it now, and will do a patch release when completed (1.3.1)

**Comment by endigo** [comment]
@jpignata Hey is it included in 1.3.1? I think it's not included in this version.

**Comment by Scarlett13** [comment]
Hi @endigo I think its still not working since I still have the same problem here. I need to use Amplify.API for query, but I need to use AppSyncClient for subscription, custom query field, and offline mutation. Can you confirm the same problem or it is been resolved in 1.3.1?

**Comment by richardmcclellan** [comment]
The fix for this was merged in last Friday (https://github.com/aws-amplify/amplify-android/pull/801), but has not been released yet.  It will be in the next release.

**Comment by karngajendra** [comment]
Thank you @richardmcclellan for the update. Do we have any tentative date for 1.3.2 rollout?

**Comment by jpignata** [comment]
We're going to ship this week - likely Thursday. Thanks!

**Comment by jamesonwilliams** [comment]
#801 went out in [1.3.2](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.3.2). Please give this latest version a try, and let us know if the issue persists. cc: @endigo @Scarlett13 @Diederikjh
