### ISSUE TITLE
[Amplify.Auth] SignIn() locks and never completes on re-login when session expired

### ISSUE THREAD

**Issue by iuriirodyk** [aws-amplify/amplify-android#714]
We use Amplify Auth 1.0.0 for sign up / login and session expiry re-login.
When the session is expired, we get an event from Hub:

```kotlin
Amplify.Hub.subscribe(HubChannel.AUTH) { hubEvent: HubEvent<*> ->
    when (hubEvent.name) {
        AuthChannelEventName.SESSION_EXPIRED.name -> {  }
    }
}
```

Where we then offer the user to log back in.

However, during `Amplify.Auth.signIn(...)`, this exception occurs:

```console
W/AWSMobileClient: Failed to federate tokens during sign-in
    java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.
        at com.amazonaws.mobile.client.AWSMobileClient$10.run(AWSMobileClient.java:1637)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1590)
        at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1159)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:772)
        at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1145)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)`
```
From this code:

```kotlin
try {
    if (isFederationEnabled()) {
        federatedSignInWithoutAssigningState(userpoolsLoginKey, mCognitoUserSession.getIdToken().getJWTToken());
    }
    releaseSignInWait();
} catch (Exception e) {
    Log.w(TAG, "Failed to federate tokens during sign-in", e);
    } finally {
        setUserState(new UserStateDetails(UserState.SIGNED_IN, getSignInDetailsMap()));
    }
}
```

`releaseSignInWait` is not called and the app hanges with `signIn(...)` is never completing. The HubEvent with state `SIGNED_IN` is still fired. We worked around this by calling `AWSMobileClient.getInstance().releaseSignInWait()`, and the execution finishes successfully, and we get our idToken.

This doesn't seem right as it is a very common case. Our config file looks like this:

```json
{
    "UserAgent":"aws-amplify-cli/2.0",
    "Version": "0.1",
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "ap-southeast-2_masked_value",
                        "AppClientId": "client_id_value",
                        "Region": "ap-southeast-2"
                    }
                }
            }
        }
    }
}
```

Apart from this use-case, everything works smoothly.

**Comment by rjuliano** [comment]
There have been quite a few updates to the library. If you can, please try using the latest version to see if the issue persists.

**Comment by iuriirodyk** [comment]
It's been a year... the project was shut down already. Closing it
