### ISSUE TITLE
[Feedback] AmplifyException {message=Sign in with web UI failed ...

### ISSUE THREAD

**Issue by rleee** [aws-amplify/amplify-android#753]
**Page**: [`/lib/auth/social_signin_web_ui/q/platform/android`](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android)

**Feedback**:

As a beginner following steps on amplify docs is a bit confusing (doesn't really explain why we did what we did), and there isn't much i can google out there with following problem.

i'm trying to use google sign in with cognito, and following the exception to check on `awsconfiguration.json` i found IdentityManager block is empty, is it because of that?

```
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
}
```

my log cat:
```
D/AWSMobileClient: getHostedUIJSON: Failed to read config
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.amazonaws.mobile.config.AWSConfiguration.optJsonObject(java.lang.String)' on a null object reference
        at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSONFromJSON(AWSMobileClient.java:654)
        at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:673)
        at com.amazonaws.mobile.client.AWSMobileClient.getHostedUIJSON(AWSMobileClient.java:668)
        at com.amazonaws.mobile.client.AWSMobileClient._showSignIn(AWSMobileClient.java:3027)
        at com.amazonaws.mobile.client.AWSMobileClient.showSignIn(AWSMobileClient.java:3007)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.signInWithWebUIHelper(AWSCognitoAuthPlugin.java:745)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.signInWithSocialWebUI(AWSCognitoAuthPlugin.java:431)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.signInWithSocialWebUI(AWSCognitoAuthPlugin.java:414)
        at com.amplifyframework.auth.AuthCategory.signInWithSocialWebUI(AuthCategory.java:115)
        at com.xxxxx.xxxxxxxxxx.MainActivity$onCreate$1.onClick(MainActivity.kt:18)
        at android.view.View.performClick(View.java:6304)
        at android.view.View$PerformClick.run(View.java:24803)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6600)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

AmplifyException {message=Sign in with web UI failed, cause=java.lang.Exception: showSignIn called with HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}
```

**Comment by TrekSoft** [comment]
Hi, yeah it seems like you haven't gone through the initial setup steps here: https://docs.amplify.aws/lib/auth/getting-started/q/platform/android

**Comment by rleee** [comment]
Apologies, i set it up using AWS config it didn't work, but with amplify config it works.

But, what would be the difference of those 2 files tho?

**Comment by raphkim** [comment]
@rleee `awsconfiguration.json` is used by the [AWS Mobile SDK library](https://github.com/aws-amplify/aws-sdk-android), whereas AWS Amplify uses `amplifyconfiguration.json`. You will not have to worry about `awsconfiguration.json` when working with the Amplify library.
