### ISSUE TITLE
here is  abug when i call singn up version 1.3.1

### ISSUE THREAD

**Issue by azisoli** [aws-amplify/amplify-android#806]
java.lang.NoSuchMethodError: No direct method <init>(ZLcom/amplifyframework/auth/result/step/AuthNextSignUpStep;)V in class Lcom/amplifyframework/auth/result/AuthSignUpResult; or its super classes (declaration of 'com.amplifyframework.auth.result.AuthSignUpResult' appears in /data/app/com.spendlee.dev-cY4ro1kRbviRTsVxjuVn3A==/base.apk)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.convertSignUpResult(AWSCognitoAuthPlugin.java:820)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.access$500(AWSCognitoAuthPlugin.java:92)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onResult(AWSCognitoAuthPlugin.java:270)
        at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$2.onResult(AWSCognitoAuthPlugin.java:267)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:75)
        at com.amazonaws.mobile.client.internal.InternalCallback.onResult(InternalCallback.java:62)
        at com.amazonaws.mobile.client.AWSMobileClient$13$1.onSuccess(AWSMobileClient.java:2026)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(CognitoUserPool.java:463)
        at com.amazonaws.mobile.client.AWSMobileClient$13.run(AWSMobileClient.java:2003)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)

**Comment by raphkim** [comment]
Hey @azisoli ,

Can you share the code sample that caused this error as well as what your use-case was? Thank you.

**Comment by azisoli** [comment]
Just trying to signup

Sent from Yahoo Mail on Android 
 
  On Tue., 8 Sep. 2020 at 6:21 p.m., Raphael Kim<notifications@github.com> wrote:   


Hey @azisoli ,

Can you share the code sample that caused this error as well as what your use-case was? Thank you.

**Comment by richardmcclellan** [comment]
Hi @azisoli, a `java.lang.NoSuchMethodError` indicates a method was available at compile time, but not at runtime. 

I do see that the constructor signature for `com.amplifyframework.auth.cognito.AuthSignUpResult` did change in the v1.1.3 release as shown in [this commit](https://github.com/aws-amplify/amplify-android/commit/d352d18b3c676a11d799560f495124cd4a18f5a7#diff-4c18afc35d96ec64e0a58d6fb4f41d25), which could be related. 

Perhaps you are somehow still building against an older version of Amplify?   Make sure you've updated all Amplify dependencies to 1.3.1, and also do a full clean and rebuild to see if it resolves this issue for you.

**Comment by azisoli** [comment]
yes when i change every thing to 1.3.1 i could do the signup but i can't sync any changes to database do you have any suggestion?
