### ISSUE TITLE
Bad subscription data for Profile: [GraphQLResponse.Error{message='Not Authorized to access onUpdateProfile on type Subscription'

### ISSUE THREAD

**Issue by azisoli** [aws-amplify/amplify-android#808]
after signup and sign in i am trying to add to profile table but i get this error
Bad subscription data for Profile: [GraphQLResponse.Error{message='Not Authorized to access onUpdateProfile on type Subscription'

what is missing here?

**Comment by azisoli** [comment]
this is complete log 
2020-09-08 22:22:04.889 23923-23923/com.spendlee.dev I/first Initialization: Initialized Amplify
2020-09-08 22:22:04.990 23923-24016/com.spendlee.dev I/amplify:aws-datastore: DataStore orchestrator transitioning states. Current mode = STOPPED, target mode = SYNC_VIA_API.
2020-09-08 22:22:04.990 23923-24016/com.spendlee.dev I/amplify:aws-datastore: Starting to observe local storage changes.
2020-09-08 22:22:05.014 23923-24019/com.spendlee.dev I/amplify:aws-datastore: Now observing local storage. Local changes will be enqueued to mutation outbox.
2020-09-08 22:22:05.016 23923-24050/com.spendlee.dev I/amplify:aws-datastore: Starting API synchronization mode.
2020-09-08 22:22:08.553 23923-24381/com.spendlee.dev W/amplify:aws-datastore: An error occurred on the remote Profile subscription for model ON_UPDATE.
    AmplifyException {message=Bad subscription data for Profile: [GraphQLResponse.Error{message='Not Authorized to access onUpdateProfile on type Subscription', locations='null', path='null', extensions='{errorType=Unauthorized}'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$2(AppSyncClient.java:284)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$JcXWwhRqFFN0mthuNQf2Zjf5Scw.accept(Unknown Source:8)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$Subscription.dispatchNextMessage(SubscriptionEndpoint.java:370)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.notifySubscriptionData(SubscriptionEndpoint.java:220)
        at com.amplifyframework.api.aws.SubscriptionEndpoint.access$600(SubscriptionEndpoint.java:60)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.processJsonMessage(SubscriptionEndpoint.java:546)
        at com.amplifyframework.api.aws.SubscriptionEndpoint$AmplifyWebSocketListener.onMessage(SubscriptionEndpoint.java:454)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-09-08 22:22:08.559 23923-24103/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.560 23923-24107/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.560 23923-24112/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.560 23923-24118/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.561 23923-24124/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.561 23923-24130/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.561 23923-24137/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.562 23923-24142/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.562 23923-24147/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.563 23923-24153/com.spendlee.dev W/amplify:aws-api: Connection attempt interrupted.
2020-09-08 22:22:08.563 23923-24050/com.spendlee.dev I/amplify:aws-datastore: Began buffering subscription events for remote mutations [class com.amplifyframework.datastore.generated.model.Receipt, class com.amplifyframework.datastore.generated.model.SpendSummary3, class com.amplifyframework.datastore.generated.model.LogEntry, class com.amplifyframework.datastore.generated.model.Profile] to Cloud models of types [ON_CREATE, ON_UPDATE, ON_DELETE].

**Comment by azisoli** [comment]
it was old version
