### ISSUE TITLE
Wanted 1 metadata for item with id MODEL_ID, but had 0.

### ISSUE THREAD

**Issue by azisoli** [aws-amplify/amplify-android#812]
```console
W/amplify:aws-datastore: Failed to publish a local change = PendingMutation{mutatedItem=Profile {id=94adedda-c8ee-4817-bcbf-13f6a0a8c0f8, username=94adedda-c8ee-4817-bcbf-13f6a0a8c0f8, state=CHANGE, spendleeId=azadehsoli+990h, avatarImage=null, scansPerDay=null}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Profile, mutationType=UPDATE, mutationId=4948cfce-f2a7-11ea-a24f-b9ff350d8ffc, predicate=MatchAllQueryPredicate}
    AmplifyException {message=Wanted 1 metadata for item with id = 94adedda-c8ee-4817-bcbf-13f6a0a8c0f8, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:89)
```

**Comment by richardmcclellan** [comment]
I thought this issue had been resolved, but looks like we need to take another look.   Here are the previous reports:

https://github.com/aws-amplify/amplify-android/issues/603
https://github.com/aws-amplify/amplify-android/issues/588
https://github.com/aws-amplify/amplify-android/issues/602

**Comment by azisoli** [comment]
@richardmcclellan  do you have any suggestion that i can do ?

**Comment by msiewert** [comment]
2020-09-15 11:40:31.259 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=2c3029e2-9b15-46da-8510-340863d32588, name=1, description=1}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d066a4e-f77a-11ea-89dc-07779c1e8fe5, predicate=MatchAllQueryPredicate}
2020-09-15 11:40:31.269 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=6f178fb5-69d1-4f41-9a24-94428bf1c5ef, name=2, description=2}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d07068f-f77a-11ea-89dc-9fe7e2a389e5, predicate=MatchAllQueryPredicate}
2020-09-15 11:40:31.280 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=5f655c3a-8fdc-4963-8dcf-436e226a9061, name=3, description=3}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0b2540-f77a-11ea-89dc-873f8ca125f9, predicate=MatchAllQueryPredicate}
2020-09-15 11:40:31.287 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=53241a44-ab9a-43e3-b897-0028dff4731d, name=4, description=4}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0c84d1-f77a-11ea-89dc-dd310ee49d84, predicate=MatchAllQueryPredicate}
2020-09-15 11:40:31.299 6937-7126/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=5c827ffa-8cfa-4a60-bc10-65ccdbff4132, name=5, description=5}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0e3282-f77a-11ea-89dc-f3762083d2a2, predicate=MatchAllQueryPredicate}
2020-09-15 11:40:31.616 6937-6988/com.example.amplify_android I/amplify:aws-datastore: Mutation outbox has pending mutation for 2c3029e2-9b15-46da-8510-340863d32588, refusing to merge.
2020-09-15 11:40:31.622 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation{mutatedItem=Todo {id=2c3029e2-9b15-46da-8510-340863d32588, name=1, description=1}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d066a4e-f77a-11ea-89dc-07779c1e8fe5, predicate=MatchAllQueryPredicate}
2020-09-15 11:40:32.054 6937-6988/com.example.amplify_android I/amplify:aws-datastore: Mutation outbox has pending mutation for 6f178fb5-69d1-4f41-9a24-94428bf1c5ef, refusing to merge.
2020-09-15 11:40:32.082 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation{mutatedItem=Todo {id=6f178fb5-69d1-4f41-9a24-94428bf1c5ef, name=2, description=2}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d07068f-f77a-11ea-89dc-9fe7e2a389e5, predicate=MatchAllQueryPredicate}
2020-09-15 11:40:32.495 6937-6988/com.example.amplify_android I/amplify:aws-datastore: Mutation outbox has pending mutation for 5f655c3a-8fdc-4963-8dcf-436e226a9061, refusing to merge.
2020-09-15 11:40:32.500 6937-7126/com.example.amplify_android I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation{mutatedItem=Todo {id=5f655c3a-8fdc-4963-8dcf-436e226a9061, name=3, description=3}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0b2540-f77a-11ea-89dc-873f8ca125f9, predicate=MatchAllQueryPredicate}
2020-09-15 11:40:32.502 6937-7126/com.example.amplify_android W/amplify:aws-datastore: Failed to publish a local change = PendingMutation{mutatedItem=Todo {id=53241a44-ab9a-43e3-b897-0028dff4731d, name=4, description=4}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0c84d1-f77a-11ea-89dc-dd310ee49d84, predicate=MatchAllQueryPredicate}
    AmplifyException {message=Wanted 1 metadata for item with id = 53241a44-ab9a-43e3-b897-0028dff4731d, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:89)
        at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:63)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$pDJF8PBRwphVueEHI3UosoRKGko.accept(Unknown Source:8)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:395)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2020-09-15 11:40:32.503 6937-6972/com.example.amplify_android W/amplify:aws-datastore: Error ended observation of mutation outbox: 
    java.lang.RuntimeException: AmplifyException {message=Wanted 1 metadata for item with id = 53241a44-ab9a-43e3-b897-0028dff4731d, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingAwait(BlockingMultiObserver.java:145)
        at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1490)
        at com.amplifyframework.datastore.syncengine.MutationProcessor.drainMutationOutbox(MutationProcessor.java:102)
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$startDrainingMutationOutbox$1$MutationProcessor(MutationProcessor.java:86)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$bjecRv6fl8W6Pcgjld1zB2NDYX8.apply(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: AmplifyException {message=Wanted 1 metadata for item with id = 53241a44-ab9a-43e3-b897-0028dff4731d, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:89)
        at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:63)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$pDJF8PBRwphVueEHI3UosoRKGko.accept(Unknown Source:8)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:395)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2020-09-15 11:40:39.612 6937-6981/com.example.amplify_android W/amplify:aws-api: Websocket connection failed.
    java.net.SocketException: Software caused connection abort
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
        at java.net.SocketInputStream.read(SocketInputStream.java:176)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.request(RealBufferedSource.kt:207)
        at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2020-09-15 11:40:39.618 6937-7074/com.example.amplify_android W/amplify:aws-api: Websocket connection failed.
    java.net.SocketException: Software caused connection abort
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
        at java.net.SocketInputStream.read(SocketInputStream.java:176)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.request(RealBufferedSource.kt:207)
        at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by msiewert** [comment]
^ I got the same thing this morning.

- Cleared DataStore
- Put emulator in airplane mode
- Added some records to the datastore
- Brought emulator back online
- Verified added items synched to back end
- Attempted to delete all items

**Comment by changxu0306** [comment]
> ```
> 2020-09-15 11:40:31.259 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=2c3029e2-9b15-46da-8510-340863d32588, name=1, description=1}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d066a4e-f77a-11ea-89dc-07779c1e8fe5, predicate=MatchAllQueryPredicate}
> 2020-09-15 11:40:31.269 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=6f178fb5-69d1-4f41-9a24-94428bf1c5ef, name=2, description=2}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d07068f-f77a-11ea-89dc-9fe7e2a389e5, predicate=MatchAllQueryPredicate}
> 2020-09-15 11:40:31.280 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=5f655c3a-8fdc-4963-8dcf-436e226a9061, name=3, description=3}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0b2540-f77a-11ea-89dc-873f8ca125f9, predicate=MatchAllQueryPredicate}
> 2020-09-15 11:40:31.287 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=53241a44-ab9a-43e3-b897-0028dff4731d, name=4, description=4}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0c84d1-f77a-11ea-89dc-dd310ee49d84, predicate=MatchAllQueryPredicate}
> 2020-09-15 11:40:31.299 6937-7126/com.example.amplify_android I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=Todo {id=5c827ffa-8cfa-4a60-bc10-65ccdbff4132, name=5, description=5}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0e3282-f77a-11ea-89dc-f3762083d2a2, predicate=MatchAllQueryPredicate}
> 2020-09-15 11:40:31.616 6937-6988/com.example.amplify_android I/amplify:aws-datastore: Mutation outbox has pending mutation for 2c3029e2-9b15-46da-8510-340863d32588, refusing to merge.
> 2020-09-15 11:40:31.622 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation{mutatedItem=Todo {id=2c3029e2-9b15-46da-8510-340863d32588, name=1, description=1}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d066a4e-f77a-11ea-89dc-07779c1e8fe5, predicate=MatchAllQueryPredicate}
> 2020-09-15 11:40:32.054 6937-6988/com.example.amplify_android I/amplify:aws-datastore: Mutation outbox has pending mutation for 6f178fb5-69d1-4f41-9a24-94428bf1c5ef, refusing to merge.
> 2020-09-15 11:40:32.082 6937-7088/com.example.amplify_android I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation{mutatedItem=Todo {id=6f178fb5-69d1-4f41-9a24-94428bf1c5ef, name=2, description=2}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d07068f-f77a-11ea-89dc-9fe7e2a389e5, predicate=MatchAllQueryPredicate}
> 2020-09-15 11:40:32.495 6937-6988/com.example.amplify_android I/amplify:aws-datastore: Mutation outbox has pending mutation for 5f655c3a-8fdc-4963-8dcf-436e226a9061, refusing to merge.
> 2020-09-15 11:40:32.500 6937-7126/com.example.amplify_android I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation{mutatedItem=Todo {id=5f655c3a-8fdc-4963-8dcf-436e226a9061, name=3, description=3}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0b2540-f77a-11ea-89dc-873f8ca125f9, predicate=MatchAllQueryPredicate}
> 2020-09-15 11:40:32.502 6937-7126/com.example.amplify_android W/amplify:aws-datastore: Failed to publish a local change = PendingMutation{mutatedItem=Todo {id=53241a44-ab9a-43e3-b897-0028dff4731d, name=4, description=4}, classOfMutatedItem=class com.amplifyframework.datastore.generated.model.Todo, mutationType=DELETE, mutationId=8d0c84d1-f77a-11ea-89dc-dd310ee49d84, predicate=MatchAllQueryPredicate}
>     AmplifyException {message=Wanted 1 metadata for item with id = 53241a44-ab9a-43e3-b897-0028dff4731d, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
>         at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:89)
>         at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:63)
>         at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$pDJF8PBRwphVueEHI3UosoRKGko.accept(Unknown Source:8)
>         at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:395)
>         at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
> 2020-09-15 11:40:32.503 6937-6972/com.example.amplify_android W/amplify:aws-datastore: Error ended observation of mutation outbox: 
>     java.lang.RuntimeException: AmplifyException {message=Wanted 1 metadata for item with id = 53241a44-ab9a-43e3-b897-0028dff4731d, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
>         at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
>         at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingAwait(BlockingMultiObserver.java:145)
>         at io.reactivex.rxjava3.core.Completable.blockingAwait(Completable.java:1490)
>         at com.amplifyframework.datastore.syncengine.MutationProcessor.drainMutationOutbox(MutationProcessor.java:102)
>         at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$startDrainingMutationOutbox$1$MutationProcessor(MutationProcessor.java:86)
>         at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$bjecRv6fl8W6Pcgjld1zB2NDYX8.apply(Unknown Source:4)
>         at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:97)
>         at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
>         at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
>         at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
>         at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
>      Caused by: AmplifyException {message=Wanted 1 metadata for item with id = 53241a44-ab9a-43e3-b897-0028dff4731d, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
>         at com.amplifyframework.datastore.syncengine.VersionRepository.extractVersion(VersionRepository.java:89)
>         at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:63)
>         at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$pDJF8PBRwphVueEHI3UosoRKGko.accept(Unknown Source:8)
>         at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:395)
>         at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
>         at java.lang.Thread.run(Thread.java:923) 
> 2020-09-15 11:40:39.612 6937-6981/com.example.amplify_android W/amplify:aws-api: Websocket connection failed.
>     java.net.SocketException: Software caused connection abort
>         at java.net.SocketInputStream.socketRead0(Native Method)
>         at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
>         at java.net.SocketInputStream.read(SocketInputStream.java:176)
>         at java.net.SocketInputStream.read(SocketInputStream.java:144)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
>         at okio.InputStreamSource.read(JvmOkio.kt:90)
>         at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
>         at okio.RealBufferedSource.request(RealBufferedSource.kt:207)
>         at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
>         at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
>         at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
>         at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
>         at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
>         at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
>         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
> 2020-09-15 11:40:39.618 6937-7074/com.example.amplify_android W/amplify:aws-api: Websocket connection failed.
>     java.net.SocketException: Software caused connection abort
>         at java.net.SocketInputStream.socketRead0(Native Method)
>         at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
>         at java.net.SocketInputStream.read(SocketInputStream.java:176)
>         at java.net.SocketInputStream.read(SocketInputStream.java:144)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
>         at okio.InputStreamSource.read(JvmOkio.kt:90)
>         at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
>         at okio.RealBufferedSource.request(RealBufferedSource.kt:207)
>         at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
>         at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
>         at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
>         at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
>         at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
>         at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
>         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:923)
> ```

Hello, could you please specify the version of Amplify framework you use?
