### ISSUE TITLE
[Amplify Android] Runtime crash "Caused by: java.lang.ClassCastException: libcore.reflect.ParameterizedTypeImpl cannot be cast to java.lang.Class" when using latest main branch amplify-android supporting nested custom types

### ISSUE THREAD

**Issue by XinSuUpitt** [aws-amplify/amplify-android#817]
Hi, I noticed that amplify-android recently support nested custom types https://github.com/aws-amplify/amplify-android/commit/55077a72a1509496359b394d18ae003fce5cbe0c, and our project need to use this feature. I pulled down the code and built locally, when running the app and try to do a mutation, I got a runtime crash:
```console
Caused by: java.lang.ClassCastException: libcore.reflect.ParameterizedTypeImpl cannot be cast to java.lang.Class
        at com.amplifyframework.api.aws.SelectionSet$Builder.getClassForField(SelectionSet.java:299)
        at com.amplifyframework.api.aws.SelectionSet$Builder.isCustomType(SelectionSet.java:278)
        at com.amplifyframework.api.aws.SelectionSet$Builder.getNestedCustomTypeFields(SelectionSet.java:263)
        at com.amplifyframework.api.aws.SelectionSet$Builder.getNestedCustomTypeFields(SelectionSet.java:264)
        at com.amplifyframework.api.aws.SelectionSet$Builder.getNestedCustomTypeFields(SelectionSet.java:264)
        at com.amplifyframework.api.aws.SelectionSet$Builder.getNestedCustomTypeFields(SelectionSet.java:264)
        at com.amplifyframework.api.aws.SelectionSet$Builder.getModelFields(SelectionSet.java:243)
        at com.amplifyframework.api.aws.SelectionSet$Builder.build(SelectionSet.java:184)
        at com.amplifyframework.api.aws.AppSyncGraphQLRequest$Builder.build(AppSyncGraphQLRequest.java:303)
        at com.amplifyframework.api.aws.AppSyncGraphQLRequestFactory.buildMutation(AppSyncGraphQLRequestFactory.java:215)
        at com.amplifyframework.api.graphql.model.ModelMutation.create(ModelMutation.java:41)
```

And my code looks like
```kotlin
val parent = Parent.builder()
    .name("Parent")
    .address(Address.builder()
        .street("street")
        .street2("street2")
        .city(City.MAKENI)
        .country("US")
        .build())
    .build()
Amplify.API.mutate(ModelMutation.create(parent),
    { response -> Log.i(TAG, "$response") },
    { error -> Log.e(TAG, "Create failed", error) }
)
```

Not sure if anyone can help. Thanks!

**Comment by XinSuUpitt** [comment]
Any updates?

**Comment by richardmcclellan** [comment]
@XinSuUpitt I believe [this unit test](https://github.com/aws-amplify/amplify-android/blob/55077a72a1509496359b394d18ae003fce5cbe0c/aws-api-appsync/src/test/java/com/amplifyframework/api/aws/SelectionSetTest.java#L50-L58) should catch an error like that, so I'm not exactly sure what the issue is yet. 

Could you provide your `schema.graphql`?

**Comment by XinSuUpitt** [comment]
> @XinSuUpitt I believe [this unit test](https://github.com/aws-amplify/amplify-android/blob/55077a72a1509496359b394d18ae003fce5cbe0c/aws-api-appsync/src/test/java/com/amplifyframework/api/aws/SelectionSetTest.java#L50-L58) should catch an error like that, so I'm not exactly sure what the issue is yet.
> 
> Could you provide your `schema.graphql` so I can try to repro?

Hi @richardmcclellan thanks for your reply.

My schema is following your unit test example
```
type Parent @model {
  id: ID!
  name: String!
  address: Address!
  children: [Child]
}

type Child {
  name: String!
  address: Address!
}

type Address {
  street: String!
  street2: String!
  city: City!
  country: String!
}

enum City {
  FREETOWN
  BO
  MAKENI
  KENEMA
}
```

And then I run `amplify codeden models` to generate amplify models.

And the way I send mutation is 
```
val parent = Parent.builder()
    .name("Parent")
    .address(Address.builder()
        .street("street")
        .street2("street2")
        .city(City.MAKENI)
        .country("US")
        .build())
    .build()
Amplify.API.mutate(ModelMutation.create(parent),
    { response -> Log.i(TAG, "$response") },
    { error -> Log.e(TAG, "Create failed", error) }
)
```

I can also upload my sample project if it can help.

**Comment by richardmcclellan** [comment]
hey @XinSuUpitt, I was able to repro, and just published a fix: https://github.com/aws-amplify/amplify-android/pull/829.
