### ISSUE TITLE
Could not check if ACCESS_NETWORK_STATE permission is available.

### ISSUE THREAD

**Issue by azisoli** [aws-amplify/amplify-android#827]
```console
2020-09-14 15:58:45.034 13752-13834/com.spendlee.dev W/AWSMobileClient: Could not check if ACCESS_NETWORK_STATE permission is available.
    java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.amazonaws.mobile.client.AWSMobileClient.isNetworkAvailable(AWSMobileClient.java:771)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:983)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:845)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:842)
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/com.spendlee.dev-kMppz6q4B32cH-kwXu3lvg==/base.apk"],nativeLibraryDirectories=[/data/app/com.spendlee.dev-kMppz6q4B32cH-kwXu3lvg==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at com.amazonaws.mobile.client.AWSMobileClient.isNetworkAvailable(AWSMobileClient.java:771) 
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:983) 
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:845) 
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:842) 
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by jamesonwilliams** [comment]
This fix will be included in the next Amplify release, 1.3.2.

**Comment by azisoli** [comment]
it didn't solve my problem .update doesn't work for me after Amplify.API.mutate(  ModelMutation.update(profile))
the result has previous data amounts and i see these in result 

((GraphQLResponse)response).data=Expecting an element; looking at ERROR_ELEMENT '(1,27) in /fragment.kt

((java.util.ArrayList)((PaginatedResult)((GraphQLResponse)response).data).items).get(0) =Expecting an element; looking at ERROR_ELEMENT '(1,67) in /fragment.kt

**Comment by jamesonwilliams** [comment]
Hi @azisoli, that looks like a different issue. Can you please create a separate issue for that?
