### ISSUE TITLE
SQLiteConstraintException: UNIQUE constraint failed when subscriptions are received

### ISSUE THREAD

**Issue by saltonmassally** [aws-amplify/amplify-android#847]
I keep getting `android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed` when subscriptions are received. I suspect it might be because of two threads writing to the DB  because of either or both of:
- [ ] Duplicating subscriptions #782  (not sure how app sync handles this)
- [ ] I manually triggered sync at the same time (a walkaround to some owner-based subscription limitations I encountered)

```
W/amplify:aws-datastore: Storage adapter subscription ended in error
    AmplifyException {message=Error in saving the model: UserGroupArtifact[id=4e92a43c-90d1-41bf-999c-eb3508502fa1], cause=android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: UserGroupArtifact.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY), recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:333)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: UserGroupArtifact.id (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:717)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:315)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
D/AndroidRuntime: Shutting down VM
```

**Comment by jamesonwilliams** [comment]
@saltonmassally Would you mind to enable verbose logging, and see what else is going around in the system, when this occurs? Can you include the full context of logs around this SQL exception?

```kotlin
Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))
Amplify.addPlugin(AWSDataStorePlugin())
Amplify.addPlugin(AWSApiPlugin())
...
```

**Comment by saltonmassally** [comment]
@jamesonwilliams been swamped... I will post the log over the weekend

**Comment by jamesonwilliams** [comment]
No worries; as always, thanks for your help here, @saltonmassally!

**Comment by saltonmassally** [comment]
Closing this it appears fixed on ensuring Orchestrator execution is sequential (mentioned here - #853). Cleaning up and send a PR for #853

**Comment by micstepper** [comment]
Hey @saltonmassally I'm using 1.6.0 and getting the same error with API sync deactivated. 

`2020-11-17 17:49:17.344 3877-3957/de.aufmaster.mobileapp E/ProjectsViewModel: newProject create failed : Error in saving the model: Project[id=c63adaa7-8608-4369-bb7f-d9c20b66b88a]
2020-11-17 17:49:17.351 3877-4122/de.aufmaster.mobileapp W/amplify:aws-datastore: Storage adapter subscription ended in error
    DataStoreException{message=Error in saving the model: Project[id=c63adaa7-8608-4369-bb7f-d9c20b66b88a], cause=android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (Sqlite code 787), (OS error - 2:No such file or directory), recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:321)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$lMf-ZzF10cDUtleQzXsLUxpfzAI.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (Sqlite code 787), (OS error - 2:No such file or directory)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:818)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:803)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:747)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:303)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$lMf-ZzF10cDUtleQzXsLUxpfzAI.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784) 
`
