### ISSUE TITLE
[DataStore] Initial Cloud sync failed using DataStore and sync with remote

### ISSUE THREAD

**Issue by XinSuUpitt** [aws-amplify/amplify-android#855]
I'm using latest main branch and build on my local. when using DataStore, and set up syncing data to cloud, I got this error
```
Error encountered in the DataStore.
    AmplifyException {message=Initial cloud sync failed., cause=AmplifyException {message=Failure performing sync query to AppSync: [GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'syncDevicePlaybackStates' in type 'Query' is undefined @ 'syncDevicePlaybackStates'', locations='[GraphQLLocation{line='2', column='3'}]', path='null', extensions='null'}], cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check your internet connection.}
        at com.amplifyframework.datastore.syncengine.SyncProcessor.lambda$createHydrationTask$8$SyncProcessor(SyncProcessor.java:161)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$SyncProcessor$-2QSLtdRgTPoxsmAWkh9ybwd5JA.accept(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:88)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:117)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableToSingle$ToSingle.onError(CompletableToSingle.java:73)
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:156)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onError(FlowableFlatMapCompletableCompletable.java:149)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableTake$TakeSubscriber.onError(FlowableTake.java:86)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.checkTerminated(FlowableFlattenIterable.java:406)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.drain(FlowableFlattenIterable.java:266)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlattenIterable$FlattenIterableSubscriber.onError(FlowableFlattenIterable.java:192)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
        at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:94)
        at io.reactivex.rxjava3.internal.util.HalfSerializer.onError(HalfSerializer.java:67)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.innerError(FlowableConcatMap.java:210)
        at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapInner.onError(FlowableConcatMap.java:571)
        at io.reactivex.rxjava3.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onError(SingleToFlowable.java:67)
        at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:95)
        at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$PymunRoF4O3jbMDeD82w6kHUXIM.accept(Unknown Source:4)
        at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$sync$0(AppSyncClient.java:89)
        at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$59c8UbYHZL8NaUlxC5GeIaYzfmw.accept(Unknown Source:6)
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:140)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

My code related to setup is
```
Amplify.addPlugin(AWSApiPlugin())
Amplify.addPlugin(AWSDataStorePlugin())
Amplify.configure(applicationContext)
```

And what I did before running app is 
* create schema.graphql
* amplify codegen models
* amplify push

I saw we used to have one similar issue: https://github.com/aws-amplify/amplify-android/issues/588 and it is recently reopened because of https://github.com/aws-amplify/amplify-android/issues/812.

Just want to make sure if they are related and are we tracking on this? Thanks!

**Comment by jamesonwilliams** [comment]
Hi @XinSuUpitt, when the DataStore tries to sync down data from the cloud, the operation fails, with this GraphQL error:

> GraphQLResponse.Error{message='Validation error of type FieldUndefined: Field 'syncDevicePlaybackStates' in type 'Query' is undefined @ 'syncDevicePlaybackStates'', locations='[GraphQLLocation{line='2', column='3'}]', path='null', extensions='null'}

This indicates that the AppSync endpoint your app is talking to doesn't have a `syncDevicePlaybackStates` defined. You can verify if that's true through the [AppSync Console](https://console.aws.amazon.com/appsync/home).

Some possible reasons for this:
1. When you provisioned the API, you did _not_ select these options, needed for DataStore:
```console
? Configure conflict detection?
    `Yes`
? Select the default resolution strategy
    `Auto Merge`
```
2. You updated your GraphQL schema to include a `DevicePlaybackState` model, but did not run `amplify update api`, to sync that to the cloud.
3. You are using an old version of the Amplify Android library, that does not include [this pluralization fix](https://github.com/aws-amplify/amplify-android/pull/628).

**Comment by XinSuUpitt** [comment]
Hi @jamesonwilliams , I tried to sync with cloud, and it made some progress. After doing `amplify update api`, the original error is gone, but I saw another error 
```
Caused by: AmplifyException {message=OkHttp client failed to make a successful request., cause=java.lang.NullPointerException: Attempt to invoke virtual method 'long java.time.LocalDateTime.getLong(java.time.temporal.TemporalField)' on a null object reference, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.AppSyncGraphQLOperation.start(AppSyncGraphQLOperation.java:104)
        at com.amplifyframework.api.aws.AWSApiPlugin.mutate(AWSApiPlugin.java:231)
        at com.amplifyframework.api.aws.AWSApiPlugin.mutate(AWSApiPlugin.java:218)
        at com.amplifyframework.api.ApiCategory.mutate(ApiCategory.java:70)
        at com.amplifyframework.datastore.appsync.AppSyncClient.mutation(AppSyncClient.java:326)
        at com.amplifyframework.datastore.appsync.AppSyncClient.create(AppSyncClient.java:119)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$2ePzU1he-KEGlM4EYt_V__SpiBs.publish(Unknown Source:2)
        at com.amplifyframework.datastore.syncengine.MutationProcessor.lambda$null$13(MutationProcessor.java:252)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$MutationProcessor$6Tf5ShojLBgz28XFsZw6idi5fmc.subscribe(Unknown Source:8)
        at io.reactivex.rxjava3.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:40)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
        at io.reactivex.rxjava3.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:43)
        at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
```

And this error also exists even I have field `AWSDateTime` and use DataStore on my local. I found one related https://github.com/aws-amplify/amplify-android/issues/848, not sure if this is similar issue.

**Comment by jamesonwilliams** [comment]
> java.lang.NullPointerException: Attempt to invoke virtual method 'long java.time.LocalDateTime.getLong(java.time.temporal.TemporalField)' on a null object reference

Which version of Amplify are you using? We have fixed a few bugs with the temporal types in the last few versions. I recommend updating to 1.4.0 and trying again. Please feel free to make a new issue for this if it persists. 

I'll close #855 since your original issue here was resolved. https://github.com/aws-amplify/amplify-android/issues/855#issue-707893199
