### ISSUE TITLE
InvalidSignatureException during amplifyPush in android studio

### ISSUE THREAD

**Issue by ghost** [aws-amplify/amplify-android#863]
```console
12:41:17 PM: Executing task 'amplifyPush --scan'...

Executing tasks: [amplifyPush] in project D:\Mobile app dev\ws\LabAssignment

> Task :createAmplifyApp UP-TO-DATE
> Task :getConfig UP-TO-DATE
> Task :datastoreSync UP-TO-DATE

> Task :amplifyPush
Note: It is recommended to run this command from the root of your app directory

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

init failed
InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/apps

host:amplify.ap-southeast-1.amazonaws.com
x-amz-content-sha256:e08aa0673341a791f7dd1e5b60ba1fbd09b2a386581b8d680a1d69a77369761a
x-amz-date:20200928T044158Z

host;x-amz-content-sha256;x-amz-date
e08aa0673341a791f7dd1e5b60ba1fbd09b2a386581b8d680a1d69a77369761a'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20200928T044158Z
20200928/ap-southeast-1/amplify/aws4_request
97c718ba9c204681eb5df4c1efd4e3352a23012a5efe24d9163cebf4dc1af974'

    at Object.extractError (C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\protocol\json.js:52:27)
    at Request.extractError (C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\protocol\rest_json.js:55:8)
    at Request.callListeners (C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\joely\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\aws-sdk\lib\request.js:690:12) {
  code: 'InvalidSignatureException',
  time: 2020-09-28T04:41:58.074Z,
  requestId: '87750970-65c8-4aa8-966c-66dce06ef666',
  statusCode: 403,
  retryable: false,
  retryDelay: 50.04643295235376
}

> Task :amplifyPush FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':amplifyPush'.
> Process 'command 'amplify.cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
1 actionable task: 1 executed

The build scan was not published due to a configuration problem.

The Gradle Terms of Service have not been agreed to.

For more information, please see https://gradle.com/help/plugin-terms-of-service.

Alternatively, if you are using Gradle Enterprise, specify the server location.
For more information, please see https://gradle.com/help/plugin-enterprise-config.

12:41:58 PM: Task execution finished 'amplifyPush --scan'.
```

**Comment by richardmcclellan** [comment]
First, please try again with the latest version of the Gradle plugin, which is 1.0.2.  This version resolves some bugs in previous versions.  

If you are still having issues with the Gradle plugin, please note that it is optional, and you can use the Amplify CLI instead, as described here in the [Amplify Android Project Setup Guide](https://docs.amplify.aws/lib/project-setup/prereq/q/platform/android)
