### ISSUE TITLE
access keys for IAM users expired after few days

### ISSUE THREAD

**Issue by 24Lathiya** [aws-amplify/amplify-android#933]
```
2020-10-27 17:16:12.630 4089-4089/com.example.aws E/MyAmplifyApp: Could not initialize Amplify
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
        at android.content.res.ResourcesImpl.openRawResource(ResourcesImpl.java:298)
        at android.content.res.Resources.openRawResource(Resources.java:1235)
        at android.content.res.Resources.openRawResource(Resources.java:1180)
        at com.amplifyframework.core.Resources.readJsonResourceFromId(Resources.java:78)
        at com.amplifyframework.core.AmplifyConfiguration.builder(AmplifyConfiguration.java:226)
        at com.amplifyframework.core.AmplifyConfiguration.fromConfigFile(AmplifyConfiguration.java:115)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:120)
        at com.example.aws.MyApp.onCreate(MyApp.java:110)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1046)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5402)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

Getting above error every time after access key expired.
Temporary solution is if we create new access key then it work fine. 
Now i would like key which don't expire.  If anyone have any idea please let me know.

**Comment by rjuliano** [comment]
How are you creating the access keys? If you're assuming a role, those credentials are temporary by nature and the expiration is controlled using whatever mechanism you're using to assume the role.

**Comment by jamesonwilliams** [comment]
Hi @24Lathiya.
 
>Could not initialize Amplify
>    android.content.res.Resources$NotFoundException: Resource ID #0x0

It looks like you don't have any `app/src/main/res/raw/amplifyconfiguration.json` file. This would prevent you from using auth as a whole, regardless of access key lifespan.

**Comment by 24Lathiya** [comment]
@rjuliano @jamesonwilliams i have updated cli using `npm i -g @aws-amplify/cli` and end of result everything is working fine. Now please let me know what is real issue??
