### ISSUE TITLE
Tokens not refreshing

### ISSUE THREAD

**Issue by camhart** [aws-amplify/amplify-android#965]
**State your question**
I have manually deployed an AWS Cognito seutp. I'm using it with the Amplify
Android library, to add authentication.  I can successfully login, and
everything works for 1 hour.  

```java
Amplify.Auth.fetchAuthSession(result -> {
    AWSCognitoAuthSession cognitoAuthSession = (AWSCognitoAuthSession) result;
    AuthSessionResult<AWSCognitoUserPoolTokens> userPoolTokens = cognitoAuthSession.getUserPoolTokens();
    AuthException exception = userPoolTokens.getError(); // error shown below
}, failure -> { /* customer did not provide */ });
```

Here's the error:
```console
2020-11-16 18:46:26.315 26696-26798/com.myapp.ooyea D/AWSMobileClient: Inspecting user state details
2020-11-16 18:46:26.327 26696-26798/com.myapp.ooyea W/CognitoUserSession: CognitoUserSession is not valid because idToken is null.
2020-11-16 18:46:26.328 26696-26798/com.myapp.ooyea W/AWSMobileClient: signalTokensNotAvailable
2020-11-16 18:46:26.346 26696-26798/com.myapp.ooyea W/AWSMobileClient: Tokens are invalid, please sign-in again.
    java.lang.Exception: No cached session.
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.signalTokensNotAvailable(AWSMobileClient.java:1858)
        at com.amazonaws.mobile.client.AWSMobileClient$11$1.getAuthenticationDetails(AWSMobileClient.java:1838)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:1032)
        at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1819)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:1785)
        at com.amazonaws.mobile.client.AWSMobileClient.getUserStateDetails(AWSMobileClient.java:1042)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:843)
        at com.amazonaws.mobile.client.AWSMobileClient$5.run(AWSMobileClient.java:840)
        at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
        at java.lang.Thread.run(Thread.java:923)
2020-11-16 18:46:33.530 26696-26798/com.myapp.ooyea W/System.err: AmplifyException {message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
2020-11-16 18:46:33.531 26696-26798/com.myapp.ooyea W/System.err:     at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.expiredSession(AWSCognitoAuthPlugin.java:1067)
2020-11-16 18:46:33.541 26696-26798/com.myapp.ooyea W/System.err:     at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin.access$700(AWSCognitoAuthPlugin.java:103)
2020-11-16 18:46:33.548 26696-26798/com.myapp.ooyea W/System.err:     at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$7.onResult(AWSCognitoAuthPlugin.java:503)
2020-11-16 18:46:33.551 26696-26798/com.myapp.ooyea W/System.err:     at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$7.onResult(AWSCognitoAuthPlugin.java:493)
2020-11-16 18:46:33.554 26696-26798/com.myapp.ooyea W/System.err:     at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
2020-11-16 18:46:33.556 26696-26798/com.myapp.ooyea W/System.err:     at java.lang.Thread.run(Thread.java:923)
```

`Amplify.Auth.fetchAuthSession` is being called form a background thread
(others have suggested this).  I've also tried calling the async form of
`AWSMobileClient.getInstance().getAWSCredentials(...)`, but that doesn't
refresh credentials either.

Refresh tokens for the Cognito App Client is set to 365 days.  Access token and
ID token at 60 minutes.  Once 60 minutes passes, the ID token expires and isn't
refreshed.

Do I need to include an offline scope or something to ensure a refresh token is
used?

**Environment(please complete the following information):**
```gradle
implementation com.amplifyframework:aws-auth-cognito:1.4.1
```

**Device Information (please complete the following information):**
 - Device: Pixel 3a
 - Android Version: 11

[This
documentation](https://docs.amplify.aws/lib/auth/overview/q/platform/android#sign-up-and-sign-in)
states:

> The Amplify client will refresh the tokens calling
> Amplify.Auth.fetchAuthSession if they are no longer valid and Amplify will
> handle the rest - retrieving, sending, and refreshing tokens as needed.

The wording here initially led me to believe that calling
`Amplify.Auth.fetchAuthSession` will handle refreshing tokens for me.   However
on second glance, it's saying the Amplify client will refresh the tokens by
calling that.  How do I force the amplify client to refresh tokens?

**Comment by camhart** [comment]
I found my error.  My amplifyconfiguration.json file only contained the User Pool App Setting secret under Auth.Default.OAuth, but it needed it there *and* under CognitoUserPool.Default.  Once I added it there the client successfully refreshed tokens.

I found this by debugging through the AWS / Amplify SDK when the client was attempting to refresh credentials.  It errored out at some point indicating 
```
Client xxxxxxxxxxxxxxxxxxxxxxxxx is configured for secret but secret was not received
```
