### ISSUE TITLE
Can't initialise AWS Amplify for Android app in Android Studio

### ISSUE THREAD

**Issue by Phobez** [aws-amplify/amplify-android#982]
**AWS Amplify Version**: 4.32.1

**Current Behaviour**:
I'm currently following the tutorial at https://docs.amplify.aws/start/getting-started/setup/q/integration/android. Everything works fine until the final part "Connect to the cloud" at https://docs.amplify.aws/start/getting-started/add-api/q/integration/android. When doing step 5 which is running the app, I get the following error:
```
AmplifyException {message=Failed to parse configuration JSON for AWS API Plugin, cause=AmplifyException {message=Failed to parse configuration, missing required key: endpoint, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Check amplifyconfiguration.json to make sure the AWS API configuration section hasn't been wrongly modified.}
        at com.amplifyframework.api.aws.AWSApiPluginConfigurationReader.parseConfigurationJson(AWSApiPluginConfigurationReader.java:97)
        at com.amplifyframework.api.aws.AWSApiPluginConfigurationReader.readFrom(AWSApiPluginConfigurationReader.java:56)
        at com.amplifyframework.api.aws.AWSApiPlugin.configure(AWSApiPlugin.java:127)
        at com.amplifyframework.core.category.Category.configure(Category.java:86)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:153)
        at com.amplifyframework.core.Amplify.configure(Amplify.java:120)
        at com.example.todo.MyAmplifyApplication.onCreate(MyAmplifyApplication.java:18)
        at android.app.Instrumentation.callApplicationOnCreate(Unknown Source:0)
        at android.app.ActivityThread.handleBindApplication(Unknown Source:1209)
        at android.app.ActivityThread.access$1400(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(Unknown Source:710)
        at android.os.Handler.dispatchMessage(Unknown Source:19)
        at android.os.Looper.loop(Unknown Source:242)
        at android.app.ActivityThread.main(Unknown Source:98)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
        at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
     Caused by: AmplifyException {message=Failed to parse configuration, missing required key: endpoint, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
        at com.amplifyframework.api.aws.AWSApiPluginConfigurationReader.parseConfigurationJson(AWSApiPluginConfigurationReader.java:72)
        at com.amplifyframework.api.aws.AWSApiPluginConfigurationReader.readFrom(AWSApiPluginConfigurationReader.java:56) 
        at com.amplifyframework.api.aws.AWSApiPlugin.configure(AWSApiPlugin.java:127) 
        at com.amplifyframework.core.category.Category.configure(Category.java:86) 
        at com.amplifyframework.core.Amplify.configure(Amplify.java:153) 
        at com.amplifyframework.core.Amplify.configure(Amplify.java:120) 
        at com.example.todo.MyAmplifyApplication.onCreate(MyAmplifyApplication.java:18) 
        at android.app.Instrumentation.callApplicationOnCreate(Unknown Source:0) 
        at android.app.ActivityThread.handleBindApplication(Unknown Source:1209) 
        at android.app.ActivityThread.access$1400(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(Unknown Source:710) 
        at android.os.Handler.dispatchMessage(Unknown Source:19) 
        at android.os.Looper.loop(Unknown Source:242) 
        at android.app.ActivityThread.main(Unknown Source:98) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11) 
        at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
```

**Current Implementation**
Starting from https://docs.amplify.aws/start/getting-started/add-api/q/integration/android, I did the following steps:

- Run "amplify init" in the project's root directory in Android Studio
- Run "amplifyPush"
- Added the following code to MainActivity.java's onCreate method:

```
Amplify.DataStore.observe(Todo.class,
       started -> Log.i("Tutorial", "Observation began."),
       change -> Log.i("Tutorial", change.item().toString()),
       failure -> Log.e("Tutorial", "Observation failed.", failure),
       () -> Log.i("Tutorial", "Observation complete.")
);
```

**Expected Behaviour**:

It should work and I should see "Observation began." in the Logcat and the locally saved data should be pushed to the cloud backend.

**Comment by jamesonwilliams** [comment]
Hi there. What is the contents of your `app/src/main/res/raw/amplifyconfiguration.json`? From your error message, it looks like you've added the AWS API Plugin, but that there is no appropriate configuration to support it in the configuration file. Please ensure that you have added an API via the CLI, and that the API is reflected in your Amplify configuration file.

**Comment by Phobez** [comment]
Hi! These are the contents of my `app/src/main/res/raw/amplifyconfiguration.json`:
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0"
}
```

I've never made changes to this file before so I'm not really sure what's happening.
