### ISSUE TITLE
Error events in DataStore.observe cause an app crash

### ISSUE THREAD

**Issue by Amplifiyer** [aws-amplify/amplify-android#984]
When there is an error calling the datastore APIs, the local storage subscription ends with the message `Storage adapter subscription ended in error`. Any subsequent error crashes the app.

To reproduce: 
* Subscribe to local storage using one of the `observe(...)` APIs.
* Call any DataStore API which results in an _expected_ error, such as deleting a non-existent ID, or saving a model instance where the predicate condition is not met.
* Check the logs, which will show:
```console
W/amplify:aws-datastore: Storage adapter subscription ended in error
    DataStoreException{message=Wanted to delete one row, but deleted 0 rows., cause=null, recoverySuggestion=This is likely a bug. Please report to AWS.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:512)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$_T5npQOSQr5NW7t4G06wJJ3nXGM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
E/amplify:flutter:datastore: Delete operation failed.
    DataStoreException{message=Wanted to delete one row, but deleted 0 rows., cause=null, recoverySuggestion=This is likely a bug. Please report to AWS.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:512)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$_T5npQOSQr5NW7t4G06wJJ3nXGM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```
* Repeat the same operation _again_, which will result in a crash:
```console
W/System.err: io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | DataStoreException{message=Wanted to delete one row, but deleted 0 rows., cause=null, recoverySuggestion=This is likely a bug. Please report to AWS.}
        at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.rxjava3.subjects.SerializedSubject.onError(SerializedSubject.java:111)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:533)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$_T5npQOSQr5NW7t4G06wJJ3nXGM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:919)
    Caused by: DataStoreException{message=Wanted to delete one row, but deleted 0 rows., cause=null, recoverySuggestion=This is likely a bug. Please report to AWS.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:512)
    	... 6 more
E/AndroidRuntime: FATAL EXCEPTION: pool-7-thread-1
    Process: com.amazonaws.amplify.amplify_datastore_example, PID: 10078
    io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | DataStoreException{message=Wanted to delete one row, but deleted 0 rows., cause=null, recoverySuggestion=This is likely a bug. Please report to AWS.}
        at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.rxjava3.subjects.SerializedSubject.onError(SerializedSubject.java:111)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:533)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$_T5npQOSQr5NW7t4G06wJJ3nXGM.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: DataStoreException{message=Wanted to delete one row, but deleted 0 rows., cause=null, recoverySuggestion=This is likely a bug. Please report to AWS.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$delete$6$SQLiteStorageAdapter(SQLiteStorageAdapter.java:512)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$_T5npQOSQr5NW7t4G06wJJ3nXGM.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by jamesonwilliams** [comment]
Thanks @Amplifiyer!

**Comment by jamesonwilliams** [comment]
I was able to reproduce this.
