### ISSUE TITLE
ClassCastException when saving Temporal types from Flutter

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-android#998]
In the Amplify Flutter Library, a model is saved by serializing it as a basic map that contains string keys to string/bool/int/nested map values and sending that map over a method channel to Android.  As all values are eventually primitive data types, we cannot directly send a "DateTime" or "Model".  

The Amplify Android Library was upgraded to support the "Model" case by taking a `SerializedModel` instead of a Java Model instance.  We need something similar for the Temporal types so that Amplify Android can take a ISO8601 string representation of time and automatically create the proper DateTime/Date/Time object.

**Comment by fjnoyp** [comment]
Please note that we have the same issue with Timestamp too.  

`cause=java.lang.ClassCastException: java.lang.Integer cannot be cast to com.amplifyframework.core.model.temporal.Temporal$Timestamp, recoverySuggestion=See attached exception for details.}`

**Comment by jamesonwilliams** [comment]
> As all values are eventually primitive data types, we cannot directly send a "DateTime" or "Model".

This isn't exactly true. Currently, you can send any value that the Android library recognizes. That includes `Boolean`, `Integer`, `Long`, `String`, etc.

Nested models should be sent as `SerializedModel`s. You can see an example of this [here](https://github.com/aws-amplify/amplify-android/blob/main/aws-datastore/src/androidTest/java/com/amplifyframework/datastore/HybridCloudSyncInstrumentationTest.java#L176-L194).

Here's an example of preparing and sending [_Temporal types_](https://github.com/aws-amplify/amplify-android/blob/8ccb280c0418853731f46fe709bda857d7b7765e/aws-api-appsync/src/test/java/com/amplifyframework/datastore/appsync/SerializedModelAdapterTest.java#L58-L85).

> The Amplify Android Library was upgraded to support the "Model" case by taking a string instead of a Model instance.

The Android library uses [`SerializedModel`](https://github.com/aws-amplify/amplify-android/blob/main/aws-api-appsync/src/main/java/com/amplifyframework/datastore/appsync/SerializedModel.java#L35)s for this purpose.

> We need something similar for the Temporal types so that Amplify Android can take a ISO8601 string representation of time and automatically create the proper DateTime/Date/Time object.

Please check the provided data and schema, [here](https://github.com/aws-amplify/amplify-android/blob/main/aws-api-appsync/src/test/java/com/amplifyframework/datastore/appsync/SerializedModelAdapterTest.java#L87-L119).

**Comment by fjnoyp** [comment]
Yes we send the DateTime/Date/Time as strings and I think that's inherently the problem.  In the example you sent it appears that's not checking if that format can actually be saved.  We're using that SerializedModel to pass to your save API and it's causing a crash. 

As you can see here we're sending very similar data (I used the same string for temporal types as in the example you provided): 

![image](https://user-images.githubusercontent.com/11478656/100285742-43577580-2f26-11eb-9e2f-757ad8843b8e.png)

However, the result of calling save is a class cast exception causing a crash to the main menu: 

`  plugin.save(
                serializedModel,`


```
2020-11-25 13:56:17.133 0-0/? D/logd: Skipping 4294967047 entries from slow reader, pid 7615, from LogBuffer::kickMe()
    
    --------- beginning of main
2020-11-25 13:56:18.152 478-478/? W/adbd: timeout expired while flushing socket, closing
2020-11-25 13:56:18.250 0-0/? D/logd: logdr: UID=2000 GID=2000 PID=7734 b tail=0 logMask=99 pid=0 start=0ns timeout=0ns
2020-11-25 13:56:27.732 7666-7723/com.amazonaws.amplify.amplify_datastore_example W/amplify:aws-datastore: Storage adapter subscription ended in error
    DataStoreException{message=Error in saving the model: AllTypeModel[id=4d4224ed-e902-47b9-9e2c-cc9af331c4de], cause=java.lang.ClassCastException: java.lang.String cannot be cast to com.amplifyframework.core.model.temporal.Temporal$DateTime, recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:319)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.amplifyframework.core.model.temporal.Temporal$DateTime
        at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:109)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:233)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.bindStatementToValues(SQLiteStorageAdapter.java:673)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:728)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:303)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2020-11-25 13:56:27.733 7666-7718/com.amazonaws.amplify.amplify_datastore_example E/amplify:flutter:datastore: Received an error
    DataStoreException{message=Error in saving the model: AllTypeModel[id=4d4224ed-e902-47b9-9e2c-cc9af331c4de], cause=java.lang.ClassCastException: java.lang.String cannot be cast to com.amplifyframework.core.model.temporal.Temporal$DateTime, recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:319)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.amplifyframework.core.model.temporal.Temporal$DateTime
        at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:109)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:233)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.bindStatementToValues(SQLiteStorageAdapter.java:673)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:728)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:303)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2020-11-25 13:56:27.750 7666-7718/com.amazonaws.amplify.amplify_datastore_example E/amplify:flutter:datastore: Save operation failed
    DataStoreException{message=Error in saving the model: AllTypeModel[id=4d4224ed-e902-47b9-9e2c-cc9af331c4de], cause=java.lang.ClassCastException: java.lang.String cannot be cast to com.amplifyframework.core.model.temporal.Temporal$DateTime, recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:319)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.amplifyframework.core.model.temporal.Temporal$DateTime
        at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertRawValueToTarget(SQLiteModelFieldTypeConverter.java:109)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteModelFieldTypeConverter.convertValueFromTarget(SQLiteModelFieldTypeConverter.java:233)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.bindStatementToValues(SQLiteStorageAdapter.java:673)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:728)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:303)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2020-11-25 13:56:27.767 7666-7697/com.amazonaws.amplify.amplify_datastore_example I/flutter: Instance of 'DataStoreError'
2020-11-25 13:57:00.011 788-788/com.android.systemui D/KeyguardClockSwitch: Updating clock: 157
2020-11-25 13:57:07.278 536-536/? E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
2020-11-25 13:57:07.301 491-491/? E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument
2020-11-25 13:57:38.571 615-3419/system_process D/WifiNl80211Manager: Scan result ready event
2020-11-25 13:57:38.571 615-3419/system_process D/WifiNative: Scan result ready event
2020-11-25 13:58:00.011 788-788/com.android.systemui D/KeyguardClockSwitch: Updating clock: 158
2020-11-25 13:58:07.303 536-536/? E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
2020-11-25 13:58:07.329 491-491/? E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument

```

**Comment by fjnoyp** [comment]
```
enum TestEnum { 
  yes,
  no,
  maybe
}

type AllTypeModel @model { 
  id: ID!
  stringType: String!
  intType: Int!
  floatType: Float!
  boolType: Boolean!
  dateType: AWSDate!
  dateTimeType: AWSDateTime!
  timeType: AWSTime!
  timestampType: AWSTimestamp!
  enumType: TestEnum 
}
```

**Comment by jamesonwilliams** [comment]
Notes to self:

1. Models are working. This ticket is about temporal types, now.
2. We looked at the `ModelField`s in the schema that Kyle was passing, and they included the below properties.

| targetType | javaClassForValue |
|---------------|-------------------|
| `AWSDate` |  `com.amplifyframework.core.model.temporal.Temporal$Date` |
| `AWSDateTime`   | `com.amplifyframework.core.model.temporal.Temporal$DateTime` |
| `AWSTime` | `com.amplifyframework.core.model.temporal.Temporal$Time` |  
| `AWSTimestamp`   | `com.amplifyframework.core.model.temporal.Temporal$Timestamp` |
